In [1]:
%config IPCompleter.use_jedi = False
%pdb off
%load_ext autoreload
%autoreload 3
# %matplotlib inline
%matplotlib qt5
import mne
mne.viz.set_browser_backend("qt")  # or "matplotlib"
mne.set_config("MNE_BROWSER_BACKEND", "qt")  # or "matplotlib"
%gui qt

import xarray as xr # Assuming you're using this
import numpy as np   # For the example

import xarray as xr
import zarr
import panel as pn
import holoviews as hv
hv.extension('bokeh', logo=False)

import hvplot.xarray
import hvplot.pandas
# This line is crucial for displaying plots in a notebook
hvplot.extension('bokeh') # You can also use 'matplotlib' or 'plotly'

# hv.extension('bokeh')
# hv.extension('matplotlib') # or 'matplotlib'
# hv.extension('plotly') # or 'matplotlib'
from holoviews import opts
import panel as pn
pn.extension()

import IPython

# Jupyter-lab enable printing for any line on its own (instead of just the last one in the cell)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

Automatic pdb calling has been turned OFF
Using qt as 2D backend.


# Use MNE to load and analyze saved EEG and Motion recordings

In [2]:
import time
import re
from datetime import datetime, timezone

import uuid
from copy import deepcopy
from typing import Dict, List, Tuple, Optional, Callable, Union, Any
from nptyping import NDArray
from matplotlib import pyplot as plt

from pathlib import Path
import numpy as np
import pandas as pd
from numpy.typing import NDArray

import mne
from mne import set_log_level
from copy import deepcopy
import mne

from mne.io import read_raw

datasets = []
# mne.viz.set_browser_backend("Matplotlib")
mne.viz.set_browser_backend("qt")

from mne_lsl.player import PlayerLSL as Player
from mne_lsl.stream import StreamLSL as Stream
from phopylslhelper.easy_time_sync import EasyTimeSyncParsingMixin, readable_dt_str, from_readable_dt_str

from phoofflineeeganalysis.analysis.MNE_helpers import MNEHelpers
from phoofflineeeganalysis.analysis.historical_data import HistoricalData
from phoofflineeeganalysis.analysis.motion_data import MotionData
from phoofflineeeganalysis.analysis.EEG_data import EEGComputations, EEGData
from phoofflineeeganalysis.analysis.anatomy_and_electrodes import ElectrodeHelper
# from ..EegProcessing import bandpower
# from phoofflineeeganalysis.EegProcessing import analyze_eeg_trends
from phoofflineeeganalysis.EegVisualization import VisHelpers
from phoofflineeeganalysis.analysis.SavedSessionsProcessor import SavedSessionsProcessor, SessionModality, DataModalityType

set_log_level("WARNING")


# db_root_path = Path('/content/drive/MyDrive/Databases').resolve()
db_root_path = Path(r'E:/Dropbox (Personal)/Databases').resolve()
assert db_root_path.exists(), f"'{db_root_path.as_posix()}' does not exist!"

# eeg_recordings_file_path: Path = Path(r'E:/Dropbox (Personal)/Databases/UnparsedData/EmotivEpocX_EEGRecordings/fif').resolve()
# headset_motion_recordings_file_path: Path = Path(r'E:/Dropbox (Personal)/Databases/UnparsedData/EmotivEpocX_EEGRecordings/MOTION_RECORDINGS/fif').resolve()

# assert eeg_recordings_file_path.exists()
# assert headset_motion_recordings_file_path.exists()

eeg_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEpocX_EEGRecordings/fif').resolve()
flutter_eeg_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEEG_FlutterRecordings').resolve()
flutter_motion_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEEG_FlutterRecordings/MOTION_RECORDINGS').resolve()
flutter_GENERIC_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEEG_FlutterRecordings/GENERIC_RECORDINGS').resolve()

headset_motion_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEpocX_EEGRecordings/MOTION_RECORDINGS/fif').resolve()
WhisperVideoTranscripts_LSL_Converted = db_root_path.joinpath('UnparsedData/WhisperVideoTranscripts_LSL_Converted').resolve()
pho_log_to_LSL_recordings_path: Path = db_root_path.joinpath('UnparsedData/PhoLogToLabStreamingLayer_logs').resolve()
## These contain little LSL .fif files with names like: '20250808_062814_log.fif',

eeg_analyzed_parent_export_path = db_root_path.joinpath('AnalysisData/MNE_preprocessed').resolve()
pickled_data_path = db_root_path.joinpath('AnalysisData/MNE_preprocessed/PICKLED_COLLECTION').resolve()
assert pickled_data_path.exists()


# n_most_recent_sessions_to_preprocess: int = None # None means all sessions
# n_most_recent_sessions_to_preprocess: int = 35
n_most_recent_sessions_to_preprocess: int = 5
# n_most_recent_sessions_to_preprocess = None

'qt'

Using matplotlib as 2D backend.

# SavedSessionProcessor

In [3]:

sso: SavedSessionsProcessor = SavedSessionsProcessor(eeg_recordings_file_path=eeg_recordings_file_path,
                                                     headset_motion_recordings_file_path=headset_motion_recordings_file_path, WhisperVideoTranscripts_LSL_Converted_file_path=WhisperVideoTranscripts_LSL_Converted, pho_log_to_LSL_recordings_path=pho_log_to_LSL_recordings_path,
                                                    eeg_analyzed_parent_export_path=eeg_analyzed_parent_export_path, 
                                                     n_most_recent_sessions_to_preprocess=n_most_recent_sessions_to_preprocess, 
                                                    should_load_data=True, should_load_preprocessed=False,
                                                    #  should_load_data=True, should_load_preprocessed=True,
													)

In [4]:
# included_xdf_file_names = [
# 	"E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T051157.400Z_eeg.xdf", ## When it started to work
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T215045.162Z_eeg.xdf"
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T164055.381Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-18T092615.398Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-17T215112.606Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-17T124127.644Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-17T214946.083Z_eeg.xdf",
#     # # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-22T182649.051Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T220233.548Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T212744.771Z_eeg.xdf",
#     # # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T212721.939Z_eeg.xdf",
#     # # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T212528.076Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-23T141026.412Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-22T213547.659Z_eeg.xdf",
# ]

# included_xdf_file_names = [Path(v).resolve() for v in included_xdf_file_names]
# included_xdf_file_names = [v.name for v in included_xdf_file_names]


included_xdf_file_names = None ## include all 
included_xdf_file_names

# 2025-09-18 - LabRecorder XDF Imports

In [5]:
from phoofflineeeganalysis.analysis.EEG_data import EEGData
from phoofflineeeganalysis.analysis.MNE_helpers import DatasetDatetimeBoundsRenderingMixin, RawArrayExtended, RawExtended, up_convert_raw_objects, up_convert_raw_obj
from phoofflineeeganalysis.analysis.SavedSessionsProcessor import LabRecorderXDF, unwrap_single_element_listlike_if_needed
from phoofflineeeganalysis.analysis.SavedSessionsProcessor import XDFDataStreamAccessor

lab_recorder_output_path = Path(r"E:\Dropbox (Personal)\Databases\UnparsedData\LabRecorderStudies\sub-P001").resolve()
assert lab_recorder_output_path.exists()

labRecorder_PostProcessed_path: Path = sso.eeg_analyzed_parent_export_path.joinpath(f'LabRecorder_PostProcessed')
labRecorder_PostProcessed_path.mkdir(exist_ok=True)

should_write_final_merged_eeg_fif: bool = True
# should_write_final_merged_eeg_fif: bool = False
_out_eeg_raw, _out_xdf_stream_infos_df, lab_recorder_xdf_files = LabRecorderXDF.load_and_process_all(lab_recorder_output_path=lab_recorder_output_path, 
                                                                                                     labRecorder_PostProcessed_path=labRecorder_PostProcessed_path, should_write_final_merged_eeg_fif=should_write_final_merged_eeg_fif,
                                                                                                     included_xdf_file_names=included_xdf_file_names, fail_on_exception=False)
xdf_dataset_indicies = np.unique(deepcopy(_out_xdf_stream_infos_df).reset_index(drop=False, inplace=False)['xdf_dataset_idx'].to_numpy())
n_unique_xdf_datasets: int = len(xdf_dataset_indicies)
print(f'n_unique_xdf_datasets: {n_unique_xdf_datasets}')
## 2m 30s

trying to process XDF file 0/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-10T140840.440Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-10 02:08:40 PM
	first_timestamp_dt: 2025-09-10 02:08:40 PM
	last_timestamp_dt: 2025-09-10 02:08:40 PM
	 failed with error:
	skipping file.
trying to process XDF file 1/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-10T153731.079Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-09-10 03:37:31 PM
	first_timestamp_dt: 2025-09-10 03:37:31 PM
	last_timestamp_dt: 2025-09-10 03:37:31 PM
	 failed with error:
	skipping file.
trying to process XDF file 2/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-10T165236.402Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-10 04:52:36 PM
	first_timestamp_dt: 2025-09-10 04:52:36 PM
	last_timestamp_dt: 2025-09-10 04:52:36 PM
	 failed with error:
	skipping file.
trying to process XDF file 3/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-11T014154.084Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-11 01:41:54 AM
	 failed with error: 'footer'
	skipping file.
trying to process XDF file 4/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-11T101328.256Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-11 10:13:28 AM
	first_timestamp_dt: 2025-09-11 10:13:28 AM
	last_timestamp_dt: 2025-09-11 10:13:28 AM
	 failed with error:
	skipping file.
trying to process XDF file 5/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-11T154549.460Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-11 03:45:49 PM
	first_timestamp_dt: 2025-09-11 03:45:49 PM
	last_timestamp_dt: 2025-09-11 03:45:49 PM
	 failed with error:
	skipping file.
trying to process XDF file 6/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-12T220903.464Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-12 10:09:03 PM
	first_timestamp_dt: 2025-09-12 10:09:03 PM
	last_timestamp_dt: 2025-09-12 10:09:03 PM
	 failed with error:
	skipping file.
trying to process XDF file 7/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-18T031842.989Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-18 03:18:42 AM
	first_timestamp_dt: 2025-09-18 03:18:42 AM
	last_timestamp_dt: 2025-09-18 03:18:42 AM
	 failed with error:
	skipping file.
trying to process XDF file 8/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-18T121337.267Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-18 12:13:37 PM
	first_timestamp_dt: 2025-09-18 12:13:37 PM
	last_timestamp_dt: 2025-09-18 12:13:37 PM
	 failed with error:
	skipping file.
trying to process XDF file 9/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-18T122106.448Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-09-18 12:21:06 PM
	first_timestamp_dt: 2025-09-18 12:21:06 PM
	last_timestamp_dt: 2025-09-18 12:21:06 PM
	 failed with error:
	skipping file.
trying to process XDF file 10/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_2025-09-18T151803.959Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-09-18 03:18:03 PM
	first_timestamp_dt: 2025-09-18 03:18:03 PM
	last_timestamp_dt: 2025-09-18 03:18:03 PM
	 failed with error:
	skipping file.
trying to process XDF file 11/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-12T215537.892Z.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-12 09:55:37 PM
	first_timestamp_dt: 2025-09-12 09:55:37 PM
	last_timestamp_dt: 2025-09-12 09:55:37 PM
	 failed with error:
	skipping file.
trying to process XDF file 12/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-18T151839.043Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-18 03:18:39 PM
	first_timestamp_dt: 2025-09-18 03:18:39 PM
	last_timestamp_dt: 2025-09-18 03:18:39 PM
	 failed with error:
	skipping file.
trying to process XDF file 13/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-18T152308.395Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-18 03:23:08 PM
	first_timestamp_dt: 2025-09-18 03:23:08 PM
	last_timestamp_dt: 2025-09-18 03:23:08 PM
	 failed with error:
	skipping file.
trying to process XDF file 14/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-18T200937.798Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-09-18 08:09:37 PM
	first_timestamp_dt: 2025-09-18 08:09:37 PM
	last_timestamp_dt: 2025-09-18 08:09:37 PM
	 failed with error:
	skipping file.
trying to process XDF file 15/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-18T201023.120Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-18 08:10:23 PM
	first_timestamp_dt: 2025-09-18 08:10:23 PM
	last_timestamp_dt: 2025-09-18 08:10:23 PM
	 failed with error:
	skipping file.
trying to process XDF file 16/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-19T051346.012Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-19 05:13:46 AM
	first_timestamp_dt: 2025-09-19 05:13:46 AM
	last_timestamp_dt: 2025-09-19 05:13:46 AM
	 failed with error:
	skipping file.
trying to process XDF file 17/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-19T115508.257Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-09-19 11:55:08 AM
	first_timestamp_dt: 2025-09-19 11:55:08 AM
	last_timestamp_dt: 2025-09-19 11:55:08 AM
	 failed with error:
	skipping file.
trying to process XDF file 18/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-19T205118.364Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-19 08:51:18 PM
	first_timestamp_dt: 2025-09-19 08:51:18 PM
	last_timestamp_dt: 2025-09-19 08:51:18 PM
	 failed with error:
	skipping file.
trying to process XDF file 19/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-20T214749.964Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-20 09:47:49 PM
	first_timestamp_dt: 2025-09-20 09:47:49 PM
	last_timestamp_dt: 2025-09-20 09:47:49 PM
	 failed with error:
	skipping file.
trying to process XDF file 20/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-21T002232.699Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-09-21 12:22:32 AM
	first_timestamp_dt: 2025-09-21 12:22:32 AM
	last_timestamp_dt: 2025-09-21 12:22:32 AM
	 failed with error:
	skipping file.
trying to process XDF file 21/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-21T002343.561Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-09-21 12:23:43 AM
	first_timestamp_dt: 2025-09-21 12:23:43 AM
	last_timestamp_dt: 2025-09-21 12:23:43 AM
	 failed with error:
	skipping file.
trying to process XDF file 22/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-21T002525.578Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-21 12:25:25 AM
	first_timestamp_dt: 2025-09-21 12:25:25 AM
	last_timestamp_dt: 2025-09-21 12:25:25 AM
	 failed with error:
	skipping file.
trying to process XDF file 23/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-21T003051.428Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-21 12:30:51 AM
	first_timestamp_dt: 2025-09-21 12:30:51 AM
	last_timestamp_dt: 2025-09-21 12:30:51 AM
	 failed with error:
	skipping file.
trying to process XDF file 24/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-21T085541.696Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-21 08:55:41 AM
	first_timestamp_dt: 2025-09-21 08:55:41 AM
	last_timestamp_dt: 2025-09-21 08:55:41 AM
	 failed with error:
	skipping file.
trying to process XDF file 25/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-22T182649.051Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-22 06:26:49 PM
	first_timestamp_dt: 2025-09-22 06:26:49 PM
	last_timestamp_dt: 2025-09-22 06:26:49 PM
	 failed with error:
	skipping file.
trying to process XDF file 26/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-22T213547.659Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-22 09:35:47 PM
	first_timestamp_dt: 2025-09-22 09:35:47 PM
	last_timestamp_dt: 2025-09-22 09:35:47 PM
	 failed with error:
	skipping file.
trying to process XDF file 27/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-23T141026.412Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-09-23 02:10:26 PM
	first_timestamp_dt: 2025-09-23 02:10:26 PM
	last_timestamp_dt: 2025-09-23 02:10:26 PM
	 failed with error:
	skipping file.
trying to process XDF file 28/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T212528.076Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-10-16 09:25:28 PM
	first_timestamp_dt: 2025-10-16 09:25:28 PM
	last_timestamp_dt: 2025-10-16 09:25:28 PM
	 failed with error:
	skipping file.
trying to process XDF file 29/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T212721.939Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-10-16 09:27:21 PM
	first_timestamp_dt: 2025-10-16 09:27:21 PM
	last_timestamp_dt: 2025-10-16 09:27:21 PM
	 failed with error:
	skipping file.
trying to process XDF file 30/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T212744.771Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-10-16 09:27:44 PM
	first_timestamp_dt: 2025-10-16 09:27:44 PM
	last_timestamp_dt: 2025-10-16 09:27:44 PM
	 failed with error:
	skipping file.
trying to process XDF file 31/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T220233.548Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-10-16 10:02:33 PM
	first_timestamp_dt: 2025-10-16 10:02:33 PM
	last_timestamp_dt: 2025-10-16 10:02:33 PM
	 failed with error:
	skipping file.
trying to process XDF file 32/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-17T124127.644Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-17 12:41:27 PM
	first_timestamp_dt: 2025-10-17 12:41:27 PM
	last_timestamp_dt: 2025-10-17 12:41:27 PM
	 failed with error:
	skipping file.
trying to process XDF file 33/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-17T214946.083Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-17 09:49:46 PM
	first_timestamp_dt: 2025-10-17 09:49:46 PM
	last_timestamp_dt: 2025-10-17 09:49:46 PM
	 failed with error:
	skipping file.
trying to process XDF file 34/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-17T215112.606Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-10-17 09:51:12 PM
	first_timestamp_dt: 2025-10-17 09:51:12 PM
	last_timestamp_dt: 2025-10-17 09:51:12 PM
	 failed with error:
	skipping file.
trying to process XDF file 35/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-18T092615.398Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-18 09:26:15 AM
	first_timestamp_dt: 2025-10-18 09:26:15 AM
	last_timestamp_dt: 2025-10-18 09:26:15 AM
	 failed with error: 'NoneType' object is not iterable
	skipping file.
trying to process XDF file 36/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-18T192330.926Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-18 07:23:30 PM
	first_timestamp_dt: 2025-10-18 07:23:30 PM
	last_timestamp_dt: 2025-10-18 07:23:30 PM
	 failed with error:
	skipping file.
trying to process XDF file 37/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-18T192425.262Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-10-18 07:24:25 PM
	first_timestamp_dt: 2025-10-18 07:24:25 PM
	last_timestamp_dt: 2025-10-18 07:24:25 PM
	 failed with error:
	skipping file.
trying to process XDF file 38/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-18T222634.622Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-18 10:26:34 PM
	first_timestamp_dt: 2025-10-18 10:26:34 PM
	last_timestamp_dt: 2025-10-18 10:26:34 PM
	 failed with error:
	skipping file.
trying to process XDF file 39/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T151321.602Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-10-20 03:13:21 PM
	first_timestamp_dt: 2025-10-20 03:13:21 PM
	last_timestamp_dt: 2025-10-20 03:13:21 PM
	 failed with error:
	skipping file.
trying to process XDF file 40/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T164055.381Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "Epoc X":
	created_at_dt: 2025-10-20 04:40:55 PM
	first_timestamp_dt: 2025-10-20 04:40:55 PM
	last_timestamp_dt: 2025-10-20 04:40:55 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 12:37:27+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 13816.0045519
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-20 04:40:55 PM
	first_timestamp_dt: 2025-10-20 04:40:55 PM
	last_timestamp_dt: 2025-10-20 04:40:55 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 12:37:27+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 13816.0045519
======== STREAM "TextLogger":
	created_at_dt: 2025-10-20 04:40:55 PM
	first_timestamp_dt: 2025-10-20 04:40:55 PM
	last_timestamp_dt: 2025-10-20 04:40:55 PM
	 failed with error:
	skipping file.
trying to process XDF file 41/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T213307.747Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-20 09:33:07 PM
	first_timestamp_dt: 2025-10-20 09:33:07 PM
	last_timestamp_dt: 2025-10-20 09:33:07 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 17:32:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31522.4804679
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-20 17:32:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 31522.480471
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	WARN: no EEG streams found in "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T213307.747Z_eeg.xdf". Skipping file.
trying to process XDF file 42/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T215045.162Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-20 09:50:45 PM
	first_timestamp_dt: 2025-10-20 09:50:45 PM
	last_timestamp_dt: 2025-10-20 09:50:45 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 17:50:18+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32587.1545579
======== STREAM "TextLogger":
	created_at_dt: 2025-10-20 09:50:45 PM
	first_timestamp_dt: 2025-10-20 09:50:45 PM
	last_timestamp_dt: 2025-10-20 09:50:45 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 17:32:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31522.4804679
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-20 17:32:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 31522.480471
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-20 09:50:45 PM
	first_timestamp_dt: 2025-10-20 09:50:45 PM
	last_timestamp_dt: 2025-10-20 09:50:45 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 17:50:18+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32587.1545579
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 37, 	expected_merged: 37

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 13 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 41 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-20T21-50-45.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 24
	n_existing_annots: 24, 	n_new_annots: 41, 	expected_merged: 65
	n_actual_post_annots: 24
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-20T21-50-45.fif"
trying to process XDF file 43/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T215109.178Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-20 09:51:09 PM
	first_timestamp_dt: 2025-10-20 09:51:09 PM
	last_timestamp_dt: 2025-10-20 09:51:09 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 17:50:18+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32587.1545579
======== STREAM "Epoc X":
	created_at_dt: 2025-10-20 09:51:09 PM
	first_timestamp_dt: 2025-10-20 09:51:09 PM
	last_timestamp_dt: 2025-10-20 09:51:09 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 17:50:18+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32587.1545579
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 3521, 	expected_merged: 3521
	n_actual_post_annots: 1776
	n_existing_annots: 1776, 	n_new_annots: 3521, 	expected_merged: 5297
	n_actual_post_annots: 1776
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-20T21-51-09.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1745 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3521 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-20T21-51-09.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 44/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T222728.335Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-20 10:27:28 PM
	first_timestamp_dt: 2025-10-20 10:27:28 PM
	last_timestamp_dt: 2025-10-20 10:27:28 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 17:50:18+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32587.1545579
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-10-20 10:27:28 PM
	first_timestamp_dt: 2025-10-20 10:27:28 PM
	last_timestamp_dt: 2025-10-20 10:27:28 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 17:50:18+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32587.1545579
	n_existing_annots: 0, 	n_new_annots: 89, 	expected_merged: 89
	n_actual_post_annots: 44
	n_existing_annots: 44, 	n_new_annots: 89, 	expected_merged: 133
	n_actual_post_annots: 44
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-20T22-27-28.fif"
trying to process XDF file 45/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T033958.955Z_eeg.xdf"...

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 45 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 89 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-20T22-27-28.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 03:39:58 AM
	first_timestamp_dt: 2025-10-21 03:39:58 AM
	last_timestamp_dt: 2025-10-21 03:39:58 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 03:39:58 AM
	first_timestamp_dt: 2025-10-21 03:39:58 AM
	last_timestamp_dt: 2025-10-21 03:39:58 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "TextLogger":
	created_at_dt: 2025-10-21 03:39:58 AM
	first_timestamp_dt: 2025-10-21 03:39:58 AM
	last_timestamp_dt: 2025-10-21 03:39:58 AM
	 failed with error:
	skipping file.
trying to process XDF file 46/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T040726.583Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 04:07:26 AM
	first_timestamp_dt: 2025-10-21 04:07:26 AM
	last_timestamp_dt: 2025-10-21 04:07:26 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 04:07:26 AM
	first_timestamp_dt: 2025-10-21 04:07:26 AM
	last_timestamp_dt: 2025-10-21 04:07:26 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
	n_existing_annots: 0, 	n_new_annots: 42, 	expected_merged: 42
	n_actual_post_annots: 15
	n_existing_annots: 15, 	n_new_annots: 42, 	expected_merged: 57
	n_actual_post_annots: 15
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-21T04-07-26.fif"
trying to process XDF file 47/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T040800.544Z_eeg.xdf"...

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 27 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 42 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-21T04-07-26.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 04:08:00 AM
	first_timestamp_dt: 2025-10-21 04:08:00 AM
	last_timestamp_dt: 2025-10-21 04:08:00 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 04:08:00 AM
	first_timestamp_dt: 2025-10-21 04:08:00 AM
	last_timestamp_dt: 2025-10-21 04:08:00 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 417, 	expected_merged: 417
	n_actual_post_annots: 169
	n_existing_annots: 169, 	n_new_annots: 417, 	expected_merged: 586
	n_actual_post_annots: 169
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-21T04-08-00.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 248 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 417 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-21T04-08-00.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 48/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T041308.185Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 04:13:08 AM
	first_timestamp_dt: 2025-10-21 04:13:08 AM
	last_timestamp_dt: 2025-10-21 04:13:08 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "TextLogger":
	created_at_dt: 2025-10-21 04:13:08 AM
	first_timestamp_dt: 2025-10-21 04:13:08 AM
	last_timestamp_dt: 2025-10-21 04:13:08 AM
	 failed with error:
	skipping file.
trying to process XDF file 49/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T041343.978Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 04:13:43 AM
	first_timestamp_dt: 2025-10-21 04:13:43 AM
	last_timestamp_dt: 2025-10-21 04:13:43 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 04:13:43 AM
	first_timestamp_dt: 2025-10-21 04:13:43 AM
	last_timestamp_dt: 2025-10-21 04:13:43 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 4676, 	expected_merged: 4676
	n_actual_post_annots: 2259
	n_existing_annots: 2259, 	n_new_annots: 4676, 	expected_merged: 6935
	n_actual_post_annots: 2259
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-21T04-13-43.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2417 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 4676 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-21T04-13-43.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 50/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T050319.400Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 05:03:19 AM
	first_timestamp_dt: 2025-10-21 05:03:19 AM
	last_timestamp_dt: 2025-10-21 05:03:19 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-10-21 05:03:19 AM
	first_timestamp_dt: 2025-10-21 05:03:19 AM
	last_timestamp_dt: 2025-10-21 05:03:19 AM
	 failed with error:
	skipping file.
trying to process XDF file 51/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T050857.606Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 05:08:57 AM
	first_timestamp_dt: 2025-10-21 05:08:57 AM
	last_timestamp_dt: 2025-10-21 05:08:57 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "TextLogger":
	created_at_dt: 2025-10-21 05:08:57 AM
	first_timestamp_dt: 2025-10-21 05:08:57 AM
	last_timestamp_dt: 2025-10-21 05:08:57 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-21 05:08:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 58856.4088291
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-21 05:08:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 58856.4088328
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 05:08:57 AM
	first_timestamp_dt: 2025-10-21 05:08:57 AM
	last_timestamp_dt: 2025-10-21 05:08:57 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
	n_existing_annots: 0, 	n_new_annots: 33, 	expected_merged: 33
	n_actual_post_annots: 14
	n_existing_annots: 14, 	n_new_annots: 40, 	expected_merged: 54
	n_actual_post_annots: 21
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 00:00:04.167524, annotation_time_range_num_secs: 4.167524
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-21T05-08-57.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 00:00:04.167524, annotation_time_range_num_secs: 4.167524
trying to process XDF file 52/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T051157.400Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 05:11:57 AM
	first_timestamp_dt: 2025-10-21 05:11:57 AM
	last_timestamp_dt: 2025-10-21 05:11:57 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-10-21 05:11:57 AM
	first_timestamp_dt: 2025-10-21 05:11:57 AM
	last_timestamp_dt: 2025-10-21 05:11:57 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-21 05:11:47+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 59076.2900127
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-21 05:11:47+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 59076.2900157
======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 05:11:57 AM
	first_timestamp_dt: 2025-10-21 05:11:57 AM
	last_timestamp_dt: 2025-10-21 05:11:57 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
	n_existing_annots: 0, 	n_new_annots: 64, 	expected_merged: 64
	n_actual_post_annots: 34
	n_existing_annots: 34, 	n_new_annots: 71, 	expected_merged: 105
	n_actual_post_annots: 41
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 00:00:11.613028, annotation_time_range_num_secs: 11.613028
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-21T05-11-57.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 00:00:11.613028, annotation_time_range_num_secs: 11.613028
trying to process XDF file 53/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T051226.496Z_eeg.xdf"...

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 19 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 33 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-21T05-08-57.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 30 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 64 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-21T05-11-57.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 05:12:26 AM
	first_timestamp_dt: 2025-10-21 05:12:26 AM
	last_timestamp_dt: 2025-10-21 05:12:26 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 05:12:26 AM
	first_timestamp_dt: 2025-10-21 05:12:26 AM
	last_timestamp_dt: 2025-10-21 05:12:26 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-20 23:39:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53549.402505
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 3057, 	expected_merged: 3057
	n_actual_post_annots: 1450
	n_existing_annots: 1450, 	n_new_annots: 3057, 	expected_merged: 4507
	n_actual_post_annots: 1450
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-21T05-12-26.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1607 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3057 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-21T05-12-26.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 54/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T135208.044Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-21 01:52:08 PM
	first_timestamp_dt: 2025-10-21 01:52:08 PM
	last_timestamp_dt: 2025-10-21 01:52:08 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-21 13:51:42+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 90271.0205485
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-21 13:51:42+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 90271.0205514
======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 01:52:08 PM
	first_timestamp_dt: 2025-10-21 01:52:08 PM
	last_timestamp_dt: 2025-10-21 01:52:08 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-21 09:50:47+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 90216.668664
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 01:52:08 PM
	first_timestamp_dt: 2025-10-21 01:52:08 PM
	last_timestamp_dt: 2025-10-21 01:52:08 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-21 09:50:47+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 90216.668664
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 9089, 	expected_merged: 9089
	n_actual_post_annots: 5069
	n_existing_annots: 5069, 	n_new_annots: 9095, 	expected_merged: 14164

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4020 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 9089 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-21T13-52-08.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 5075
debug_test_annotations_timestamps(...):
	len(annotations_df): 6, annotation_time_range: 0 days 00:19:25.957850, annotation_time_range_num_secs: 1165.95785
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-21T13-52-08.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 6, annotation_time_range: 0 days 00:19:25.957850, annotation_time_range_num_secs: 1165.95785
trying to process XDF file 55/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T172531.902Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-21 05:25:31 PM
	first_timestamp_dt: 2025-10-21 05:25:31 PM
	last_timestamp_dt: 2025-10-21 05:25:31 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-21 17:25:09+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 103078.1179276
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-21 17:25:09+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 103078.1179303
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-21 05:25:31 PM
	first_timestamp_dt: 2025-10-21 05:25:31 PM
	last_timestamp_dt: 2025-10-21 05:25:31 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-21 13:23:28+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 102977.3713961
======== STREAM "Epoc X":
	created_at_dt: 2025-10-21 05:25:31 PM
	first_timestamp_dt: 2025-10-21 05:25:31 PM
	last_timestamp_dt: 2025-10-21 05:25:31 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-21 13:23:28+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 102977.3713961
	n_existing_annots: 0, 	n_new_annots: 8696, 	expected_merged: 8696
	n_actual_post_annots: 4068
	n_existing_annots: 4068, 	n_new_annots: 8701, 	expected_merged: 12769

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4628 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 8696 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-21T17-25-31.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 4073
debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 01:24:14.364687, annotation_time_range_num_secs: 5054.364687
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-21T17-25-31.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 01:24:14.364687, annotation_time_range_num_secs: 5054.364687
trying to process XDF file 56/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-22T115730.331Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-22 11:57:30 AM
	first_timestamp_dt: 2025-10-22 11:57:30 AM
	last_timestamp_dt: 2025-10-22 11:57:30 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-22 11:51:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 1264.0469147
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-22 11:51:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 1264.0469174
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-22 11:57:30 AM
	first_timestamp_dt: 2025-10-22 11:57:30 AM
	last_timestamp_dt: 2025-10-22 11:57:30 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-22 07:56:52+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 1570.7916
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-10-22 11:57:30 AM
	first_timestamp_dt: 2025-10-22 11:57:30 AM
	last_timestamp_dt: 2025-10-22 11:57:30 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-22 07:56:52+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 1570.7916
	n_existing_annots: 0, 	n_new_annots: 9380, 	expected_merged: 9380
	n_actual_post_annots: 5056
	n_existing_annots: 5056, 	n_new_annots: 9386, 	expected_merged: 14442

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4324 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 9380 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-22T11-57-30.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 5062
debug_test_annotations_timestamps(...):
	len(annotations_df): 6, annotation_time_range: 0 days 01:17:07.999187, annotation_time_range_num_secs: 4627.999187
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-22T11-57-30.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 6, annotation_time_range: 0 days 01:17:07.999187, annotation_time_range_num_secs: 4627.999187
trying to process XDF file 57/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-22T201127.037Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-22 08:11:27 PM
	first_timestamp_dt: 2025-10-22 08:11:27 PM
	last_timestamp_dt: 2025-10-22 08:11:27 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-22 16:10:27+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31186.8705811
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-10-22 08:11:27 PM
	first_timestamp_dt: 2025-10-22 08:11:27 PM
	last_timestamp_dt: 2025-10-22 08:11:27 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-22 16:10:27+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31186.8705811
======== STREAM "WhisperLiveLogger":
	created_at_dt: 2025-10-22 08:11:27 PM
	first_timestamp_dt: 2025-10-22 08:11:27 PM
	last_timestamp_dt: 2025-10-22 08:11:27 PM
	 failed with error:
	skipping file.
trying to process XDF file 58/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-23T062730.227Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-23 06:27:30 AM
	first_timestamp_dt: 2025-10-23 06:27:30 AM
	last_timestamp_dt: 2025-10-23 06:27:30 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-23 02:23:14+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 638.1210347
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "WhisperLiveLogger":
	created_at_dt: 2025-10-23 06:27:30 AM
	first_timestamp_dt: 2025-10-23 06:27:30 AM
	last_timestamp_dt: 2025-10-23 06:27:30 AM
	 failed with error:
	skipping file.
trying to process XDF file 59/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-23T194319.592Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-23 07:43:19 PM
	first_timestamp_dt: 2025-10-23 07:43:19 PM
	last_timestamp_dt: 2025-10-23 07:43:19 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-23 15:34:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32502.4834414
======== STREAM "Epoc X":
	created_at_dt: 2025-10-23 07:43:19 PM
	first_timestamp_dt: 2025-10-23 07:43:19 PM
	last_timestamp_dt: 2025-10-23 07:43:19 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-23 15:34:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32502.4834414
	n_existing_annots: 0, 	n_new_annots: 9553, 	expected_merged: 9553
	n_actual_post_annots: 4805
	n_existing_annots: 4805, 	n_new_annots: 9553, 	expected_merged: 14358

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4748 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 9553 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-23T19-43-19.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 4805
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-23T19-43-19.fif"
trying to process XDF file 60/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-23T205331.243Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-23 08:53:31 PM
	first_timestamp_dt: 2025-10-23 08:53:31 PM
	last_timestamp_dt: 2025-10-23 08:53:31 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-23 15:34:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32502.4834414
======== STREAM "Epoc X":
	created_at_dt: 2025-10-23 08:53:31 PM
	first_timestamp_dt: 2025-10-23 08:53:31 PM
	last_timestamp_dt: 2025-10-23 08:53:31 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-23 15:34:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 32502.4834414
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
	n_existing_annots: 0, 	n_new_annots: 2871, 	expected_merged: 2871
	n_actual_post_annots: 1764
	n_existing_annots: 1764, 	n_new_annots: 2871, 	expected_merged: 4635
	n_actual_post_annots: 1764
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-23T20-53-31.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1107 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 2871 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-23T20-53-31.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 61/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-23T221410.502Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-23 10:14:10 PM
	first_timestamp_dt: 2025-10-23 10:14:10 PM
	last_timestamp_dt: 2025-10-23 10:14:10 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-23 18:12:23+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 41957.1141676
======== STREAM "WhisperLiveLogger":
	created_at_dt: 2025-10-23 10:14:10 PM
	first_timestamp_dt: 2025-10-23 10:14:10 PM
	last_timestamp_dt: 2025-10-23 10:14:10 PM
	 failed with error:
	skipping file.
trying to process XDF file 62/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-23T231938.135Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-23 11:19:38 PM
	first_timestamp_dt: 2025-10-23 11:19:38 PM
	last_timestamp_dt: 2025-10-23 11:19:38 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-23 18:12:23+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 41957.1141676
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-23 11:19:38 PM
	first_timestamp_dt: 2025-10-23 11:19:38 PM
	last_timestamp_dt: 2025-10-23 11:19:38 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-23 18:12:23+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 41957.1141676
	n_existing_annots: 0, 	n_new_annots: 6809, 	expected_merged: 6809
	n_actual_post_annots: 3139
	n_existing_annots: 3139, 	n_new_annots: 6809, 	expected_merged: 9948

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 3670 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 6809 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-23T23-19-38.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 3139
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-23T23-19-38.fif"
trying to process XDF file 63/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-27T134738.673Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-27 01:47:38 PM
	first_timestamp_dt: 2025-10-27 01:47:38 PM
	last_timestamp_dt: 2025-10-27 01:47:38 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-27 08:44:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 353483.0892279
======== STREAM "Epoc X":
	created_at_dt: 2025-10-27 01:47:38 PM
	first_timestamp_dt: 2025-10-27 01:47:38 PM
	last_timestamp_dt: 2025-10-27 01:47:38 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-27 08:44:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 353483.0892279
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "TextLogger":
	created_at_dt: 2025-10-27 01:47:38 PM
	first_timestamp_dt: 2025-10-27 01:47:38 PM
	last_timestamp_dt: 2025-10-27 01:47:38 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-27 13:46:00+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 357171.3577758
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-27 13:46:00+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 357171.3577798
	n_existing_annots: 0, 	n_new_annots: 4975, 	expected_merged: 4975
	n_actual_post_annots: 2898
	n_existing_annots: 2898, 	n_new_annots: 5065, 	expected_merged: 7963

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2077 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 4985 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-27T13-47-38.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 2978
debug_test_annotations_timestamps(...):
	len(annotations_df): 80, annotation_time_range: 0 days 00:23:30.534232, annotation_time_range_num_secs: 1410.534232
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-27T13-47-38.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 80, annotation_time_range: 0 days 00:23:30.534232, annotation_time_range_num_secs: 1410.534232
trying to process XDF file 64/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-28T024016.200Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-28 02:40:16 AM
	first_timestamp_dt: 2025-10-28 02:40:16 AM
	last_timestamp_dt: 2025-10-28 02:40:16 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-28 02:29:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 402991.0111789
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-28 02:29:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 402991.0111835
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-28 02:40:16 AM
	first_timestamp_dt: 2025-10-28 02:40:16 AM
	last_timestamp_dt: 2025-10-28 02:40:16 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-27 22:38:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 403496.3397695
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-28 02:40:16 AM
	first_timestamp_dt: 2025-10-28 02:40:16 AM
	last_timestamp_dt: 2025-10-28 02:40:16 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-27 22:38:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 403496.3397695
======== STREAM "Epoc X":
	created_at_dt: 2025-10-28 02:40:16 AM
	first_timestamp_dt: 2025-10-28 02:40:16 AM
	last_timestamp_dt: 2025-10-28 02:40:16 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-27 22:38:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 403496.3397695
	n_existing_annots: 0, 	n_new_annots: 8726, 	expected_merged: 8726

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4367 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 4359
	n_existing_annots: 4359, 	n_new_annots: 8745, 	expected_merged: 13104

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 8726 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-28T02-40-16.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 4378
debug_test_annotations_timestamps(...):
	len(annotations_df): 19, annotation_time_range: 0 days 01:23:35.146314, annotation_time_range_num_secs: 5015.146314
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-28T02-40-16.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 19, annotation_time_range: 0 days 01:23:35.146314, annotation_time_range_num_secs: 5015.146314
trying to process XDF file 65/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-28T040425.234Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-28 04:04:25 AM
	first_timestamp_dt: 2025-10-28 04:04:25 AM
	last_timestamp_dt: 2025-10-28 04:04:25 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-27 22:38:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 403496.3397695
======== STREAM "Epoc X":
	created_at_dt: 2025-10-28 04:04:25 AM
	first_timestamp_dt: 2025-10-28 04:04:25 AM
	last_timestamp_dt: 2025-10-28 04:04:25 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-27 22:38:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 403496.3397695
======== STREAM "TextLogger":
	created_at_dt: 2025-10-28 04:04:25 AM
	first_timestamp_dt: 2025-10-28 04:04:25 AM
	last_timestamp_dt: 2025-10-28 04:04:25 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-28 02:29:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 402991.0111789
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-28 02:29:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 402991.0111835
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-28 04:04:25 AM
	first_timestamp_dt: 2025-10-28 04:04:25 AM
	last_timestamp_dt: 2025-10-28 04:04:25 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-27 22:38:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 403496.3397695
	n_existing_annots: 0, 	n_new_annots: 3693, 	expected_merged: 3693
	n_actual_post_annots: 1582
	n_existing_annots: 1582, 	n_new_annots: 3695, 	expected_merged: 5277
	n_actual_post_annots: 1584
debug_test_annotations_timestamps(...):
	len(annotations_df): 2, annotation_time_range: 0 days 00:00:03.605934, annotation_time_range_num_secs: 3.605934
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-28T04-04-25.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2111 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3693 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-28T04-04-25.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 2, annotation_time_range: 0 days 00:00:03.605934, annotation_time_range_num_secs: 3.605934
trying to process XDF file 66/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-28T192440.172Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-28 07:24:40 PM
	first_timestamp_dt: 2025-10-28 07:24:40 PM
	last_timestamp_dt: 2025-10-28 07:24:40 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-28 15:23:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 463825.7610266
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-28 07:24:40 PM
	first_timestamp_dt: 2025-10-28 07:24:40 PM
	last_timestamp_dt: 2025-10-28 07:24:40 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-28 15:23:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 463825.7610266
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-28 07:24:40 PM
	first_timestamp_dt: 2025-10-28 07:24:40 PM
	last_timestamp_dt: 2025-10-28 07:24:40 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-28 15:23:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 463825.7610266
======== STREAM "TextLogger":
	created_at_dt: 2025-10-28 07:24:40 PM
	first_timestamp_dt: 2025-10-28 07:24:40 PM
	last_timestamp_dt: 2025-10-28 07:24:40 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-28 19:22:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 463770.2989125
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-28 19:22:40+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 463770.2989224
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
	n_existing_annots: 0, 	n_new_annots: 7196, 	expected_merged: 7196

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 3432 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 7196 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 3764
	n_existing_annots: 3764, 	n_new_annots: 7198, 	expected_merged: 10962
	n_actual_post_annots: 3766
debug_test_annotations_timestamps(...):
	len(annotations_df): 2, annotation_time_range: 0 days 00:26:55.753304, annotation_time_range_num_secs: 1615.753304
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-28T19-24-40.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-28T19-24-40.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 2, annotation_time_range: 0 days 00:26:55.753304, annotation_time_range_num_secs: 1615.753304
trying to process XDF file 67/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-28T204139.491Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-28 08:41:39 PM
	first_timestamp_dt: 2025-10-28 08:41:39 PM
	last_timestamp_dt: 2025-10-28 08:41:39 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-28 15:23:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 463825.7610266
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-10-28 08:41:39 PM
	first_timestamp_dt: 2025-10-28 08:41:39 PM
	last_timestamp_dt: 2025-10-28 08:41:39 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-28 15:23:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 463825.7610266
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-28 08:41:39 PM
	first_timestamp_dt: 2025-10-28 08:41:39 PM
	last_timestamp_dt: 2025-10-28 08:41:39 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-28 15:23:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 463825.7610266
	n_existing_annots: 0, 	n_new_annots: 2337, 	expected_merged: 2337
	n_actual_post_annots: 1164
	n_existing_annots: 1164, 	n_new_annots: 2337, 	expected_merged: 3501
	n_actual_post_annots: 1164
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-28T20-41-39.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1173 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 2337 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-28T20-41-39.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 68/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-29T054820.686Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-29 05:48:20 AM
	first_timestamp_dt: 2025-10-29 05:48:20 AM
	last_timestamp_dt: 2025-10-29 05:48:20 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 01:46:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 501218.2655937
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-29 05:48:20 AM
	first_timestamp_dt: 2025-10-29 05:48:20 AM
	last_timestamp_dt: 2025-10-29 05:48:20 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 01:46:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 501218.2655937
======== STREAM "TextLogger":
	created_at_dt: 2025-10-29 05:48:20 AM
	first_timestamp_dt: 2025-10-29 05:48:20 AM
	last_timestamp_dt: 2025-10-29 05:48:20 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 05:47:25+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 501255.0365872
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-29 05:47:25+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 501255.0365914
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-29 05:48:20 AM
	first_timestamp_dt: 2025-10-29 05:48:20 AM
	last_timestamp_dt: 2025-10-29 05:48:20 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 01:46:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 501218.2655937
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
	n_existing_annots: 0, 	n_new_annots: 5730, 	expected_merged: 5730
	n_actual_post_annots: 2805
	n_existing_annots: 2805, 	n_new_annots: 5757, 	expected_merged: 8562
	n_actual_post_annots: 2832
debug_test_annotations_timestamps(...):
	len(annotations_df): 27, annotation_time_range: 0 days 00:33:49.678092, annotation_time_range_num_secs: 2029.678092

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2925 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 5730 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-29T05-48-20.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-29T05-48-20.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 27, annotation_time_range: 0 days 00:33:49.678092, annotation_time_range_num_secs: 2029.678092
trying to process XDF file 69/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-29T062306.061Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-29 06:23:06 AM
	first_timestamp_dt: 2025-10-29 06:23:06 AM
	last_timestamp_dt: 2025-10-29 06:23:06 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 05:47:25+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 501255.0365872
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-29 05:47:25+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 501255.0365914
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-29 06:23:06 AM
	first_timestamp_dt: 2025-10-29 06:23:06 AM
	last_timestamp_dt: 2025-10-29 06:23:06 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 01:46:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 501218.2655937
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-29 06:23:06 AM
	first_timestamp_dt: 2025-10-29 06:23:06 AM
	last_timestamp_dt: 2025-10-29 06:23:06 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 01:46:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 501218.2655937
======== STREAM "Epoc X":
	created_at_dt: 2025-10-29 06:23:06 AM
	first_timestamp_dt: 2025-10-29 06:23:06 AM
	last_timestamp_dt: 2025-10-29 06:23:06 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 01:46:48+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 501218.2655937
	n_existing_annots: 0, 	n_new_annots: 3347, 	expected_merged: 3347
	n_actual_post_annots: 1444
	n_existing_annots: 1444, 	n_new_annots: 3357, 	expected_merged: 4801
	n_actual_post_annots: 1454
debug_test_annotations_timestamps(...):
	len(annotations_df): 10, annotation_time_range: 0 days 00:02:40.635489, annotation_time_range_num_secs: 160.635489
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-29T06-23-06.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1903 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3347 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-29T06-23-06.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 10, annotation_time_range: 0 days 00:02:40.635489, annotation_time_range_num_secs: 160.635489
trying to process XDF file 70/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-29T133859.160Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-29 01:38:59 PM
	first_timestamp_dt: 2025-10-29 01:38:59 PM
	last_timestamp_dt: 2025-10-29 01:38:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 09:36:22+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 316.8447617
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-29 01:38:59 PM
	first_timestamp_dt: 2025-10-29 01:38:59 PM
	last_timestamp_dt: 2025-10-29 01:38:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 09:36:22+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 316.8447617
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-29 01:38:59 PM
	first_timestamp_dt: 2025-10-29 01:38:59 PM
	last_timestamp_dt: 2025-10-29 01:38:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 09:36:22+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 316.8447617
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-10-29 01:38:59 PM
	first_timestamp_dt: 2025-10-29 01:38:59 PM
	last_timestamp_dt: 2025-10-29 01:38:59 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 13:37:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 387.6350936
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-29 13:37:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 387.6350981
	n_existing_annots: 0, 	n_new_annots: 14157, 	expected_merged: 14157
	n_actual_post_annots: 8527

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 5630 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_existing_annots: 8527, 	n_new_annots: 14178, 	expected_merged: 22705

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 14157 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-29T13-38-59.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 8548
debug_test_annotations_timestamps(...):
	len(annotations_df): 21, annotation_time_range: 0 days 01:27:37.695900, annotation_time_range_num_secs: 5257.6959
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-29T13-38-59.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 21, annotation_time_range: 0 days 01:27:37.695900, annotation_time_range_num_secs: 5257.6959
trying to process XDF file 71/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-29T173858.018Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-29 05:38:58 PM
	first_timestamp_dt: 2025-10-29 05:38:58 PM
	last_timestamp_dt: 2025-10-29 05:38:58 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 13:31:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 14397.7245047
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-29 05:38:58 PM
	first_timestamp_dt: 2025-10-29 05:38:58 PM
	last_timestamp_dt: 2025-10-29 05:38:58 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 13:31:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 14397.7245047
======== STREAM "TextLogger":
	created_at_dt: 2025-10-29 05:38:58 PM
	first_timestamp_dt: 2025-10-29 05:38:58 PM
	last_timestamp_dt: 2025-10-29 05:38:58 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 17:30:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 14340.2783281
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-29 17:30:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 14340.2783324
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-29 05:38:58 PM
	first_timestamp_dt: 2025-10-29 05:38:58 PM
	last_timestamp_dt: 2025-10-29 05:38:58 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 13:31:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 14397.7245047
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
	n_existing_annots: 0, 	n_new_annots: 10550, 	expected_merged: 10550
	n_actual_post_annots: 5024
	n_existing_annots: 5024, 	n_new_annots: 10564, 	expected_merged: 15588

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 5526 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 10550 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-29T17-38-58.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 5038
debug_test_annotations_timestamps(...):
	len(annotations_df): 14, annotation_time_range: 0 days 00:36:19.905025, annotation_time_range_num_secs: 2179.905025
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-29T17-38-58.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 14, annotation_time_range: 0 days 00:36:19.905025, annotation_time_range_num_secs: 2179.905025
trying to process XDF file 72/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-29T213604.784Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-29 09:36:04 PM
	first_timestamp_dt: 2025-10-29 09:36:04 PM
	last_timestamp_dt: 2025-10-29 09:36:04 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 17:34:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 29008.3681331
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-29 09:36:04 PM
	first_timestamp_dt: 2025-10-29 09:36:04 PM
	last_timestamp_dt: 2025-10-29 09:36:04 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 17:34:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 29008.3681331
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-10-29 09:36:04 PM
	first_timestamp_dt: 2025-10-29 09:36:04 PM
	last_timestamp_dt: 2025-10-29 09:36:04 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 19:57:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 23199.8480465
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-29 19:57:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 23199.8480504
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-29 09:36:04 PM
	first_timestamp_dt: 2025-10-29 09:36:04 PM
	last_timestamp_dt: 2025-10-29 09:36:04 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-29 17:34:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 29008.3681331
	n_existing_annots: 0, 	n_new_annots: 13348, 	expected_merged: 13348

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 7195 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 6153
	n_existing_annots: 6153, 	n_new_annots: 13356, 	expected_merged: 19509

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 13348 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-29T21-36-04.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 6161
debug_test_annotations_timestamps(...):
	len(annotations_df): 8, annotation_time_range: 0 days 01:09:38.969701, annotation_time_range_num_secs: 4178.969701
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-29T21-36-04.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 8, annotation_time_range: 0 days 01:09:38.969701, annotation_time_range_num_secs: 4178.969701
trying to process XDF file 73/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-30T193005.610Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-10-30 07:30:05 PM
	first_timestamp_dt: 2025-10-30 07:30:05 PM
	last_timestamp_dt: 2025-10-30 07:30:05 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-30 15:21:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 24055.8357324
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-30 07:30:05 PM
	first_timestamp_dt: 2025-10-30 07:30:05 PM
	last_timestamp_dt: 2025-10-30 07:30:05 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-30 15:21:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 24055.8357324
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-30 07:30:05 PM
	first_timestamp_dt: 2025-10-30 07:30:05 PM
	last_timestamp_dt: 2025-10-30 07:30:05 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-30 15:21:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 24055.8357324
	n_existing_annots: 0, 	n_new_annots: 2007, 	expected_merged: 2007
	n_actual_post_annots: 1140
	n_existing_annots: 1140, 	n_new_annots: 2007, 	expected_merged: 3147
	n_actual_post_annots: 1140
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-30T19-30-05.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 867 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 2007 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-30T19-30-05.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 74/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-31T041919.680Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-31 04:19:19 AM
	first_timestamp_dt: 2025-10-31 04:19:19 AM
	last_timestamp_dt: 2025-10-31 04:19:19 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-31 00:17:09+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 56219.7065599
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-31 04:19:19 AM
	first_timestamp_dt: 2025-10-31 04:19:19 AM
	last_timestamp_dt: 2025-10-31 04:19:19 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-31 00:17:09+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 56219.7065599
======== STREAM "Epoc X":
	created_at_dt: 2025-10-31 04:19:19 AM
	first_timestamp_dt: 2025-10-31 04:19:19 AM
	last_timestamp_dt: 2025-10-31 04:19:19 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-31 00:17:09+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 56219.7065599
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-10-31 04:19:19 AM
	first_timestamp_dt: 2025-10-31 04:19:19 AM
	last_timestamp_dt: 2025-10-31 04:19:19 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-31 04:18:12+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 56282.4976533
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-31 04:18:12+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 56282.4976623
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
	n_existing_annots: 0, 	n_new_annots: 10611, 	expected_merged: 10611
	n_actual_post_annots: 5726
	n_existing_annots: 5726, 	n_new_annots: 10910, 	expected_merged: 16636

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4885 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 10611 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-31T04-19-19.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 6025
debug_test_annotations_timestamps(...):
	len(annotations_df): 299, annotation_time_range: 0 days 00:52:12.941899, annotation_time_range_num_secs: 3132.941899
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-31T04-19-19.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 299, annotation_time_range: 0 days 00:52:12.941899, annotation_time_range_num_secs: 3132.941899
trying to process XDF file 75/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-31T212433.122Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-10-31 09:24:33 PM
	first_timestamp_dt: 2025-10-31 09:24:33 PM
	last_timestamp_dt: 2025-10-31 09:24:33 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-31 21:21:59+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 22054.4273866
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-10-31 21:21:59+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 22054.4273994
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-10-31 09:24:33 PM
	first_timestamp_dt: 2025-10-31 09:24:33 PM
	last_timestamp_dt: 2025-10-31 09:24:33 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-31 21:24:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 22178.0406171
======== STREAM "Epoc X":
	created_at_dt: 2025-10-31 09:24:33 PM
	first_timestamp_dt: 2025-10-31 09:24:33 PM
	last_timestamp_dt: 2025-10-31 09:24:33 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-31 21:24:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 22178.0406171
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-10-31 09:24:33 PM
	first_timestamp_dt: 2025-10-31 09:24:33 PM
	last_timestamp_dt: 2025-10-31 09:24:33 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-10-31 21:24:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 22178.0406171
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 20791, 	expected_merged: 20791

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 10967 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 9824
	n_existing_annots: 9824, 	n_new_annots: 20845, 	expected_merged: 30669

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 11002 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-10-31T21-24-33.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 19667
debug_test_annotations_timestamps(...):
	len(annotations_df): 54, annotation_time_range: 0 days 01:37:36.156155, annotation_time_range_num_secs: 5856.156155
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-10-31T21-24-33.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 54, annotation_time_range: 0 days 01:37:36.156155, annotation_time_range_num_secs: 5856.156155
trying to process XDF file 76/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-03T133558.299Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-11-03 01:35:58 PM
	first_timestamp_dt: 2025-11-03 01:35:58 PM
	last_timestamp_dt: 2025-11-03 01:35:58 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-03 13:34:09+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 13382.2372838
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-03 13:34:09+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 13382.2372878
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-03 01:35:58 PM
	first_timestamp_dt: 2025-11-03 01:35:58 PM
	last_timestamp_dt: 2025-11-03 01:35:58 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-03 13:33:41+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 13353.8771662
======== STREAM "Epoc X":
	created_at_dt: 2025-11-03 01:35:58 PM
	first_timestamp_dt: 2025-11-03 01:35:58 PM
	last_timestamp_dt: 2025-11-03 01:35:58 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-03 13:33:41+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 13353.8771662
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-03 01:35:58 PM
	first_timestamp_dt: 2025-11-03 01:35:58 PM
	last_timestamp_dt: 2025-11-03 01:35:58 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-03 13:33:41+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 13353.8771662
	n_existing_annots: 0, 	n_new_annots: 12022, 	expected_merged: 12022
	n_actual_post_annots: 5209
	n_existing_annots: 5209, 	n_new_annots: 12237, 	expected_merged: 17446

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 6813 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 6904 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-03T13-35-58.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 10542
debug_test_annotations_timestamps(...):
	len(annotations_df): 215, annotation_time_range: 0 days 00:42:01.783655, annotation_time_range_num_secs: 2521.783655
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-03T13-35-58.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 215, annotation_time_range: 0 days 00:42:01.783655, annotation_time_range_num_secs: 2521.783655
trying to process XDF file 77/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-04T105347.435Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-11-04 10:53:47 AM
	first_timestamp_dt: 2025-11-04 10:53:47 AM
	last_timestamp_dt: 2025-11-04 10:53:47 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-04 10:53:12+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 90123.9789901
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-04 10:53:12+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 90123.9790084
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-04 10:53:47 AM
	first_timestamp_dt: 2025-11-04 10:53:47 AM
	last_timestamp_dt: 2025-11-04 10:53:47 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-04 10:52:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 90084.3203884
======== STREAM "Epoc X":
	created_at_dt: 2025-11-04 10:53:47 AM
	first_timestamp_dt: 2025-11-04 10:53:47 AM
	last_timestamp_dt: 2025-11-04 10:53:47 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-04 10:52:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 90084.3203884
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-04 10:53:47 AM
	first_timestamp_dt: 2025-11-04 10:53:47 AM
	last_timestamp_dt: 2025-11-04 10:53:47 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-04 10:52:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 90084.3203884
	n_existing_annots: 0, 	n_new_annots: 8919, 	expected_merged: 8919
	n_actual_post_annots: 4585
	n_existing_annots: 4585, 	n_new_annots: 8927, 	expected_merged: 13512

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4334 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 4431 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-04T10-53-47.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 9081
debug_test_annotations_timestamps(...):
	len(annotations_df): 8, annotation_time_range: 0 days 01:16:30.398465, annotation_time_range_num_secs: 4590.398465
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-04T10-53-47.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 8, annotation_time_range: 0 days 01:16:30.398465, annotation_time_range_num_secs: 4590.398465
trying to process XDF file 78/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-04T200752.400Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-11-04 08:07:52 PM
	first_timestamp_dt: 2025-11-04 08:07:52 PM
	last_timestamp_dt: 2025-11-04 08:07:52 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-04 20:07:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 123387.956941
======== STREAM "TextLogger":
	created_at_dt: 2025-11-04 08:07:52 PM
	first_timestamp_dt: 2025-11-04 08:07:52 PM
	last_timestamp_dt: 2025-11-04 08:07:52 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-04 20:07:13+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 123364.6009927
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-04 20:07:13+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 123364.6009969
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-04 08:07:52 PM
	first_timestamp_dt: 2025-11-04 08:07:52 PM
	last_timestamp_dt: 2025-11-04 08:07:52 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-04 20:07:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 123387.956941
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-04 08:07:52 PM
	first_timestamp_dt: 2025-11-04 08:07:52 PM
	last_timestamp_dt: 2025-11-04 08:07:52 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-04 20:07:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 123387.956941
	n_existing_annots: 0, 	n_new_annots: 13613, 	expected_merged: 13613
	n_actual_post_annots: 7028

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 6585 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_existing_annots: 7028, 	n_new_annots: 13634, 	expected_merged: 20662

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 6567 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-04T20-07-52.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 14095
debug_test_annotations_timestamps(...):
	len(annotations_df): 21, annotation_time_range: 0 days 01:32:50.202347, annotation_time_range_num_secs: 5570.202347
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-04T20-07-52.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 21, annotation_time_range: 0 days 01:32:50.202347, annotation_time_range_num_secs: 5570.202347
trying to process XDF file 79/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-05T202621.126Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-05 08:26:21 PM
	first_timestamp_dt: 2025-11-05 08:26:21 PM
	last_timestamp_dt: 2025-11-05 08:26:21 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-05 20:25:06+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 33900.2192236
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-05 08:26:21 PM
	first_timestamp_dt: 2025-11-05 08:26:21 PM
	last_timestamp_dt: 2025-11-05 08:26:21 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-05 20:25:06+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 33900.2192236
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-05 08:26:21 PM
	first_timestamp_dt: 2025-11-05 08:26:21 PM
	last_timestamp_dt: 2025-11-05 08:26:21 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-05 20:25:06+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 33900.2192236
======== STREAM "TextLogger":
	created_at_dt: 2025-11-05 08:26:21 PM
	first_timestamp_dt: 2025-11-05 08:26:21 PM
	last_timestamp_dt: 2025-11-05 08:26:21 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-05 20:22:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 33746.8341364
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-05 20:22:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 33746.8341403
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
	n_existing_annots: 0, 	n_new_annots: 10880, 	expected_merged: 10880
	n_actual_post_annots: 5570
	n_existing_annots: 5570, 	n_new_annots: 10895, 	expected_merged: 16465

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 5310 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 5392 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-05T20-26-21.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 11073
debug_test_annotations_timestamps(...):
	len(annotations_df): 15, annotation_time_range: 0 days 00:28:39.198668, annotation_time_range_num_secs: 1719.198668
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-05T20-26-21.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 15, annotation_time_range: 0 days 00:28:39.198668, annotation_time_range_num_secs: 1719.198668
trying to process XDF file 80/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-06T131841.457Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-06 01:18:41 PM
	first_timestamp_dt: 2025-11-06 01:18:41 PM
	last_timestamp_dt: 2025-11-06 01:18:41 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-06 13:18:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 4015.7265041
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "TextLogger":
	created_at_dt: 2025-11-06 01:18:41 PM
	first_timestamp_dt: 2025-11-06 01:18:41 PM
	last_timestamp_dt: 2025-11-06 01:18:41 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-06 13:16:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3888.2678793
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-06 13:16:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 3888.2678828
======== STREAM "Epoc X":
	created_at_dt: 2025-11-06 01:18:41 PM
	first_timestamp_dt: 2025-11-06 01:18:41 PM
	last_timestamp_dt: 2025-11-06 01:18:41 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-06 13:18:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 4015.7265041
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-06 01:18:41 PM
	first_timestamp_dt: 2025-11-06 01:18:41 PM
	last_timestamp_dt: 2025-11-06 01:18:41 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-06 13:18:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 4015.7265041
	n_existing_annots: 0, 	n_new_annots: 17193, 	expected_merged: 17193
	n_actual_post_annots: 8362

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 8831 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_existing_annots: 8362, 	n_new_annots: 18020, 	expected_merged: 26382

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 8849 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-06T13-18-41.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 17533
debug_test_annotations_timestamps(...):
	len(annotations_df): 827, annotation_time_range: 0 days 01:43:58.379597, annotation_time_range_num_secs: 6238.379597
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-06T13-18-41.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 827, annotation_time_range: 0 days 01:43:58.379597, annotation_time_range_num_secs: 6238.379597
trying to process XDF file 81/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-06T150252.171Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-11-06 03:02:52 PM
	first_timestamp_dt: 2025-11-06 03:02:52 PM
	last_timestamp_dt: 2025-11-06 03:02:52 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-06 13:16:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3888.2678793
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-06 13:16:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 3888.2678828
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-06 03:02:52 PM
	first_timestamp_dt: 2025-11-06 03:02:52 PM
	last_timestamp_dt: 2025-11-06 03:02:52 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-06 13:18:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 4015.7265041
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-06 03:02:52 PM
	first_timestamp_dt: 2025-11-06 03:02:52 PM
	last_timestamp_dt: 2025-11-06 03:02:52 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-06 13:18:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 4015.7265041
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-06 03:02:52 PM
	first_timestamp_dt: 2025-11-06 03:02:52 PM
	last_timestamp_dt: 2025-11-06 03:02:52 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-06 13:18:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 4015.7265041
	n_existing_annots: 0, 	n_new_annots: 19, 	expected_merged: 19
	n_actual_post_annots: 11
	n_existing_annots: 11, 	n_new_annots: 660, 	expected_merged: 671
	n_actual_post_annots: 12

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 8 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 659 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-06T15-02-52.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-06T15-02-52.fif"
trying to process XDF file 82/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-06T185825.201Z_eeg.xdf"...
	 failed with error: 'NoneType' object is not subscriptable
	skipping file.
trying to process XDF file 83/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-06T185901.803Z_eeg.xdf"...
	 failed with error: 'NoneType' object is not subscriptable
	skipping file.
trying to process XDF file 84/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-06T190831.325Z_eeg.xdf"...
	 failed with error: 'NoneType' object is not subscriptable
	skipping file.
trying to process XDF file 85/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-10T192805.239Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-11-10 07:28:05 PM
	first_timestamp_dt: 2025-11-10 07:28:05 PM
	last_timestamp_dt: 2025-11-10 07:28:05 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-10 19:27:26+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 18166.6394303
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-10 19:27:26+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 18166.6394339
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-10 07:28:05 PM
	first_timestamp_dt: 2025-11-10 07:28:05 PM
	last_timestamp_dt: 2025-11-10 07:28:05 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-10 19:27:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 18186.0775719
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "Epoc X":
	created_at_dt: 2025-11-10 07:28:05 PM
	first_timestamp_dt: 2025-11-10 07:28:05 PM
	last_timestamp_dt: 2025-11-10 07:28:05 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-10 19:27:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 18186.0775719
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-10 07:28:05 PM
	first_timestamp_dt: 2025-11-10 07:28:05 PM
	last_timestamp_dt: 2025-11-10 07:28:05 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-10 19:27:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 18186.0775719
	n_existing_annots: 0, 	n_new_annots: 1564, 	expected_merged: 1564
	n_actual_post_annots: 829
	n_existing_annots: 829, 	n_new_annots: 1568, 	expected_merged: 2397
	n_actual_post_annots: 1639
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-10T19-28-05.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 735 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 758 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-10T19-28-05.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 86/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-10T201101.861Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-10 08:11:01 PM
	first_timestamp_dt: 2025-11-10 08:11:01 PM
	last_timestamp_dt: 2025-11-10 08:11:01 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-10 19:27:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 18186.0775719
	 failed with error: len(data) (0) does not match len(info["ch_names"]) (6)
	skipping file.
trying to process XDF file 87/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-11T222222.616Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-11-11 10:22:22 PM
	first_timestamp_dt: 2025-11-11 10:22:22 PM
	last_timestamp_dt: 2025-11-11 10:22:22 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-11 22:21:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 115016.8282726
======== STREAM "TextLogger":
	created_at_dt: 2025-11-11 10:22:22 PM
	first_timestamp_dt: 2025-11-11 10:22:22 PM
	last_timestamp_dt: 2025-11-11 10:22:22 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-11 22:21:46+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 115026.7978407
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-11 22:21:46+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 115026.7978452
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-11 10:22:22 PM
	first_timestamp_dt: 2025-11-11 10:22:22 PM
	last_timestamp_dt: 2025-11-11 10:22:22 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-11 22:21:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 115016.8282726
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-11 10:22:22 PM
	first_timestamp_dt: 2025-11-11 10:22:22 PM
	last_timestamp_dt: 2025-11-11 10:22:22 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-11 22:21:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 115016.8282726
	n_existing_annots: 0, 	n_new_annots: 13320, 	expected_merged: 13320
	n_actual_post_annots: 7339

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 5981 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_existing_annots: 7339, 	n_new_annots: 13326, 	expected_merged: 20665

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 6022 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-11T22-22-22.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 14643
debug_test_annotations_timestamps(...):
	len(annotations_df): 6, annotation_time_range: 0 days 02:05:00.301689, annotation_time_range_num_secs: 7500.301689
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-11T22-22-22.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 6, annotation_time_range: 0 days 02:05:00.301689, annotation_time_range_num_secs: 7500.301689
trying to process XDF file 88/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-12T171146.441Z_eeg.xdf"...
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-12 05:11:46 PM
	first_timestamp_dt: 2025-11-12 05:11:46 PM
	last_timestamp_dt: 2025-11-12 05:11:46 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-12 17:10:38+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 182759.2789677
======== STREAM "Epoc X":
	created_at_dt: 2025-11-12 05:11:46 PM
	first_timestamp_dt: 2025-11-12 05:11:46 PM
	last_timestamp_dt: 2025-11-12 05:11:46 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-12 17:10:38+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 182759.2789677
======== STREAM "TextLogger":
	created_at_dt: 2025-11-12 05:11:46 PM
	first_timestamp_dt: 2025-11-12 05:11:46 PM
	last_timestamp_dt: 2025-11-12 05:11:46 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-12 17:10:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 182726.3307129
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-12 17:10:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 182726.3307214
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-12 05:11:46 PM
	first_timestamp_dt: 2025-11-12 05:11:46 PM
	last_timestamp_dt: 2025-11-12 05:11:46 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-12 17:10:38+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 182759.2789677
	n_existing_annots: 0, 	n_new_annots: 13328, 	expected_merged: 13328

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 7400 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 5928
	n_existing_annots: 5928, 	n_new_annots: 13340, 	expected_merged: 19268

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 7419 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-12T17-11-46.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 11849
debug_test_annotations_timestamps(...):
	len(annotations_df): 12, annotation_time_range: 0 days 01:15:55.917580, annotation_time_range_num_secs: 4555.91758
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-12T17-11-46.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 12, annotation_time_range: 0 days 01:15:55.917580, annotation_time_range_num_secs: 4555.91758
trying to process XDF file 89/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-13T124711.812Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-13 12:47:11 PM
	first_timestamp_dt: 2025-11-13 12:47:11 PM
	last_timestamp_dt: 2025-11-13 12:47:11 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 12:47:00+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 7992.8812037
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-13 12:47:11 PM
	first_timestamp_dt: 2025-11-13 12:47:11 PM
	last_timestamp_dt: 2025-11-13 12:47:11 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 12:47:00+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 7992.8812037
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	created_at_dt: 2025-11-13 12:47:11 PM
	first_timestamp_dt: 2025-11-13 12:47:11 PM
	last_timestamp_dt: 2025-11-13 12:47:11 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 12:01:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 5252.6060399
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-13 12:01:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 5252.6060443
======== STREAM "Epoc X":
	created_at_dt: 2025-11-13 12:47:11 PM
	first_timestamp_dt: 2025-11-13 12:47:11 PM
	last_timestamp_dt: 2025-11-13 12:47:11 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 12:47:00+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 7992.8812037
	n_existing_annots: 0, 	n_new_annots: 1253, 	expected_merged: 1253
	n_actual_post_annots: 608
	n_existing_annots: 608, 	n_new_annots: 1258, 	expected_merged: 1866
	n_actual_post_annots: 1208
debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 00:01:13.219790, annotation_time_range_num_secs: 73.21979
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-13T12-47-11.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 645 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 658 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-13T12-47-11.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 00:01:13.219790, annotation_time_range_num_secs: 73.21979
trying to process XDF file 90/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-13T132514.888Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-13 01:25:14 PM
	first_timestamp_dt: 2025-11-13 01:25:14 PM
	last_timestamp_dt: 2025-11-13 01:25:14 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 13:25:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 10278.1871402
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "TextLogger":
	created_at_dt: 2025-11-13 01:25:14 PM
	first_timestamp_dt: 2025-11-13 01:25:14 PM
	last_timestamp_dt: 2025-11-13 01:25:14 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 13:24:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 10244.71895
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-13 13:24:32+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 10244.7189628
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-13 01:25:14 PM
	first_timestamp_dt: 2025-11-13 01:25:14 PM
	last_timestamp_dt: 2025-11-13 01:25:14 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 13:25:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 10278.1871402
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-13 01:25:14 PM
	first_timestamp_dt: 2025-11-13 01:25:14 PM
	last_timestamp_dt: 2025-11-13 01:25:14 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 13:25:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 10278.1871402
	n_existing_annots: 0, 	n_new_annots: 5274, 	expected_merged: 5274
	n_actual_post_annots: 2744
	n_existing_annots: 2744, 	n_new_annots: 5320, 	expected_merged: 8064

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2530 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 2543 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-13T13-25-14.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 5521
debug_test_annotations_timestamps(...):
	len(annotations_df): 46, annotation_time_range: 0 days 00:39:59.730016, annotation_time_range_num_secs: 2399.730016
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-13T13-25-14.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 46, annotation_time_range: 0 days 00:39:59.730016, annotation_time_range_num_secs: 2399.730016
trying to process XDF file 91/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-13T191927.251Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-13 07:19:27 PM
	first_timestamp_dt: 2025-11-13 07:19:27 PM
	last_timestamp_dt: 2025-11-13 07:19:27 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 19:19:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31520.1923745
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-13 07:19:27 PM
	first_timestamp_dt: 2025-11-13 07:19:27 PM
	last_timestamp_dt: 2025-11-13 07:19:27 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 19:19:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31520.1923745
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-13 07:19:27 PM
	first_timestamp_dt: 2025-11-13 07:19:27 PM
	last_timestamp_dt: 2025-11-13 07:19:27 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 19:19:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31520.1923745
======== STREAM "TextLogger":
	created_at_dt: 2025-11-13 07:19:27 PM
	first_timestamp_dt: 2025-11-13 07:19:27 PM
	last_timestamp_dt: 2025-11-13 07:19:27 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 19:17:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31446.8693349
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-13 19:17:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 31446.869339
	n_existing_annots: 0, 	n_new_annots: 1467, 	expected_merged: 1467
	n_actual_post_annots: 732
	n_existing_annots: 732, 	n_new_annots: 1472, 	expected_merged: 2204
	n_actual_post_annots: 1459
debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 00:12:42.212381, annotation_time_range_num_secs: 762.212381
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-13T19-19-27.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 735 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 745 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-13T19-19-27.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 00:12:42.212381, annotation_time_range_num_secs: 762.212381
trying to process XDF file 92/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-13T194919.223Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-11-13 07:49:19 PM
	first_timestamp_dt: 2025-11-13 07:49:19 PM
	last_timestamp_dt: 2025-11-13 07:49:19 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 19:17:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31446.8693349
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-13 19:17:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 31446.869339
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-13 07:49:19 PM
	first_timestamp_dt: 2025-11-13 07:49:19 PM
	last_timestamp_dt: 2025-11-13 07:49:19 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 19:19:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31520.1923745
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-13 07:49:19 PM
	first_timestamp_dt: 2025-11-13 07:49:19 PM
	last_timestamp_dt: 2025-11-13 07:49:19 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 19:19:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31520.1923745
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-13 07:49:19 PM
	first_timestamp_dt: 2025-11-13 07:49:19 PM
	last_timestamp_dt: 2025-11-13 07:49:19 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 19:19:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31520.1923745
	n_existing_annots: 0, 	n_new_annots: 4340, 	expected_merged: 4340
	n_actual_post_annots: 2047
	n_existing_annots: 2047, 	n_new_annots: 4343, 	expected_merged: 6390
	n_actual_post_annots: 4319
debug_test_annotations_timestamps(...):
	len(annotations_df): 3, annotation_time_range: 0 days 00:00:05.456246, annotation_time_range_num_secs: 5.456246
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-13T19-49-19.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2293 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 2071 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-13T19-49-19.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 3, annotation_time_range: 0 days 00:00:05.456246, annotation_time_range_num_secs: 5.456246
trying to process XDF file 93/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-13T230537.397Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-11-13 11:05:37 PM
	first_timestamp_dt: 2025-11-13 11:05:37 PM
	last_timestamp_dt: 2025-11-13 11:05:37 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 23:04:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 45058.3742294
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-13 11:05:37 PM
	first_timestamp_dt: 2025-11-13 11:05:37 PM
	last_timestamp_dt: 2025-11-13 11:05:37 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 23:04:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 45058.3742294
======== STREAM "TextLogger":
	created_at_dt: 2025-11-13 11:05:37 PM
	first_timestamp_dt: 2025-11-13 11:05:37 PM
	last_timestamp_dt: 2025-11-13 11:05:37 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 19:17:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 31446.8693349
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-13 19:17:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 31446.869339
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-13 11:05:37 PM
	first_timestamp_dt: 2025-11-13 11:05:37 PM
	last_timestamp_dt: 2025-11-13 11:05:37 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-13 23:04:45+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 45058.3742294
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 6991, 	expected_merged: 6991
	n_actual_post_annots: 3941
	n_existing_annots: 3941, 	n_new_annots: 7002, 	expected_merged: 10943

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 3050 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3039 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 7904
debug_test_annotations_timestamps(...):
	len(annotations_df): 11, annotation_time_range: 0 days 00:50:56.364771, annotation_time_range_num_secs: 3056.364771
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-13T23-05-37.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-13T23-05-37.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 11, annotation_time_range: 0 days 00:50:56.364771, annotation_time_range_num_secs: 3056.364771
trying to process XDF file 94/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-14T131135.732Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-11-14 01:11:35 PM
	first_timestamp_dt: 2025-11-14 01:11:35 PM
	last_timestamp_dt: 2025-11-14 01:11:35 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-14 13:10:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 95808.0539841
======== STREAM "TextLogger":
	created_at_dt: 2025-11-14 01:11:35 PM
	first_timestamp_dt: 2025-11-14 01:11:35 PM
	last_timestamp_dt: 2025-11-14 01:11:35 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-14 09:53:50+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 84003.1183489
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-14 09:53:50+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 84003.1183546
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-14 01:11:35 PM
	first_timestamp_dt: 2025-11-14 01:11:35 PM
	last_timestamp_dt: 2025-11-14 01:11:35 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-14 13:10:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 95808.0539841
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-14 01:11:35 PM
	first_timestamp_dt: 2025-11-14 01:11:35 PM
	last_timestamp_dt: 2025-11-14 01:11:35 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-14 13:10:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 95808.0539841
	n_existing_annots: 0, 	n_new_annots: 12195, 	expected_merged: 12195
	n_actual_post_annots: 6708
	n_existing_annots: 6708, 	n_new_annots: 12202, 	expected_merged: 18910

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 5487 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 5512 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-14T13-11-35.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 13398
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 01:16:00.414721, annotation_time_range_num_secs: 4560.414721
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-14T13-11-35.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 01:16:00.414721, annotation_time_range_num_secs: 4560.414721
trying to process XDF file 95/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-14T193359.345Z_eeg.xdf"...
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-14 07:33:59 PM
	first_timestamp_dt: 2025-11-14 07:33:59 PM
	last_timestamp_dt: 2025-11-14 07:33:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-14 19:33:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 118754.8137985
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-14 07:33:59 PM
	first_timestamp_dt: 2025-11-14 07:33:59 PM
	last_timestamp_dt: 2025-11-14 07:33:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-14 19:33:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 118754.8137985
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "TextLogger":
	created_at_dt: 2025-11-14 07:33:59 PM
	first_timestamp_dt: 2025-11-14 07:33:59 PM
	last_timestamp_dt: 2025-11-14 07:33:59 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-14 09:53:50+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 84003.1183489
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-14 09:53:50+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 84003.1183546
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-14 07:33:59 PM
	first_timestamp_dt: 2025-11-14 07:33:59 PM
	last_timestamp_dt: 2025-11-14 07:33:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-14 19:33:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 118754.8137985
	n_existing_annots: 0, 	n_new_annots: 11257, 	expected_merged: 11257
	n_actual_post_annots: 5665
	n_existing_annots: 5665, 	n_new_annots: 11297, 	expected_merged: 16962

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 5592 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 5615 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-14T19-33-59.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 11347
debug_test_annotations_timestamps(...):
	len(annotations_df): 40, annotation_time_range: 0 days 00:47:36.635519, annotation_time_range_num_secs: 2856.635519
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-14T19-33-59.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 40, annotation_time_range: 0 days 00:47:36.635519, annotation_time_range_num_secs: 2856.635519
trying to process XDF file 96/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-17T142443.651Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-17 02:24:43 PM
	first_timestamp_dt: 2025-11-17 02:24:43 PM
	last_timestamp_dt: 2025-11-17 02:24:43 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-17 14:24:08+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 359417.7975368
======== STREAM "TextLogger":
	created_at_dt: 2025-11-17 02:24:43 PM
	first_timestamp_dt: 2025-11-17 02:24:43 PM
	last_timestamp_dt: 2025-11-17 02:24:43 PM
	 failed with error: 'NoneType' object is not iterable
	skipping file.
trying to process XDF file 97/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-17T181736.294Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-17 06:17:36 PM
	first_timestamp_dt: 2025-11-17 06:17:36 PM
	last_timestamp_dt: 2025-11-17 06:17:36 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-17 18:16:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 373384.2790763
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-17 06:17:36 PM
	first_timestamp_dt: 2025-11-17 06:17:36 PM
	last_timestamp_dt: 2025-11-17 06:17:36 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-17 18:16:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 373384.2790763
======== STREAM "Epoc X":
	created_at_dt: 2025-11-17 06:17:36 PM
	first_timestamp_dt: 2025-11-17 06:17:36 PM
	last_timestamp_dt: 2025-11-17 06:17:36 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-17 18:16:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 373384.2790763
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
	n_existing_annots: 0, 	n_new_annots: 20158, 	expected_merged: 20158

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 9869 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 10289
	n_existing_annots: 10289, 	n_new_annots: 20158, 	expected_merged: 30447

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 9853 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-17T18-17-36.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 20594
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-17T18-17-36.fif"
trying to process XDF file 98/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-18T001005.371Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-18 12:10:05 AM
	first_timestamp_dt: 2025-11-18 12:10:05 AM
	last_timestamp_dt: 2025-11-18 12:10:05 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-18 00:07:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 10827.5510308
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-18 12:10:05 AM
	first_timestamp_dt: 2025-11-18 12:10:05 AM
	last_timestamp_dt: 2025-11-18 12:10:05 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-18 00:07:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 10827.5510308
======== STREAM "Epoc X":
	created_at_dt: 2025-11-18 12:10:05 AM
	first_timestamp_dt: 2025-11-18 12:10:05 AM
	last_timestamp_dt: 2025-11-18 12:10:05 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-18 00:07:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 10827.5510308
	n_existing_annots: 0, 	n_new_annots: 9094, 	expected_merged: 9094
	n_actual_post_annots: 4749
	n_existing_annots: 4749, 	n_new_annots: 9094, 	expected_merged: 13843

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4345 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 4380 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-18T00-10-05.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 9463
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-18T00-10-05.fif"
trying to process XDF file 99/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-18T020918.340Z_eeg.xdf"...
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-18 02:09:18 AM
	first_timestamp_dt: 2025-11-18 02:09:18 AM
	last_timestamp_dt: 2025-11-18 02:09:18 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-18 02:08:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 18102.1135059
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-18 02:09:18 AM
	first_timestamp_dt: 2025-11-18 02:09:18 AM
	last_timestamp_dt: 2025-11-18 02:09:18 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-18 02:08:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 18102.1135059
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-18 02:09:18 AM
	first_timestamp_dt: 2025-11-18 02:09:18 AM
	last_timestamp_dt: 2025-11-18 02:09:18 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-18 02:08:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 18102.1135059
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 8062, 	expected_merged: 8062
	n_actual_post_annots: 4174
	n_existing_annots: 4174, 	n_new_annots: 8062, 	expected_merged: 12236

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 3888 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3859 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-18T02-09-18.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 8377
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-18T02-09-18.fif"
trying to process XDF file 100/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-19T102728.216Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-11-19 10:27:28 AM
	first_timestamp_dt: 2025-11-19 10:27:28 AM
	last_timestamp_dt: 2025-11-19 10:27:28 AM
	 failed with error: 'NoneType' object is not iterable
	skipping file.
trying to process XDF file 101/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-19T155821.538Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-19 03:58:21 PM
	first_timestamp_dt: 2025-11-19 03:58:21 PM
	last_timestamp_dt: 2025-11-19 03:58:21 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 15:57:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 66261.1231403
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-19 03:58:21 PM
	first_timestamp_dt: 2025-11-19 03:58:21 PM
	last_timestamp_dt: 2025-11-19 03:58:21 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 15:57:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 66261.1231403
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-19 03:58:21 PM
	first_timestamp_dt: 2025-11-19 03:58:21 PM
	last_timestamp_dt: 2025-11-19 03:58:21 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 15:57:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 66261.1231403
	n_existing_annots: 0, 	n_new_annots: 6666, 	expected_merged: 6666
	n_actual_post_annots: 2941
	n_existing_annots: 2941, 	n_new_annots: 6666, 	expected_merged: 9607

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 3725 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3755 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 5852
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-19T15-58-21.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-19T15-58-21.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 102/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-19T191014.806Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-19 07:10:14 PM
	first_timestamp_dt: 2025-11-19 07:10:14 PM
	last_timestamp_dt: 2025-11-19 07:10:14 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 19:09:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 77780.7003549
======== STREAM "Epoc X":
	created_at_dt: 2025-11-19 07:10:14 PM
	first_timestamp_dt: 2025-11-19 07:10:14 PM
	last_timestamp_dt: 2025-11-19 07:10:14 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 19:09:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 77780.7003549
======== STREAM "TextLogger":
	created_at_dt: 2025-11-19 07:10:14 PM
	first_timestamp_dt: 2025-11-19 07:10:14 PM
	last_timestamp_dt: 2025-11-19 07:10:14 PM
	 failed with error: 'NoneType' object is not iterable
	skipping file.
trying to process XDF file 103/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-19T193520.829Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-19 07:35:20 PM
	first_timestamp_dt: 2025-11-19 07:35:20 PM
	last_timestamp_dt: 2025-11-19 07:35:20 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 19:09:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 77780.7003549
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-19 07:35:20 PM
	first_timestamp_dt: 2025-11-19 07:35:20 PM
	last_timestamp_dt: 2025-11-19 07:35:20 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 19:09:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 77780.7003549
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-19 07:35:20 PM
	first_timestamp_dt: 2025-11-19 07:35:20 PM
	last_timestamp_dt: 2025-11-19 07:35:20 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 19:09:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 77780.7003549
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-19 07:35:20 PM
	first_timestamp_dt: 2025-11-19 07:35:20 PM
	last_timestamp_dt: 2025-11-19 07:35:20 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 15:57:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 66261.1231403
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-19 07:35:20 PM
	first_timestamp_dt: 2025-11-19 07:35:20 PM
	last_timestamp_dt: 2025-11-19 07:35:20 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 15:57:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 66261.1231403
======== STREAM "Epoc X":
	created_at_dt: 2025-11-19 07:35:20 PM
	first_timestamp_dt: 2025-11-19 07:35:20 PM
	last_timestamp_dt: 2025-11-19 07:35:20 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-19 15:57:39+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 66261.1231403
	n_existing_annots: 0, 	n_new_annots: 1856, 	expected_merged: 1856
	n_actual_post_annots: 875

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 981 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_existing_annots: 875, 	n_new_annots: 1856, 	expected_merged: 2731
	n_actual_post_annots: 1750
	n_existing_annots: 1750, 	n_new_annots: 3712, 	expected_merged: 5462
	n_actual_post_annots: 1885

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 981 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3577 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)

	n_existing_annots: 0, 	n_new_annots: 1856, 	expected_merged: 1856
	n_actual_post_annots: 875

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 981 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_existing_annots: 875, 	n_new_annots: 1856, 	expected_merged: 2731
	n_actual_post_annots: 1750
	n_existing_annots: 1750, 	n_new_annots: 3712, 	expected_merged: 5462
	n_actual_post_annots: 1885

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 981 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3577 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)

saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-19T19-35-20.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-19T19-35-20.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 4, annotation_time_range: 0 days 00:13:47.390625, annotation_time_range_num_secs: 827.390625
trying to process XDF file 104/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-20T202324.754Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-20 08:23:24 PM
	first_timestamp_dt: 2025-11-20 08:23:24 PM
	last_timestamp_dt: 2025-11-20 08:23:24 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-20 20:17:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 34019.4772333
======== STREAM "Epoc X":
	created_at_dt: 2025-11-20 08:23:24 PM
	first_timestamp_dt: 2025-11-20 08:23:24 PM
	last_timestamp_dt: 2025-11-20 08:23:24 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-20 20:17:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 34019.4772333
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-20 08:23:24 PM
	first_timestamp_dt: 2025-11-20 08:23:24 PM
	last_timestamp_dt: 2025-11-20 08:23:24 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-20 20:17:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 34019.4772333
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
	n_existing_annots: 0, 	n_new_annots: 445, 	expected_merged: 445
	n_actual_post_annots: 252
	n_existing_annots: 252, 	n_new_annots: 445, 	expected_merged: 697
	n_actual_post_annots: 252
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-20T20-23-24.fif"
trying to process XDF file 105/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-20T202818.818Z_eeg.xdf"...

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 193 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 445 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-20T20-23-24.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

======== STREAM "TextLogger":
	created_at_dt: 2025-11-20 08:28:18 PM
	first_timestamp_dt: 2025-11-20 08:28:18 PM
	last_timestamp_dt: 2025-11-20 08:28:18 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-20 20:26:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 34610.2741704
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-20 20:26:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 34610.274175
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-20 08:28:18 PM
	first_timestamp_dt: 2025-11-20 08:28:18 PM
	last_timestamp_dt: 2025-11-20 08:28:18 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-20 20:17:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 34019.4772333
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-20 08:28:18 PM
	first_timestamp_dt: 2025-11-20 08:28:18 PM
	last_timestamp_dt: 2025-11-20 08:28:18 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-20 20:17:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 34019.4772333
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-20 08:28:18 PM
	first_timestamp_dt: 2025-11-20 08:28:18 PM
	last_timestamp_dt: 2025-11-20 08:28:18 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-20 20:17:03+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 34019.4772333
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
	n_existing_annots: 0, 	n_new_annots: 7866, 	expected_merged: 7866

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 3814 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 4052
	n_existing_annots: 4052, 	n_new_annots: 7883, 	expected_merged: 11935

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3703 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-20T20-28-18.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 8232
debug_test_annotations_timestamps(...):
	len(annotations_df): 17, annotation_time_range: 0 days 00:47:04.918003, annotation_time_range_num_secs: 2824.918003
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-20T20-28-18.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 17, annotation_time_range: 0 days 00:47:04.918003, annotation_time_range_num_secs: 2824.918003
trying to process XDF file 106/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-21T233804.234Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-21 11:38:04 PM
	first_timestamp_dt: 2025-11-21 11:38:04 PM
	last_timestamp_dt: 2025-11-21 11:38:04 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-21 23:36:13+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 93160.8158351
======== STREAM "Epoc X":
	created_at_dt: 2025-11-21 11:38:04 PM
	first_timestamp_dt: 2025-11-21 11:38:04 PM
	last_timestamp_dt: 2025-11-21 11:38:04 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-21 23:36:13+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 93160.8158351
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-21 11:38:04 PM
	first_timestamp_dt: 2025-11-21 11:38:04 PM
	last_timestamp_dt: 2025-11-21 11:38:04 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-21 23:36:13+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 93160.8158351
	n_existing_annots: 0, 	n_new_annots: 7001, 	expected_merged: 7001
	n_actual_post_annots: 3773
	n_existing_annots: 3773, 	n_new_annots: 7001, 	expected_merged: 10774

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 3228 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3301 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-21T23-38-04.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 7473
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-21T23-38-04.fif"
trying to process XDF file 107/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-24T175559.761Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-24 05:55:59 PM
	first_timestamp_dt: 2025-11-24 05:55:59 PM
	last_timestamp_dt: 2025-11-24 05:55:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-24 17:55:13+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 12319.928738
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-24 05:55:59 PM
	first_timestamp_dt: 2025-11-24 05:55:59 PM
	last_timestamp_dt: 2025-11-24 05:55:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-24 17:55:13+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 12319.928738
======== STREAM "TextLogger":
	created_at_dt: 2025-11-24 05:55:59 PM
	first_timestamp_dt: 2025-11-24 05:55:59 PM
	last_timestamp_dt: 2025-11-24 05:55:59 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-24 17:55:27+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 12334.3060225
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-24 17:55:27+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 12334.3060261
======== STREAM "Epoc X":
	created_at_dt: 2025-11-24 05:55:59 PM
	first_timestamp_dt: 2025-11-24 05:55:59 PM
	last_timestamp_dt: 2025-11-24 05:55:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-24 17:55:13+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 12319.928738
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
	n_existing_annots: 0, 	n_new_annots: 27048, 	expected_merged: 27048

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 11649 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 15399
	n_existing_annots: 15399, 	n_new_annots: 28012, 	expected_merged: 43411

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 11612 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-24T17-55-59.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 31799
debug_test_annotations_timestamps(...):
	len(annotations_df): 964, annotation_time_range: 0 days 01:38:42.618714, annotation_time_range_num_secs: 5922.618714
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-24T17-55-59.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 964, annotation_time_range: 0 days 01:38:42.618714, annotation_time_range_num_secs: 5922.618714
trying to process XDF file 108/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-25T005533.559Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-25 12:55:33 AM
	first_timestamp_dt: 2025-11-25 12:55:33 AM
	last_timestamp_dt: 2025-11-25 12:55:33 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 00:54:52+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 37499.0100302
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-25 12:55:33 AM
	first_timestamp_dt: 2025-11-25 12:55:33 AM
	last_timestamp_dt: 2025-11-25 12:55:33 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 00:54:52+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 37499.0100302
======== STREAM "TextLogger":
	created_at_dt: 2025-11-25 12:55:33 AM
	first_timestamp_dt: 2025-11-25 12:55:33 AM
	last_timestamp_dt: 2025-11-25 12:55:33 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 00:55:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 37512.0368505
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-25 00:55:05+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 37512.0368559
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-25 12:55:33 AM
	first_timestamp_dt: 2025-11-25 12:55:33 AM
	last_timestamp_dt: 2025-11-25 12:55:33 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 00:54:52+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 37499.0100302
	n_existing_annots: 0, 	n_new_annots: 10696, 	expected_merged: 10696
	n_actual_post_annots: 5616
	n_existing_annots: 5616, 	n_new_annots: 10775, 	expected_merged: 16391

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 5080 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 5153 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-25T00-55-33.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 11238
debug_test_annotations_timestamps(...):
	len(annotations_df): 79, annotation_time_range: 0 days 00:59:03.761303, annotation_time_range_num_secs: 3543.761303
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-25T00-55-33.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 79, annotation_time_range: 0 days 00:59:03.761303, annotation_time_range_num_secs: 3543.761303
trying to process XDF file 109/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-25T190238.675Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-25 07:02:38 PM
	first_timestamp_dt: 2025-11-25 07:02:38 PM
	last_timestamp_dt: 2025-11-25 07:02:38 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 19:01:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 102691.4965178
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "TextLogger":
	created_at_dt: 2025-11-25 07:02:38 PM
	first_timestamp_dt: 2025-11-25 07:02:38 PM
	last_timestamp_dt: 2025-11-25 07:02:38 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 19:01:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 102701.9699301
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-25 19:01:35+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 102701.9699342
======== STREAM "Epoc X":
	created_at_dt: 2025-11-25 07:02:38 PM
	first_timestamp_dt: 2025-11-25 07:02:38 PM
	last_timestamp_dt: 2025-11-25 07:02:38 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 19:01:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 102691.4965178
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-25 07:02:38 PM
	first_timestamp_dt: 2025-11-25 07:02:38 PM
	last_timestamp_dt: 2025-11-25 07:02:38 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 19:01:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 102691.4965178
	n_existing_annots: 0, 	n_new_annots: 10706, 	expected_merged: 10706
	n_actual_post_annots: 5803
	n_existing_annots: 5803, 	n_new_annots: 10713, 	expected_merged: 16516

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4903 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 5011 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-25T19-02-38.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 11505
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 01:20:24.865076, annotation_time_range_num_secs: 4824.865076
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-25T19-02-38.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 01:20:24.865076, annotation_time_range_num_secs: 4824.865076
trying to process XDF file 110/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-11-25T224802.536Z_eeg.xdf"...
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-11-25 10:48:02 PM
	first_timestamp_dt: 2025-11-25 10:48:02 PM
	last_timestamp_dt: 2025-11-25 10:48:02 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 22:46:44+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 116210.7461574
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-25 10:48:02 PM
	first_timestamp_dt: 2025-11-25 10:48:02 PM
	last_timestamp_dt: 2025-11-25 10:48:02 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 22:46:44+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 116210.7461574
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-11-25 10:48:02 PM
	first_timestamp_dt: 2025-11-25 10:48:02 PM
	last_timestamp_dt: 2025-11-25 10:48:02 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 22:46:44+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 116210.7461574
======== STREAM "TextLogger":
	created_at_dt: 2025-11-25 10:48:02 PM
	first_timestamp_dt: 2025-11-25 10:48:02 PM
	last_timestamp_dt: 2025-11-25 10:48:02 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-11-25 22:47:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 116238.2329473
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-11-25 22:47:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 116238.2329518
	n_existing_annots: 0, 	n_new_annots: 6867, 	expected_merged: 6867
	n_actual_post_annots: 4345
	n_existing_annots: 4345, 	n_new_annots: 6874, 	expected_merged: 11219

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2522 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 2645 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-11-25T22-48-02.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 8574
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 01:01:18.509933, annotation_time_range_num_secs: 3678.509933
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-11-25T22-48-02.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 01:01:18.509933, annotation_time_range_num_secs: 3678.509933
trying to process XDF file 111/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-01T135656.348Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-12-01 01:56:56 PM
	first_timestamp_dt: 2025-12-01 01:56:56 PM
	last_timestamp_dt: 2025-12-01 01:56:56 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 13:56:26+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53205.5268825
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-01 13:56:26+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 53205.5268868
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-01 01:56:56 PM
	first_timestamp_dt: 2025-12-01 01:56:56 PM
	last_timestamp_dt: 2025-12-01 01:56:56 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 13:54:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53070.9888754
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "Epoc X":
	created_at_dt: 2025-12-01 01:56:56 PM
	first_timestamp_dt: 2025-12-01 01:56:56 PM
	last_timestamp_dt: 2025-12-01 01:56:56 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 13:54:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53070.9888754
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-01 01:56:56 PM
	first_timestamp_dt: 2025-12-01 01:56:56 PM
	last_timestamp_dt: 2025-12-01 01:56:56 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 13:54:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 53070.9888754
	n_existing_annots: 0, 	n_new_annots: 23542, 	expected_merged: 23542

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 10802 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 12740
	n_existing_annots: 12740, 	n_new_annots: 24100, 	expected_merged: 36840

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 10945 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-01T13-56-56.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 25895
debug_test_annotations_timestamps(...):
	len(annotations_df): 558, annotation_time_range: 0 days 01:46:45.303512, annotation_time_range_num_secs: 6405.303512
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-01T13-56-56.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 558, annotation_time_range: 0 days 01:46:45.303512, annotation_time_range_num_secs: 6405.303512
trying to process XDF file 112/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-01T180806.895Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-12-01 06:08:06 PM
	first_timestamp_dt: 2025-12-01 06:08:06 PM
	last_timestamp_dt: 2025-12-01 06:08:06 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 18:07:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 68263.5240749
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-01 06:08:06 PM
	first_timestamp_dt: 2025-12-01 06:08:06 PM
	last_timestamp_dt: 2025-12-01 06:08:06 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 18:07:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 68263.5240749
======== STREAM "TextLogger":
	created_at_dt: 2025-12-01 06:08:06 PM
	first_timestamp_dt: 2025-12-01 06:08:06 PM
	last_timestamp_dt: 2025-12-01 06:08:06 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 15:56:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 60413.0503945
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-01 15:56:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 60413.050398
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-01 06:08:06 PM
	first_timestamp_dt: 2025-12-01 06:08:06 PM
	last_timestamp_dt: 2025-12-01 06:08:06 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 18:07:24+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 68263.5240749
	n_existing_annots: 0, 	n_new_annots: 2852, 	expected_merged: 2852
	n_actual_post_annots: 1413
	n_existing_annots: 1413, 	n_new_annots: 2902, 	expected_merged: 4315
	n_actual_post_annots: 2867
debug_test_annotations_timestamps(...):
	len(annotations_df): 50, annotation_time_range: 0 days 00:25:09.342255, annotation_time_range_num_secs: 1509.342255
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-01T18-08-06.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1439 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 1448 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-01T18-08-06.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 50, annotation_time_range: 0 days 00:25:09.342255, annotation_time_range_num_secs: 1509.342255
trying to process XDF file 113/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-01T192014.998Z_eeg.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-12-01 07:20:14 PM
	first_timestamp_dt: 2025-12-01 07:20:14 PM
	last_timestamp_dt: 2025-12-01 07:20:14 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 19:18:25+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 72524.8136698
======== STREAM "TextLogger":
	created_at_dt: 2025-12-01 07:20:14 PM
	first_timestamp_dt: 2025-12-01 07:20:14 PM
	last_timestamp_dt: 2025-12-01 07:20:14 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 19:19:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 72592.0342812
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-01 19:19:33+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 72592.034286
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-01 07:20:14 PM
	first_timestamp_dt: 2025-12-01 07:20:14 PM
	last_timestamp_dt: 2025-12-01 07:20:14 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 19:18:25+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 72524.8136698
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-01 07:20:14 PM
	first_timestamp_dt: 2025-12-01 07:20:14 PM
	last_timestamp_dt: 2025-12-01 07:20:14 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 19:18:25+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 72524.8136698
	n_existing_annots: 0, 	n_new_annots: 3561, 	expected_merged: 3561
	n_actual_post_annots: 2007
	n_existing_annots: 2007, 	n_new_annots: 3562, 	expected_merged: 5569
	n_actual_post_annots: 3975
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-01T19-20-14.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1554 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 1594 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-01T19-20-14.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 114/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-01T212557.902Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-01 09:25:57 PM
	first_timestamp_dt: 2025-12-01 09:25:57 PM
	last_timestamp_dt: 2025-12-01 09:25:57 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 21:24:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 80113.2578098
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-12-01 09:25:57 PM
	first_timestamp_dt: 2025-12-01 09:25:57 PM
	last_timestamp_dt: 2025-12-01 09:25:57 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 21:24:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 80113.2578098
======== STREAM "TextLogger":
	created_at_dt: 2025-12-01 09:25:57 PM
	first_timestamp_dt: 2025-12-01 09:25:57 PM
	last_timestamp_dt: 2025-12-01 09:25:57 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 21:25:23+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 80142.6936751
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-01 21:25:23+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 80142.6936812
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-01 09:25:57 PM
	first_timestamp_dt: 2025-12-01 09:25:57 PM
	last_timestamp_dt: 2025-12-01 09:25:57 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-01 21:24:54+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 80113.2578098
	n_existing_annots: 0, 	n_new_annots: 6496, 	expected_merged: 6496
	n_actual_post_annots: 3281
	n_existing_annots: 3281, 	n_new_annots: 6509, 	expected_merged: 9790

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 3215 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3273 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)

	n_actual_post_annots: 6517
debug_test_annotations_timestamps(...):
	len(annotations_df): 13, annotation_time_range: 0 days 00:46:28.913837, annotation_time_range_num_secs: 2788.913837
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-01T21-25-57.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-01T21-25-57.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 13, annotation_time_range: 0 days 00:46:28.913837, annotation_time_range_num_secs: 2788.913837
trying to process XDF file 115/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-02T083234.940Z_eeg.xdf"...
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-02 08:32:34 AM
	first_timestamp_dt: 2025-12-02 08:32:34 AM
	last_timestamp_dt: 2025-12-02 08:32:34 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-02 08:30:55+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 29614.1815108
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "TextLogger":
	created_at_dt: 2025-12-02 08:32:34 AM
	first_timestamp_dt: 2025-12-02 08:32:34 AM
	last_timestamp_dt: 2025-12-02 08:32:34 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-02 08:31:56+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 29674.9172209
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-02 08:31:56+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 29674.9172258
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-02 08:32:34 AM
	first_timestamp_dt: 2025-12-02 08:32:34 AM
	last_timestamp_dt: 2025-12-02 08:32:34 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-02 08:30:55+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 29614.1815108
======== STREAM "Epoc X":
	created_at_dt: 2025-12-02 08:32:34 AM
	first_timestamp_dt: 2025-12-02 08:32:34 AM
	last_timestamp_dt: 2025-12-02 08:32:34 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-02 08:30:55+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 29614.1815108
	n_existing_annots: 0, 	n_new_annots: 5890, 	expected_merged: 5890
	n_actual_post_annots: 2949
	n_existing_annots: 2949, 	n_new_annots: 5895, 	expected_merged: 8844
	n_actual_post_annots: 5836

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2941 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3008 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-02T08-32-34.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 00:59:25.634914, annotation_time_range_num_secs: 3565.634914
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-02T08-32-34.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 00:59:25.634914, annotation_time_range_num_secs: 3565.634914
trying to process XDF file 116/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-02T192131.361Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-02 07:21:31 PM
	first_timestamp_dt: 2025-12-02 07:21:31 PM
	last_timestamp_dt: 2025-12-02 07:21:31 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-02 19:20:14+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 68573.2404914
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-02 07:21:31 PM
	first_timestamp_dt: 2025-12-02 07:21:31 PM
	last_timestamp_dt: 2025-12-02 07:21:31 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-02 19:20:14+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 68573.2404914
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "TextLogger":
	created_at_dt: 2025-12-02 07:21:31 PM
	first_timestamp_dt: 2025-12-02 07:21:31 PM
	last_timestamp_dt: 2025-12-02 07:21:31 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-02 19:20:58+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 68617.3391878
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-02 19:20:58+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 68617.3391923
======== STREAM "Epoc X":
	created_at_dt: 2025-12-02 07:21:31 PM
	first_timestamp_dt: 2025-12-02 07:21:31 PM
	last_timestamp_dt: 2025-12-02 07:21:31 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-02 19:20:14+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 68573.2404914
	n_existing_annots: 0, 	n_new_annots: 7429, 	expected_merged: 7429
	n_actual_post_annots: 3652
	n_existing_annots: 3652, 	n_new_annots: 7436, 	expected_merged: 11088

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 3777 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3828 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-02T19-21-31.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 7260
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 00:01:02.608534, annotation_time_range_num_secs: 62.608534
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-02T19-21-31.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 7, annotation_time_range: 0 days 00:01:02.608534, annotation_time_range_num_secs: 62.608534
trying to process XDF file 117/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-03T151842.085Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "WhisperLiveLogger":
	created_at_dt: 2025-12-03 03:18:42 PM
	first_timestamp_dt: 2025-12-03 03:18:42 PM
	last_timestamp_dt: 2025-12-03 03:18:42 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:18:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3636.925253
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-03 15:18:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 3636.9252622
======== STREAM "TextLogger":
	created_at_dt: 2025-12-03 03:18:42 PM
	first_timestamp_dt: 2025-12-03 03:18:42 PM
	last_timestamp_dt: 2025-12-03 03:18:42 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:18:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3636.925253
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-03 15:18:07+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 3636.9252622
======== STREAM "Epoc X":
	created_at_dt: 2025-12-03 03:18:42 PM
	first_timestamp_dt: 2025-12-03 03:18:42 PM
	last_timestamp_dt: 2025-12-03 03:18:42 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:17:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3603.9302885
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-03 03:18:42 PM
	first_timestamp_dt: 2025-12-03 03:18:42 PM
	last_timestamp_dt: 2025-12-03 03:18:42 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:17:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3603.9302885
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-03 03:18:42 PM
	first_timestamp_dt: 2025-12-03 03:18:42 PM
	last_timestamp_dt: 2025-12-03 03:18:42 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:17:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3603.9302885
	n_existing_annots: 0, 	n_new_annots: 4734, 	expected_merged: 4734
	n_actual_post_annots: 2607
	n_existing_annots: 2607, 	n_new_annots: 4798, 	expected_merged: 7405

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2127 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 2221 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-03T15-18-42.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 5184
debug_test_annotations_timestamps(...):
	len(annotations_df): 62, annotation_time_range: 0 days 00:30:22.870381, annotation_time_range_num_secs: 1822.870381
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-03T15-18-42.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 62, annotation_time_range: 0 days 00:30:22.870381, annotation_time_range_num_secs: 1822.870381
trying to process XDF file 118/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-03T155530.436Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-03 03:55:30 PM
	first_timestamp_dt: 2025-12-03 03:55:30 PM
	last_timestamp_dt: 2025-12-03 03:55:30 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:17:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3603.9302885
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-03 03:55:30 PM
	first_timestamp_dt: 2025-12-03 03:55:30 PM
	last_timestamp_dt: 2025-12-03 03:55:30 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:17:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3603.9302885
======== STREAM "Epoc X":
	created_at_dt: 2025-12-03 03:55:30 PM
	first_timestamp_dt: 2025-12-03 03:55:30 PM
	last_timestamp_dt: 2025-12-03 03:55:30 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:17:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3603.9302885
	n_existing_annots: 0, 	n_new_annots: 4497, 	expected_merged: 4497
	n_actual_post_annots: 2630
	n_existing_annots: 2630, 	n_new_annots: 4497, 	expected_merged: 7127
	n_actual_post_annots: 3482
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-03T15-55-30.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1867 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3645 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-03T15-55-30.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 119/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-03T162355.980Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-03 04:23:55 PM
	first_timestamp_dt: 2025-12-03 04:23:55 PM
	last_timestamp_dt: 2025-12-03 04:23:55 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:17:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3603.9302885
======== STREAM "Epoc X":
	created_at_dt: 2025-12-03 04:23:55 PM
	first_timestamp_dt: 2025-12-03 04:23:55 PM
	last_timestamp_dt: 2025-12-03 04:23:55 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:17:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3603.9302885
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-03 04:23:55 PM
	first_timestamp_dt: 2025-12-03 04:23:55 PM
	last_timestamp_dt: 2025-12-03 04:23:55 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 15:17:34+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 3603.9302885
	n_existing_annots: 0, 	n_new_annots: 1222, 	expected_merged: 1222
	n_actual_post_annots: 704
	n_existing_annots: 704, 	n_new_annots: 1222, 	expected_merged: 1926
	n_actual_post_annots: 704
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-03T16-23-55.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 518 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 1222 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-03T16-23-55.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 120/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-03T225241.243Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-03 10:52:41 PM
	first_timestamp_dt: 2025-12-03 10:52:41 PM
	last_timestamp_dt: 2025-12-03 10:52:41 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 22:51:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 30846.4749642
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "TextLogger":
	created_at_dt: 2025-12-03 10:52:41 PM
	first_timestamp_dt: 2025-12-03 10:52:41 PM
	last_timestamp_dt: 2025-12-03 10:52:41 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 22:51:57+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 30866.8777708
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-03 22:51:57+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 30866.8777775
======== STREAM "Epoc X":
	created_at_dt: 2025-12-03 10:52:41 PM
	first_timestamp_dt: 2025-12-03 10:52:41 PM
	last_timestamp_dt: 2025-12-03 10:52:41 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 22:51:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 30846.4749642
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-03 10:52:41 PM
	first_timestamp_dt: 2025-12-03 10:52:41 PM
	last_timestamp_dt: 2025-12-03 10:52:41 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-03 22:51:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 30846.4749642
	n_existing_annots: 0, 	n_new_annots: 13743, 	expected_merged: 13743
	n_actual_post_annots: 6957

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 6786 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_existing_annots: 6957, 	n_new_annots: 13847, 	expected_merged: 20804

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 6795 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-03T22-52-41.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 14009
debug_test_annotations_timestamps(...):
	len(annotations_df): 104, annotation_time_range: 0 days 01:18:56.554126, annotation_time_range_num_secs: 4736.554126
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-03T22-52-41.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 104, annotation_time_range: 0 days 01:18:56.554126, annotation_time_range_num_secs: 4736.554126
trying to process XDF file 121/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-09T165549.280Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-09 04:55:49 PM
	first_timestamp_dt: 2025-12-09 04:55:49 PM
	last_timestamp_dt: 2025-12-09 04:55:49 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-09 16:54:53+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 5536.0961526
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-09 04:55:49 PM
	first_timestamp_dt: 2025-12-09 04:55:49 PM
	last_timestamp_dt: 2025-12-09 04:55:49 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-09 16:54:53+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 5536.0961526
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
======== STREAM "Epoc X":
	created_at_dt: 2025-12-09 04:55:49 PM
	first_timestamp_dt: 2025-12-09 04:55:49 PM
	last_timestamp_dt: 2025-12-09 04:55:49 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-09 16:54:53+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 5536.0961526
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "TextLogger":
	created_at_dt: 2025-12-09 04:55:49 PM
	first_timestamp_dt: 2025-12-09 04:55:49 PM
	last_timestamp_dt: 2025-12-09 04:55:49 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-09 16:55:17+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 5559.9717335
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-09 16:55:17+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 5559.9717374
	n_existing_annots: 0, 	n_new_annots: 10476, 	expected_merged: 10476
	n_actual_post_annots: 5920
	n_existing_annots: 5920, 	n_new_annots: 10726, 	expected_merged: 16646

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4556 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 4508 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-09T16-55-49.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 12138
debug_test_annotations_timestamps(...):
	len(annotations_df): 250, annotation_time_range: 0 days 00:46:17.964393, annotation_time_range_num_secs: 2777.964393
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-09T16-55-49.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 250, annotation_time_range: 0 days 00:46:17.964393, annotation_time_range_num_secs: 2777.964393
trying to process XDF file 122/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-09T205559.916Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-09 08:55:59 PM
	first_timestamp_dt: 2025-12-09 08:55:59 PM
	last_timestamp_dt: 2025-12-09 08:55:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-09 20:54:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 19923.607507
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-09 08:55:59 PM
	first_timestamp_dt: 2025-12-09 08:55:59 PM
	last_timestamp_dt: 2025-12-09 08:55:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-09 20:54:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 19923.607507
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X":
	created_at_dt: 2025-12-09 08:55:59 PM
	first_timestamp_dt: 2025-12-09 08:55:59 PM
	last_timestamp_dt: 2025-12-09 08:55:59 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-09 20:54:36+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 19923.607507
======== STREAM "TextLogger":
	created_at_dt: 2025-12-09 08:55:59 PM
	first_timestamp_dt: 2025-12-09 08:55:59 PM
	last_timestamp_dt: 2025-12-09 08:55:59 PM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-09 20:54:56+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 19944.307238
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-09 20:54:56+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 19944.3072425
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
	n_existing_annots: 0, 	n_new_annots: 8951, 	expected_merged: 8951
	n_actual_post_annots: 4503
	n_existing_annots: 4503, 	n_new_annots: 9066, 	expected_merged: 13569

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 4448 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 4509 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-09T20-55-59.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

	n_actual_post_annots: 9060
debug_test_annotations_timestamps(...):
	len(annotations_df): 115, annotation_time_range: 0 days 01:35:31.022372, annotation_time_range_num_secs: 5731.022372
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-09T20-55-59.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 115, annotation_time_range: 0 days 01:35:31.022372, annotation_time_range_num_secs: 5731.022372
trying to process XDF file 123/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-10T022542.819Z_eeg.xdf"...
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-10 02:25:42 AM
	first_timestamp_dt: 2025-12-10 02:25:42 AM
	last_timestamp_dt: 2025-12-10 02:25:42 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:25:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39767.0337614
======== STREAM "Epoc X":
	created_at_dt: 2025-12-10 02:25:42 AM
	first_timestamp_dt: 2025-12-10 02:25:42 AM
	last_timestamp_dt: 2025-12-10 02:25:42 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:25:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39767.0337614
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-10 02:25:42 AM
	first_timestamp_dt: 2025-12-10 02:25:42 AM
	last_timestamp_dt: 2025-12-10 02:25:42 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:25:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39767.0337614
	n_existing_annots: 0, 	n_new_annots: 391, 	expected_merged: 391
	n_actual_post_annots: 161
	n_existing_annots: 161, 	n_new_annots: 391, 	expected_merged: 552
	n_actual_post_annots: 333
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-10T02-25-42.fif"
trying to process XDF file 124/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-10T022835.454Z_eeg.xdf"...

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 230 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 219 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-10T02-25-42.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

======== STREAM "TextLogger":
	created_at_dt: 2025-12-10 02:28:35 AM
	first_timestamp_dt: 2025-12-10 02:28:35 AM
	last_timestamp_dt: 2025-12-10 02:28:35 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:27:16+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39883.9785053
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-10 02:27:16+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 39883.9785205
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-10 02:28:35 AM
	first_timestamp_dt: 2025-12-10 02:28:35 AM
	last_timestamp_dt: 2025-12-10 02:28:35 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:25:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39767.0337614
======== STREAM "Epoc X":
	created_at_dt: 2025-12-10 02:28:35 AM
	first_timestamp_dt: 2025-12-10 02:28:35 AM
	last_timestamp_dt: 2025-12-10 02:28:35 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:25:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39767.0337614
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-10 02:28:35 AM
	first_timestamp_dt: 2025-12-10 02:28:35 AM
	last_timestamp_dt: 2025-12-10 02:28:35 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:25:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39767.0337614
	n_existing_annots: 0, 	n_new_annots: 2041, 	expected_merged: 2041
	n_actual_post_annots: 999

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1042 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)

	n_existing_annots: 999, 	n_new_annots: 2042, 	expected_merged: 3041
	n_actual_post_annots: 2016
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-10T02-28-35.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 1025 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-10T02-28-35.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

trying to process XDF file 125/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-10T030252.580Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-10 03:02:52 AM
	first_timestamp_dt: 2025-12-10 03:02:52 AM
	last_timestamp_dt: 2025-12-10 03:02:52 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:25:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39767.0337614
======== STREAM "TextLogger":
	created_at_dt: 2025-12-10 03:02:52 AM
	first_timestamp_dt: 2025-12-10 03:02:52 AM
	last_timestamp_dt: 2025-12-10 03:02:52 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 03:02:26+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 41993.9221482
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-10 03:02:26+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 41993.9221726
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-10 03:02:52 AM
	first_timestamp_dt: 2025-12-10 03:02:52 AM
	last_timestamp_dt: 2025-12-10 03:02:52 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:25:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39767.0337614
======== STREAM "Epoc X":
	created_at_dt: 2025-12-10 03:02:52 AM
	first_timestamp_dt: 2025-12-10 03:02:52 AM
	last_timestamp_dt: 2025-12-10 03:02:52 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 02:25:19+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 39767.0337614
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
	n_existing_annots: 0, 	n_new_annots: 3250, 	expected_merged: 3250
	n_actual_post_annots: 1825
	n_existing_annots: 1825, 	n_new_annots: 3254, 	expected_merged: 5079
	n_actual_post_annots: 3207
debug_test_annotations_timestamps(...):
	len(annotations_df): 4, annotation_time_range: 0 days 00:36:00.840471, annotation_time_range_num_secs: 2160.840471
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-10T03-02-52.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1425 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 1872 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-10T03-02-52.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 4, annotation_time_range: 0 days 00:36:00.840471, annotation_time_range_num_secs: 2160.840471
trying to process XDF file 126/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-10T100939.066Z_eeg.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-12-10 10:09:39 AM
	first_timestamp_dt: 2025-12-10 10:09:39 AM
	last_timestamp_dt: 2025-12-10 10:09:39 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:09:06+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67593.9153397
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-10 10:09:06+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 67593.9153568
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-10 10:09:39 AM
	first_timestamp_dt: 2025-12-10 10:09:39 AM
	last_timestamp_dt: 2025-12-10 10:09:39 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "Epoc X":
	created_at_dt: 2025-12-10 10:09:39 AM
	first_timestamp_dt: 2025-12-10 10:09:39 AM
	last_timestamp_dt: 2025-12-10 10:09:39 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-10 10:09:39 AM
	first_timestamp_dt: 2025-12-10 10:09:39 AM
	last_timestamp_dt: 2025-12-10 10:09:39 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "EventBoard":
	WARN: skipping "EventBoard" with name in skipped_stream_names: ['EventBoard']
	n_existing_annots: 0, 	n_new_annots: 5404, 	expected_merged: 5404
	n_actual_post_annots: 2742
	n_existing_annots: 2742, 	n_new_annots: 5421, 	expected_merged: 8163
	n_actual_post_annots: 5464
debug_test_annotations_timestamps(...):
	len(annotations_df): 17, annotation_time_range: 0 days 00:40:15.287797, annotation_time_range_num_secs: 2415.287797

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 2662 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 2699 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-10T10-09-39.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-10T10-09-39.fif"
debug_test_annotations_timestamps(...):
	len(annotations_df): 17, annotation_time_range: 0 days 00:40:15.287797, annotation_time_range_num_secs: 2415.287797
trying to process XDF file 127/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-10T112254.084Z_eeg.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-10 11:22:54 AM
	first_timestamp_dt: 2025-12-10 11:22:54 AM
	last_timestamp_dt: 2025-12-10 11:22:54 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-12-10 11:22:54 AM
	first_timestamp_dt: 2025-12-10 11:22:54 AM
	last_timestamp_dt: 2025-12-10 11:22:54 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "TextLogger":
	created_at_dt: 2025-12-10 11:22:54 AM
	first_timestamp_dt: 2025-12-10 11:22:54 AM
	last_timestamp_dt: 2025-12-10 11:22:54 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:09:06+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67593.9153397
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-10 10:09:06+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 67593.9153568
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-10 11:22:54 AM
	first_timestamp_dt: 2025-12-10 11:22:54 AM
	last_timestamp_dt: 2025-12-10 11:22:54 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
	n_existing_annots: 0, 	n_new_annots: 2051, 	expected_merged: 2051
	n_actual_post_annots: 1084
	n_existing_annots: 1084, 	n_new_annots: 2053, 	expected_merged: 3137
	n_actual_post_annots: 1086
debug_test_annotations_timestamps(...):
	len(annotations_df): 2, annotation_time_range: 0 days 00:00:07.229546, annotation_time_range_num_secs: 7.229546
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-10T11-22-54.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 967 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 2051 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-10T11-22-54.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 2, annotation_time_range: 0 days 00:00:07.229546, annotation_time_range_num_secs: 7.229546
trying to process XDF file 128/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-10T115301.153Z_eeg.xdf"...
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-10 11:53:01 AM
	first_timestamp_dt: 2025-12-10 11:53:01 AM
	last_timestamp_dt: 2025-12-10 11:53:01 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-10 11:53:01 AM
	first_timestamp_dt: 2025-12-10 11:53:01 AM
	last_timestamp_dt: 2025-12-10 11:53:01 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "Epoc X":
	created_at_dt: 2025-12-10 11:53:01 AM
	first_timestamp_dt: 2025-12-10 11:53:01 AM
	last_timestamp_dt: 2025-12-10 11:53:01 AM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "TextLogger":
	created_at_dt: 2025-12-10 11:53:01 AM
	first_timestamp_dt: 2025-12-10 11:53:01 AM
	last_timestamp_dt: 2025-12-10 11:53:01 AM
WARN: (len(phopylslhelper_dict)5
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 11:52:30+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 73798.0647736
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_datetime": 2025-12-10 11:52:30+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "recording_start_lsl_local_offset_seconds": 73798.064788
	n_existing_annots: 0, 	n_new_annots: 3901, 	expected_merged: 3901
	n_actual_post_annots: 1984
	n_existing_annots: 1984, 	n_new_annots: 3906, 	expected_merged: 5890
	n_actual_post_annots: 1989
debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 00:09:39.023504, annotation_time_range_num_secs: 579.023504
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-10T11-53-01.fif"

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 1917 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 3901 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-10T11-53-01.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

debug_test_annotations_timestamps(...):
	len(annotations_df): 5, annotation_time_range: 0 days 00:09:39.023504, annotation_time_range_num_secs: 579.023504
trying to process XDF file 129/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-12-10T124922.453Z_eeg.xdf"...
======== STREAM "EventBoard":
	WARN: skipping empty stream: "EventBoard"
======== STREAM "TextLogger":
	WARN: skipping empty stream: "TextLogger"
======== STREAM "Epoc X eQuality":
	created_at_dt: 2025-12-10 12:49:22 PM
	first_timestamp_dt: 2025-12-10 12:49:22 PM
	last_timestamp_dt: 2025-12-10 12:49:22 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-12-10 12:49:22 PM
	first_timestamp_dt: 2025-12-10 12:49:22 PM
	last_timestamp_dt: 2025-12-10 12:49:22 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "Epoc X":
	created_at_dt: 2025-12-10 12:49:22 PM
	first_timestamp_dt: 2025-12-10 12:49:22 PM
	last_timestamp_dt: 2025-12-10 12:49:22 PM
WARN: (len(phopylslhelper_dict)3
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_datetime": 2025-12-10 10:08:11+00:00
	 FOUND CUSTOM TIMESTAMP SYNC KEY: "stream_start_lsl_local_offset_seconds": 67539.3844641
======== STREAM "WhisperLiveLogger":
	WARN: skipping empty stream: "WhisperLiveLogger"
	n_existing_annots: 0, 	n_new_annots: 226, 	expected_merged: 226
	n_actual_post_annots: 142
	n_existing_annots: 142, 	n_new_annots: 226, 	expected_merged: 368
	n_actual_post_annots: 142
saving finalized EEG data out to "E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/LabRecorder_PostProcessed/2025-12-10T12-49-22.fif"
trying to process XDF file 130/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-09-11T213635.043Z.xdf"...
======== STREAM "Epoc X":
	created_at_dt: 2025-09-11 09:36:35 PM
	first_timestamp_dt: 2025-09-11 09:36:35 PM
	last_timestamp_dt: 2025-09-11 09:36:35 PM
	 failed with error:
	skipping file.
trying to process XDF file 131/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-09-12T014018.162Z.xdf"...

C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:337: RuntimeWarning: Omitted 84 annotation(s) that were outside data range.
  raw = raw.set_annotations(new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\MNE_helpers.py:363: RuntimeWarning: Omitted 226 annotation(s) that were outside data range.
  raw = raw.set_annotations(existing_annotations + new_annots, **set_annotations_kwargs)
C:\Users\pho\repos\EmotivEpoc\PhoOfflineEEGAnalysis\src\phoofflineeeganalysis\analysis\SavedSessionsProcessor.py:1532: RuntimeWarning: This filename (E:\Dropbox (Personal)\Databases\AnalysisData\MNE_preprocessed\LabRecorder_PostProcessed\2025-12-10T12-49-22.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  eeg_raw.save(a_lab_recorder_filepath, overwrite=True)

======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-12 01:40:18 AM
	first_timestamp_dt: 2025-09-12 01:40:18 AM
	last_timestamp_dt: 2025-09-12 01:40:18 AM
	 failed with error:
	skipping file.
trying to process XDF file 132/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-09-13T021042.451Z.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-13 02:10:42 AM
	first_timestamp_dt: 2025-09-13 02:10:42 AM
	last_timestamp_dt: 2025-09-13 02:10:42 AM
	 failed with error:
	skipping file.
trying to process XDF file 133/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-09-13T031209.598Z.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-13 03:12:09 AM
	first_timestamp_dt: 2025-09-13 03:12:09 AM
	last_timestamp_dt: 2025-09-13 03:12:09 AM
	 failed with error:
	skipping file.
trying to process XDF file 134/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-09-19T001746.449Z.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-19 12:17:46 AM
	first_timestamp_dt: 2025-09-19 12:17:46 AM
	last_timestamp_dt: 2025-09-19 12:17:46 AM
	 failed with error:
	skipping file.
trying to process XDF file 135/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-09-19T012938.518Z.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-19 01:29:38 AM
	first_timestamp_dt: 2025-09-19 01:29:38 AM
	last_timestamp_dt: 2025-09-19 01:29:38 AM
	 failed with error:
	skipping file.
trying to process XDF file 136/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-09-19T015439.979Z.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-19 01:54:39 AM
	first_timestamp_dt: 2025-09-19 01:54:39 AM
	last_timestamp_dt: 2025-09-19 01:54:39 AM
	 failed with error:
	skipping file.
trying to process XDF file 137/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-09-19T022210.910Z.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-19 02:22:10 AM
	first_timestamp_dt: 2025-09-19 02:22:10 AM
	last_timestamp_dt: 2025-09-19 02:22:10 AM
	 failed with error:
	skipping file.
trying to process XDF file 138/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-09-20T023803.932Z.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-20 02:38:03 AM
	first_timestamp_dt: 2025-09-20 02:38:03 AM
	last_timestamp_dt: 2025-09-20 02:38:03 AM
	 failed with error:
	skipping file.
trying to process XDF file 139/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBPPinkDot_2025-11-14T021444.604Z.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-11-14 02:14:44 AM
	first_timestamp_dt: 2025-11-14 02:14:44 AM
	last_timestamp_dt: 2025-11-14 02:14:44 AM
	 failed with error:
	skipping file.
trying to process XDF file 140/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBP_2025-09-11T203807.731Z.xdf"...
======== STREAM "Epoc X Motion":
	created_at_dt: 2025-09-11 08:38:07 PM
	first_timestamp_dt: 2025-09-11 08:38:07 PM
	last_timestamp_dt: 2025-09-11 08:38:07 PM
	 failed with error:
	skipping file.
trying to process XDF file 141/142: "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_rMBP_2025-09-11T210420.828Z.xdf"...
======== STREAM "TextLogger":
	created_at_dt: 2025-09-11 09:04:20 PM
	first_timestamp_dt: 2025-09-11 09:04:20 PM
	last_timestamp_dt: 2025-09-11 09:04:20 PM
	 failed with error:
	skipping file.
n_unique_xdf_datasets: 75

In [8]:
_out_eeg_raw[-1].annotations.to_data_frame('datetime')

In [ ]:
(1435.384078 / 60.0) # ~24 mins

(3884.001499 / 60.0) # ~65 mins

In [8]:
_out_xdf_stream_infos_df: pd.DataFrame = XDFDataStreamAccessor.init_from_results(_out_xdf_stream_infos_df=_out_xdf_stream_infos_df, active_only_out_eeg_raws=_out_eeg_raw) # [_out_xdf_stream_infos_df['name'] == 'Epoc X']
_out_xdf_stream_infos_df

,name,fs,n_samples,n_channels,type,stream_id,effective_srate,hostname,source_id,channel_count,...,proccessed_mat_filename,xdf_dataset_idx,recording_datetime,recording_day_date,duration_sec,created_at_rel,first_timestamp_rel,last_timestamp_rel,duration_sec_check,duration_rel
xdf_dataset_idx,,,,,,,,,,,,,,,,,,,,,
0,TextLogger,0.0,4,1,Markers,1,1.938226,Apogee,textlogger_001,1,...,2025-10-20T21-50-45.mat,0,2025-10-20 21:50:45+00:00,2025-10-20 00:00:00+00:00,NaT,0.364848,0.377568,0.377592,0 days 00:00:02.063742700,0.000024
0,Epoc X,128.0,2444,14,EEG,4,128.624640,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-20T21-50-45.mat,0,2025-10-20 21:50:45+00:00,2025-10-20 00:00:00+00:00,0 days 00:00:19.093750,0.377183,0.377476,0.377696,0 days 00:00:19.001019200,0.000220
0,Epoc X Motion,16.0,609,6,SIGNAL,2,32.069478,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-10-20T21-50-45.mat,0,2025-10-20 21:50:45+00:00,2025-10-20 00:00:00+00:00,0 days 00:00:38.062500,0.377183,0.377476,0.377696,0 days 00:00:18.990016900,0.000220
1,Epoc X Motion,16.0,69633,6,SIGNAL,4,32.015464,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-10-20T21-51-09.mat,1,2025-10-20 21:51:09+00:00,2025-10-20 00:00:00+00:00,0 days 01:12:32.062500,0.377183,0.377754,0.402927,0 days 00:36:14.980186699,0.025173
1,Epoc X,128.0,279275,14,EEG,3,128.402111,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-20T21-51-09.mat,1,2025-10-20 21:51:09+00:00,2025-10-20 00:00:00+00:00,0 days 00:36:21.835937500,0.377183,0.377754,0.402927,0 days 00:36:15.003185999,0.025174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Epoc X,128.0,323742,14,EEG,2,128.392663,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T11-53-01.mat,73,2025-12-10 11:53:01+00:00,2025-12-10 00:00:00+00:00,0 days 00:42:09.234375,0.781706,0.854498,0.883682,0 days 00:42:01.499227200,0.029184
73,TextLogger,0.0,5,1,Markers,4,0.008635,Apogee,textlogger_001,1,...,2025-12-10T11-53-01.mat,73,2025-12-10 11:53:01+00:00,2025-12-10 00:00:00+00:00,NaT,0.854148,0.876905,0.883607,0 days 00:09:39.023505700,0.006702
74,Epoc X eQuality,128.0,17005,14,Raw,6,128.341998,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T12-49-22.mat,74,2025-12-10 12:49:22+00:00,2025-12-10 00:00:00+00:00,0 days 00:02:12.851562500,0.781706,0.893633,0.895167,0 days 00:02:12.497548700,0.001534
74,Epoc X Motion,16.0,4243,6,SIGNAL,1,32.024928,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-12-10T12-49-22.mat,74,2025-12-10 12:49:22+00:00,2025-12-10 00:00:00+00:00,0 days 00:04:25.187500,0.781706,0.893633,0.895167,0 days 00:02:12.490548300,0.001533
74,Epoc X,128.0,17005,14,EEG,2,128.341991,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T12-49-22.mat,74,2025-12-10 12:49:22+00:00,2025-12-10 00:00:00+00:00,0 days 00:02:12.851562500,0.781706,0.893633,0.895167,0 days 00:02:12.497556400,0.001534

In [9]:
## sort by 'recording_day_date'
from datetime import timedelta


_filtering_xdf_stream_infos_df = deepcopy(_out_xdf_stream_infos_df).reset_index(drop=True)
_all_xdf_filenames = list(set(_filtering_xdf_stream_infos_df['xdf_filename'].to_list())) ## set(...) to de-duplicate the list

# _out_xdf_stream_infos_df['recording_day_date']
is_eeg_stream = (_filtering_xdf_stream_infos_df['type'] == 'EEG') ## only EEG files
_filtering_xdf_stream_infos_df = _filtering_xdf_stream_infos_df[is_eeg_stream].reset_index(drop=True)
# _filtering_xdf_stream_infos_df
# is_sufficiently_long = [(_filtering_xdf_stream_infos_df['duration_sec'] > timedelta(seconds=30.0))]
# _filtering_xdf_stream_infos_df = _filtering_xdf_stream_infos_df[is_sufficiently_long].reset_index(drop=True)
_filtering_xdf_stream_infos_df = _filtering_xdf_stream_infos_df[(_filtering_xdf_stream_infos_df['duration_sec'] > timedelta(seconds=90.0))].reset_index(drop=True)

_filtering_xdf_stream_infos_df = _filtering_xdf_stream_infos_df.sort_values(by=['recording_datetime', 'created_at_dt', 'first_timestamp_dt', 'last_timestamp_dt'], ascending=True, inplace=False)
_filtering_xdf_stream_infos_df
# _out_xdf_stream_infos_df[is_sufficiently_long]

,name,fs,n_samples,n_channels,type,stream_id,effective_srate,hostname,source_id,channel_count,...,proccessed_mat_filename,xdf_dataset_idx,recording_datetime,recording_day_date,duration_sec,created_at_rel,first_timestamp_rel,last_timestamp_rel,duration_sec_check,duration_rel
0,Epoc X,128.0,279275,14,EEG,3,128.402111,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-20T21-51-09.mat,1,2025-10-20 21:51:09+00:00,2025-10-20 00:00:00+00:00,0 days 00:36:21.835937500,0.377183,0.377754,0.402927,0 days 00:36:15.003185999,0.025174
1,Epoc X,128.0,36781,14,EEG,1,128.381819,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-21T04-08-00.mat,4,2025-10-21 04:08:00+00:00,2025-10-21 00:00:00+00:00,0 days 00:04:47.351562500,0.619785,0.639459,0.642775,0 days 00:04:46.496961100,0.003316
2,Epoc X,128.0,364481,14,EEG,1,128.383850,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-21T04-13-43.mat,5,2025-10-21 04:13:43+00:00,2025-10-21 00:00:00+00:00,0 days 00:47:27.507812500,0.619785,0.643434,0.676293,0 days 00:47:18.994163700,0.032859
3,Epoc X,128.0,215329,14,EEG,1,128.362960,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-21T05-12-26.mat,8,2025-10-21 05:12:26+00:00,2025-10-21 00:00:00+00:00,0 days 00:28:02.257812500,0.619785,0.684204,0.703620,0 days 00:27:57.501046300,0.019416
4,Epoc X,128.0,576547,14,EEG,3,128.392450,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-21T13-52-08.mat,9,2025-10-21 13:52:08+00:00,2025-10-21 00:00:00+00:00,0 days 01:15:04.273437500,1.044175,1.045102,1.097075,0 days 01:14:50.505461400,0.051973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Epoc X,128.0,278184,14,EEG,4,128.402398,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T03-02-52.mat,70,2025-12-10 03:02:52+00:00,2025-12-10 00:00:00+00:00,0 days 00:36:13.312500,0.460267,0.486343,0.511418,0 days 00:36:06.501597500,0.025075
66,Epoc X,128.0,538911,14,EEG,3,128.388681,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T10-09-39.mat,71,2025-12-10 10:09:39+00:00,2025-12-10 00:00:00+00:00,0 days 01:10:10.242187500,0.781706,0.782714,0.831296,0 days 01:09:57.496188500,0.048582
67,Epoc X,128.0,218881,14,EEG,5,128.375705,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T11-22-54.mat,72,2025-12-10 11:22:54+00:00,2025-12-10 00:00:00+00:00,0 days 00:28:30.007812500,0.781706,0.833582,0.853316,0 days 00:28:25.003286600,0.019734
68,Epoc X,128.0,323742,14,EEG,2,128.392663,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T11-53-01.mat,73,2025-12-10 11:53:01+00:00,2025-12-10 00:00:00+00:00,0 days 00:42:09.234375,0.781706,0.854498,0.883682,0 days 00:42:01.499227200,0.029184
69,Epoc X,128.0,17005,14,EEG,2,128.341991,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T12-49-22.mat,74,2025-12-10 12:49:22+00:00,2025-12-10 00:00:00+00:00,0 days 00:02:12.851562500,0.781706,0.893633,0.895167,0 days 00:02:12.497556400,0.001534

In [10]:
_all_xdf_filenames

['LabRecorder_Apogee_2025-11-04T105347.435Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-18T001005.371Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T051226.496Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-29T213604.784Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-31T212433.122Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-03T133558.299Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-19T155821.538Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-27T134738.673Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-06T131841.457Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T040726.583Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-28T192440.172Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-10T192805.239Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-20T215109.178Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-05T202621.126Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T041343.978Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-12T171146.441Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-22T115730.331Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-13T230537.397Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-03T162355.980Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-21T233804.234Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T050857.606Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-24T175559.761Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-28T204139.491Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-18T020918.340Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-20T202324.754Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T172531.902Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-23T194319.592Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-23T205331.243Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-04T200752.400Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-20T222728.335Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-28T024016.200Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-14T193359.345Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-10T112254.084Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-10T124922.453Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-31T041919.680Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-09T205559.916Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-13T132514.888Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-25T224802.536Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-13T124711.812Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-25T005533.559Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-20T202818.818Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-17T181736.294Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-03T151842.085Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-10T030252.580Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-14T131135.732Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-10T022835.454Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-10T022542.819Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T040800.544Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-25T190238.675Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-03T155530.436Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-06T150252.171Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-29T133859.160Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-13T191927.251Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-03T225241.243Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T135208.044Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T051157.400Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-01T135656.348Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-10T115301.153Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-01T212557.902Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-11T222222.616Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-20T215045.162Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-01T192014.998Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-29T173858.018Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-13T194919.223Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-19T193520.829Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-29T062306.061Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-02T083234.940Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-30T193005.610Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-10T100939.066Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-28T040425.234Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-02T192131.361Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-09T165549.280Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-29T054820.686Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-23T231938.135Z_eeg.xdf',
 'LabRecorder_Apogee_2025-12-01T180806.895Z_eeg.xdf']

In [11]:
included_xdf_filenames: List[str] = _filtering_xdf_stream_infos_df['xdf_filename'].to_list()
excluded_xdf_filenames: List[str] = list(set(_all_xdf_filenames) - set(included_xdf_filenames))
excluded_xdf_filenames

# included_xdf_filenames = ['LabRecorder_2025-09-10T153731.079Z_eeg.xdf',
#  'LabRecorder_2025-09-11T014154.084Z_eeg.xdf',
#  'LabRecorder_2025-09-11T101328.256Z_eeg.xdf',
#  'LabRecorder_2025-09-11T154549.460Z_eeg.xdf',
#  'LabRecorder_2025-09-12T220903.464Z_eeg.xdf',
#  'LabRecorder_2025-09-18T031842.989Z_eeg.xdf',
#  'LabRecorder_2025-09-18T121337.267Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-12T215537.892Z.xdf',
#  'LabRecorder_Apogee_2025-09-18T151839.043Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-18T152308.395Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-19T051346.012Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-19T205118.364Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-20T214749.964Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-21T003051.428Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-21T085541.696Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-22T213547.659Z_eeg.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-12T014018.162Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-13T021042.451Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-13T031209.598Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-19T001746.449Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-19T012938.518Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-19T015439.979Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-19T022210.910Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-20T023803.932Z.xdf']




# ['xdf_filename', 'first_timestamp', 'last_timestamp', 'sample_count',
    #    'lab_recorder_xdf_file_idx', 'xdf_filename', 'proccessed_fif_filename',
    #    'proccessed_mat_filename', 'xdf_dataset_idx', 'recording_datetime',
    #    'recording_day_date', 'duration_sec']

['LabRecorder_Apogee_2025-10-21T050857.606Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-20T222728.335Z_eeg.xdf',
 'LabRecorder_Apogee_2025-11-06T150252.171Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T040726.583Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-21T051157.400Z_eeg.xdf',
 'LabRecorder_Apogee_2025-10-20T215045.162Z_eeg.xdf']

In [ ]:
_out_xdf_stream_infos_df.reset_index(drop=True).groupby('xdf_dataset_idx').first()

In [ ]:
lab_recorder_xdf_files

In [12]:


def extract_annotations_df(active_only_out_eeg_raws) -> pd.DataFrame:
    ## Extract comments/notes/annotations/etc from the outputs

    _extracted_comments = []
    ignored_comment_descriptions = ['BAD_motion', '']
    for a_raw in active_only_out_eeg_raws:
        an_annotations = a_raw.annotations
        if (an_annotations is not None) and (len(an_annotations) > 0):
            an_annotation_df = an_annotations.to_data_frame(time_format='datetime')
            an_annotation_df = an_annotation_df[np.logical_not(np.isin(an_annotation_df['description'], ignored_comment_descriptions))]
            _extracted_comments.append(an_annotation_df)
            # an_annotation_df


    extracted_comments_df: pd.DataFrame = pd.concat(_extracted_comments)
    extracted_comments_df = extracted_comments_df.rename(columns={'onset':'time', 'description':'text'}, inplace=False)
    return extracted_comments_df

annotations_df = extract_annotations_df(_out_eeg_raw)
annotations_df

,time,duration,text
1,2025-10-21 05:08:58.753650000,0.0,test
4,2025-10-21 05:08:59.700884000,0.0,m
7,2025-10-21 05:09:00.287942000,0.0,m
12,2025-10-21 05:09:00.983398000,0.0,m
14,2025-10-21 05:09:01.696406000,0.0,m
...,...,...,...
1455,2025-12-10 12:25:16.516487000,0.0,Thanks for watching!
1694,2025-12-10 12:30:08.679300000,0.0,Thanks for watching!
1856,2025-12-10 12:33:18.520750999,0.0,Thanks for watching!
1867,2025-12-10 12:33:25.394925000,0.0,Thanks for watching!
1973,2025-12-10 12:34:55.539991000,0.0,My eyes are rash shedding tears.

In [ ]:
# from pyphoplacecellanalysis.GUI.PyQtPlot.Widgets.SpikeRasterWidgets.Spike2DRaster import Spike2DRaster, SynchronizedPlotMode

In [ ]:
_out_xdf_stream_infos_df

In [ ]:
len(_out_xdf_stream_infos_df)
_out_xdf_stream_infos_df.loc[0]

In [ ]:
_out_eeg_raw

# Run Batch Computations on `_out_eeg_raw`

# ACTIVE: refine the active raws and compute them

In [6]:
from phoofflineeeganalysis.analysis.EEG_data import EEGComputations, EEGData
from phoofflineeeganalysis.PendingNotebookCode import batch_compute_all_eeg_datasets, render_all_spectograms_to_high_quality_pdfs, plot_all_spectograms
from phoofflineeeganalysis.PendingNotebookCode import plot_session_spectogram
## INPUTS: _out_eeg_raw
# Process only the last 5 datasets using 4 workers:
# limit_num_items: int = 150
limit_num_items: int = 5
active_only_out_eeg_raws, results = batch_compute_all_eeg_datasets(eeg_raws=_out_eeg_raw, limit_num_items=limit_num_items, max_workers = 4)

## OUTPUTS: active_only_out_eeg_raws, results
# 1m 19.8s for 25 sessions

Processing 5 EEG datasets using 4 parallel workers...
  Processing dataset 1/5 (meas_date: 2025-12-10 03:02:52+00:00)
running raw_data_topo...
  Processing dataset 2/5 (meas_date: 2025-12-10 10:09:39+00:00)
running raw_data_topo...
  Processing dataset 3/5 (meas_date: 2025-12-10 11:22:54+00:00)
running raw_data_topo...
  Processing dataset 4/5 (meas_date: 2025-12-10 11:53:01+00:00)
running raw_data_topo...
for INPUT PARAMS: epoch_dur: 4, epoch_step: 0.25, moving_avg_epochs: 32
	step_samples: 32, window_samples: 512
	n_ch: 14, n_times: 278184
for INPUT PARAMS: epoch_dur: 4, epoch_step: 0.25, moving_avg_epochs: 32
	step_samples: 32, window_samples: 512
	n_ch: 14, n_times: 218881
for INPUT PARAMS: epoch_dur: 4, epoch_step: 0.25, moving_avg_epochs: 32
	step_samples: 32, window_samples: 512
	n_ch: 14, n_times: 323742
for INPUT PARAMS: epoch_dur: 4, epoch_step: 0.25, moving_avg_epochs: 32
	step_samples: 32, window_samples: 512
	n_ch: 14, n_times: 538911
	done.
running cwt...
	done.
running cwt...
	done.
running spectogram...
	done.
running cwt...
	done.
  Completed dataset 3/5 (meas_date: 2025-12-10 11:22:54+00:00)
  Processing dataset 5/5 (meas_date: 2025-12-10 12:49:22+00:00)
running raw_data_topo...
for INPUT PARAMS: epoch_dur: 4, epoch_step: 0.25, moving_avg_epochs: 32
	step_samples: 32, window_samples: 512
	n_ch: 14, n_times: 17005
	done.
running cwt...
	done.
running spectogram...
	done.
  Completed dataset 5/5 (meas_date: 2025-12-10 12:49:22+00:00)
	done.
running spectogram...
	done.
running spectogram...
	done.
  Completed dataset 1/5 (meas_date: 2025-12-10 03:02:52+00:00)
	done.
running cwt...
	done.
  Completed dataset 4/5 (meas_date: 2025-12-10 11:53:01+00:00)
	done.
running spectogram...
	done.
  Completed dataset 2/5 (meas_date: 2025-12-10 10:09:39+00:00)
Completed processing all 5 EEG datasets.

In [7]:
from phoofflineeeganalysis.analysis.SavedSessionsProcessor import XDFDataStreamAccessor

num_sessions: int = len(results)
num_sessions

# xdf_stream_infos_df: pd.DataFrame = XDFDataStreamAccessor.init_from_results(_out_xdf_stream_infos_df=_out_xdf_stream_infos_df, active_only_out_eeg_raws=active_only_out_eeg_raws)
xdf_stream_infos_df: pd.DataFrame = XDFDataStreamAccessor.init_from_results(_out_xdf_stream_infos_df=_out_xdf_stream_infos_df, active_only_out_eeg_raws=active_only_out_eeg_raws)
# xdf_stream_infos_df: pd.DataFrame = XDFDataStreamAccessor.init_from_results(_out_xdf_stream_infos_df=_out_xdf_stream_infos_df[_out_xdf_stream_infos_df['name'] == 'Epoc X'], active_only_out_eeg_raws=active_only_out_eeg_raws)
xdf_stream_infos_df

5

,name,fs,n_samples,n_channels,type,stream_id,effective_srate,hostname,source_id,channel_count,...,proccessed_mat_filename,xdf_dataset_idx,recording_datetime,recording_day_date,duration_sec,created_at_rel,first_timestamp_rel,last_timestamp_rel,duration_sec_check,duration_rel
xdf_dataset_idx,,,,,,,,,,,,,,,,,,,,,
0,TextLogger,0.0,4,1,Markers,1,1.938226,Apogee,textlogger_001,1,...,2025-10-20T21-50-45.mat,0,2025-12-10 03:02:52+00:00,2025-12-10 00:00:00+00:00,NaT,0.364848,0.377568,0.377592,0 days 00:00:02.063742700,0.000024
0,Epoc X,128.0,2444,14,EEG,4,128.624640,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-20T21-50-45.mat,0,2025-12-10 03:02:52+00:00,2025-12-10 00:00:00+00:00,0 days 00:00:19.093750,0.377183,0.377476,0.377696,0 days 00:00:19.001019200,0.000220
0,Epoc X Motion,16.0,609,6,SIGNAL,2,32.069478,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-10-20T21-50-45.mat,0,2025-12-10 03:02:52+00:00,2025-12-10 00:00:00+00:00,0 days 00:00:38.062500,0.377183,0.377476,0.377696,0 days 00:00:18.990016900,0.000220
1,Epoc X Motion,16.0,69633,6,SIGNAL,4,32.015464,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-10-20T21-51-09.mat,1,2025-12-10 10:09:39+00:00,2025-12-10 00:00:00+00:00,0 days 01:12:32.062500,0.377183,0.377754,0.402927,0 days 00:36:14.980186699,0.025173
1,Epoc X,128.0,279275,14,EEG,3,128.402111,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-20T21-51-09.mat,1,2025-12-10 10:09:39+00:00,2025-12-10 00:00:00+00:00,0 days 00:36:21.835937500,0.377183,0.377754,0.402927,0 days 00:36:15.003185999,0.025174
2,Epoc X Motion,16.0,1265,6,SIGNAL,2,32.043215,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-10-20T22-27-28.mat,2,2025-12-10 11:22:54+00:00,2025-12-10 00:00:00+00:00,0 days 00:01:19.062500,0.377183,0.402976,0.403433,0 days 00:00:39.477943,0.000457
2,Epoc X,128.0,5067,14,EEG,4,128.301409,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-20T22-27-28.mat,2,2025-12-10 11:22:54+00:00,2025-12-10 00:00:00+00:00,0 days 00:00:39.585937500,0.377183,0.402976,0.403433,0 days 00:00:39.492942601,0.000457
3,Epoc X Motion,16.0,865,6,SIGNAL,1,32.054846,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-10-21T04-07-26.mat,3,2025-12-10 11:53:01+00:00,2025-12-10 00:00:00+00:00,0 days 00:00:54.062500,0.619785,0.639066,0.639379,0 days 00:00:26.984998700,0.000312
3,Epoc X,128.0,3464,14,EEG,4,128.291579,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-21T04-07-26.mat,3,2025-12-10 11:53:01+00:00,2025-12-10 00:00:00+00:00,0 days 00:00:27.062500,0.619785,0.639066,0.639379,0 days 00:00:27.000983500,0.000313
4,Epoc X Motion,16.0,9174,6,SIGNAL,4,32.020820,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-10-21T04-08-00.mat,4,2025-12-10 12:49:22+00:00,2025-12-10 00:00:00+00:00,0 days 00:09:33.375000,0.619785,0.639460,0.642776,0 days 00:04:46.501084500,0.003316
4,Epoc X,128.0,36781,14,EEG,1,128.381819,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-21T04-08-00.mat,4,2025-12-10 12:49:22+00:00,2025-12-10 00:00:00+00:00,0 days 00:04:47.351562500,0.619785,0.639459,0.642775,0 days 00:04:46.496961100,0.003316

In [14]:
## Extract comments/notes/annotations/etc from the outputs

_extracted_comments = []
ignored_comment_descriptions = ['BAD_motion', '']
for a_raw in active_only_out_eeg_raws:
    an_annotations = a_raw.annotations
    if (an_annotations is not None) and (len(an_annotations) > 0):
        an_annotation_df = an_annotations.to_data_frame(time_format='datetime')
        an_annotation_df = an_annotation_df[np.logical_not(np.isin(an_annotation_df['description'], ignored_comment_descriptions))]
        _extracted_comments.append(an_annotation_df)
        # an_annotation_df


extracted_comments_df: pd.DataFrame = pd.concat(_extracted_comments)
extracted_comments_df = extracted_comments_df.rename(columns={'onset':'time', 'description':'text'}, inplace=False)
extracted_comments_df

In [16]:
active_only_out_eeg_raws

In [ ]:
results

In [ ]:
from phoofflineeeganalysis.PendingNotebookCode import build_merged


cog_categorical_cats = ['cog_bad', 'cog_poor', 'cog_okay', 'cog_good', 'cog_great']

day_status_dict = {
    # '2025-09-19/01-54-39': 'cog_poor',
    # '2025-09-18/15-23-08': 'cog_poor',
    # '2025-09-22/21-35-47': 'cog_okay',
    # '2025-09-19/20-51-18': 'cog_good',
    # '2025-09-18/03-18-42': 'cog_great',
    # '2025-09-22/21-35-47': 'cog_bad',
    # '2025-09-21/08-55-41': 'cog_bad',
    ## new sessions
    # '2025-11-06/15:02:52': 'cog_okay',
    '2025-11-10/19-28-05': 'cog_okay',
    '2025-11-11/22-22-22': 'cog_bad',

}


# combined_spectogram_da: xr.DataArray = build_merged(active_only_out_eeg_raws=active_only_out_eeg_raws, results=results, day_status_dict=day_status_dict)
# combined_spectogram_da

combined_spectogram_ds, combined_spectogram_da = build_merged(active_only_out_eeg_raws=active_only_out_eeg_raws, results=results, day_status_dict=day_status_dict)
combined_spectogram_ds

In [24]:
# netcdf_save_path = Path("2025-10-16_saved_spectogram.nc")
outputs_root_folder: Path = Path(r'L:\AITEMP\PhoOfflineEEGAnalysisOutputs').resolve()
outputs_root_folder.exists()

# netcdf_save_path = Path("2025-10-16_saved_spectogram.nc")
netcdf_save_path: Path = outputs_root_folder.joinpath("2025-11-12_saved_spectogram.nc").resolve()
combined_spectogram_da.to_netcdf(netcdf_save_path)
print(f'netcdf_save_path: "{netcdf_save_path.as_posix()}"')
# combined_spectogram_da.to_
# combined_spectogram_ds.to_netcdf(

## Plotting/Viz

In [25]:
from phoofflineeeganalysis.analysis.UI.standalone_data_browser_gui import make_app

## INPUTS: combined_spectogram_ds, extracted_comments_df
app = make_app(ds=combined_spectogram_ds, comments_df=extracted_comments_df)
pn.serve(app, show=True)

### 2025-09-30 - Programmatic output to .html interactive plot

In [ ]:
netcdf_save_path = Path(r'L:/AITEMP/PhoOfflineEEGAnalysisOutputs/2025-11-12_saved_spectogram.nc').resolve()
assert netcdf_save_path.exists()
ds_disk = xr.open_dataset(netcdf_save_path)
ds_disk = ds_disk.load()
ds_disk

ds_disk

In [ ]:
from phoofflineeeganalysis.analysis.UI.spectrogram_gui import make_app

app = make_app(ds_disk, channels_to_select=['AF3','F7','F3','FC5'])
# app = make_app(combined_spectogram_da, channels_to_select=['AF3','F7','F3','FC5'])
# app = make_app(combined_spectogram_ds, channels_to_select=['AF3','F7','F3','FC5'])
pn.serve(app, show=True) # if using programmatic server

# make_app(ds, channels_to_select)

# 2025-10-02 - Plot Single Raw EEG

In [ ]:
import holoviews as hv
import mne
import pandas as pd
import panel as pn
from holoviews.operation.downsample import downsample1d

# pn.extension('tabulator')
hv.extension('bokeh')
# hv.extension('plotly') # type: ignore

from bokeh.io import output_notebook, show
output_notebook()

from phoofflineeeganalysis.PendingNotebookCode import plot_holoviews_multichannel_raw

# then any show(fig) will display inline

a_raw = active_only_out_eeg_raws[-2]
a_raw
curves_overlay_lttb = plot_holoviews_multichannel_raw(a_raw=a_raw, time_col_name = 'time')
curves_overlay_lttb

## 2025-10-16 - Batch Figure Export to .html files

In [ ]:
from phoofflineeeganalysis.PendingNotebookCode import build_merged

## INPUTS: active_only_out_eeg_raws, results

cog_categorical_cats = ['cog_bad', 'cog_poor', 'cog_okay', 'cog_good', 'cog_great']

day_status_dict = {
    '2025-09-19/01-54-39': 'cog_poor',
    '2025-09-18/15-23-08': 'cog_poor',
    '2025-09-22/21-35-47': 'cog_okay',
    '2025-09-19/20-51-18': 'cog_good',
    '2025-09-18/03-18-42': 'cog_great',
    '2025-09-22/21-35-47': 'cog_bad',
    '2025-09-21/08-55-41': 'cog_bad',
}


# combined_spectogram_da: xr.DataArray = build_merged(active_only_out_eeg_raws=active_only_out_eeg_raws, results=results, day_status_dict=day_status_dict)
# combined_spectogram_da

combined_spectogram_ds, combined_spectogram_da = build_merged(active_only_out_eeg_raws=active_only_out_eeg_raws, results=results, day_status_dict=day_status_dict, only_include_sessions_with_status_entries=False)
combined_spectogram_ds

In [ ]:
## OUTPUTS: combined_spectogram_da
combined_spectogram_da.sel(session=['2025-09-10/15-37-31'])

In [ ]:
import holoviews as hv
from plotly.io import to_html
from bokeh.layouts import column, row
from bokeh.embed import file_html
from bokeh.resources import CDN
from phoofflineeeganalysis.PendingNotebookCode import plot_holoviews_multichannel_raw
from phoofflineeeganalysis.PendingNotebookCode import plot_scrollable_spectogram

# active_data = ds_disk
# # active_data = partial_sess_ds

channels_to_select = ['AF3', 'F3', 'AF4', 'F4']
# _out = plot_scrollable_spectogram(ds_disk=active_data,
#     channels_to_select = channels_to_select,
#     fig_export_path="spectrogram_sessions.html",
#     # fig_export_path=None,
#     plot_indiv_channels=False,
# )
# _out.show()



export_html_parent_path = Path(r"L:/SlowSwap/Databases/AnalysisData/MNE_preprocessed/outputs/viz").resolve()
assert export_html_parent_path.exists()

num_sessions: int = len(active_only_out_eeg_raws)
assert len(results) == num_sessions, f"len(results): {len(results)} != num_sessions: {num_sessions}, but they should be equal!"
print(f'exporting {num_sessions} sessions to "{export_html_parent_path.as_posix()}"....')
for idx, (a_raw, a_result) in enumerate(zip(active_only_out_eeg_raws, results)):
    a_meas_date = a_raw.info.get('meas_date')
    a_raw_key: str = a_meas_date.strftime("%Y-%m-%d/%H-%M-%S") # '2025-09-22/21-35-47' or '2025-09-10/15-37-31'
    print(f'raw[{idx}/{num_sessions}]: a_raw_key: "{a_raw_key}"')
    curves_overlay_lttb = plot_holoviews_multichannel_raw(a_raw=a_raw, time_col_name = 'time', enable_downsampling=False)
    print(f'\ttype(curves_overlay_lttb): {type(curves_overlay_lttb)}')
    active_data = combined_spectogram_da.sel(session=[a_raw_key]) ## retains the .sessions property
    a_scrollable_spectogram = plot_scrollable_spectogram(ds_disk=active_data,
        channels_to_select = channels_to_select,
        # fig_export_path="spectrogram_sessions.html",
        fig_export_path=None,
        plot_indiv_channels=False,
    )
    print(f'\ttype(a_scrollable_spectogram): {type(a_scrollable_spectogram)}')

    # --- Holoviews (Bokeh) HTML ---
    bokeh_obj = hv.render(curves_overlay_lttb, backend='bokeh')
    bokeh_html = file_html(bokeh_obj, resources=CDN, title=f"EEG Overlay {a_raw_key}")
    html_str: str = file_html(bokeh_obj, resources=CDN, title="EEG Overlay")


    # --- Plotly HTML ---
    plotly_html: str = to_html(a_scrollable_spectogram, include_plotlyjs='cdn', full_html=False)

    # --- Combine both into one page ---
    combined_html: str = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>EEG Session {idx}: {a_raw_key}</title>
        <style>
            body {{
                display: flex;
                flex-direction: column;
                gap: 2em;
                margin: 2em;
                font-family: sans-serif;
                background-color: #fafafa;
            }}
            iframe {{
                border: none;
                width: 100%;
                height: 1000px;
            }}
        </style>
    </head>
    <body>
        <h2>EEG Session {idx}: {a_raw_key}</h2>
        <section>
            <h3>Raw Multichannel Overlay</h3>
            {bokeh_html}
        </section>
        <section>
            <h3>Scrollable Spectrogram</h3>
            {plotly_html}
        </section>
    </body>
    </html>
    """

    ## TODO: how do I create a column of the two valid html strings?
    # all_items = hv.Div((curves_overlay_lttb, a_scrollable_spectogram))
    # convert Holoviews object to Bokeh
    # bokeh_obj = hv.render(curves_overlay_lttb, backend='bokeh')
    # html_str: str = file_html(bokeh_obj, resources=CDN, title="EEG Overlay")

    # write to HTML
    an_export_path = export_html_parent_path.joinpath(f"curves_overlay_lttb_{idx}.html").resolve()
    print(f'\twriting to "{an_export_path.as_posix()}"...')
    
    with open(an_export_path, "w", encoding="utf-8") as f:
        f.write(combined_html)

print(f'done with all.')

# XXX  2025-10-02 - tried to get it computing spectogram for Epoch-type objects in addition to RawEEG

In [ ]:
from phoofflineeeganalysis.analysis.EEG_data import EEGComputations, EEGData
from phoofflineeeganalysis.PendingNotebookCode import batch_compute_all_eeg_datasets, render_all_spectograms_to_high_quality_pdfs, plot_all_spectograms
from phoofflineeeganalysis.PendingNotebookCode import plot_session_spectogram

## INPUTS: _out_eeg_raw
## INPUTS: epochs_cleaned
epochs_cleaned_result = EEGComputations.run_all(raw=epochs_cleaned)

In [ ]:
import scipy.ndimage
from scipy.signal import spectrogram

## INPUTS: epochs_cleaned
# nperseg = 1024
# noverlap = 512

nperseg = 32
noverlap = 16

picks = mne.pick_types(epochs_cleaned.info, eeg=True, meg=False)

fs: float = epochs_cleaned.info["sfreq"]
data = epochs_cleaned.get_data(picks=picks) # np.shape(data) (229, 14, 384) - (n_epochs, n_chan, n_times)
ch_names = deepcopy(epochs_cleaned.info.ch_names)
# raw = deepcopy(raw)
# raw.down_convert_to_base_type()
Sxx_list = []
Sxx_avg_list = []

spectogram_result_dict = {}
for ch_idx, a_ch in enumerate(epochs_cleaned.info.ch_names):
    f, t, Sxx = spectrogram(data[ch_idx], fs=fs, nperseg=nperseg, noverlap=noverlap) # #TODO 2025-09-28 13:25: - [ ] Convert to newer `ShortTimeFFT.spectrogram`
    # np.shape(Sxx): (14, 17, 23) - (n_chan, n_freq, n_time)

    spectogram_result_dict[a_ch] = (f, t, Sxx) ## a tuple
    Sxx_list.append(Sxx) # np.shape(Sxx) # (513, 1116) - (n_freqs, n_times)
    Sxx_avg = np.nanmean(Sxx, axis=-1) ## average over all time to get one per session
    Sxx_avg_list.append(Sxx_avg)

Sxx_avg_list = np.stack(Sxx_avg_list) # (14, 513) - (n_channels, n_freqs)
Sxx_list = np.stack(Sxx_list) # (14, 513, 1116) - (n_channels, n_freqs, n_times)

In [ ]:
np.shape(f)
np.shape(t)
np.shape(Sxx) # (14, 17, 23) - (n_chan, n_freq, n_time)
np.shape(data[ch_idx]) # (14, 384) - (n_chan, n_epochs)

In [ ]:
np.shape(data) # (229, 14, 384) - (

In [ ]:
np.shape(Sxx_avg_list) # (14, 14, 17)
np.shape(Sxx_list) # (14, 14, 17, 23)

In [ ]:
Sxx_avg_list = xr.DataArray(Sxx_avg_list, dims=("channels", "freqs"), coords={"channels": ch_names, "freqs": f})

In [ ]:
Sxx_list = xr.DataArray(Sxx_list, dims=("channels", "freqs", "times"), coords={"channels": ch_names, "freqs": f, "times": t})

In [ ]:
combined_spectogram_ds, combined_spectogram_da = build_merged(active_only_out_eeg_raws=active_only_out_eeg_raws, results=results, day_status_dict=day_status_dict)
combined_spectogram_ds

In [ ]:
epochs.compute_psd().plot_topomap(ch_type="eeg", normalize=False, contours=0)

# 2025-10-01 - Plot Bokeh to .html file

In [ ]:
import holoviews as hv
from bokeh.embed import file_html
from bokeh.resources import CDN

# convert Holoviews object to Bokeh
bokeh_obj = hv.render(curves_overlay_lttb, backend='bokeh')

# write to HTML
html_str = file_html(bokeh_obj, CDN, "EEG Overlay")
with open("curves_overlay_lttb.html", "w", encoding="utf-8") as f:
    f.write(html_str)

# 2025-10-01 - Plot Single

In [ ]:
# ds_disk = 
partial_sess_ds = ds_disk.sel(session=['2025-09-21/08-55-41', '2025-09-22/21-35-47'])
partial_sess_ds

# small_netcdf_save_path = Path("2025-09-30_small_saved_spectogram.nc")
small_netcdf_save_path = Path("2025-11-05_small_saved_spectogram.nc")
partial_sess_ds.to_netcdf(small_netcdf_save_path)

In [ ]:
partial_sess_ds.cognitive_status.loc['2025-09-21/08-55-41'].item()

# 2025-10-02 - ONLY THING WORTH DOING IN THE WHOLE WORLD

In [ ]:
# a_raw.compute_psd().plot_topomap(ch_type="eeg", normalize=False, contours=0)

In [ ]:
a_raw.plot()

In [ ]:

from phoofflineeeganalysis.PendingNotebookCode import plot_scrollable_spectogram

active_data = ds_disk
# active_data = partial_sess_ds

channels_to_select = ['AF3', 'F3', 'AF4', 'F4']
_out = plot_scrollable_spectogram(ds_disk=active_data,
    channels_to_select = channels_to_select,
    fig_export_path="spectrogram_sessions.html",
    # fig_export_path=None,
    plot_indiv_channels=False,
)
_out.show()

## 2025-09-29 - Resume

In [ ]:
import hvplot.xarray

for a_result in results:
    spec_da = a_result['spectogram']['Sxx']
spec_da

In [ ]:
# spec_da = combined_spectogram_ds.sel(session='2025-09-19/20-51-18', cognitive_status='cog_great')
spec_da = combined_spectogram_da.sel(session='2025-09-19/20-51-18')
spec_da

In [ ]:
# --- Define the channels you want to select ---
channels_to_select = ['AF3', 'F7', 'F3', 'FC5']

# --- Use .sel() to select the desired channels by label ---
selected_da = spec_da.sel(channels=channels_to_select)
# selected_da = spec_da.sel(channels=['AF3'])
selected_da

# --- Average over the 'channels' dimension ---
# This is the key operation
da_mean = spec_da.mean(dim='channels')
da_mean

In [ ]:

# Assuming 'spec_da' is your xarray DataArray with dimensions ('channels', 'freqs', 'times')

# Plot each channel's spectrogram in a vertical stack
stacked_plot = selected_da.hvplot(
    x='times',
    y='freqs',
    col='channels',  # This is the key change to create a stacked column plot
    cmap='viridis',
    clim=(selected_da.min(), selected_da.max()),
    width=1800,
    height=900,      # You may want to adjust the height of individual plots
    title='Spectrograms per Channel'
).opts(width=900)

# layout.opts(
#     opts.Curve( height=200, width=900, xaxis=None, line_width=1.50, color='red', tools=['hover']),
#     opts.Spikes(height=150, width=900, yaxis=None, line_width=0.25, color='grey')).cols(1)

# %output backend='bokeh'
stacked_plot

In [ ]:
# display graph in browser
# a bokeh server is automatically started
bokeh_server = pn.Row(stacked_plot).show(port=12345)

In [ ]:

# stop the bokeh server (when needed)
bokeh_server.stop()

In [ ]:
hv.extension('bokeh', 'matplotlib')
from bokeh.plotting import show

show(hv.render(stacked_plot))

In [ ]:
%%output backend='bokeh' fig='png'
stacked_plot

In [ ]:
# plt.show()
fig = plt.figure()
fig.show()

In [ ]:
!bokeh info

In [ ]:
display(stacked_plot)

In [ ]:
# Generate an interactive spectrogram with a slider for the time dimension
hv_plot_slider = spec_da.hvplot(
    x='times',
    y='freqs',
    cmap='viridis',
    clim=(spec_da.min(), spec_da.max()), # Set color limits
    width=800,
    height=400,
    groupby='times', # This is the key argument
    title='Interactive Spectrogram with hvPlot Slider'
)

hv_plot_slider

In [ ]:

# Save the linked layout to a self-contained HTML file
hv.save(
    stacked_plot,
    'holoviz_spectrogram.html',
    backend='bokeh',
    # The resources parameter can be used to control how JS/CSS are included,
    # with 'INLINE' being the most portable option.
    resources='INLINE'
)

In [ ]:
from phoofflineeeganalysis.analysis.EEG_data import EEGComputations
from phoofflineeeganalysis.analysis.SavedSessionsProcessor import LabRecorderXDF

hdf5_out_path: Path = Path('E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed').joinpath('2025-09-29_all_HDF.h5').resolve()

hdf5_out_path.unlink(missing_ok=True)

LabRecorderXDF.to_hdf(active_only_out_eeg_raws=active_only_out_eeg_raws, results=results, xdf_stream_infos_df=xdf_stream_infos_df, file_path=hdf5_out_path, root_key='/')

In [ ]:
flat_annotations = []
for an_xdf_dataset_idx in np.arange(num_sessions):
    a_raw = active_only_out_eeg_raws[an_xdf_dataset_idx]
    a_meas_date = a_raw.info.get('meas_date')
    a_raw_key: str = a_meas_date.strftime("%Y-%m-%d/%H-%M-%S") # '2025-09-22/21-35-47'
    a_result = results[an_xdf_dataset_idx]
    # EEGComputations.to_hdf(a_result=a_result, file_path=hdf5_out_path, root_key=f'/result/{a_raw_key}')
    # EEGComputations.to_hdf(a_result=a_result, file_path=f, root_key=f'/result/{a_raw_key}')
    # EEGComputations.perform_write_to_hdf(a_result=a_result, f=f, root_key=f'/result/{a_raw_key}')
    # a_stream_info = deepcopy(_out_xdf_stream_infos_df).loc[an_xdf_dataset_idx]    
    # print(f'i: {i}, a_meas_date: {a_meas_date}, a_stream_info: {a_stream_info}\n\n')
    # print(f'i: {an_xdf_dataset_idx}, a_meas_date: {a_meas_date}')
    an_annotations_df = a_raw.annotations.to_data_frame(time_format='datetime')
    an_annotations_df = an_annotations_df[an_annotations_df['description'] != 'BAD_motion']
    an_annotations_df['xdf_dataset_idx'] = an_xdf_dataset_idx
    an_annotations_df['xdf_raw_key'] = a_raw_key
    flat_annotations.append(an_annotations_df)

    ## Add metadata to a_raw and a_result
    # 2025-09-18/03-18-42

flat_annotations = pd.concat(flat_annotations, ignore_index=True)
flat_annotations

In [ ]:
import xarray as xr

cog_categorical_cats = ['cog_bad', 'cog_poor', 'cog_okay', 'cog_good', 'cog_great']

day_status_dict = {'2025-09-19/01-54-39': 'cog_poor',
'2025-09-18/15-23-08': 'cog_poor',
'2025-09-22/21-35-47': 'cog_okay',
'2025-09-19/20-51-18': 'cog_good',
'2025-09-18/03-18-42': 'cog_great',
'2025-09-22/21-35-47': 'cog_bad',
'2025-09-21/08-55-41': 'cog_bad',
}

In [ ]:
netcdf_save_path = Path("2025-09-30_saved_spectogram.nc")
combined_spectogram_da.to_netcdf(netcdf_save_path)

In [ ]:
netcdf_save_path = Path("2025-09-30_saved_spectogram.nc")

ds_disk = xr.open_dataset(netcdf_save_path)
ds_disk = ds_disk.load()
ds_disk

In [ ]:
import xarray as xr
import zarr
import numcodecs
import numpy as np
from pathlib import Path
from typing import Union
from phoofflineeeganalysis.PendingNotebookCode import ZarrSerialization

cog_categorical_cats = ['cog_bad', 'cog_poor', 'cog_okay', 'cog_good', 'cog_great']

day_status_dict = {
    '2025-09-19/01-54-39': 'cog_poor',
    '2025-09-18/15-23-08': 'cog_poor',
    '2025-09-22/21-35-47': 'cog_okay',
    '2025-09-19/20-51-18': 'cog_good',
    '2025-09-18/03-18-42': 'cog_great',
    '2025-09-22/21-35-47': 'cog_bad',
    '2025-09-21/08-55-41': 'cog_bad',
}


zarr_out_path = Path("2025-09-30_all_sessions.zarr")

zarr_out_path = ZarrSerialization.save_sessions_as_zarr(active_only_out_eeg_raws=active_only_out_eeg_raws, results=results, day_status_dict=day_status_dict, out_path=zarr_out_path)

## Immediately re-load from file
all_data = ZarrSerialization.load_sessions_from_zarr(zarr_out_path, verbose=True)

# Export Spectogram XArray Spectograms to Interactive Plots

In [ ]:
import xarray as xr
import zarr
import panel as pn
import hvplot.xarray
import numpy as np
from pathlib import Path

# # # --- 1. Data Loading Function ---

# # --- 2. Setup the Interactive Dashboard ---
# ZARR_FILE_PATH = Path("2025-09-29_all_sessions.zarr")

# try:
#     all_data = load_sessions_from_zarr(ZARR_FILE_PATH)
#     all_data = deepcopy(
# except (FileNotFoundError, ValueError) as e:
#     pn.pane.Alert(f"Error loading data: {e}", alert_type='danger').servable()
# else:

In [ ]:
# all_data = results
# all_data = all_Sxx
all_data = combined_spectogram_da
## INPUTS: all_data

pn.extension(sizing_mode="stretch_width")

# --- 3. Create Interactive Widgets ---
# cog_statuses = sorted(np.unique(all_data.cognitive_status.values).tolist())
cog_statuses = sorted(np.unique([v.attrs['cognitive_status'] for v in all_data]).tolist())

channels = all_data.channels.values.tolist()

status_select = pn.widgets.Select(name='Cognitive Status', options=['All'] + cog_statuses, value='All')
session_select = pn.widgets.Select(name='Session')
channel_select = pn.widgets.Select(name='Channel', options=channels)

# --- 4. Dependent Widgets ---
@pn.depends(status_select.param.value, watch=True)
def _update_session_options(status):
    if status == 'All':
        sessions = sorted(all_data.session.values.tolist())
    else:
        filtered_data = all_data.where(all_data.cognitive_status == status, drop=True)
        sessions = sorted(filtered_data.session.values.tolist())
    session_select.options = sessions
    if sessions:
        session_select.value = sessions[0]

# --- 5. Plot Function ---
@pn.depends(session_select.param.value, channel_select.param.value)
def plot_spectrogram(session_key, channel):
    if not session_key or channel is None:
        return pn.pane.Markdown("### Please select a session and channel to view the spectrogram.")
    spec_da = all_data['Sxx'].sel(session=session_key, channels=channel).squeeze()
    spec_da_db = 10 * np.log10(spec_da + 1e-10)
    spec_da_db.attrs['long_name'] = 'Power (dB)'
    plot = spec_da_db.hvplot.quadmesh(
        x='times', y='freqs', cmap='viridis', rasterize=True, height=500,
        title=f"Session: {session_key} | Channel: {channel}", xlabel="Time (s)", ylabel="Frequency (Hz)",
        clabel="Power Spectral Density (dB)"
    ).opts(responsive=True)
    return plot

# --- 6. Dashboard Layout ---
dashboard = pn.template.FastListTemplate(
    site="EEG Spectrogram Viewer",
    title="Interactive Session Analysis",
    sidebar=[status_select, session_select, channel_select],
    main=[plot_spectrogram],
    accent_base_color="#4A90E2",
    header_background="#4A90E2",
)

dashboard.servable()

In [ ]:
from pyphocorehelpers.plotting.image_plotting_helpers import IMShowHelpers


def plot_matrix(xbin_edges, ybin_edges, matrix, ax, **kwargs):

    def setup_stable_axes_limits(xbins_edges, ybin_edges, ax):
        " manually sets the axis data limits to disable autoscaling given the xbins_edges/ybin_edges "
        # x == horizontal orientation:
        ax.set_xlim(left=xbins_edges[0], right=xbins_edges[-1])
        ax.set_ylim(bottom=ybin_edges[0], top=ybin_edges[-1])


    variable_value = matrix

    xmin, xmax, ymin, ymax = (xbin_edges[0], xbin_edges[-1], ybin_edges[0], ybin_edges[-1]) # the same for both orientations
    x_first_extent = (xmin, xmax, ymin, ymax) # traditional order of the extant axes
    # y_first_extent = (ymin, ymax, xmin, xmax) # swapped the order of the extent axes.
    main_plot_kwargs = {
        'cmap': 'viridis',
        'origin':'lower',
        'extent':x_first_extent,
        'aspect': 'auto',        
    }

    """
    Note that changing the origin while keeping everything else the same doesn't flip the direction of the yaxis labels despite flipping the yaxis of the data.
    """
    im_out = ax.imshow(variable_value, **main_plot_kwargs)
    setup_stable_axes_limits(xbin_edges, ybin_edges, ax)
    return im_out

In [ ]:
fig = plt.figure(layout="constrained", figsize=[9, 9], dpi=220, clear=True) # figsize=[Width, height] in inches.
long_width_ratio = 1
ax_dict = fig.subplot_mosaic(
    [
        ["ax_dumb", "ax_dumb_avg"],
        ["ax_good", "ax_good_avg"],
		
        # ["ax_dumb_avg"],
        # ["ax_good_avg"],
    ],
    # set the height ratios between the rows
    # set the width ratios between the columns
    width_ratios=[10, 1],
    sharey=True,
    gridspec_kw=dict(wspace=0, hspace=0.0) # `wspace=0`` is responsible for sticking the pf and the activity axes together with no spacing
)
fig.show()

In [ ]:
import napari

viewer = napari.Viewer(ndisplay=3)

# viewer.add_points(mov_avg_filtered, size=2, face_color='red', name='mov_avg_filtered')
# viewer.add_points(data2, size=2, face_color='green', name='dataset2')
# viewer.add_points(data3, size=2, face_color='blue', name='dataset3')

In [ ]:

named_sessions_dict = {'dumb': -2,
					   'good': -6,
}

# dumb_session_idx: int = -2

_out_layers = {}

for a_name, an_xdf_dataset_idx in named_sessions_dict.items():
    a_raw = active_only_out_eeg_raws[an_xdf_dataset_idx]
    a_meas_date: datetime = a_raw.info.get('meas_date')
    a_raw_key: str = a_meas_date.strftime("%Y-%m-%d/%H-%M-%S") # '2025-09-22/21-35-47'

    # an_annotations_df = a_raw.annotations.to_data_frame(time_format='datetime')
    # an_annotations_df = an_annotations_df[an_annotations_df['description'] != 'BAD_motion']

    # a_result = results[an_xdf_dataset_idx]
    # # a_stream_info = deepcopy(_out_xdf_stream_infos_df).loc[an_xdf_dataset_idx]    
    # Sxx = a_result['spectogram']['Sxx']
    # Sxx_avg = a_result['spectogram']['Sxx_avg']
    # # t = a_result['spectogram']['t']
    # # freqs = a_result['spectogram']['freqs']
    # # fs = a_result['spectogram']['fs']
    # freqs, t, _ = a_result['spectogram']['spectogram_result_dict']['AF3']
    
    # Sxx_avg_across_channel_avg = np.atleast_2d(Sxx_avg.mean(dim='channels', skipna=True))
    # # Sxx_avg_across_channel_avg
    
    # Sxx_across_channel_avg = Sxx.mean(dim='channels', skipna=True)
    # # Sxx_across_channel_avg

    # ax_label = f"ax_{a_name}"
    # ax_label_avg = f"ax_{a_name}_avg"
    # # np.shape(Sxx_across_channel_avg)
    
    # # xbin = deepcopy(t)
    # # ybin = deepcopy(freqs)
    # # xmin, xmax, ymin, ymax = (xbin[0], xbin[-1], ybin[0], ybin[-1])
    # # # xmin, xmax, ymin, ymax = (active_one_step_decoder.ybin[0], active_one_step_decoder.ybin[-1], active_one_step_decoder.xbin[0], active_one_step_decoder.xbin[-1]) # Reversed x and y axes, seems not good.
    # # extent = (xmin, xmax, ymin, ymax)
    
    # # ax_dict[ax_label].imshow(Sxx_avg_across_channel_avg.T)
    # # ax_dict[ax_label_avg].imshow(Sxx_across_channel_avg, extent=extent, origin='lower')
    
    # # fig, axs, plot_im_out = IMShowHelpers.final_x_vertical_plot_imshow(xbin_edges=np.arange(1), ybin_edges=freqs, matrix=Sxx_avg_across_channel_avg, ax=ax_dict[ax_label])
    # # ax_dict[ax_label].autoscale(False)
    # # fig, axs, plot_im_out = IMShowHelpers.final_x_horizontal_plot_imshow(xbin_edges=t, ybin_edges=freqs, matrix=Sxx_across_channel_avg, ax=ax_dict[ax_label])
    # im_out = plot_matrix(xbin_edges=t, ybin_edges=freqs, matrix=Sxx_across_channel_avg, ax=ax_dict[ax_label])
    # ax_dict[ax_label].set_ylabel(a_name)
    # # ax_dict[ax_label].autoscale(False)
    

    # # fig, axs, plot_im_out = IMShowHelpers.final_x_vertical_plot_imshow(xbin_edges=t, ybin_edges=freqs, matrix=Sxx_avg_across_channel_avg, ax=ax_dict[ax_label_avg])
    # avg_im_out = plot_matrix(xbin_edges=[0.0, 1.0], ybin_edges=freqs, matrix=Sxx_avg_across_channel_avg, ax=ax_dict[ax_label_avg])
    # # ax_dict[ax_label_avg].set_ylabel(f"{a_name}_avg")

    
    # napari_img_layer_kwargs = dict(
    #     # channel_axis=None,
    #     # rgb=None,
    #     colormap='yellow', #'bop_blue',
    #     # contrast_limits=None,
    #     gamma=0.02,
    #     interpolation2d='nearest',
    #     interpolation3d='linear',
    #     rendering='mip',
    #     depiction='volume',
    #     # iso_threshold=None,
    #     # attenuation=0.05,
    #     # name=None,
    #     # metadata=None,
    #     # scale=None,
    #     translate=None,
    #     # rotate=None,
    #     # shear=None,
    #     # affine=None,
    #     # opacity=1,
    #     blending='additive',
    #     visible=True,
    #     # multiscale=None,
    #     # cache=True,
    #     # plane=None,
    #     # experimental_clipping_planes=None,
    #     # custom_interpolation_kernel_2d=None,
    # )
    

    # curr_name = f"{a_name}"
    # _out_layers[curr_name] = viewer.add_image(Sxx, name=curr_name, **napari_img_layer_kwargs)
    # viewer.dims.axis_labels = Sxx.dims # ('channels', 'freqs', 'times')

    # curr_name = f"{a_name}_avg"
    # # napari_img_layer_kwargs['translate'] = [0.0, 1852.0]
    # napari_img_layer_kwargs['translate'] = [0.0, -2.0]
    # _out_avg_layer = viewer.add_image(Sxx_avg.T, name=curr_name, **napari_img_layer_kwargs) #  colormap='bop_blue', gamma=0.20, rendering='additive'
    # _out_layers[curr_name] = _out_avg_layer

In [ ]:
# _out_avg_layer.translate([512.0, 0.0])
# _out_avg_layer.set_translation([512.0, 0.0])
# _out_avg_layer.translate = [0.0, 513.0]
_out_avg_layer.translate = [0.0, 1852.0]
_out_avg_layer.translate

In [ ]:
_out_avg_layer.

In [ ]:
viewer.dims
viewer.layers

In [ ]:
from pyphoplacecellanalysis.GUI.Napari.napari_helpers import napari_extract_layers_info

# @function_attributes(short_name=None, tags=['napari', 'config'], input_requires=[], output_provides=[], uses=[], used_by=['napari_extract_layers_info'], creation_date='2024-08-12 08:54', related_items=[])
def extract_layer_info(a_layer):
    """ Extracts info as a dict from a single Napari layer. 
    by default Napari layers print like: `<Shapes layer 'Shapes' at 0x1635a1e8460>`: without any properties that can be easily referenced.
    This function extracts a dict of properties.

    from pyphoplacecellanalysis.GUI.Napari.napari_helpers import extract_layer_info

    """
    out_properties_dict = {}
    positioning = ['scale', 'translate', 'rotate', 'shear', 'affine', 'corner_pixels']
    visual = ['opacity', 'blending', 'visible', 'z_index', 'contrast_limits_range', '_colormap_name', 'gamma']
    # positioning = ['scale', 'translate', 'rotate', 'shear', 'affine']
    out_properties_dict['positioning'] = {}

    for a_property_name in positioning:
        out_properties_dict['positioning'][a_property_name] = getattr(a_layer, a_property_name)

    out_properties_dict['visual'] = {}
    for a_property_name in visual:
        try:
            out_properties_dict['visual'][a_property_name] = getattr(a_layer, a_property_name)
        except (AttributeError, ValueError, KeyError, TypeError) as e:
            print(f'failed to get property: "{a_property_name}" with error {e}')
            pass
        except Exception as e:
            raise

    return out_properties_dict


# @function_attributes(short_name=None, tags=['napari', 'config'], input_requires=[], output_provides=[], uses=['extract_layer_info'], used_by=[], creation_date='2024-08-12 08:54', related_items=[])
def napari_extract_layers_info(layers):
	"""extracts info dict from each layer as well.
	Usage:
        from pyphoplacecellanalysis.GUI.Napari.napari_helpers import napari_extract_layers_info
		layers = directional_viewer.layers # [<Shapes layer 'Shapes' at 0x1635a1e8460>, <Shapes layer 'Shapes [1]' at 0x164d5402e50>]
		out_layers_info_dict = debug_print_layers_info(layers)

	"""
	out_layers_info_dict = {}
	for a_layer in layers:
		a_name: str = str(a_layer.name)
		out_properties_dict = extract_layer_info(a_layer)
		out_layers_info_dict[a_name] = out_properties_dict
		# if isinstance(a_layer, Shapes):
		# 	print(f'shapes layer: {a_layer}')
		# 	a_shapes_layer: Shapes = a_layer
		# 	# print(f'a_shapes_layer.properties: {a_shapes_layer.properties}')
		# 	out_properties_dict = extract_layer_info(a_layer)
		# 	print(f'\tout_properties_dict: {out_properties_dict}')
		# 	out_layers_info_dict[a_name] = out_properties_dict
		# else:
		# 	print(f'unknown layer: {a_layer}')	
	return out_layers_info_dict





layers = viewer.layers # [<Shapes layer 'Shapes' at 0x1635a1e8460>, <Shapes layer 'Shapes [1]' at 0x164d5402e50>]
out_layers_info_dict = napari_extract_layers_info(layers)
out_layers_info_dict

In [ ]:
out_layers_info_dict['dumb']

In [ ]:
from napari.layers.image.image import Image

property_names = ['metadata', 'blending', 'opacity', 'rendering', 'scale', 'gamma', 'contrast_limits_range', 'colormap']
for a_layer in layers:
    an_img_layer: Image = a_layer
    
#    type(a_layer)

# an_img_layer.blending
an_img_layer.__dict__

In [ ]:
napari.run()

In [ ]:
import xarray as xr

## INPUTS: a_result
a_spectogram_result: Dict = a_result['spectogram'] 

ch_names = a_spectogram_result['ch_names']
fs = a_spectogram_result['fs']
a_spectogram_result_dict = a_spectogram_result['spectogram_result_dict'] # Dict[channel: Tuple]
Sxx = a_spectogram_result['Sxx']
Sxx_avg = a_spectogram_result['Sxx_avg']

Sxx

In [ ]:

Sxx_avg_list = [] 

# ch_names = a_raw.info.ch_names

for a_ch, a_tuple in a_spectogram_result_dict.items():
    f, t, Sxx = a_tuple ## unpack the tuple
    # np.shape(Sxx) # (513, 1116) - (n_freqs, n_times)
    n_freqs = np.shape(f)
    n_times = np.shape(t) 
    Sxx_avg = np.nanmean(Sxx, axis=-1) ## average over all time to get one per session
    Sxx_avg_list.append(Sxx_avg)
    
Sxx_avg_list = np.stack(Sxx_avg_list) # (14, 513) - (n_channels, n_freqs)
Sxx_avg_list = xr.DataArray(Sxx_avg_list, dims=("channels", "freqs"), coords={"channels": ch_names, "freqs": f})
np.shape(Sxx_avg_list)
Sxx_avg_list

In [ ]:
ch_names

In [ ]:
a_raw.annotations

In [ ]:
Sxx_avg = np.nanmean(Sxx, axis=-1) ## average over all time to get one per session
Sxx_avg

In [ ]:
plt.close('all')

In [ ]:
plot_all_spectograms(active_only_out_eeg_raws, results)

In [ ]:
import matplotlib.pyplot as plt

plt.rcParams["axes.titlesize"] = 8
plt.rcParams["axes.labelsize"] = 8
plt.rcParams["xtick.labelsize"] = 6
plt.rcParams["ytick.labelsize"] = 6
plt.rcParams["legend.fontsize"] = 6
plt.rcParams["figure.titlesize"] = 8
plt.rcParams["axes.titlepad"] = 0
plt.rcParams["figure.constrained_layout.use"] = True
plt.rcParams["figure.constrained_layout.h_pad"] = 0.0
plt.rcParams["figure.constrained_layout.w_pad"] = 0.0
plt.rcParams["figure.constrained_layout.hspace"] = 0.0
plt.rcParams["figure.constrained_layout.wspace"] = 0.0
plt.rcParams["figure.subplot.wspace"] = 0.0
plt.rcParams["figure.subplot.hspace"] = 0.0
plt.rcParams["figure.subplot.wspace"] = 0.0
plt.rcParams["figure.subplot.hspace"] = 0.0

In [ ]:
## Plot a synchronized EEG Raw data and Spectogram Figure together:
active_eeg_idx: int = -4
mne_raw_fig = active_only_out_eeg_raws[active_eeg_idx].plot(time_format='datetime', scalings='auto') # MNEBrowseFigure
fig, axs = plot_session_spectogram(active_only_out_eeg_raws[active_eeg_idx], results[active_eeg_idx], sync_to_mne_raw_fig=mne_raw_fig)
# plt.subplots_adjust(wspace=0, hspace=0)  # remove spacing

In [ ]:
active_eeg_idx: int = -6
mne_raw_fig2 = active_only_out_eeg_raws[active_eeg_idx].plot(time_format='datetime', scalings='auto') # MNEBrowseFigure
fig2, axs2 = plot_session_spectogram(active_only_out_eeg_raws[active_eeg_idx], results[active_eeg_idx], sync_to_mne_raw_fig=mne_raw_fig)

### Compute and show all spectograms

In [ ]:
# Compute results first
active_only_out_eeg_raws, results = batch_compute_all_eeg_datasets(eeg_raws=_out_eeg_raw, limit_num_items=3)

# Render to PDFs (paged)
from pathlib import Path
out_paths = render_all_spectograms_to_high_quality_pdfs(
    active_only_out_eeg_raws,
    results,
    output_parent_folder=Path(r"E:/Dropbox (Personal)/Databases/AnalysisData/MNE_preprocessed/exports"),
    mode="paged",
    seconds_per_page=180.0,
    freq_min_hz=1.0,
    freq_max_hz=40.0,
    dpi=300
)
print(f"Wrote {len(out_paths)} PDF(s)")

## ANalysis for Fatigue/Bandpowers

In [ ]:
from phoofflineeeganalysis.analysis.computations.fatigue_analysis import compare_multiple_recordings, compute_fatigue_metrics, analyze_fatigue_trends, print_analysis_report, visualize_fatigue_comparison

raw_objects = deepcopy(_out_eeg_raw)
raw_obj_labels = [str(a_raw) for a_raw in raw_objects]
if len(raw_objects) >= 2:
    results = compare_multiple_recordings(raw_objects, raw_obj_labels[:len(raw_objects)])
    print_analysis_report(results)
    visualize_fatigue_comparison(results)

    results
else:
    print("Not enough data files found for comparison.")

# 2025-12-10 - Build Timeline Browser from parsed streams

_out_xdf_stream_infos_df: pd.DataFrame = XDFDataStreamAccessor.init_from_results(_out_xdf_stream_infos_df=_out_xdf_stream_infos_df, active_only_out_eeg_raws=_out_eeg_raw) # [_out_xdf_stream_infos_df['name'] == 'Epoc X']
_out_xdf_stream_infos_df

In [ ]:
## INPUTS: _out_xdf_stream_infos_df: pd.DataFrame

In [ ]:
_out_xdf_stream_infos_df

csv_save_path = Path('../output').joinpath('2025-12-10_all_xdf_stream_infos.csv').resolve()
print(f'csv_save_path: "{csv_save_path.as_posix()}"')
_out_xdf_stream_infos_df.to_csv(csv_save_path)

## load with: 
# csv_save_path = Path('../output').joinpath('2025-12-10_all_xdf_stream_infos.csv').resolve()
# assert csv_save_path.exists()
# all_xdf_stream_infos_df: pd.DataFrame = pd.read_csv(csv_save_path)

,name,fs,n_samples,n_channels,type,stream_id,effective_srate,hostname,source_id,channel_count,...,proccessed_mat_filename,xdf_dataset_idx,recording_datetime,recording_day_date,duration_sec,created_at_rel,first_timestamp_rel,last_timestamp_rel,duration_sec_check,duration_rel
xdf_dataset_idx,,,,,,,,,,,,,,,,,,,,,
0,TextLogger,0.0,4,1,Markers,1,1.938226,Apogee,textlogger_001,1,...,2025-10-20T21-50-45.mat,0,2025-10-20 21:50:45+00:00,2025-10-20 00:00:00+00:00,NaT,0.364848,0.377568,0.377592,0 days 00:00:02.063742700,0.000024
0,Epoc X,128.0,2444,14,EEG,4,128.624640,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-20T21-50-45.mat,0,2025-10-20 21:50:45+00:00,2025-10-20 00:00:00+00:00,0 days 00:00:19.093750,0.377183,0.377476,0.377696,0 days 00:00:19.001019200,0.000220
0,Epoc X Motion,16.0,609,6,SIGNAL,2,32.069478,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-10-20T21-50-45.mat,0,2025-10-20 21:50:45+00:00,2025-10-20 00:00:00+00:00,0 days 00:00:38.062500,0.377183,0.377476,0.377696,0 days 00:00:18.990016900,0.000220
1,Epoc X Motion,16.0,69633,6,SIGNAL,4,32.015464,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-10-20T21-51-09.mat,1,2025-10-20 21:51:09+00:00,2025-10-20 00:00:00+00:00,0 days 01:12:32.062500,0.377183,0.377754,0.402927,0 days 00:36:14.980186699,0.025173
1,Epoc X,128.0,279275,14,EEG,3,128.402111,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-10-20T21-51-09.mat,1,2025-10-20 21:51:09+00:00,2025-10-20 00:00:00+00:00,0 days 00:36:21.835937500,0.377183,0.377754,0.402927,0 days 00:36:15.003185999,0.025174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Epoc X,128.0,323742,14,EEG,2,128.392663,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T11-53-01.mat,73,2025-12-10 11:53:01+00:00,2025-12-10 00:00:00+00:00,0 days 00:42:09.234375,0.781706,0.854498,0.883682,0 days 00:42:01.499227200,0.029184
73,TextLogger,0.0,5,1,Markers,4,0.008635,Apogee,textlogger_001,1,...,2025-12-10T11-53-01.mat,73,2025-12-10 11:53:01+00:00,2025-12-10 00:00:00+00:00,NaT,0.854148,0.876905,0.883607,0 days 00:09:39.023505700,0.006702
74,Epoc X eQuality,128.0,17005,14,Raw,6,128.341998,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T12-49-22.mat,74,2025-12-10 12:49:22+00:00,2025-12-10 00:00:00+00:00,0 days 00:02:12.851562500,0.781706,0.893633,0.895167,0 days 00:02:12.497548700,0.001534
74,Epoc X Motion,16.0,4243,6,SIGNAL,1,32.024928,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,6,...,2025-12-10T12-49-22.mat,74,2025-12-10 12:49:22+00:00,2025-12-10 00:00:00+00:00,0 days 00:04:25.187500,0.781706,0.893633,0.895167,0 days 00:02:12.490548300,0.001533
74,Epoc X,128.0,17005,14,EEG,2,128.341991,Apogee,Emotiv Epoc X_8_36463030463646303630314636464631,14,...,2025-12-10T12-49-22.mat,74,2025-12-10 12:49:22+00:00,2025-12-10 00:00:00+00:00,0 days 00:02:12.851562500,0.781706,0.893633,0.895167,0 days 00:02:12.497556400,0.001534

csv_save_path: "C:/Users/pho/repos/EmotivEpoc/PhoOfflineEEGAnalysis/output/2025-12-10_all_xdf_stream_infos.csv"

In [19]:
from phoofflineeeganalysis.analysis.UI.historical_data_timeline import (
    TimelineWidget, VideoMetadataTrack, EEGRecordingTrack, 
    MotionRecordingTrack, PhoLogTrack, WhisperTrack
)

timeline = TimelineWidget()


csv_save_path = Path('../output').joinpath('2025-12-09_parsed_videos.csv').resolve()
assert csv_save_path.exists()
video_df: pd.DataFrame = pd.read_csv(csv_save_path)

csv_save_path = Path('../output').joinpath('2025-12-10_all_xdf_stream_infos.csv').resolve()
assert csv_save_path.exists()
all_xdf_stream_infos_df: pd.DataFrame = pd.read_csv(csv_save_path)


# Add tracks from different modalities
timeline.add_track(VideoMetadataTrack(video_df))
timeline.add_tracks_from_xdf_streams(all_xdf_stream_infos_df)
timeline.show()

In [ ]:
timeline.add_tracks_from_xdf_streams(all_xdf_stream_infos_df)

In [ ]:

timeline.add_track(EEGRecordingTrack(eeg_df))
timeline.add_track(MotionRecordingTrack(motion_df))
timeline.add_track(PhoLogTrack(pho_log_df))
timeline.add_track(WhisperTrack(whisper_df))