# Parses and builds the metadata for all recorded videos in the videos directory using 

https://abhitronix.github.io/deffcode/latest
https://abhitronix.github.io/deffcode/latest/recipes/basic/

In [1]:
%config IPCompleter.use_jedi = False
%pdb off
%load_ext autoreload
%autoreload 3
# %matplotlib inline
%matplotlib qt5
import mne
mne.viz.set_browser_backend("qt")  # or "matplotlib"
mne.set_config("MNE_BROWSER_BACKEND", "qt")  # or "matplotlib"
%gui qt

# ==================================================================================================================================================================================================================================================================================== #
# PyQtInspect:                                                                                                                                                                                                                                                                         #
# ==================================================================================================================================================================================================================================================================================== #
# 1. Launch `pqi-server` in a new terminal BEFORE running this notebook cell. Be sure to click 'Serve' button in the GUI that appears so this notebook can connect.

# # IMPORTANT: Call settrace BEFORE importing PyQt5
# import PyQtInspect.pqi as pqi

# # Connect to the server (default: localhost:19394)
# # Make sure the server is already running!
# pqi.settrace(
#     host='127.0.0.1',
#     port=19394,  # Default port, or use the port shown in the server GUI
#     qt_support='pyqt5',  # or 'auto' for auto-detection
#     patch_multiprocessing=False
# )

# # # !pip install viztracer
# %load_ext viztracer
# from viztracer import VizTracer


import xarray as xr # Assuming you're using this
import numpy as np   # For the example

import xarray as xr
import zarr
import panel as pn
import holoviews as hv
hv.extension('bokeh', logo=False)

import hvplot.xarray
import hvplot.pandas
# This line is crucial for displaying plots in a notebook
hvplot.extension('bokeh') # You can also use 'matplotlib' or 'plotly'

# hv.extension('bokeh')
# hv.extension('matplotlib') # or 'matplotlib'
# hv.extension('plotly') # or 'matplotlib'
from holoviews import opts
import panel as pn
pn.extension()

import IPython


# Jupyter-lab enable printing for any line on its own (instead of just the last one in the cell)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import time
import re
from datetime import datetime, timezone

import uuid
from copy import deepcopy
from typing import Dict, List, Tuple, Optional, Callable, Union, Any
from nptyping import NDArray
from matplotlib import pyplot as plt

from pathlib import Path
import numpy as np
import pandas as pd
from numpy.typing import NDArray

import mne
from mne import set_log_level
from copy import deepcopy
import mne

from mne.io import read_raw

datasets = []
# mne.viz.set_browser_backend("Matplotlib")
mne.viz.set_browser_backend("qt")

from phopylslhelper.easy_time_sync import EasyTimeSyncParsingMixin, readable_dt_str, from_readable_dt_str

from phoofflineeeganalysis.analysis.MNE_helpers import MNEHelpers
from phoofflineeeganalysis.analysis.historical_data import HistoricalData
from phoofflineeeganalysis.analysis.motion_data import MotionData
from phoofflineeeganalysis.analysis.EEG_data import EEGComputations, EEGData
from phoofflineeeganalysis.analysis.anatomy_and_electrodes import ElectrodeHelper
# from ..EegProcessing import bandpower
# from phoofflineeeganalysis.EegProcessing import analyze_eeg_trends
from phoofflineeeganalysis.EegVisualization import VisHelpers
from phoofflineeeganalysis.analysis.SavedSessionsProcessor import SavedSessionsProcessor, SessionModality, DataModalityType

def get_now_time_str(time_separator='-') -> str:
    return str(time.strftime(f"%Y-%m-%d_%H{time_separator}%m", time.localtime(time.time())))


set_log_level("WARNING")


# db_root_path = Path('/content/drive/MyDrive/Databases')
# db_root_path = Path(r'E:/Dropbox (Personal)/Databases') ## APOGEE
db_root_path = Path(r'E:/Dropbox (Personal)/Databases') # WIN10_VM
assert db_root_path.exists(), f"'{db_root_path.as_posix()}' does not exist!"

# eeg_recordings_file_path: Path = Path(r'E:/Dropbox (Personal)/Databases/UnparsedData/EmotivEpocX_EEGRecordings/fif')
# headset_motion_recordings_file_path: Path = Path(r'E:/Dropbox (Personal)/Databases/UnparsedData/EmotivEpocX_EEGRecordings/MOTION_RECORDINGS/fif')

# assert eeg_recordings_file_path.exists()
# assert headset_motion_recordings_file_path.exists()

eeg_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEpocX_EEGRecordings/fif')
flutter_eeg_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEEG_FlutterRecordings')
flutter_motion_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEEG_FlutterRecordings/MOTION_RECORDINGS')
flutter_GENERIC_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEEG_FlutterRecordings/GENERIC_RECORDINGS')

headset_motion_recordings_file_path: Path = db_root_path.joinpath('UnparsedData/EmotivEpocX_EEGRecordings/MOTION_RECORDINGS/fif')
WhisperVideoTranscripts_LSL_Converted = db_root_path.joinpath('UnparsedData/WhisperVideoTranscripts_LSL_Converted')
pho_log_to_LSL_recordings_path: Path = db_root_path.joinpath('UnparsedData/PhoLogToLabStreamingLayer_logs')
## These contain little LSL .fif files with names like: '20250808_062814_log.fif',

eeg_analyzed_parent_export_path = db_root_path.joinpath('AnalysisData/MNE_preprocessed')
# pickled_data_path = db_root_path.joinpath('AnalysisData/MNE_preprocessed/PICKLED_COLLECTION')
# assert pickled_data_path.exists()

# lab_recorder_output_path = Path(r"E:\Dropbox (Personal)\Databases\UnparsedData\LabRecorderStudies\sub-P001")
lab_recorder_output_path = db_root_path.joinpath('UnparsedData/LabRecorderStudies/sub-P001')
assert lab_recorder_output_path.exists()

# n_most_recent_sessions_to_preprocess: int = None # None means all sessions
# n_most_recent_sessions_to_preprocess: int = 35
# n_most_recent_sessions_to_preprocess: int = 5
n_most_recent_sessions_to_preprocess: int = 10
# n_most_recent_sessions_to_preprocess = None

# # modern_found_EEG_recording_files = HistoricalData.get_recording_files(recordings_dir=lab_recorder_output_path, recordings_extensions=['.xdf'])
# modern_found_EEG_recording_files = HistoricalData.get_recording_files(recordings_dir=[lab_recorder_output_path, pho_log_to_LSL_recordings_path], recordings_extensions=['.xdf']) ## both sources
# # modern_found_EEG_recording_files

# most_recent_modern_found_EEG_recording_files: List[Path] = modern_found_EEG_recording_files[:n_most_recent_sessions_to_preprocess]
# # most_recent_modern_found_EEG_recording_files

Automatic pdb calling has been turned OFF
Using qt as 2D backend.

## Timeline

In [ ]:
import pyphoplacecellanalysis.External.pyqtgraph as pg
from pypho_timeline.timeline_builder import TimelineBuilder
# from pypho_timeline.widgets import SimpleTimelineWidget, perform_process_all_streams
# from pypho_timeline.__main__ import PositionTrackDatasource, VideoTrackDatasource, main, main_all_modalities_from_xdf_file_example

# Create Qt application
app = pg.mkQApp("pyPhoTimelineXDFExample")

builder: TimelineBuilder = TimelineBuilder()


# Timeline Widget from just Video Track

In [4]:
from pathlib import Path
import os
from pypho_timeline.rendering.datasources.specific.video import VideoTrackDatasource


max_num_video_files: int = 1000

# Specify your video folder path
# video_folder = Path(r"E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/Videos")
video_folder = Path(r"M:/ScreenRecordings/EyeTrackerVR_Recordings")
assert video_folder.exists() and video_folder.is_dir()

# Gather all video files (adjust extensions as needed)
video_extensions = ('.mp4', '.avi', '.mov', '.mkv', '.wmv')
all_videos = [p for p in video_folder.glob('*') if p.suffix.lower() in video_extensions]

# Sort by modification time (descending), get 5 most recent
all_videos.sort(key=lambda p: p.stat().st_mtime, reverse=True)
recent_videos = all_videos[:max_num_video_files]
recent_videos


# Create the VideoTrackDatasource
video_ds: VideoTrackDatasource = VideoTrackDatasource(video_paths=recent_videos)

# Choose a name for the new video track
video_track_name: str = "RecentVideosTrack"

C:\Users\pho\repos\ACTIVE_DEV\pyPhoCoreHelpers\src\pyphocorehelpers\indexing_helpers.py:1183: UserWarning: registration of accessor <class 'pyphocorehelpers.indexing_helpers.PhoDataframeAccessor'> under name 'pho' for type <class 'pandas.core.frame.DataFrame'> is overriding a preexisting attribute with the same name.
  class PhoDataframeAccessor:

[WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T100228.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T090224.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T080220.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T070216.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T060212.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T050208.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T040153.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T030150.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T020145.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T010141.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-17T000138.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T230134.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T220129.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T212149.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T212147.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T192336.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T182207.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T172202.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T162158.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T152155.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T142150.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T132116.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T131052.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T121048.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T113945.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T103941.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T093934.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T083929.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-16T073925.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T182645.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T161937.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T151933.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T141929.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T131926.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T121922.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T111918.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T101914.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T081809.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T071805.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T014407.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-13T004403.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T234400.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T224356.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T211254.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T201251.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T191248.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T181245.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T171242.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T161238.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T151233.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T141230.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T131227.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T121223.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T093235.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T083231.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T072605.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-12T072602.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T193927.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T183923.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T164201.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T154157.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T144153.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T134150.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T124146.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T114143.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T073643.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T063638.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T053634.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T043630.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T033625.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T030327.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-11T020231.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T200336.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T190331.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T180326.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T142510.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T132505.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T122500.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T112454.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T102449.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T092445.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T081304.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T071259.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T040108.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T030104.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T020100.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T010056.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-10T000051.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T230047.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T220042.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T195735.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T185730.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T175725.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T174315.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T164310.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T164144.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T154118.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T151940.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T141935.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T140100.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T112349.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T102347.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T092343.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T082339.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-09T072334.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T234049.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T232646.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T222642.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T212639.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T202635.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T192631.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T182627.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T172624.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T172431.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T103418.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T093415.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T091246.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-06T081241.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T200742.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T190738.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T180734.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T170730.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T162727.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T152722.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T092434.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T082431.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T072427.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T062424.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T052421.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T042417.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-05T032413.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T202406.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T192402.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T182414.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T172408.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T162404.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T152400.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T142356.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T132353.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T122349.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T112346.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T102342.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T092338.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T082335.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T072331.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T062328.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T054222.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T044218.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T034214.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T024211.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T014208.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-04T004205.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T192320.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T182316.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T152847.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T142843.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T132838.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T122831.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T112827.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T102823.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T092817.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T082813.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T072808.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T062803.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T052800.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T042757.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T032754.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T022750.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T012747.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-03T002743.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-02T234837.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-02T225954.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-02T195957.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-02T194913.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-02T184908.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-02T174905.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-02-02T164900.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T215814.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T205810.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T195807.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T185802.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T175758.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T165754.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T155750.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T145745.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T135741.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T125736.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T115730.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T105726.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T095722.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T085719.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T084659.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T074647.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-23T064641.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-22T203459.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-22T193454.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-22T183451.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-22T173447.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-22T163920.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-22T153904.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-22T143900.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-22T084311.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T184419.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T174413.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T164409.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T092008.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T082005.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T072001.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T061958.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T051955.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T041951.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T031949.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T021946.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-21T011943.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T234311.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T224307.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T214302.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T204258.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T194841.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T184838.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T174835.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T162818.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T152814.mp4'),
 WindowsPath('M:/ScreenRecordings/EyeTrackerVR_Recordings/Debut_2026-01-19T142810.mp4'),

C:\Users\pho\repos\ACTIVE_DEV\pyPhoTimeline\pypho_timeline\rendering\datasources\track_datasource.py:389: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
  intervals_df = intervals_df.astype({'t_start_dt': 'datetime64[ns]', 't_end_dt': 'datetime64[ns]'})

In [ ]:
video_only_timeline = builder.build_from_video(video_datasource=video_ds) # , video_paths=recent_videos

In [ ]:
video_ds.total_df_start_end_times
video_metadata_df: pd.DataFrame = deepcopy(video_ds.df).drop(columns=['pen', 'brush', 'series_vertical_offset', 'series_height'], inplace=False)
video_metadata_df

(Timestamp('2025-09-08 15:11:01'), Timestamp('2026-02-17 10:42:05.467317708'))

,t_start,t_duration,video_file_path,video_num_frames,video_fps,video_width,video_height,video_file_size,cache_file_size,cache_file_mtime,t_start_dt,t_end_dt,label
0,2025-09-08 15:11:01,3600.265299,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,107754,29.929461,640,480,110763068,110763068,1.757362e+09,2025-09-08 15:11:01,2025-09-08 16:11:01.265299479,Debut_2025-09-08T151101.mp4
1,2025-09-08 16:11:04,3600.265299,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,107709,29.916962,640,480,109516780,109516780,1.757366e+09,2025-09-08 16:11:04,2025-09-08 17:11:04.265299479,Debut_2025-09-08T161104.mp4
2,2025-09-08 17:11:06,3473.603320,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,103942,29.923394,640,480,101564456,101564456,1.757369e+09,2025-09-08 17:11:06,2025-09-08 18:08:59.603320313,Debut_2025-09-08T171106.mp4
3,2025-09-08 18:10:01,3600.265299,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,107929,29.978069,640,480,108463680,108463680,1.757373e+09,2025-09-08 18:10:01,2025-09-08 19:10:01.265299479,Debut_2025-09-08T181001.mp4
4,2025-09-08 19:10:04,1616.397331,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,29717,18.384712,640,480,45915895,45915895,1.757375e+09,2025-09-08 19:10:04,2025-09-08 19:37:00.397330729,Debut_2025-09-08T191004.mp4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,2026-02-17 06:02:12,3600.181315,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,52454,14.569822,640,480,98834992,98834992,1.771330e+09,2026-02-17 06:02:12,2026-02-17 07:02:12.181315104,Debut_2026-02-17T060212.mp4
979,2026-02-17 07:02:16,3600.299284,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,54010,15.001531,640,480,98529745,98529745,1.771333e+09,2026-02-17 07:02:16,2026-02-17 08:02:16.299283854,Debut_2026-02-17T070216.mp4
980,2026-02-17 08:02:20,3600.327344,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,53999,14.998358,640,480,98303527,98303527,1.771337e+09,2026-02-17 08:02:20,2026-02-17 09:02:20.327343750,Debut_2026-02-17T080220.mp4
981,2026-02-17 09:02:24,3600.477344,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,85460,23.735742,640,480,104178310,104178310,1.771341e+09,2026-02-17 09:02:24,2026-02-17 10:02:24.477343750,Debut_2026-02-17T090224.mp4
982,2026-02-17 10:02:28,2377.467318,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,70142,29.502824,640,480,70243673,70243673,1.771343e+09,2026-02-17 10:02:28,2026-02-17 10:42:05.467317708,Debut_2026-02-17T100228.mp4

In [13]:
parsed_video_out_path: Path = Path(r'C:\Users\pho\repos\ACTIVE_DEV\PhoOfflineEEGAnalysis\output').resolve()
assert parsed_video_out_path.exists() and parsed_video_out_path.is_dir()
parsed_video_out_file_path = parsed_video_out_path.joinpath(f'2026-02-17_parsed_videos.csv')
print(f'writing video metadata csv out to "{parsed_video_out_file_path}"...')
video_metadata_df.to_csv(parsed_video_out_file_path)
print(f'\tdone.')

writing video metadata csv out to "C:\Users\pho\repos\ACTIVE_DEV\PhoOfflineEEGAnalysis\output\2026-02-17_parsed_videos.csv"...
	done.

In [14]:

# Add the new video track to the existing timeline
# timeline.add_video_track(video_track_name, video_ds)
video_widget, root_graphics, plot_item, dock = timeline.add_video_track(track_name=video_track_name, video_datasource=video_ds)

# timeline.add_track(video_ds, name=video_track_name)

NameError: name 'timeline' is not defined

In [15]:
video_metadata_df

,t_start,t_duration,video_file_path,video_num_frames,video_fps,video_width,video_height,video_file_size,cache_file_size,cache_file_mtime,t_start_dt,t_end_dt,label
0,2025-09-08 15:11:01,3600.265299,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,107754,29.929461,640,480,110763068,110763068,1.757362e+09,2025-09-08 15:11:01,2025-09-08 16:11:01.265299479,Debut_2025-09-08T151101.mp4
1,2025-09-08 16:11:04,3600.265299,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,107709,29.916962,640,480,109516780,109516780,1.757366e+09,2025-09-08 16:11:04,2025-09-08 17:11:04.265299479,Debut_2025-09-08T161104.mp4
2,2025-09-08 17:11:06,3473.603320,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,103942,29.923394,640,480,101564456,101564456,1.757369e+09,2025-09-08 17:11:06,2025-09-08 18:08:59.603320313,Debut_2025-09-08T171106.mp4
3,2025-09-08 18:10:01,3600.265299,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,107929,29.978069,640,480,108463680,108463680,1.757373e+09,2025-09-08 18:10:01,2025-09-08 19:10:01.265299479,Debut_2025-09-08T181001.mp4
4,2025-09-08 19:10:04,1616.397331,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,29717,18.384712,640,480,45915895,45915895,1.757375e+09,2025-09-08 19:10:04,2025-09-08 19:37:00.397330729,Debut_2025-09-08T191004.mp4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,2026-02-17 06:02:12,3600.181315,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,52454,14.569822,640,480,98834992,98834992,1.771330e+09,2026-02-17 06:02:12,2026-02-17 07:02:12.181315104,Debut_2026-02-17T060212.mp4
979,2026-02-17 07:02:16,3600.299284,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,54010,15.001531,640,480,98529745,98529745,1.771333e+09,2026-02-17 07:02:16,2026-02-17 08:02:16.299283854,Debut_2026-02-17T070216.mp4
980,2026-02-17 08:02:20,3600.327344,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,53999,14.998358,640,480,98303527,98303527,1.771337e+09,2026-02-17 08:02:20,2026-02-17 09:02:20.327343750,Debut_2026-02-17T080220.mp4
981,2026-02-17 09:02:24,3600.477344,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,85460,23.735742,640,480,104178310,104178310,1.771341e+09,2026-02-17 09:02:24,2026-02-17 10:02:24.477343750,Debut_2026-02-17T090224.mp4
982,2026-02-17 10:02:28,2377.467318,\\APOGEE\mdd_m\ScreenRecordings\EyeTrackerVR_R...,70142,29.502824,640,480,70243673,70243673,1.771343e+09,2026-02-17 10:02:28,2026-02-17 10:42:05.467317708,Debut_2026-02-17T100228.mp4

In [ ]:
from deffcode import FFdecoder
import imageio
from deffcode import Sourcer ## for metadata extraction


def fetch_video_metadata_and_thumbnail_for_cache(a_video_file):
    """ 

    See also:
        https://abhitronix.github.io/deffcode/latest/recipes/advanced/decode-hw-acceleration/ - speed up decoding/frame generation with GPU

    """
    # initialize and formulate the decoder using suitable source
    sourcer = Sourcer(a_video_file).probe_stream()

    # print metadata as `json.dump`
    vid_json: str = str(sourcer.retrieve_metadata(pretty_json=True))

    # define the FFmpeg parameter to jump to 00:00:01.45(or 1s and 45msec)
    # in time in the video before it starts reading it and get one single frame
    ffparams = {"-ffprefixes": ["-ss", "00:00:01.45"], "-frames:v": 1}

    # initialize and formulate the decoder with suitable source
    decoder = FFdecoder(a_video_file, **ffparams).formulate()

    # grab the RGB24(default) frame from the decoder
    frame = next(decoder.generateFrame(), None)

    # check if frame is None
    if not(frame is None):
        # Save our output
        thumbnail_path = a_video_file.with_suffix(f'_thumb.png')
        imageio.imwrite(thumbnail_path, frame)
    else:
        raise ValueError("Something is wrong!")

    # terminate the decoder
    decoder.terminate()

In [ ]:
for a_video_row in video_metadata_df.itertuples():
    a_path = Path(a_video_row.video_file_path).resolve()
    if a_path.exists():
        fetch_video_metadata_and_thumbnail_for_cache(a_video_file=a_path)

Pandas(Index=0, t_start=Timestamp('2025-09-08 15:11:01'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-08T151101.mp4', video_num_frames=107754, video_fps=29.92946103599317, video_width=640, video_height=480, video_file_size=110763068, cache_file_size=110763068, cache_file_mtime=1757362264.1948273, t_start_dt=Timestamp('2025-09-08 15:11:01'), t_end_dt=Timestamp('2025-09-08 16:11:01.265299479'), label='Debut_2025-09-08T151101.mp4')

Pandas(Index=1, t_start=Timestamp('2025-09-08 16:11:04'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-08T161104.mp4', video_num_frames=107709, video_fps=29.916961957104036, video_width=640, video_height=480, video_file_size=109516780, cache_file_size=109516780, cache_file_mtime=1757365866.6600223, t_start_dt=Timestamp('2025-09-08 16:11:04'), t_end_dt=Timestamp('2025-09-08 17:11:04.265299479'), label='Debut_2025-09-08T161104.mp4')

Pandas(Index=2, t_start=Timestamp('2025-09-08 17:11:06'), t_duration=3473.6033203125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-08T171106.mp4', video_num_frames=103942, video_fps=29.92339378310156, video_width=640, video_height=480, video_file_size=101564456, cache_file_size=101564456, cache_file_mtime=1757369342.3449137, t_start_dt=Timestamp('2025-09-08 17:11:06'), t_end_dt=Timestamp('2025-09-08 18:08:59.603320313'), label='Debut_2025-09-08T171106.mp4')

Pandas(Index=3, t_start=Timestamp('2025-09-08 18:10:01'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-08T181001.mp4', video_num_frames=107929, video_fps=29.978068565006467, video_width=640, video_height=480, video_file_size=108463680, cache_file_size=108463680, cache_file_mtime=1757373003.6133268, t_start_dt=Timestamp('2025-09-08 18:10:01'), t_end_dt=Timestamp('2025-09-08 19:10:01.265299479'), label='Debut_2025-09-08T181001.mp4')

Pandas(Index=4, t_start=Timestamp('2025-09-08 19:10:04'), t_duration=1616.3973307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-08T191004.mp4', video_num_frames=29717, video_fps=18.38471236932474, video_width=640, video_height=480, video_file_size=45915895, cache_file_size=45915895, cache_file_mtime=1757374621.3919153, t_start_dt=Timestamp('2025-09-08 19:10:04'), t_end_dt=Timestamp('2025-09-08 19:37:00.397330729'), label='Debut_2025-09-08T191004.mp4')

Pandas(Index=5, t_start=Timestamp('2025-09-08 19:40:51'), t_duration=2570.2753255208336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-08T194051.mp4', video_num_frames=38560, video_fps=15.002283847620998, video_width=640, video_height=480, video_file_size=68432559, cache_file_size=68432559, cache_file_mtime=1757377423.1793377, t_start_dt=Timestamp('2025-09-08 19:40:51'), t_end_dt=Timestamp('2025-09-08 20:23:41.275325521'), label='Debut_2025-09-08T194051.mp4')

Pandas(Index=6, t_start=Timestamp('2025-09-08 21:37:53'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-08T213753.mp4', video_num_frames=53997, video_fps=14.998061123821964, video_width=640, video_height=480, video_file_size=101091904, cache_file_size=101091904, cache_file_mtime=1757385475.4309192, t_start_dt=Timestamp('2025-09-08 21:37:53'), t_end_dt=Timestamp('2025-09-08 22:37:53.265364583'), label='Debut_2025-09-08T213753.mp4')

Pandas(Index=7, t_start=Timestamp('2025-09-08 22:37:55'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-08T223755.mp4', video_num_frames=54000, video_fps=14.999144471541102, video_width=640, video_height=480, video_file_size=100128692, cache_file_size=100128692, cache_file_mtime=1757389077.672672, t_start_dt=Timestamp('2025-09-08 22:37:55'), t_end_dt=Timestamp('2025-09-08 23:37:55.205338542'), label='Debut_2025-09-08T223755.mp4')

Pandas(Index=8, t_start=Timestamp('2025-09-08 23:37:58'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-08T233758.mp4', video_num_frames=53988, video_fps=14.995686317165138, video_width=640, video_height=480, video_file_size=99351484, cache_file_size=99351484, cache_file_mtime=1757392680.04189, t_start_dt=Timestamp('2025-09-08 23:37:58'), t_end_dt=Timestamp('2025-09-09 00:37:58.235351562'), label='Debut_2025-09-08T233758.mp4')

Pandas(Index=9, t_start=Timestamp('2025-09-09 00:38:00'), t_duration=3600.3853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T003800.mp4', video_num_frames=54189, video_fps=15.050888921232552, video_width=640, video_height=480, video_file_size=98946852, cache_file_size=98946852, cache_file_mtime=1757396282.7559144, t_start_dt=Timestamp('2025-09-09 00:38:00'), t_end_dt=Timestamp('2025-09-09 01:38:00.385351563'), label='Debut_2025-09-09T003800.mp4')

Pandas(Index=10, t_start=Timestamp('2025-09-09 01:38:03'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T013803.mp4', video_num_frames=53967, video_fps=14.989728404713222, video_width=640, video_height=480, video_file_size=98847068, cache_file_size=98847068, cache_file_mtime=1757399885.277042, t_start_dt=Timestamp('2025-09-09 01:38:03'), t_end_dt=Timestamp('2025-09-09 02:38:03.265364583'), label='Debut_2025-09-09T013803.mp4')

Pandas(Index=11, t_start=Timestamp('2025-09-09 02:38:05'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T023805.mp4', video_num_frames=54000, video_fps=14.999144471541102, video_width=640, video_height=480, video_file_size=98756667, cache_file_size=98756667, cache_file_mtime=1757403487.2817159, t_start_dt=Timestamp('2025-09-09 02:38:05'), t_end_dt=Timestamp('2025-09-09 03:38:05.205338542'), label='Debut_2025-09-09T023805.mp4')

Pandas(Index=12, t_start=Timestamp('2025-09-09 03:38:07'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T033807.mp4', video_num_frames=53998, video_fps=14.998588947671786, video_width=640, video_height=480, video_file_size=98605039, cache_file_size=98605039, cache_file_mtime=1757407089.2836647, t_start_dt=Timestamp('2025-09-09 03:38:07'), t_end_dt=Timestamp('2025-09-09 04:38:07.205338542'), label='Debut_2025-09-09T033807.mp4')

Pandas(Index=13, t_start=Timestamp('2025-09-09 04:38:09'), t_duration=3600.207356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T043809.mp4', video_num_frames=53999, video_fps=14.998858301437897, video_width=640, video_height=480, video_file_size=98832233, cache_file_size=98832233, cache_file_mtime=1757410691.4421842, t_start_dt=Timestamp('2025-09-09 04:38:09'), t_end_dt=Timestamp('2025-09-09 05:38:09.207356771'), label='Debut_2025-09-09T043809.mp4')

Pandas(Index=14, t_start=Timestamp('2025-09-09 05:38:11'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T053811.mp4', video_num_frames=55414, video_fps=15.391780162396882, video_width=640, video_height=480, video_file_size=98354766, cache_file_size=98354766, cache_file_mtime=1757414293.5980122, t_start_dt=Timestamp('2025-09-09 05:38:11'), t_end_dt=Timestamp('2025-09-09 06:38:11.233333333'), label='Debut_2025-09-09T053811.mp4')

Pandas(Index=15, t_start=Timestamp('2025-09-09 06:38:14'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T063814.mp4', video_num_frames=54588, video_fps=15.162342088638411, video_width=640, video_height=480, video_file_size=98114264, cache_file_size=98114264, cache_file_mtime=1757417895.6859982, t_start_dt=Timestamp('2025-09-09 06:38:14'), t_end_dt=Timestamp('2025-09-09 07:38:14.235351562'), label='Debut_2025-09-09T063814.mp4')

Pandas(Index=16, t_start=Timestamp('2025-09-09 07:38:16'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T073816.mp4', video_num_frames=54000, video_fps=14.999144471541102, video_width=640, video_height=480, video_file_size=97966684, cache_file_size=97966684, cache_file_mtime=1757421497.82023, t_start_dt=Timestamp('2025-09-09 07:38:16'), t_end_dt=Timestamp('2025-09-09 08:38:16.205338542'), label='Debut_2025-09-09T073816.mp4')

Pandas(Index=17, t_start=Timestamp('2025-09-09 08:38:18'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T083818.mp4', video_num_frames=53998, video_fps=14.998338881125589, video_width=640, video_height=480, video_file_size=98205510, cache_file_size=98205510, cache_file_mtime=1757425099.9720714, t_start_dt=Timestamp('2025-09-09 08:38:18'), t_end_dt=Timestamp('2025-09-09 09:38:18.265364583'), label='Debut_2025-09-09T083818.mp4')

Pandas(Index=18, t_start=Timestamp('2025-09-09 09:38:20'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T093820.mp4', video_num_frames=53999, video_fps=14.99874167297548, video_width=640, video_height=480, video_file_size=98212489, cache_file_size=98212489, cache_file_mtime=1757428702.0069342, t_start_dt=Timestamp('2025-09-09 09:38:20'), t_end_dt=Timestamp('2025-09-09 10:38:20.235351562'), label='Debut_2025-09-09T093820.mp4')

Pandas(Index=19, t_start=Timestamp('2025-09-09 10:38:22'), t_duration=2107.8572916666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T103822.mp4', video_num_frames=36979, video_fps=17.543407775372206, video_width=640, video_height=480, video_file_size=58572853, cache_file_size=58572853, cache_file_mtime=1757430811.4152331, t_start_dt=Timestamp('2025-09-09 10:38:22'), t_end_dt=Timestamp('2025-09-09 11:13:29.857291667'), label='Debut_2025-09-09T103822.mp4')

Pandas(Index=20, t_start=Timestamp('2025-09-09 16:51:30'), t_duration=3600.357356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T165130.mp4', video_num_frames=107751, video_fps=29.92786252102543, video_width=640, video_height=480, video_file_size=104049562, cache_file_size=104049562, cache_file_mtime=1757454692.2385507, t_start_dt=Timestamp('2025-09-09 16:51:30'), t_end_dt=Timestamp('2025-09-09 17:51:30.357356771'), label='Debut_2025-09-09T165130.mp4')

Pandas(Index=21, t_start=Timestamp('2025-09-09 17:51:32'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T175132.mp4', video_num_frames=107993, video_fps=29.995827675342472, video_width=640, video_height=480, video_file_size=104554918, cache_file_size=104554918, cache_file_mtime=1757458294.6329672, t_start_dt=Timestamp('2025-09-09 17:51:32'), t_end_dt=Timestamp('2025-09-09 18:51:32.267382813'), label='Debut_2025-09-09T175132.mp4')

Pandas(Index=22, t_start=Timestamp('2025-09-09 18:51:35'), t_duration=2184.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T185135.mp4', video_num_frames=65511, video_fps=29.99261934898974, video_width=640, video_height=480, video_file_size=63734078, cache_file_size=63734078, cache_file_mtime=1757460480.7985399, t_start_dt=Timestamp('2025-09-09 18:51:35'), t_end_dt=Timestamp('2025-09-09 19:27:59.237369792'), label='Debut_2025-09-09T185135.mp4')

Pandas(Index=23, t_start=Timestamp('2025-09-09 21:32:32'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T213232.mp4', video_num_frames=53999, video_fps=14.998616638429214, video_width=640, video_height=480, video_file_size=98194414, cache_file_size=98194414, cache_file_mtime=1757471554.2325423, t_start_dt=Timestamp('2025-09-09 21:32:32'), t_end_dt=Timestamp('2025-09-09 22:32:32.265364583'), label='Debut_2025-09-09T213232.mp4')

Pandas(Index=24, t_start=Timestamp('2025-09-09 22:32:34'), t_duration=284.6822916666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-09T223234.mp4', video_num_frames=4267, video_fps=14.988638650542454, video_width=640, video_height=480, video_file_size=7768825, cache_file_size=7768825, cache_file_mtime=1757471840.420118, t_start_dt=Timestamp('2025-09-09 22:32:34'), t_end_dt=Timestamp('2025-09-09 22:37:18.682291667'), label='Debut_2025-09-09T223234.mp4')

Pandas(Index=25, t_start=Timestamp('2025-09-10 05:59:04'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T055904.mp4', video_num_frames=53999, video_fps=14.998483469437122, video_width=640, video_height=480, video_file_size=99769084, cache_file_size=99769084, cache_file_mtime=1757501946.1919842, t_start_dt=Timestamp('2025-09-10 05:59:04'), t_end_dt=Timestamp('2025-09-10 06:59:04.297330729'), label='Debut_2025-09-10T055904.mp4')

Pandas(Index=26, t_start=Timestamp('2025-09-10 06:59:06'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T065906.mp4', video_num_frames=54000, video_fps=14.999144471541102, video_width=640, video_height=480, video_file_size=98020254, cache_file_size=98020254, cache_file_mtime=1757505548.42269, t_start_dt=Timestamp('2025-09-10 06:59:06'), t_end_dt=Timestamp('2025-09-10 07:59:06.205338542'), label='Debut_2025-09-10T065906.mp4')

Pandas(Index=27, t_start=Timestamp('2025-09-10 07:59:08'), t_duration=3600.2033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T075908.mp4', video_num_frames=54000, video_fps=14.999152879874785, video_width=640, video_height=480, video_file_size=97672618, cache_file_size=97672618, cache_file_mtime=1757509150.5841215, t_start_dt=Timestamp('2025-09-10 07:59:08'), t_end_dt=Timestamp('2025-09-10 08:59:08.203320313'), label='Debut_2025-09-10T075908.mp4')

Pandas(Index=28, t_start=Timestamp('2025-09-10 08:59:11'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T085911.mp4', video_num_frames=53674, video_fps=14.908345514751192, video_width=640, video_height=480, video_file_size=97701420, cache_file_size=97701420, cache_file_mtime=1757512752.9245937, t_start_dt=Timestamp('2025-09-10 08:59:11'), t_end_dt=Timestamp('2025-09-10 09:59:11.265364583'), label='Debut_2025-09-10T085911.mp4')

Pandas(Index=29, t_start=Timestamp('2025-09-10 09:59:13'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T095913.mp4', video_num_frames=60905, video_fps=16.91694990854728, video_width=640, video_height=480, video_file_size=99406708, cache_file_size=99406708, cache_file_mtime=1757516355.1544526, t_start_dt=Timestamp('2025-09-10 09:59:13'), t_end_dt=Timestamp('2025-09-10 10:59:13.235286458'), label='Debut_2025-09-10T095913.mp4')

Pandas(Index=30, t_start=Timestamp('2025-09-10 10:59:15'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T105915.mp4', video_num_frames=107995, video_fps=29.996383189638312, video_width=640, video_height=480, video_file_size=106225148, cache_file_size=106225148, cache_file_mtime=1757519957.7883675, t_start_dt=Timestamp('2025-09-10 10:59:15'), t_end_dt=Timestamp('2025-09-10 11:59:15.267382813'), label='Debut_2025-09-10T105915.mp4')

Pandas(Index=31, t_start=Timestamp('2025-09-10 11:59:18'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T115918.mp4', video_num_frames=107979, video_fps=29.991456392730136, video_width=640, video_height=480, video_file_size=103939591, cache_file_size=103939591, cache_file_mtime=1757523560.9332738, t_start_dt=Timestamp('2025-09-10 11:59:18'), t_end_dt=Timestamp('2025-09-10 12:59:18.325325521'), label='Debut_2025-09-10T115918.mp4')

Pandas(Index=32, t_start=Timestamp('2025-09-10 12:59:22'), t_duration=3600.3533203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T125922.mp4', video_num_frames=107406, video_fps=29.832072145263087, video_width=640, video_height=480, video_file_size=104513904, cache_file_size=104513904, cache_file_mtime=1757527164.8937004, t_start_dt=Timestamp('2025-09-10 12:59:22'), t_end_dt=Timestamp('2025-09-10 13:59:22.353320312'), label='Debut_2025-09-10T125922.mp4')

Pandas(Index=33, t_start=Timestamp('2025-09-10 13:59:25'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T135925.mp4', video_num_frames=107943, video_fps=29.982207109076747, video_width=640, video_height=480, video_file_size=104953314, cache_file_size=104953314, cache_file_mtime=1757530767.824314, t_start_dt=Timestamp('2025-09-10 13:59:25'), t_end_dt=Timestamp('2025-09-10 14:59:25.235286458'), label='Debut_2025-09-10T135925.mp4')

Pandas(Index=34, t_start=Timestamp('2025-09-10 14:59:28'), t_duration=3600.5973307291665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T145928.mp4', video_num_frames=107969, video_fps=29.986413387173986, video_width=640, video_height=480, video_file_size=104767842, cache_file_size=104767842, cache_file_mtime=1757534370.7609947, t_start_dt=Timestamp('2025-09-10 14:59:28'), t_end_dt=Timestamp('2025-09-10 15:59:28.597330729'), label='Debut_2025-09-10T145928.mp4')

Pandas(Index=35, t_start=Timestamp('2025-09-10 15:59:31'), t_duration=3600.293359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T155931.mp4', video_num_frames=107968, video_fps=29.988667373133982, video_width=640, video_height=480, video_file_size=105505601, cache_file_size=105505601, cache_file_mtime=1757537973.9718652, t_start_dt=Timestamp('2025-09-10 15:59:31'), t_end_dt=Timestamp('2025-09-10 16:59:31.293359375'), label='Debut_2025-09-10T155931.mp4')

Pandas(Index=36, t_start=Timestamp('2025-09-10 16:59:35'), t_duration=3600.361328125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T165935.mp4', video_num_frames=107982, video_fps=29.991989736273215, video_width=640, video_height=480, video_file_size=105075745, cache_file_size=105075745, cache_file_mtime=1757541577.3460572, t_start_dt=Timestamp('2025-09-10 16:59:35'), t_end_dt=Timestamp('2025-09-10 17:59:35.361328125'), label='Debut_2025-09-10T165935.mp4')

Pandas(Index=37, t_start=Timestamp('2025-09-10 17:59:38'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T175938.mp4', video_num_frames=107955, video_fps=29.98504028966374, video_width=640, video_height=480, video_file_size=107025243, cache_file_size=107025243, cache_file_mtime=1757545180.453011, t_start_dt=Timestamp('2025-09-10 17:59:38'), t_end_dt=Timestamp('2025-09-10 18:59:38.295312500'), label='Debut_2025-09-10T175938.mp4')

Pandas(Index=38, t_start=Timestamp('2025-09-10 18:59:41'), t_duration=378.38535156250003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-10T185941.mp4', video_num_frames=11329, video_fps=29.94037679634838, video_width=640, video_height=480, video_file_size=11665867, cache_file_size=11665867, cache_file_mtime=1757545560.556803, t_start_dt=Timestamp('2025-09-10 18:59:41'), t_end_dt=Timestamp('2025-09-10 19:05:59.385351563'), label='Debut_2025-09-10T185941.mp4')

Pandas(Index=39, t_start=Timestamp('2025-09-11 05:27:09'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T052709.mp4', video_num_frames=107993, video_fps=29.995845032759902, video_width=640, video_height=480, video_file_size=105063700, cache_file_size=105063700, cache_file_mtime=1757586431.4841352, t_start_dt=Timestamp('2025-09-11 05:27:09'), t_end_dt=Timestamp('2025-09-11 06:27:09.265299479'), label='Debut_2025-09-11T052709.mp4')

Pandas(Index=40, t_start=Timestamp('2025-09-11 06:27:11'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T062711.mp4', video_num_frames=107940, video_fps=29.981373830204312, video_width=640, video_height=480, video_file_size=104027740, cache_file_size=104027740, cache_file_mtime=1757590033.8959646, t_start_dt=Timestamp('2025-09-11 06:27:11'), t_end_dt=Timestamp('2025-09-11 07:27:11.235286458'), label='Debut_2025-09-11T062711.mp4')

Pandas(Index=41, t_start=Timestamp('2025-09-11 07:27:14'), t_duration=3600.2693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T072714.mp4', video_num_frames=107961, video_fps=29.986923178870246, video_width=640, video_height=480, video_file_size=104188054, cache_file_size=104188054, cache_file_mtime=1757593636.4368193, t_start_dt=Timestamp('2025-09-11 07:27:14'), t_end_dt=Timestamp('2025-09-11 08:27:14.269335937'), label='Debut_2025-09-11T072714.mp4')

Pandas(Index=42, t_start=Timestamp('2025-09-11 08:27:16'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T082716.mp4', video_num_frames=107975, video_fps=29.991095417049383, video_width=640, video_height=480, video_file_size=103752857, cache_file_size=103752857, cache_file_mtime=1757597239.074108, t_start_dt=Timestamp('2025-09-11 08:27:16'), t_end_dt=Timestamp('2025-09-11 09:27:16.235286458'), label='Debut_2025-09-11T082716.mp4')

Pandas(Index=43, t_start=Timestamp('2025-09-11 09:27:19'), t_duration=2371.7053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T092719.mp4', video_num_frames=71045, video_fps=29.955238893076288, video_width=640, video_height=480, video_file_size=68651207, cache_file_size=68651207, cache_file_mtime=1757599614.439015, t_start_dt=Timestamp('2025-09-11 09:27:19'), t_end_dt=Timestamp('2025-09-11 10:06:50.705338542'), label='Debut_2025-09-11T092719.mp4')

Pandas(Index=44, t_start=Timestamp('2025-09-11 10:40:24'), t_duration=1.1953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T104024.mp4', video_num_frames=21, video_fps=17.568627450980394, video_width=640, video_height=480, video_file_size=35361, cache_file_size=35361, cache_file_mtime=1757601626.2687218, t_start_dt=Timestamp('2025-09-11 10:40:24'), t_end_dt=Timestamp('2025-09-11 10:40:25.195312500'), label='Debut_2025-09-11T104024.mp4')

Pandas(Index=45, t_start=Timestamp('2025-09-11 11:23:22'), t_duration=228.20930989583334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T112322.mp4', video_num_frames=6832, video_fps=29.937428946779086, video_width=640, video_height=480, video_file_size=7081662, cache_file_size=7081662, cache_file_mtime=1757604431.5172777, t_start_dt=Timestamp('2025-09-11 11:23:22'), t_end_dt=Timestamp('2025-09-11 11:27:10.209309896'), label='Debut_2025-09-11T112322.mp4')

Pandas(Index=46, t_start=Timestamp('2025-09-11 11:29:19'), t_duration=3600.3293619791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T112919.mp4', video_num_frames=107934, video_fps=29.978923911746428, video_width=640, video_height=480, video_file_size=104239650, cache_file_size=104239650, cache_file_mtime=1757608161.7597263, t_start_dt=Timestamp('2025-09-11 11:29:19'), t_end_dt=Timestamp('2025-09-11 12:29:19.329361979'), label='Debut_2025-09-11T112919.mp4')

Pandas(Index=47, t_start=Timestamp('2025-09-11 12:29:22'), t_duration=443.6053385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T122922.mp4', video_num_frames=13291, video_fps=29.961316614659296, video_width=640, video_height=480, video_file_size=13065299, cache_file_size=13065299, cache_file_mtime=1757608606.7654438, t_start_dt=Timestamp('2025-09-11 12:29:22'), t_end_dt=Timestamp('2025-09-11 12:36:45.605338542'), label='Debut_2025-09-11T122922.mp4')

Pandas(Index=48, t_start=Timestamp('2025-09-11 12:40:31'), t_duration=3600.3273437499997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T124031.mp4', video_num_frames=107873, video_fps=29.96199781313288, video_width=640, video_height=480, video_file_size=106378582, cache_file_size=106378582, cache_file_mtime=1757612433.9781709, t_start_dt=Timestamp('2025-09-11 12:40:31'), t_end_dt=Timestamp('2025-09-11 13:40:31.327343750'), label='Debut_2025-09-11T124031.mp4')

Pandas(Index=49, t_start=Timestamp('2025-09-11 13:40:34'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T134034.mp4', video_num_frames=107990, video_fps=29.994511672185585, video_width=640, video_height=480, video_file_size=104419240, cache_file_size=104419240, cache_file_mtime=1757616037.8039546, t_start_dt=Timestamp('2025-09-11 13:40:34'), t_end_dt=Timestamp('2025-09-11 14:40:34.325325521'), label='Debut_2025-09-11T134034.mp4')

Pandas(Index=50, t_start=Timestamp('2025-09-11 14:40:38'), t_duration=3600.3313151041666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T144038.mp4', video_num_frames=107947, video_fps=29.98251842744001, video_width=640, video_height=480, video_file_size=104518706, cache_file_size=104518706, cache_file_mtime=1757619641.4311264, t_start_dt=Timestamp('2025-09-11 14:40:38'), t_end_dt=Timestamp('2025-09-11 15:40:38.331315104'), label='Debut_2025-09-11T144038.mp4')

Pandas(Index=51, t_start=Timestamp('2025-09-11 15:40:42'), t_duration=448.5873046875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T154042.mp4', video_num_frames=13442, video_fps=29.965181492071245, video_width=640, video_height=480, video_file_size=13104820, cache_file_size=13104820, cache_file_mtime=1757620091.7405586, t_start_dt=Timestamp('2025-09-11 15:40:42'), t_end_dt=Timestamp('2025-09-11 15:48:10.587304688'), label='Debut_2025-09-11T154042.mp4')

Pandas(Index=52, t_start=Timestamp('2025-09-11 15:57:35'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T155735.mp4', video_num_frames=104912, video_fps=29.14007476481723, video_width=640, video_height=480, video_file_size=104936436, cache_file_size=104936436, cache_file_mtime=1757624258.0342405, t_start_dt=Timestamp('2025-09-11 15:57:35'), t_end_dt=Timestamp('2025-09-11 16:57:35.265299479'), label='Debut_2025-09-11T155735.mp4')

Pandas(Index=53, t_start=Timestamp('2025-09-11 16:57:38'), t_duration=3600.3293619791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T165738.mp4', video_num_frames=107820, video_fps=29.947260141980284, video_width=640, video_height=480, video_file_size=104897622, cache_file_size=104897622, cache_file_mtime=1757627861.847859, t_start_dt=Timestamp('2025-09-11 16:57:38'), t_end_dt=Timestamp('2025-09-11 17:57:38.329361979'), label='Debut_2025-09-11T165738.mp4')

Pandas(Index=54, t_start=Timestamp('2025-09-11 17:57:42'), t_duration=3600.299348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T175742.mp4', video_num_frames=107682, video_fps=29.909179643952495, video_width=640, video_height=480, video_file_size=104699441, cache_file_size=104699441, cache_file_mtime=1757631464.8982153, t_start_dt=Timestamp('2025-09-11 17:57:42'), t_end_dt=Timestamp('2025-09-11 18:57:42.299348958'), label='Debut_2025-09-11T175742.mp4')

Pandas(Index=55, t_start=Timestamp('2025-09-11 18:57:45'), t_duration=3600.297395833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T185745.mp4', video_num_frames=107968, video_fps=29.988633751465265, video_width=640, video_height=480, video_file_size=105058102, cache_file_size=105058102, cache_file_mtime=1757635067.7240138, t_start_dt=Timestamp('2025-09-11 18:57:45'), t_end_dt=Timestamp('2025-09-11 19:57:45.297395833'), label='Debut_2025-09-11T185745.mp4')

Pandas(Index=56, t_start=Timestamp('2025-09-11 19:57:48'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T195748.mp4', video_num_frames=107948, video_fps=29.98309600471142, video_width=640, video_height=480, video_file_size=101921733, cache_file_size=101921733, cache_file_mtime=1757638670.4695785, t_start_dt=Timestamp('2025-09-11 19:57:48'), t_end_dt=Timestamp('2025-09-11 20:57:48.295312500'), label='Debut_2025-09-11T195748.mp4')

Pandas(Index=57, t_start=Timestamp('2025-09-11 20:57:51'), t_duration=2754.505338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-11T205751.mp4', video_num_frames=70868, video_fps=25.728031457553843, video_width=640, video_height=480, video_file_size=75922224, cache_file_size=75922224, cache_file_mtime=1757641887.4183476, t_start_dt=Timestamp('2025-09-11 20:57:51'), t_end_dt=Timestamp('2025-09-11 21:43:45.505338541'), label='Debut_2025-09-11T205751.mp4')

Pandas(Index=58, t_start=Timestamp('2025-09-12 17:52:09'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-12T175209.mp4', video_num_frames=107935, video_fps=29.97973510885835, video_width=640, video_height=480, video_file_size=106326118, cache_file_size=106326118, cache_file_mtime=1757717531.600526, t_start_dt=Timestamp('2025-09-12 17:52:09'), t_end_dt=Timestamp('2025-09-12 18:52:09.265299479'), label='Debut_2025-09-12T175209.mp4')

Pandas(Index=59, t_start=Timestamp('2025-09-12 18:52:12'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-12T185212.mp4', video_num_frames=107974, video_fps=29.99081765742524, video_width=640, video_height=480, video_file_size=105793861, cache_file_size=105793861, cache_file_mtime=1757721134.3739345, t_start_dt=Timestamp('2025-09-12 18:52:12'), t_end_dt=Timestamp('2025-09-12 19:52:12.235286458'), label='Debut_2025-09-12T185212.mp4')

Pandas(Index=60, t_start=Timestamp('2025-09-12 19:52:14'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-12T195214.mp4', video_num_frames=107996, video_fps=29.996944642476876, video_width=640, video_height=480, video_file_size=105564940, cache_file_size=105564940, cache_file_mtime=1757724737.0066535, t_start_dt=Timestamp('2025-09-12 19:52:14'), t_end_dt=Timestamp('2025-09-12 20:52:14.233333333'), label='Debut_2025-09-12T195214.mp4')

Pandas(Index=61, t_start=Timestamp('2025-09-12 20:52:17'), t_duration=1600.3153645833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-12T205217.mp4', video_num_frames=47323, video_fps=29.571046462033607, video_width=640, video_height=480, video_file_size=46760678, cache_file_size=46760678, cache_file_mtime=1757726340.3955235, t_start_dt=Timestamp('2025-09-12 20:52:17'), t_end_dt=Timestamp('2025-09-12 21:18:57.315364583'), label='Debut_2025-09-12T205217.mp4')

Pandas(Index=62, t_start=Timestamp('2025-09-17 23:07:21'), t_duration=3600.293294270833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-17T230721.mp4', video_num_frames=107272, video_fps=29.795350331791727, video_width=640, video_height=480, video_file_size=108346784, cache_file_size=108346784, cache_file_mtime=1758168443.5593903, t_start_dt=Timestamp('2025-09-17 23:07:21'), t_end_dt=Timestamp('2025-09-18 00:07:21.293294271'), label='Debut_2025-09-17T230721.mp4')

Pandas(Index=63, t_start=Timestamp('2025-09-18 00:07:27'), t_duration=1706.3652994791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T000727.mp4', video_num_frames=51171, video_fps=29.98830321714753, video_width=640, video_height=480, video_file_size=50259829, cache_file_size=50259829, cache_file_mtime=1758170155.0763688, t_start_dt=Timestamp('2025-09-18 00:07:27'), t_end_dt=Timestamp('2025-09-18 00:35:53.365299479'), label='Debut_2025-09-18T000727.mp4')

Pandas(Index=64, t_start=Timestamp('2025-09-18 00:41:13'), t_duration=3609.7563802083337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T004113.mp4', video_num_frames=66761, video_fps=18.494599903206474, video_width=640, video_height=480, video_file_size=101683245, cache_file_size=101683245, cache_file_mtime=1758174075.656127, t_start_dt=Timestamp('2025-09-18 00:41:13'), t_end_dt=Timestamp('2025-09-18 01:41:22.756380208'), label='Debut_2025-09-18T004113.mp4')

Pandas(Index=65, t_start=Timestamp('2025-09-18 01:41:16'), t_duration=3600.207356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T014116.mp4', video_num_frames=53999, video_fps=14.998858301437897, video_width=640, video_height=480, video_file_size=98081685, cache_file_size=98081685, cache_file_mtime=1758177677.9475503, t_start_dt=Timestamp('2025-09-18 01:41:16'), t_end_dt=Timestamp('2025-09-18 02:41:16.207356771'), label='Debut_2025-09-18T014116.mp4')

Pandas(Index=66, t_start=Timestamp('2025-09-18 02:41:18'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T024118.mp4', video_num_frames=54000, video_fps=14.999144471541102, video_width=640, video_height=480, video_file_size=98672784, cache_file_size=98672784, cache_file_mtime=1758181280.4126613, t_start_dt=Timestamp('2025-09-18 02:41:18'), t_end_dt=Timestamp('2025-09-18 03:41:18.205338542'), label='Debut_2025-09-18T024118.mp4')

Pandas(Index=67, t_start=Timestamp('2025-09-18 03:41:21'), t_duration=3600.2673177083334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T034121.mp4', video_num_frames=53998, video_fps=14.998330744610145, video_width=640, video_height=480, video_file_size=97977359, cache_file_size=97977359, cache_file_mtime=1758184882.8558557, t_start_dt=Timestamp('2025-09-18 03:41:21'), t_end_dt=Timestamp('2025-09-18 04:41:21.267317708'), label='Debut_2025-09-18T034121.mp4')

Pandas(Index=68, t_start=Timestamp('2025-09-18 04:41:23'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T044123.mp4', video_num_frames=53999, video_fps=14.998616638429214, video_width=640, video_height=480, video_file_size=98270478, cache_file_size=98270478, cache_file_mtime=1758188485.693636, t_start_dt=Timestamp('2025-09-18 04:41:23'), t_end_dt=Timestamp('2025-09-18 05:41:23.265364583'), label='Debut_2025-09-18T044123.mp4')

Pandas(Index=69, t_start=Timestamp('2025-09-18 05:41:26'), t_duration=3600.237369791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T054126.mp4', video_num_frames=54000, video_fps=14.999011024410535, video_width=640, video_height=480, video_file_size=98220401, cache_file_size=98220401, cache_file_mtime=1758192088.3131077, t_start_dt=Timestamp('2025-09-18 05:41:26'), t_end_dt=Timestamp('2025-09-18 06:41:26.237369792'), label='Debut_2025-09-18T054126.mp4')

Pandas(Index=70, t_start=Timestamp('2025-09-18 06:41:29'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T064129.mp4', video_num_frames=54000, video_fps=14.999144471541102, video_width=640, video_height=480, video_file_size=98405884, cache_file_size=98405884, cache_file_mtime=1758195690.8550148, t_start_dt=Timestamp('2025-09-18 06:41:29'), t_end_dt=Timestamp('2025-09-18 07:41:29.205338542'), label='Debut_2025-09-18T064129.mp4')

Pandas(Index=71, t_start=Timestamp('2025-09-18 07:41:31'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T074131.mp4', video_num_frames=53999, video_fps=14.998625046326817, video_width=640, video_height=480, video_file_size=99239894, cache_file_size=99239894, cache_file_mtime=1758199293.8686972, t_start_dt=Timestamp('2025-09-18 07:41:31'), t_end_dt=Timestamp('2025-09-18 08:41:31.263346354'), label='Debut_2025-09-18T074131.mp4')

Pandas(Index=72, t_start=Timestamp('2025-09-18 08:41:34'), t_duration=3600.47734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T084134.mp4', video_num_frames=53996, video_fps=14.996900367594488, video_width=640, video_height=480, video_file_size=98638468, cache_file_size=98638468, cache_file_mtime=1758202896.8052418, t_start_dt=Timestamp('2025-09-18 08:41:34'), t_end_dt=Timestamp('2025-09-18 09:41:34.477343750'), label='Debut_2025-09-18T084134.mp4')

Pandas(Index=73, t_start=Timestamp('2025-09-18 09:41:37'), t_duration=1117.4373697916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T094137.mp4', video_num_frames=16744, video_fps=14.984284983346965, video_width=640, video_height=480, video_file_size=30831185, cache_file_size=30831185, cache_file_mtime=1758204016.4717667, t_start_dt=Timestamp('2025-09-18 09:41:37'), t_end_dt=Timestamp('2025-09-18 10:00:14.437369792'), label='Debut_2025-09-18T094137.mp4')

Pandas(Index=74, t_start=Timestamp('2025-09-18 11:17:49'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T111749.mp4', video_num_frames=103429, video_fps=28.728176260977726, video_width=640, video_height=480, video_file_size=104005279, cache_file_size=104005279, cache_file_mtime=1758212271.521978, t_start_dt=Timestamp('2025-09-18 11:17:49'), t_end_dt=Timestamp('2025-09-18 12:17:49.263346354'), label='Debut_2025-09-18T111749.mp4')

Pandas(Index=75, t_start=Timestamp('2025-09-18 12:17:52'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T121752.mp4', video_num_frames=106367, video_fps=29.543948798933652, video_width=640, video_height=480, video_file_size=104021159, cache_file_size=104021159, cache_file_mtime=1758215874.2401853, t_start_dt=Timestamp('2025-09-18 12:17:52'), t_end_dt=Timestamp('2025-09-18 13:17:52.297330729'), label='Debut_2025-09-18T121752.mp4')

Pandas(Index=76, t_start=Timestamp('2025-09-18 13:17:54'), t_duration=3600.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T131754.mp4', video_num_frames=102006, video_fps=28.333131825111504, video_width=640, video_height=480, video_file_size=113294472, cache_file_size=113294472, cache_file_mtime=1758219476.8295302, t_start_dt=Timestamp('2025-09-18 13:17:54'), t_end_dt=Timestamp('2025-09-18 14:17:54.237369792'), label='Debut_2025-09-18T131754.mp4')

Pandas(Index=77, t_start=Timestamp('2025-09-18 14:17:57'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T141757.mp4', video_num_frames=100450, video_fps=27.900969381614154, video_width=640, video_height=480, video_file_size=110678158, cache_file_size=110678158, cache_file_mtime=1758223079.385106, t_start_dt=Timestamp('2025-09-18 14:17:57'), t_end_dt=Timestamp('2025-09-18 15:17:57.233333333'), label='Debut_2025-09-18T141757.mp4')

Pandas(Index=78, t_start=Timestamp('2025-09-18 15:17:59'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T151759.mp4', video_num_frames=107975, video_fps=29.991095417049383, video_width=640, video_height=480, video_file_size=107193757, cache_file_size=107193757, cache_file_mtime=1758226681.8512492, t_start_dt=Timestamp('2025-09-18 15:17:59'), t_end_dt=Timestamp('2025-09-18 16:17:59.235286458'), label='Debut_2025-09-18T151759.mp4')

Pandas(Index=79, t_start=Timestamp('2025-09-18 16:18:02'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T161802.mp4', video_num_frames=107980, video_fps=29.99248421517011, video_width=640, video_height=480, video_file_size=107243916, cache_file_size=107243916, cache_file_mtime=1758230284.4626696, t_start_dt=Timestamp('2025-09-18 16:18:02'), t_end_dt=Timestamp('2025-09-18 17:18:02.235286458'), label='Debut_2025-09-18T161802.mp4')

Pandas(Index=80, t_start=Timestamp('2025-09-18 17:18:05'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T171805.mp4', video_num_frames=107864, video_fps=29.960264098769297, video_width=640, video_height=480, video_file_size=106889742, cache_file_size=106889742, cache_file_mtime=1758233887.098493, t_start_dt=Timestamp('2025-09-18 17:18:05'), t_end_dt=Timestamp('2025-09-18 18:18:05.235286458'), label='Debut_2025-09-18T171805.mp4')

Pandas(Index=81, t_start=Timestamp('2025-09-18 18:18:07'), t_duration=3125.965299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-18T181807.mp4', video_num_frames=93760, video_fps=29.993934998453707, video_width=640, video_height=480, video_file_size=92939126, cache_file_size=92939126, cache_file_mtime=1758237015.3930037, t_start_dt=Timestamp('2025-09-18 18:18:07'), t_end_dt=Timestamp('2025-09-18 19:10:12.965299479'), label='Debut_2025-09-18T181807.mp4')

Pandas(Index=82, t_start=Timestamp('2025-09-19 01:11:39'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T011139.mp4', video_num_frames=94578, video_fps=26.269744988453446, video_width=640, video_height=480, video_file_size=103705819, cache_file_size=103705819, cache_file_mtime=1758262302.001808, t_start_dt=Timestamp('2025-09-19 01:11:39'), t_end_dt=Timestamp('2025-09-19 02:11:39.263346354'), label='Debut_2025-09-19T011139.mp4')

Pandas(Index=83, t_start=Timestamp('2025-09-19 02:11:42'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T021142.mp4', video_num_frames=88351, video_fps=24.540135976307447, video_width=640, video_height=480, video_file_size=102385878, cache_file_size=102385878, cache_file_mtime=1758265904.3127737, t_start_dt=Timestamp('2025-09-19 02:11:42'), t_end_dt=Timestamp('2025-09-19 03:11:42.265299479'), label='Debut_2025-09-19T021142.mp4')

Pandas(Index=84, t_start=Timestamp('2025-09-19 03:11:44'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T031144.mp4', video_num_frames=100475, video_fps=27.90789823596237, video_width=640, video_height=480, video_file_size=104261489, cache_file_size=104261489, cache_file_mtime=1758269506.7978494, t_start_dt=Timestamp('2025-09-19 03:11:44'), t_end_dt=Timestamp('2025-09-19 04:11:44.235286458'), label='Debut_2025-09-19T031144.mp4')

Pandas(Index=85, t_start=Timestamp('2025-09-19 04:11:47'), t_duration=3600.2693359375003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T041147.mp4', video_num_frames=93559, video_fps=25.98666690464076, video_width=640, video_height=480, video_file_size=103173480, cache_file_size=103173480, cache_file_mtime=1758273109.397471, t_start_dt=Timestamp('2025-09-19 04:11:47'), t_end_dt=Timestamp('2025-09-19 05:11:47.269335938'), label='Debut_2025-09-19T041147.mp4')

Pandas(Index=86, t_start=Timestamp('2025-09-19 05:11:49'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T051149.mp4', video_num_frames=86557, video_fps=24.041825452525796, video_width=640, video_height=480, video_file_size=101901579, cache_file_size=101901579, cache_file_mtime=1758276711.8683672, t_start_dt=Timestamp('2025-09-19 05:11:49'), t_end_dt=Timestamp('2025-09-19 06:11:49.267382813'), label='Debut_2025-09-19T051149.mp4')

Pandas(Index=87, t_start=Timestamp('2025-09-19 06:11:52'), t_duration=3600.2393229166664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T061152.mp4', video_num_frames=99324, video_fps=27.588165977681317, video_width=640, video_height=480, video_file_size=103995453, cache_file_size=103995453, cache_file_mtime=1758280314.3463142, t_start_dt=Timestamp('2025-09-19 06:11:52'), t_end_dt=Timestamp('2025-09-19 07:11:52.239322917'), label='Debut_2025-09-19T061152.mp4')

Pandas(Index=88, t_start=Timestamp('2025-09-19 07:11:54'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T071154.mp4', video_num_frames=102780, video_fps=28.54787966323465, video_width=640, video_height=480, video_file_size=105104770, cache_file_size=105104770, cache_file_mtime=1758283916.7489865, t_start_dt=Timestamp('2025-09-19 07:11:54'), t_end_dt=Timestamp('2025-09-19 08:11:54.267382812'), label='Debut_2025-09-19T071154.mp4')

Pandas(Index=89, t_start=Timestamp('2025-09-19 08:11:57'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T081157.mp4', video_num_frames=106514, video_fps=29.585534708180166, video_width=640, video_height=480, video_file_size=105351380, cache_file_size=105351380, cache_file_mtime=1758287519.424212, t_start_dt=Timestamp('2025-09-19 08:11:57'), t_end_dt=Timestamp('2025-09-19 09:11:57.205338542'), label='Debut_2025-09-19T081157.mp4')

Pandas(Index=90, t_start=Timestamp('2025-09-19 09:12:00'), t_duration=1372.3473958333334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T091200.mp4', video_num_frames=34629, video_fps=25.233406719857665, video_width=640, video_height=480, video_file_size=39380939, cache_file_size=39380939, cache_file_mtime=1758288893.3689365, t_start_dt=Timestamp('2025-09-19 09:12:00'), t_end_dt=Timestamp('2025-09-19 09:34:52.347395833'), label='Debut_2025-09-19T091200.mp4')

Pandas(Index=91, t_start=Timestamp('2025-09-19 16:50:06'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T165006.mp4', video_num_frames=107780, video_fps=29.936682726018002, video_width=640, video_height=480, video_file_size=106808271, cache_file_size=106808271, cache_file_mtime=1758318608.4942203, t_start_dt=Timestamp('2025-09-19 16:50:06'), t_end_dt=Timestamp('2025-09-19 17:50:06.265299479'), label='Debut_2025-09-19T165006.mp4')

Pandas(Index=92, t_start=Timestamp('2025-09-19 17:50:09'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T175009.mp4', video_num_frames=107720, video_fps=29.920017287499157, video_width=640, video_height=480, video_file_size=107186511, cache_file_size=107186511, cache_file_mtime=1758322211.3951776, t_start_dt=Timestamp('2025-09-19 17:50:09'), t_end_dt=Timestamp('2025-09-19 18:50:09.265299479'), label='Debut_2025-09-19T175009.mp4')

Pandas(Index=93, t_start=Timestamp('2025-09-19 18:50:12'), t_duration=389.9093098958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-19T185012.mp4', video_num_frames=11603, video_fps=29.758201985738204, video_width=640, video_height=480, video_file_size=11669907, cache_file_size=11669907, cache_file_mtime=1758322603.454307, t_start_dt=Timestamp('2025-09-19 18:50:12'), t_end_dt=Timestamp('2025-09-19 18:56:41.909309896'), label='Debut_2025-09-19T185012.mp4')

Pandas(Index=94, t_start=Timestamp('2025-09-20 17:46:16'), t_duration=2.2753255208333334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-20T174616.mp4', video_num_frames=55, video_fps=24.1723654467939, video_width=640, video_height=480, video_file_size=69150, cache_file_size=69150, cache_file_mtime=1758404779.750584, t_start_dt=Timestamp('2025-09-20 17:46:16'), t_end_dt=Timestamp('2025-09-20 17:46:18.275325521'), label='Debut_2025-09-20T174616.mp4')

Pandas(Index=95, t_start=Timestamp('2025-09-20 17:46:22'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-20T174622.mp4', video_num_frames=107984, video_fps=29.99359525366669, video_width=640, video_height=480, video_file_size=140335633, cache_file_size=140335633, cache_file_mtime=1758408384.8097768, t_start_dt=Timestamp('2025-09-20 17:46:22'), t_end_dt=Timestamp('2025-09-20 18:46:22.235286458'), label='Debut_2025-09-20T174622.mp4')

Pandas(Index=96, t_start=Timestamp('2025-09-20 18:46:25'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-20T184625.mp4', video_num_frames=107992, video_fps=29.995567275451254, video_width=640, video_height=480, video_file_size=122168103, cache_file_size=122168103, cache_file_mtime=1758411987.668852, t_start_dt=Timestamp('2025-09-20 18:46:25'), t_end_dt=Timestamp('2025-09-20 19:46:25.265299479'), label='Debut_2025-09-20T184625.mp4')

Pandas(Index=97, t_start=Timestamp('2025-09-20 19:46:28'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-20T194628.mp4', video_num_frames=107993, video_fps=29.995578164686812, video_width=640, video_height=480, video_file_size=111431345, cache_file_size=111431345, cache_file_mtime=1758415590.7275777, t_start_dt=Timestamp('2025-09-20 19:46:28'), t_end_dt=Timestamp('2025-09-20 20:46:28.297330729'), label='Debut_2025-09-20T194628.mp4')

Pandas(Index=98, t_start=Timestamp('2025-09-20 20:46:31'), t_duration=3600.299348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-20T204631.mp4', video_num_frames=107994, video_fps=29.995839104669358, video_width=640, video_height=480, video_file_size=112564140, cache_file_size=112564140, cache_file_mtime=1758419193.6285307, t_start_dt=Timestamp('2025-09-20 20:46:31'), t_end_dt=Timestamp('2025-09-20 21:46:31.299348958'), label='Debut_2025-09-20T204631.mp4')

Pandas(Index=99, t_start=Timestamp('2025-09-20 21:46:34'), t_duration=3600.2033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-20T214634.mp4', video_num_frames=107944, video_fps=29.98275108268896, video_width=640, video_height=480, video_file_size=105285502, cache_file_size=105285502, cache_file_mtime=1758422795.976736, t_start_dt=Timestamp('2025-09-20 21:46:34'), t_end_dt=Timestamp('2025-09-20 22:46:34.203320313'), label='Debut_2025-09-20T214634.mp4')

Pandas(Index=100, t_start=Timestamp('2025-09-20 22:46:36'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-20T224636.mp4', video_num_frames=107944, video_fps=29.98248486870089, video_width=640, video_height=480, video_file_size=108873621, cache_file_size=108873621, cache_file_mtime=1758426398.571095, t_start_dt=Timestamp('2025-09-20 22:46:36'), t_end_dt=Timestamp('2025-09-20 23:46:36.235286458'), label='Debut_2025-09-20T224636.mp4')

Pandas(Index=101, t_start=Timestamp('2025-09-20 23:46:39'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-20T234639.mp4', video_num_frames=107992, video_fps=29.995300409849325, video_width=640, video_height=480, video_file_size=108703584, cache_file_size=108703584, cache_file_mtime=1758430001.2485828, t_start_dt=Timestamp('2025-09-20 23:46:39'), t_end_dt=Timestamp('2025-09-21 00:46:39.297330729'), label='Debut_2025-09-20T234639.mp4')

Pandas(Index=102, t_start=Timestamp('2025-09-21 00:46:41'), t_duration=3600.2712890625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T004641.mp4', video_num_frames=107989, video_fps=29.99468410285271, video_width=640, video_height=480, video_file_size=107753471, cache_file_size=107753471, cache_file_mtime=1758433604.0876133, t_start_dt=Timestamp('2025-09-21 00:46:41'), t_end_dt=Timestamp('2025-09-21 01:46:41.271289062'), label='Debut_2025-09-21T004641.mp4')

Pandas(Index=103, t_start=Timestamp('2025-09-21 01:46:44'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T014644.mp4', video_num_frames=107924, video_fps=29.97616319175839, video_width=640, video_height=480, video_file_size=106538037, cache_file_size=106538037, cache_file_mtime=1758437207.1488495, t_start_dt=Timestamp('2025-09-21 01:46:44'), t_end_dt=Timestamp('2025-09-21 02:46:44.327343750'), label='Debut_2025-09-21T014644.mp4')

Pandas(Index=104, t_start=Timestamp('2025-09-21 02:46:48'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T024648.mp4', video_num_frames=107992, video_fps=29.995549918194552, video_width=640, video_height=480, video_file_size=108774838, cache_file_size=108774838, cache_file_mtime=1758440810.1173937, t_start_dt=Timestamp('2025-09-21 02:46:48'), t_end_dt=Timestamp('2025-09-21 03:46:48.267382813'), label='Debut_2025-09-21T024648.mp4')

Pandas(Index=105, t_start=Timestamp('2025-09-21 03:46:50'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T034650.mp4', video_num_frames=107994, video_fps=29.996105432490392, video_width=640, video_height=480, video_file_size=108839275, cache_file_size=108839275, cache_file_mtime=1758444412.7059956, t_start_dt=Timestamp('2025-09-21 03:46:50'), t_end_dt=Timestamp('2025-09-21 04:46:50.267382813'), label='Debut_2025-09-21T034650.mp4')

Pandas(Index=106, t_start=Timestamp('2025-09-21 04:46:53'), t_duration=3600.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T044653.mp4', video_num_frames=107987, video_fps=29.994411175796678, video_width=640, video_height=480, video_file_size=109876555, cache_file_size=109876555, cache_file_mtime=1758448015.351083, t_start_dt=Timestamp('2025-09-21 04:46:53'), t_end_dt=Timestamp('2025-09-21 05:46:53.237369792'), label='Debut_2025-09-21T044653.mp4')

Pandas(Index=107, t_start=Timestamp('2025-09-21 05:46:55'), t_duration=3600.2033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T054655.mp4', video_num_frames=73663, video_fps=20.460788862781783, video_width=640, video_height=480, video_file_size=104810941, cache_file_size=104810941, cache_file_mtime=1758451618.1636038, t_start_dt=Timestamp('2025-09-21 05:46:55'), t_end_dt=Timestamp('2025-09-21 06:46:55.203320313'), label='Debut_2025-09-21T054655.mp4')

Pandas(Index=108, t_start=Timestamp('2025-09-21 06:46:59'), t_duration=3600.2673177083334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T064659.mp4', video_num_frames=53999, video_fps=14.998608501763089, video_width=640, video_height=480, video_file_size=99601292, cache_file_size=99601292, cache_file_mtime=1758455220.9067388, t_start_dt=Timestamp('2025-09-21 06:46:59'), t_end_dt=Timestamp('2025-09-21 07:46:59.267317708'), label='Debut_2025-09-21T064659.mp4')

Pandas(Index=109, t_start=Timestamp('2025-09-21 07:47:01'), t_duration=3600.2093098958335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T074701.mp4', video_num_frames=53999, video_fps=14.998850164509568, video_width=640, video_height=480, video_file_size=99951429, cache_file_size=99951429, cache_file_mtime=1758458823.078972, t_start_dt=Timestamp('2025-09-21 07:47:01'), t_end_dt=Timestamp('2025-09-21 08:47:01.209309896'), label='Debut_2025-09-21T074701.mp4')

Pandas(Index=110, t_start=Timestamp('2025-09-21 08:47:03'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T084703.mp4', video_num_frames=53999, video_fps=14.998625046326817, video_width=640, video_height=480, video_file_size=99859134, cache_file_size=99859134, cache_file_mtime=1758462425.655579, t_start_dt=Timestamp('2025-09-21 08:47:03'), t_end_dt=Timestamp('2025-09-21 09:47:03.263346354'), label='Debut_2025-09-21T084703.mp4')

Pandas(Index=111, t_start=Timestamp('2025-09-21 09:47:06'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T094706.mp4', video_num_frames=56684, video_fps=15.744394998661484, video_width=640, video_height=480, video_file_size=100541613, cache_file_size=100541613, cache_file_mtime=1758466028.3414168, t_start_dt=Timestamp('2025-09-21 09:47:06'), t_end_dt=Timestamp('2025-09-21 10:47:06.265364583'), label='Debut_2025-09-21T094706.mp4')

Pandas(Index=112, t_start=Timestamp('2025-09-21 10:47:08'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T104708.mp4', video_num_frames=53999, video_fps=14.998616638429214, video_width=640, video_height=480, video_file_size=99660081, cache_file_size=99660081, cache_file_mtime=1758469630.6896148, t_start_dt=Timestamp('2025-09-21 10:47:08'), t_end_dt=Timestamp('2025-09-21 11:47:08.265364583'), label='Debut_2025-09-21T104708.mp4')

Pandas(Index=113, t_start=Timestamp('2025-09-21 11:47:11'), t_duration=1947.8953124999998, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-21T114711.mp4', video_num_frames=29225, video_fps=15.003373031629492, video_width=640, video_height=480, video_file_size=54213479, cache_file_size=54213479, cache_file_mtime=1758471580.250718, t_start_dt=Timestamp('2025-09-21 11:47:11'), t_end_dt=Timestamp('2025-09-21 12:19:38.895312500'), label='Debut_2025-09-21T114711.mp4')

Pandas(Index=114, t_start=Timestamp('2025-09-22 07:45:30'), t_duration=1.5833333333333335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T074530.mp4', video_num_frames=25, video_fps=15.789473684210526, video_width=640, video_height=480, video_file_size=44429, cache_file_size=44429, cache_file_mtime=1758541532.8253496, t_start_dt=Timestamp('2025-09-22 07:45:30'), t_end_dt=Timestamp('2025-09-22 07:45:31.583333333'), label='Debut_2025-09-22T074530.mp4')

Pandas(Index=115, t_start=Timestamp('2025-09-22 07:45:39'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T074539.mp4', video_num_frames=92138, video_fps=25.592215786674103, video_width=640, video_height=480, video_file_size=103209263, cache_file_size=103209263, cache_file_mtime=1758545141.6627958, t_start_dt=Timestamp('2025-09-22 07:45:39'), t_end_dt=Timestamp('2025-09-22 08:45:39.235351562'), label='Debut_2025-09-22T074539.mp4')

Pandas(Index=116, t_start=Timestamp('2025-09-22 08:45:42'), t_duration=1541.0633463541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T084542.mp4', video_num_frames=46221, video_fps=29.992926708268815, video_width=640, video_height=480, video_file_size=45303221, cache_file_size=45303221, cache_file_mtime=1758546684.1515927, t_start_dt=Timestamp('2025-09-22 08:45:42'), t_end_dt=Timestamp('2025-09-22 09:11:23.063346353'), label='Debut_2025-09-22T084542.mp4')

Pandas(Index=117, t_start=Timestamp('2025-09-22 14:21:58'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T142158.mp4', video_num_frames=107990, video_fps=29.99474490017435, video_width=640, video_height=480, video_file_size=109734372, cache_file_size=109734372, cache_file_mtime=1758568920.7553132, t_start_dt=Timestamp('2025-09-22 14:21:58'), t_end_dt=Timestamp('2025-09-22 15:21:58.297330729'), label='Debut_2025-09-22T142158.mp4')

Pandas(Index=118, t_start=Timestamp('2025-09-22 15:22:01'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T152201.mp4', video_num_frames=107995, video_fps=29.996416820275645, video_width=640, video_height=480, video_file_size=107553780, cache_file_size=107553780, cache_file_mtime=1758572523.3197963, t_start_dt=Timestamp('2025-09-22 15:22:01'), t_end_dt=Timestamp('2025-09-22 16:22:01.263346354'), label='Debut_2025-09-22T152201.mp4')

Pandas(Index=119, t_start=Timestamp('2025-09-22 16:22:03'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T162203.mp4', video_num_frames=107987, video_fps=29.993911635661892, video_width=640, video_height=480, video_file_size=107741549, cache_file_size=107741549, cache_file_mtime=1758576126.2557867, t_start_dt=Timestamp('2025-09-22 16:22:03'), t_end_dt=Timestamp('2025-09-22 17:22:03.297330729'), label='Debut_2025-09-22T162203.mp4')

Pandas(Index=120, t_start=Timestamp('2025-09-22 17:22:07'), t_duration=267.68528645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T172207.mp4', video_num_frames=8019, video_fps=29.956820212635037, video_width=640, video_height=480, video_file_size=8507854, cache_file_size=8507854, cache_file_mtime=1758576395.3488646, t_start_dt=Timestamp('2025-09-22 17:22:07'), t_end_dt=Timestamp('2025-09-22 17:26:34.685286458'), label='Debut_2025-09-22T172207.mp4')

Pandas(Index=121, t_start=Timestamp('2025-09-22 17:29:14'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T172914.mp4', video_num_frames=107424, video_fps=29.838049864145525, video_width=640, video_height=480, video_file_size=116232097, cache_file_size=116232097, cache_file_mtime=1758580156.905898, t_start_dt=Timestamp('2025-09-22 17:29:14'), t_end_dt=Timestamp('2025-09-22 18:29:14.235286458'), label='Debut_2025-09-22T172914.mp4')

Pandas(Index=122, t_start=Timestamp('2025-09-22 18:29:17'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T182917.mp4', video_num_frames=107986, video_fps=29.994150772914978, video_width=640, video_height=480, video_file_size=108351141, cache_file_size=108351141, cache_file_mtime=1758583759.554115, t_start_dt=Timestamp('2025-09-22 18:29:17'), t_end_dt=Timestamp('2025-09-22 19:29:17.235286458'), label='Debut_2025-09-22T182917.mp4')

Pandas(Index=123, t_start=Timestamp('2025-09-22 19:29:20'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T192920.mp4', video_num_frames=107113, video_fps=29.751682761302508, video_width=640, video_height=480, video_file_size=102626291, cache_file_size=102626291, cache_file_mtime=1758587361.9848866, t_start_dt=Timestamp('2025-09-22 19:29:20'), t_end_dt=Timestamp('2025-09-22 20:29:20.233333333'), label='Debut_2025-09-22T192920.mp4')

Pandas(Index=124, t_start=Timestamp('2025-09-22 20:29:22'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T202922.mp4', video_num_frames=86397, video_fps=23.997797868661788, video_width=640, video_height=480, video_file_size=97886062, cache_file_size=97886062, cache_file_mtime=1758590964.2501605, t_start_dt=Timestamp('2025-09-22 20:29:22'), t_end_dt=Timestamp('2025-09-22 21:29:22.205338542'), label='Debut_2025-09-22T202922.mp4')

Pandas(Index=125, t_start=Timestamp('2025-09-22 21:29:24'), t_duration=3600.2073567708335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T212924.mp4', video_num_frames=86397, video_fps=23.997784415810106, video_width=640, video_height=480, video_file_size=97948056, cache_file_size=97948056, cache_file_mtime=1758594566.5202458, t_start_dt=Timestamp('2025-09-22 21:29:24'), t_end_dt=Timestamp('2025-09-22 22:29:24.207356771'), label='Debut_2025-09-22T212924.mp4')

Pandas(Index=126, t_start=Timestamp('2025-09-22 22:29:26'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T222926.mp4', video_num_frames=86397, video_fps=23.997797868661788, video_width=640, video_height=480, video_file_size=97965682, cache_file_size=97965682, cache_file_mtime=1758598168.7535052, t_start_dt=Timestamp('2025-09-22 22:29:26'), t_end_dt=Timestamp('2025-09-22 23:29:26.205338542'), label='Debut_2025-09-22T222926.mp4')

Pandas(Index=127, t_start=Timestamp('2025-09-22 23:29:29'), t_duration=274.34733072916663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-22T232929.mp4', video_num_frames=6377, video_fps=23.244257500341128, video_width=640, video_height=480, video_file_size=7516867, cache_file_size=7516867, cache_file_mtime=1758598444.4449246, t_start_dt=Timestamp('2025-09-22 23:29:29'), t_end_dt=Timestamp('2025-09-22 23:34:03.347330729'), label='Debut_2025-09-22T232929.mp4')

Pandas(Index=128, t_start=Timestamp('2025-09-23 10:00:45'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-23T100045.mp4', video_num_frames=100309, video_fps=27.861572987870083, video_width=640, video_height=480, video_file_size=103731500, cache_file_size=103731500, cache_file_mtime=1758639647.3296669, t_start_dt=Timestamp('2025-09-23 10:00:45'), t_end_dt=Timestamp('2025-09-23 11:00:45.263346354'), label='Debut_2025-09-23T100045.mp4')

Pandas(Index=129, t_start=Timestamp('2025-09-23 11:00:47'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-23T110047.mp4', video_num_frames=104867, video_fps=29.127575685928093, video_width=640, video_height=480, video_file_size=103548830, cache_file_size=103548830, cache_file_mtime=1758643249.8383448, t_start_dt=Timestamp('2025-09-23 11:00:47'), t_end_dt=Timestamp('2025-09-23 12:00:47.265299479'), label='Debut_2025-09-23T110047.mp4')

Pandas(Index=130, t_start=Timestamp('2025-09-23 12:00:50'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-23T120050.mp4', video_num_frames=102417, video_fps=28.447307426051836, video_width=640, video_height=480, video_file_size=106056225, cache_file_size=106056225, cache_file_mtime=1758646852.403195, t_start_dt=Timestamp('2025-09-23 12:00:50'), t_end_dt=Timestamp('2025-09-23 13:00:50.235286458'), label='Debut_2025-09-23T120050.mp4')

Pandas(Index=131, t_start=Timestamp('2025-09-23 13:00:52'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-23T130052.mp4', video_num_frames=107993, video_fps=29.995328115781138, video_width=640, video_height=480, video_file_size=105706636, cache_file_size=105706636, cache_file_mtime=1758650455.0242739, t_start_dt=Timestamp('2025-09-23 13:00:52'), t_end_dt=Timestamp('2025-09-23 14:00:52.327343750'), label='Debut_2025-09-23T130052.mp4')

Pandas(Index=132, t_start=Timestamp('2025-09-23 14:00:55'), t_duration=3600.237369791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-23T140055.mp4', video_num_frames=107994, video_fps=29.996355492040582, video_width=640, video_height=480, video_file_size=105540536, cache_file_size=105540536, cache_file_mtime=1758654057.849164, t_start_dt=Timestamp('2025-09-23 14:00:55'), t_end_dt=Timestamp('2025-09-23 15:00:55.237369792'), label='Debut_2025-09-23T140055.mp4')

Pandas(Index=133, t_start=Timestamp('2025-09-23 15:00:58'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-23T150058.mp4', video_num_frames=107995, video_fps=29.996400547377196, video_width=640, video_height=480, video_file_size=105821779, cache_file_size=105821779, cache_file_mtime=1758657660.7308822, t_start_dt=Timestamp('2025-09-23 15:00:58'), t_end_dt=Timestamp('2025-09-23 16:00:58.265299479'), label='Debut_2025-09-23T150058.mp4')

Pandas(Index=134, t_start=Timestamp('2025-09-23 16:01:01'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-23T160101.mp4', video_num_frames=107992, video_fps=29.995317224411714, video_width=640, video_height=480, video_file_size=106679145, cache_file_size=106679145, cache_file_mtime=1758661263.6281898, t_start_dt=Timestamp('2025-09-23 16:01:01'), t_end_dt=Timestamp('2025-09-23 17:01:01.295312500'), label='Debut_2025-09-23T160101.mp4')

Pandas(Index=135, t_start=Timestamp('2025-09-23 17:01:05'), t_duration=403.61738281249995, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-09-23T170105.mp4', video_num_frames=12093, video_fps=29.961544063670296, video_width=640, video_height=480, video_file_size=11938579, cache_file_size=11938579, cache_file_mtime=1758661669.4009955, t_start_dt=Timestamp('2025-09-23 17:01:05'), t_end_dt=Timestamp('2025-09-23 17:07:48.617382812'), label='Debut_2025-09-23T170105.mp4')

Pandas(Index=136, t_start=Timestamp('2025-10-02 08:00:55'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-02T080055.mp4', video_num_frames=107978, video_fps=29.991678673130192, video_width=640, video_height=480, video_file_size=107460260, cache_file_size=107460260, cache_file_mtime=1759410057.9013796, t_start_dt=Timestamp('2025-10-02 08:00:55'), t_end_dt=Timestamp('2025-10-02 09:00:55.265299479'), label='Debut_2025-10-02T080055.mp4')

Pandas(Index=137, t_start=Timestamp('2025-10-02 09:00:58'), t_duration=3600.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-02T090058.mp4', video_num_frames=107996, video_fps=29.996911010967413, video_width=640, video_height=480, video_file_size=105916639, cache_file_size=105916639, cache_file_mtime=1759413660.5646243, t_start_dt=Timestamp('2025-10-02 09:00:58'), t_end_dt=Timestamp('2025-10-02 10:00:58.237369792'), label='Debut_2025-10-02T090058.mp4')

Pandas(Index=138, t_start=Timestamp('2025-10-02 10:01:00'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-02T100100.mp4', video_num_frames=107989, video_fps=29.994984051787412, video_width=640, video_height=480, video_file_size=106805780, cache_file_size=106805780, cache_file_mtime=1759417262.9650548, t_start_dt=Timestamp('2025-10-02 10:01:00'), t_end_dt=Timestamp('2025-10-02 11:01:00.235286458'), label='Debut_2025-10-02T100100.mp4')

Pandas(Index=139, t_start=Timestamp('2025-10-02 11:01:03'), t_duration=134.60735677083335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-02T110103.mp4', video_num_frames=4024, video_fps=29.89435419083958, video_width=640, video_height=480, video_file_size=4397180, cache_file_size=4397180, cache_file_mtime=1759417398.4071195, t_start_dt=Timestamp('2025-10-02 11:01:03'), t_end_dt=Timestamp('2025-10-02 11:03:17.607356771'), label='Debut_2025-10-02T110103.mp4')

Pandas(Index=140, t_start=Timestamp('2025-10-02 18:01:52'), t_duration=3600.2033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-02T180152.mp4', video_num_frames=106592, video_fps=29.607216736511354, video_width=640, video_height=480, video_file_size=113164482, cache_file_size=113164482, cache_file_mtime=1759446114.3653274, t_start_dt=Timestamp('2025-10-02 18:01:52'), t_end_dt=Timestamp('2025-10-02 19:01:52.203320313'), label='Debut_2025-10-02T180152.mp4')

Pandas(Index=141, t_start=Timestamp('2025-10-02 19:01:54'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-02T190154.mp4', video_num_frames=65509, video_fps=18.19576508929977, video_width=640, video_height=480, video_file_size=102768111, cache_file_size=102768111, cache_file_mtime=1759449716.7773738, t_start_dt=Timestamp('2025-10-02 19:01:54'), t_end_dt=Timestamp('2025-10-02 20:01:54.233333333'), label='Debut_2025-10-02T190154.mp4')

Pandas(Index=142, t_start=Timestamp('2025-10-02 20:01:57'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-02T200157.mp4', video_num_frames=54100, video_fps=15.026795394506815, video_width=640, video_height=480, video_file_size=95595411, cache_file_size=95595411, cache_file_mtime=1759453318.7404528, t_start_dt=Timestamp('2025-10-02 20:01:57'), t_end_dt=Timestamp('2025-10-02 21:01:57.235351562'), label='Debut_2025-10-02T200157.mp4')

Pandas(Index=143, t_start=Timestamp('2025-10-02 21:01:59'), t_duration=1169.3973307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-02T210159.mp4', video_num_frames=17536, video_fps=14.995758532359222, video_width=640, video_height=480, video_file_size=30848621, cache_file_size=30848621, cache_file_mtime=1759454538.151084, t_start_dt=Timestamp('2025-10-02 21:01:59'), t_end_dt=Timestamp('2025-10-02 21:21:28.397330729'), label='Debut_2025-10-02T210159.mp4')

Pandas(Index=144, t_start=Timestamp('2025-10-09 15:36:18'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-09T153618.mp4', video_num_frames=107995, video_fps=29.996400547377196, video_width=640, video_height=480, video_file_size=111144813, cache_file_size=111144813, cache_file_mtime=1760042180.1405606, t_start_dt=Timestamp('2025-10-09 15:36:18'), t_end_dt=Timestamp('2025-10-09 16:36:18.265299479'), label='Debut_2025-10-09T153618.mp4')

Pandas(Index=145, t_start=Timestamp('2025-10-09 16:36:20'), t_duration=3600.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-09T163620.mp4', video_num_frames=107995, video_fps=29.996633251503997, video_width=640, video_height=480, video_file_size=107706955, cache_file_size=107706955, cache_file_mtime=1760045782.6318588, t_start_dt=Timestamp('2025-10-09 16:36:20'), t_end_dt=Timestamp('2025-10-09 17:36:20.237369792'), label='Debut_2025-10-09T163620.mp4')

Pandas(Index=146, t_start=Timestamp('2025-10-09 17:36:23'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-09T173623.mp4', video_num_frames=107807, video_fps=29.944431800193037, video_width=640, video_height=480, video_file_size=114363490, cache_file_size=114363490, cache_file_mtime=1760049385.1380613, t_start_dt=Timestamp('2025-10-09 17:36:23'), t_end_dt=Timestamp('2025-10-09 18:36:23.235286458'), label='Debut_2025-10-09T173623.mp4')

Pandas(Index=147, t_start=Timestamp('2025-10-09 18:36:25'), t_duration=1558.1053385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-09T183625.mp4', video_num_frames=46727, video_fps=29.989628328810472, video_width=640, video_height=480, video_file_size=48186665, cache_file_size=48186665, cache_file_mtime=1760050945.1174197, t_start_dt=Timestamp('2025-10-09 18:36:25'), t_end_dt=Timestamp('2025-10-09 19:02:23.105338542'), label='Debut_2025-10-09T183625.mp4')

Pandas(Index=148, t_start=Timestamp('2025-10-16 16:45:51'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-16T164551.mp4', video_num_frames=107994, video_fps=29.996139062816315, video_width=640, video_height=480, video_file_size=108639760, cache_file_size=108639760, cache_file_mtime=1760651153.8805938, t_start_dt=Timestamp('2025-10-16 16:45:51'), t_end_dt=Timestamp('2025-10-16 17:45:51.263346354'), label='Debut_2025-10-16T164551.mp4')

Pandas(Index=149, t_start=Timestamp('2025-10-16 17:45:54'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-16T174554.mp4', video_num_frames=107859, video_fps=29.95860821752117, video_width=640, video_height=480, video_file_size=105966639, cache_file_size=105966639, cache_file_mtime=1760654756.8337927, t_start_dt=Timestamp('2025-10-16 17:45:54'), t_end_dt=Timestamp('2025-10-16 18:45:54.267382812'), label='Debut_2025-10-16T174554.mp4')

Pandas(Index=150, t_start=Timestamp('2025-10-16 18:45:57'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-16T184557.mp4', video_num_frames=107957, video_fps=29.985595799650117, video_width=640, video_height=480, video_file_size=106680708, cache_file_size=106680708, cache_file_mtime=1760658359.991043, t_start_dt=Timestamp('2025-10-16 18:45:57'), t_end_dt=Timestamp('2025-10-16 19:45:57.295312500'), label='Debut_2025-10-16T184557.mp4')

Pandas(Index=151, t_start=Timestamp('2025-10-16 19:46:00'), t_duration=1470.0573567708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-16T194600.mp4', video_num_frames=44089, video_fps=29.991346798091644, video_width=640, video_height=480, video_file_size=43658333, cache_file_size=43658333, cache_file_mtime=1760659831.712455, t_start_dt=Timestamp('2025-10-16 19:46:00'), t_end_dt=Timestamp('2025-10-16 20:10:30.057356771'), label='Debut_2025-10-16T194600.mp4')

Pandas(Index=152, t_start=Timestamp('2025-10-17 08:41:07'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-17T084107.mp4', video_num_frames=107750, video_fps=29.928332688397873, video_width=640, video_height=480, video_file_size=105908767, cache_file_size=105908767, cache_file_mtime=1760708469.667748, t_start_dt=Timestamp('2025-10-17 08:41:07'), t_end_dt=Timestamp('2025-10-17 09:41:07.267382812'), label='Debut_2025-10-17T084107.mp4')

Pandas(Index=153, t_start=Timestamp('2025-10-17 09:41:10'), t_duration=594.1753255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-17T094110.mp4', video_num_frames=17810, video_fps=29.974317739277335, video_width=640, video_height=480, video_file_size=17799157, cache_file_size=17799157, cache_file_mtime=1760709065.1965754, t_start_dt=Timestamp('2025-10-17 09:41:10'), t_end_dt=Timestamp('2025-10-17 09:51:04.175325521'), label='Debut_2025-10-17T094110.mp4')

Pandas(Index=154, t_start=Timestamp('2025-10-17 17:44:30'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-17T174430.mp4', video_num_frames=107623, video_fps=29.89307482856036, video_width=640, video_height=480, video_file_size=107456454, cache_file_size=107456454, cache_file_mtime=1760741072.6908832, t_start_dt=Timestamp('2025-10-17 17:44:30'), t_end_dt=Timestamp('2025-10-17 18:44:30.265299479'), label='Debut_2025-10-17T174430.mp4')

Pandas(Index=155, t_start=Timestamp('2025-10-17 18:44:33'), t_duration=1319.7233723958332, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-17T184433.mp4', video_num_frames=35903, video_fps=27.2049436654452, video_width=640, video_height=480, video_file_size=38643778, cache_file_size=38643778, cache_file_mtime=1760742394.0621724, t_start_dt=Timestamp('2025-10-17 18:44:33'), t_end_dt=Timestamp('2025-10-17 19:06:32.723372396'), label='Debut_2025-10-17T184433.mp4')

Pandas(Index=156, t_start=Timestamp('2025-10-18 05:21:59'), t_duration=3600.263346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-18T052159.mp4', video_num_frames=54140, video_fps=15.037788848092257, video_width=640, video_height=480, video_file_size=98505646, cache_file_size=98505646, cache_file_mtime=1760782921.7492952, t_start_dt=Timestamp('2025-10-18 05:21:59'), t_end_dt=Timestamp('2025-10-18 06:21:59.263346354'), label='Debut_2025-10-18T052159.mp4')

Pandas(Index=157, t_start=Timestamp('2025-10-18 06:22:02'), t_duration=2755.4673177083337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-18T062202.mp4', video_num_frames=41327, video_fps=14.998181881674732, video_width=640, video_height=480, video_file_size=76173578, cache_file_size=76173578, cache_file_mtime=1760785679.135565, t_start_dt=Timestamp('2025-10-18 06:22:02'), t_end_dt=Timestamp('2025-10-18 07:07:57.467317708'), label='Debut_2025-10-18T062202.mp4')

Pandas(Index=158, t_start=Timestamp('2025-10-18 18:25:04'), t_duration=3600.263346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-18T182504.mp4', video_num_frames=107985, video_fps=29.99363924568235, video_width=640, video_height=480, video_file_size=111319538, cache_file_size=111319538, cache_file_mtime=1760829906.1902654, t_start_dt=Timestamp('2025-10-18 18:25:04'), t_end_dt=Timestamp('2025-10-18 19:25:04.263346354'), label='Debut_2025-10-18T182504.mp4')

Pandas(Index=159, t_start=Timestamp('2025-10-18 19:25:06'), t_duration=546.2333333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-18T192506.mp4', video_num_frames=16375, video_fps=29.978031366326967, video_width=640, video_height=480, video_file_size=16727684, cache_file_size=16727684, cache_file_mtime=1760830453.6972842, t_start_dt=Timestamp('2025-10-18 19:25:06'), t_end_dt=Timestamp('2025-10-18 19:34:12.233333333'), label='Debut_2025-10-18T192506.mp4')

Pandas(Index=160, t_start=Timestamp('2025-10-20 12:39:43'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-20T123943.mp4', video_num_frames=107995, video_fps=29.996400547377196, video_width=640, video_height=480, video_file_size=106609826, cache_file_size=106609826, cache_file_mtime=1760981985.6504698, t_start_dt=Timestamp('2025-10-20 12:39:43'), t_end_dt=Timestamp('2025-10-20 13:39:43.265299479'), label='Debut_2025-10-20T123943.mp4')

Pandas(Index=161, t_start=Timestamp('2025-10-20 13:39:45'), t_duration=858.1733072916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-20T133945.mp4', video_num_frames=25734, video_fps=29.98694993347516, video_width=640, video_height=480, video_file_size=25392247, cache_file_size=25392247, cache_file_mtime=1760982844.924775, t_start_dt=Timestamp('2025-10-20 13:39:45'), t_end_dt=Timestamp('2025-10-20 13:54:03.173307292'), label='Debut_2025-10-20T133945.mp4')

Pandas(Index=162, t_start=Timestamp('2025-10-20 23:37:40'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-20T233740.mp4', video_num_frames=54022, video_fps=15.00513014421529, video_width=640, video_height=480, video_file_size=98181506, cache_file_size=98181506, cache_file_mtime=1761021462.487231, t_start_dt=Timestamp('2025-10-20 23:37:40'), t_end_dt=Timestamp('2025-10-21 00:37:40.235351562'), label='Debut_2025-10-20T233740.mp4')

Pandas(Index=163, t_start=Timestamp('2025-10-21 00:37:42'), t_duration=3600.2033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T003742.mp4', video_num_frames=54000, video_fps=14.999152879874785, video_width=640, video_height=480, video_file_size=98770170, cache_file_size=98770170, cache_file_mtime=1761025064.598126, t_start_dt=Timestamp('2025-10-21 00:37:42'), t_end_dt=Timestamp('2025-10-21 01:37:42.203320313'), label='Debut_2025-10-21T003742.mp4')

Pandas(Index=164, t_start=Timestamp('2025-10-21 01:37:44'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T013744.mp4', video_num_frames=53998, video_fps=14.998463913356359, video_width=640, video_height=480, video_file_size=98781874, cache_file_size=98781874, cache_file_mtime=1761028666.7790143, t_start_dt=Timestamp('2025-10-21 01:37:44'), t_end_dt=Timestamp('2025-10-21 02:37:44.235351562'), label='Debut_2025-10-21T013744.mp4')

Pandas(Index=165, t_start=Timestamp('2025-10-21 02:37:47'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T023747.mp4', video_num_frames=53988, video_fps=14.995811328325203, video_width=640, video_height=480, video_file_size=98977782, cache_file_size=98977782, cache_file_mtime=1761032268.9972055, t_start_dt=Timestamp('2025-10-21 02:37:47'), t_end_dt=Timestamp('2025-10-21 03:37:47.205338542'), label='Debut_2025-10-21T023747.mp4')

Pandas(Index=166, t_start=Timestamp('2025-10-21 03:37:49'), t_duration=1434.9853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T033749.mp4', video_num_frames=21520, video_fps=14.99666876499311, video_width=640, video_height=480, video_file_size=39331465, cache_file_size=39331465, cache_file_mtime=1761033705.5979595, t_start_dt=Timestamp('2025-10-21 03:37:49'), t_end_dt=Timestamp('2025-10-21 04:01:43.985351562'), label='Debut_2025-10-21T033749.mp4')

Pandas(Index=167, t_start=Timestamp('2025-10-21 04:01:48'), t_duration=702.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T040148.mp4', video_num_frames=10529, video_fps=14.993548781861493, video_width=640, video_height=480, video_file_size=19381793, cache_file_size=19381793, cache_file_mtime=1761034461.391243, t_start_dt=Timestamp('2025-10-21 04:01:48'), t_end_dt=Timestamp('2025-10-21 04:13:30.235351562'), label='Debut_2025-10-21T040148.mp4')

Pandas(Index=168, t_start=Timestamp('2025-10-21 09:51:44'), t_duration=3600.5353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T095144.mp4', video_num_frames=64877, video_fps=18.018709348832186, video_width=640, video_height=480, video_file_size=101516750, cache_file_size=101516750, cache_file_mtime=1761058308.7237723, t_start_dt=Timestamp('2025-10-21 09:51:44'), t_end_dt=Timestamp('2025-10-21 10:51:44.535351563'), label='Debut_2025-10-21T095144.mp4')

Pandas(Index=169, t_start=Timestamp('2025-10-21 10:51:50'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T105150.mp4', video_num_frames=63042, video_fps=17.510220464828144, video_width=640, video_height=480, video_file_size=99098301, cache_file_size=99098301, cache_file_mtime=1761061911.9277475, t_start_dt=Timestamp('2025-10-21 10:51:50'), t_end_dt=Timestamp('2025-10-21 11:51:50.297330729'), label='Debut_2025-10-21T105150.mp4')

Pandas(Index=170, t_start=Timestamp('2025-10-21 11:51:52'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T115152.mp4', video_num_frames=107865, video_fps=29.96054185839344, video_width=640, video_height=480, video_file_size=106211284, cache_file_size=106211284, cache_file_mtime=1761065514.535, t_start_dt=Timestamp('2025-10-21 11:51:52'), t_end_dt=Timestamp('2025-10-21 12:51:52.235286458'), label='Debut_2025-10-21T115152.mp4')

Pandas(Index=171, t_start=Timestamp('2025-10-21 12:51:55'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T125155.mp4', video_num_frames=107990, video_fps=29.99474490017435, video_width=640, video_height=480, video_file_size=106362351, cache_file_size=106362351, cache_file_mtime=1761069117.3011076, t_start_dt=Timestamp('2025-10-21 12:51:55'), t_end_dt=Timestamp('2025-10-21 13:51:55.297330729'), label='Debut_2025-10-21T125155.mp4')

Pandas(Index=172, t_start=Timestamp('2025-10-21 13:51:57'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T135157.mp4', video_num_frames=107994, video_fps=29.996372849908138, video_width=640, video_height=480, video_file_size=106461893, cache_file_size=106461893, cache_file_mtime=1761072719.9071074, t_start_dt=Timestamp('2025-10-21 13:51:57'), t_end_dt=Timestamp('2025-10-21 14:51:57.235286458'), label='Debut_2025-10-21T135157.mp4')

Pandas(Index=173, t_start=Timestamp('2025-10-21 14:52:00'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T145200.mp4', video_num_frames=107980, video_fps=29.992216832419512, video_width=640, video_height=480, video_file_size=106322346, cache_file_size=106322346, cache_file_mtime=1761076322.5670726, t_start_dt=Timestamp('2025-10-21 14:52:00'), t_end_dt=Timestamp('2025-10-21 15:52:00.267382812'), label='Debut_2025-10-21T145200.mp4')

Pandas(Index=174, t_start=Timestamp('2025-10-21 15:52:03'), t_duration=3600.2073567708335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T155203.mp4', video_num_frames=107868, video_fps=29.961607571612493, video_width=640, video_height=480, video_file_size=107872669, cache_file_size=107872669, cache_file_mtime=1761079925.1644657, t_start_dt=Timestamp('2025-10-21 15:52:03'), t_end_dt=Timestamp('2025-10-21 16:52:03.207356771'), label='Debut_2025-10-21T155203.mp4')

Pandas(Index=175, t_start=Timestamp('2025-10-21 16:52:05'), t_duration=3600.275325520833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T165205.mp4', video_num_frames=107991, video_fps=29.995205987302512, video_width=640, video_height=480, video_file_size=107264198, cache_file_size=107264198, cache_file_mtime=1761083527.6975012, t_start_dt=Timestamp('2025-10-21 16:52:05'), t_end_dt=Timestamp('2025-10-21 17:52:05.275325521'), label='Debut_2025-10-21T165205.mp4')

Pandas(Index=176, t_start=Timestamp('2025-10-21 17:52:08'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T175208.mp4', video_num_frames=107627, video_fps=29.893936651897913, video_width=640, video_height=480, video_file_size=105645916, cache_file_size=105645916, cache_file_mtime=1761087130.324358, t_start_dt=Timestamp('2025-10-21 17:52:08'), t_end_dt=Timestamp('2025-10-21 18:52:08.295312500'), label='Debut_2025-10-21T175208.mp4')

Pandas(Index=177, t_start=Timestamp('2025-10-21 18:52:10'), t_duration=617.4573567708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-21T185210.mp4', video_num_frames=18507, video_fps=29.97292006817694, video_width=640, video_height=480, video_file_size=18285112, cache_file_size=18285112, cache_file_mtime=1761087749.0437927, t_start_dt=Timestamp('2025-10-21 18:52:10'), t_end_dt=Timestamp('2025-10-21 19:02:27.457356771'), label='Debut_2025-10-21T185210.mp4')

Pandas(Index=178, t_start=Timestamp('2025-10-22 07:51:08'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T075108.mp4', video_num_frames=107987, video_fps=29.994194760601008, video_width=640, video_height=480, video_file_size=105709930, cache_file_size=105709930, cache_file_mtime=1761137470.8230786, t_start_dt=Timestamp('2025-10-22 07:51:08'), t_end_dt=Timestamp('2025-10-22 08:51:08.263346354'), label='Debut_2025-10-22T075108.mp4')

Pandas(Index=179, t_start=Timestamp('2025-10-22 08:51:11'), t_duration=3600.2313151041667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T085111.mp4', video_num_frames=106703, video_fps=29.637817868075715, video_width=640, video_height=480, video_file_size=104644557, cache_file_size=104644557, cache_file_mtime=1761141073.4602065, t_start_dt=Timestamp('2025-10-22 08:51:11'), t_end_dt=Timestamp('2025-10-22 09:51:11.231315104'), label='Debut_2025-10-22T085111.mp4')

Pandas(Index=180, t_start=Timestamp('2025-10-22 09:51:14'), t_duration=1380.6873697916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T095114.mp4', video_num_frames=41403, video_fps=29.987237448436527, video_width=640, video_height=480, video_file_size=40208802, cache_file_size=40208802, cache_file_mtime=1761142455.7785008, t_start_dt=Timestamp('2025-10-22 09:51:14'), t_end_dt=Timestamp('2025-10-22 10:14:14.687369792'), label='Debut_2025-10-22T095114.mp4')

Pandas(Index=181, t_start=Timestamp('2025-10-22 10:22:02'), t_duration=15.505338541666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T102202.mp4', video_num_frames=452, video_fps=29.151249989502944, video_width=640, video_height=480, video_file_size=441811, cache_file_size=441811, cache_file_mtime=1761142938.523535, t_start_dt=Timestamp('2025-10-22 10:22:02'), t_end_dt=Timestamp('2025-10-22 10:22:17.505338541'), label='Debut_2025-10-22T102202.mp4')

Pandas(Index=182, t_start=Timestamp('2025-10-22 10:25:59'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T102559.mp4', video_num_frames=107976, video_fps=29.99110580382783, video_width=640, video_height=480, video_file_size=104561376, cache_file_size=104561376, cache_file_mtime=1761146761.6935697, t_start_dt=Timestamp('2025-10-22 10:25:59'), t_end_dt=Timestamp('2025-10-22 11:25:59.267382813'), label='Debut_2025-10-22T102559.mp4')

Pandas(Index=183, t_start=Timestamp('2025-10-22 11:26:02'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T112602.mp4', video_num_frames=107763, video_fps=29.931960851770995, video_width=640, video_height=480, video_file_size=103182808, cache_file_size=103182808, cache_file_mtime=1761150364.4341524, t_start_dt=Timestamp('2025-10-22 11:26:02'), t_end_dt=Timestamp('2025-10-22 12:26:02.265299479'), label='Debut_2025-10-22T112602.mp4')

Pandas(Index=184, t_start=Timestamp('2025-10-22 12:26:04'), t_duration=3600.253385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T122604.mp4', video_num_frames=107981, video_fps=29.992611197143024, video_width=640, video_height=480, video_file_size=104293427, cache_file_size=104293427, cache_file_mtime=1761153967.3394487, t_start_dt=Timestamp('2025-10-22 12:26:04'), t_end_dt=Timestamp('2025-10-22 13:26:04.253385417'), label='Debut_2025-10-22T122604.mp4')

Pandas(Index=185, t_start=Timestamp('2025-10-22 13:26:07'), t_duration=3600.2473307291666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T132607.mp4', video_num_frames=107980, video_fps=29.992383878284983, video_width=640, video_height=480, video_file_size=104435089, cache_file_size=104435089, cache_file_mtime=1761157569.248574, t_start_dt=Timestamp('2025-10-22 13:26:07'), t_end_dt=Timestamp('2025-10-22 14:26:07.247330729'), label='Debut_2025-10-22T132607.mp4')

Pandas(Index=186, t_start=Timestamp('2025-10-22 14:26:09'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T142609.mp4', video_num_frames=107837, video_fps=29.952780838279, video_width=640, video_height=480, video_file_size=103267331, cache_file_size=103267331, cache_file_mtime=1761161171.9720936, t_start_dt=Timestamp('2025-10-22 14:26:09'), t_end_dt=Timestamp('2025-10-22 15:26:09.233333333'), label='Debut_2025-10-22T142609.mp4')

Pandas(Index=187, t_start=Timestamp('2025-10-22 15:26:12'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T152612.mp4', video_num_frames=107954, video_fps=29.984995146573585, video_width=640, video_height=480, video_file_size=106517017, cache_file_size=106517017, cache_file_mtime=1761164774.7642424, t_start_dt=Timestamp('2025-10-22 15:26:12'), t_end_dt=Timestamp('2025-10-22 16:26:12.267382813'), label='Debut_2025-10-22T152612.mp4')

Pandas(Index=188, t_start=Timestamp('2025-10-22 16:26:15'), t_duration=3600.249348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T162615.mp4', video_num_frames=107986, video_fps=29.994033616378207, video_width=640, video_height=480, video_file_size=104574539, cache_file_size=104574539, cache_file_mtime=1761168377.6402504, t_start_dt=Timestamp('2025-10-22 16:26:15'), t_end_dt=Timestamp('2025-10-22 17:26:15.249348958'), label='Debut_2025-10-22T162615.mp4')

Pandas(Index=189, t_start=Timestamp('2025-10-22 17:26:18'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T172618.mp4', video_num_frames=107922, video_fps=29.975857571225266, video_width=640, video_height=480, video_file_size=104151129, cache_file_size=104151129, cache_file_mtime=1761171980.4324734, t_start_dt=Timestamp('2025-10-22 17:26:18'), t_end_dt=Timestamp('2025-10-22 18:26:18.297330729'), label='Debut_2025-10-22T172618.mp4')

Pandas(Index=190, t_start=Timestamp('2025-10-22 18:26:21'), t_duration=788.6333333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-22T182621.mp4', video_num_frames=23583, video_fps=29.903630753624412, video_width=640, video_height=480, video_file_size=22874901, cache_file_size=22874901, cache_file_mtime=1761172772.7894032, t_start_dt=Timestamp('2025-10-22 18:26:21'), t_end_dt=Timestamp('2025-10-22 18:39:29.633333333'), label='Debut_2025-10-22T182621.mp4')

Pandas(Index=191, t_start=Timestamp('2025-10-23 02:16:35'), t_duration=1.6733723958333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T021635.mp4', video_num_frames=37, video_fps=22.111037622067464, video_width=640, video_height=480, video_file_size=48144, cache_file_size=48144, cache_file_mtime=1761200198.2261138, t_start_dt=Timestamp('2025-10-23 02:16:35'), t_end_dt=Timestamp('2025-10-23 02:16:36.673372396'), label='Debut_2025-10-23T021635.mp4')

Pandas(Index=192, t_start=Timestamp('2025-10-23 02:16:41'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T021641.mp4', video_num_frames=107488, video_fps=29.8558264800908, video_width=640, video_height=480, video_file_size=104343361, cache_file_size=104343361, cache_file_mtime=1761203804.4491782, t_start_dt=Timestamp('2025-10-23 02:16:41'), t_end_dt=Timestamp('2025-10-23 03:16:41.235286458'), label='Debut_2025-10-23T021641.mp4')

Pandas(Index=193, t_start=Timestamp('2025-10-23 03:16:45'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T031645.mp4', video_num_frames=107808, video_fps=29.94447617538105, video_width=640, video_height=480, video_file_size=103713038, cache_file_size=103713038, cache_file_mtime=1761207407.8808453, t_start_dt=Timestamp('2025-10-23 03:16:45'), t_end_dt=Timestamp('2025-10-23 04:16:45.263346354'), label='Debut_2025-10-23T031645.mp4')

Pandas(Index=194, t_start=Timestamp('2025-10-23 04:16:48'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T041648.mp4', video_num_frames=107967, video_fps=29.988623342735067, video_width=640, video_height=480, video_file_size=103960080, cache_file_size=103960080, cache_file_mtime=1761211010.8901348, t_start_dt=Timestamp('2025-10-23 04:16:48'), t_end_dt=Timestamp('2025-10-23 05:16:48.265299479'), label='Debut_2025-10-23T041648.mp4')

Pandas(Index=195, t_start=Timestamp('2025-10-23 15:22:23'), t_duration=3600.2933593750004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T152223.mp4', video_num_frames=107991, video_fps=29.995055741442943, video_width=640, video_height=480, video_file_size=107994470, cache_file_size=107994470, cache_file_mtime=1761250945.7210543, t_start_dt=Timestamp('2025-10-23 15:22:23'), t_end_dt=Timestamp('2025-10-23 16:22:23.293359375'), label='Debut_2025-10-23T152223.mp4')

Pandas(Index=196, t_start=Timestamp('2025-10-23 16:22:26'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T162226.mp4', video_num_frames=107847, video_fps=29.95529246569738, video_width=640, video_height=480, video_file_size=107380188, cache_file_size=107380188, cache_file_mtime=1761254548.855188, t_start_dt=Timestamp('2025-10-23 16:22:26'), t_end_dt=Timestamp('2025-10-23 17:22:26.265299479'), label='Debut_2025-10-23T162226.mp4')

Pandas(Index=197, t_start=Timestamp('2025-10-23 17:22:29'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T172229.mp4', video_num_frames=101988, video_fps=28.327896002081875, video_width=640, video_height=480, video_file_size=105052318, cache_file_size=105052318, cache_file_mtime=1761258152.7196636, t_start_dt=Timestamp('2025-10-23 17:22:29'), t_end_dt=Timestamp('2025-10-23 18:22:29.267382813'), label='Debut_2025-10-23T172229.mp4')

Pandas(Index=198, t_start=Timestamp('2025-10-23 18:22:34'), t_duration=3600.301302083333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T182234.mp4', video_num_frames=104250, video_fps=28.955909867786673, video_width=640, video_height=480, video_file_size=106320970, cache_file_size=106320970, cache_file_mtime=1761261756.7536056, t_start_dt=Timestamp('2025-10-23 18:22:34'), t_end_dt=Timestamp('2025-10-23 19:22:34.301302083'), label='Debut_2025-10-23T182234.mp4')

Pandas(Index=199, t_start=Timestamp('2025-10-23 19:22:37'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T192237.mp4', video_num_frames=104270, video_fps=28.961737813635697, video_width=640, video_height=480, video_file_size=110016185, cache_file_size=110016185, cache_file_mtime=1761265359.9450574, t_start_dt=Timestamp('2025-10-23 19:22:37'), t_end_dt=Timestamp('2025-10-23 20:22:37.267382812'), label='Debut_2025-10-23T192237.mp4')

Pandas(Index=200, t_start=Timestamp('2025-10-23 20:22:40'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T202240.mp4', video_num_frames=107855, video_fps=29.95749718892949, video_width=640, video_height=480, video_file_size=100288105, cache_file_size=100288105, cache_file_mtime=1761268962.9720461, t_start_dt=Timestamp('2025-10-23 20:22:40'), t_end_dt=Timestamp('2025-10-23 21:22:40.267382812'), label='Debut_2025-10-23T202240.mp4')

Pandas(Index=201, t_start=Timestamp('2025-10-23 21:22:43'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T212243.mp4', video_num_frames=107888, video_fps=29.966663174810854, video_width=640, video_height=480, video_file_size=100178568, cache_file_size=100178568, cache_file_mtime=1761272565.7726467, t_start_dt=Timestamp('2025-10-23 21:22:43'), t_end_dt=Timestamp('2025-10-23 22:22:43.267382813'), label='Debut_2025-10-23T212243.mp4')

Pandas(Index=202, t_start=Timestamp('2025-10-23 22:22:46'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T222246.mp4', video_num_frames=107888, video_fps=29.966663174810854, video_width=640, video_height=480, video_file_size=100193436, cache_file_size=100193436, cache_file_mtime=1761276168.5993423, t_start_dt=Timestamp('2025-10-23 22:22:46'), t_end_dt=Timestamp('2025-10-23 23:22:46.267382813'), label='Debut_2025-10-23T222246.mp4')

Pandas(Index=203, t_start=Timestamp('2025-10-23 23:22:49'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-23T232249.mp4', video_num_frames=107876, video_fps=29.963330089035814, video_width=640, video_height=480, video_file_size=100181832, cache_file_size=100181832, cache_file_mtime=1761279771.4368799, t_start_dt=Timestamp('2025-10-23 23:22:49'), t_end_dt=Timestamp('2025-10-24 00:22:49.267382812'), label='Debut_2025-10-23T232249.mp4')

Pandas(Index=204, t_start=Timestamp('2025-10-24 00:22:52'), t_duration=3600.2093098958335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T002252.mp4', video_num_frames=82087, video_fps=22.800618779127333, video_width=640, video_height=480, video_file_size=97311998, cache_file_size=97311998, cache_file_mtime=1761283374.1218758, t_start_dt=Timestamp('2025-10-24 00:22:52'), t_end_dt=Timestamp('2025-10-24 01:22:52.209309896'), label='Debut_2025-10-24T002252.mp4')

Pandas(Index=205, t_start=Timestamp('2025-10-24 01:22:54'), t_duration=3600.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T012254.mp4', video_num_frames=53998, video_fps=14.998455505483706, video_width=640, video_height=480, video_file_size=93848394, cache_file_size=93848394, cache_file_mtime=1761286976.6567435, t_start_dt=Timestamp('2025-10-24 01:22:54'), t_end_dt=Timestamp('2025-10-24 02:22:54.237369792'), label='Debut_2025-10-24T012254.mp4')

Pandas(Index=206, t_start=Timestamp('2025-10-24 02:22:57'), t_duration=3600.2093098958335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T022257.mp4', video_num_frames=53998, video_fps=14.998572402881306, video_width=640, video_height=480, video_file_size=93830188, cache_file_size=93830188, cache_file_mtime=1761290579.1626904, t_start_dt=Timestamp('2025-10-24 02:22:57'), t_end_dt=Timestamp('2025-10-24 03:22:57.209309896'), label='Debut_2025-10-24T022257.mp4')

Pandas(Index=207, t_start=Timestamp('2025-10-24 03:22:59'), t_duration=3600.2693359375003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T032259.mp4', video_num_frames=53998, video_fps=14.998322336886796, video_width=640, video_height=480, video_file_size=93829126, cache_file_size=93829126, cache_file_mtime=1761294181.705869, t_start_dt=Timestamp('2025-10-24 03:22:59'), t_end_dt=Timestamp('2025-10-24 04:22:59.269335938'), label='Debut_2025-10-24T032259.mp4')

Pandas(Index=208, t_start=Timestamp('2025-10-24 04:23:02'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T042302.mp4', video_num_frames=53996, video_fps=14.99778336651834, video_width=640, video_height=480, video_file_size=93839771, cache_file_size=93839771, cache_file_mtime=1761297784.1836677, t_start_dt=Timestamp('2025-10-24 04:23:02'), t_end_dt=Timestamp('2025-10-24 05:23:02.265364583'), label='Debut_2025-10-24T042302.mp4')

Pandas(Index=209, t_start=Timestamp('2025-10-24 05:23:04'), t_duration=3600.2673177083334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T052304.mp4', video_num_frames=53997, video_fps=14.998052987457203, video_width=640, video_height=480, video_file_size=93829918, cache_file_size=93829918, cache_file_mtime=1761301386.6931844, t_start_dt=Timestamp('2025-10-24 05:23:04'), t_end_dt=Timestamp('2025-10-24 06:23:04.267317708'), label='Debut_2025-10-24T052304.mp4')

Pandas(Index=210, t_start=Timestamp('2025-10-24 06:23:07'), t_duration=3600.205338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T062307.mp4', video_num_frames=53996, video_fps=14.998033423802468, video_width=640, video_height=480, video_file_size=93823437, cache_file_size=93823437, cache_file_mtime=1761304989.1932888, t_start_dt=Timestamp('2025-10-24 06:23:07'), t_end_dt=Timestamp('2025-10-24 07:23:07.205338542'), label='Debut_2025-10-24T062307.mp4')

Pandas(Index=211, t_start=Timestamp('2025-10-24 07:23:09'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T072309.mp4', video_num_frames=53996, video_fps=14.99778336651834, video_width=640, video_height=480, video_file_size=94273765, cache_file_size=94273765, cache_file_mtime=1761308591.725355, t_start_dt=Timestamp('2025-10-24 07:23:09'), t_end_dt=Timestamp('2025-10-24 08:23:09.265364583'), label='Debut_2025-10-24T072309.mp4')

Pandas(Index=212, t_start=Timestamp('2025-10-24 08:23:12'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T082312.mp4', video_num_frames=65869, video_fps=18.29559583245419, video_width=640, video_height=480, video_file_size=95532787, cache_file_size=95532787, cache_file_mtime=1761312194.2760887, t_start_dt=Timestamp('2025-10-24 08:23:12'), t_end_dt=Timestamp('2025-10-24 09:23:12.265364583'), label='Debut_2025-10-24T082312.mp4')

Pandas(Index=213, t_start=Timestamp('2025-10-24 09:23:14'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T092314.mp4', video_num_frames=96567, video_fps=26.82219002415458, video_width=640, video_height=480, video_file_size=98478716, cache_file_size=98478716, cache_file_mtime=1761315797.0457191, t_start_dt=Timestamp('2025-10-24 09:23:14'), t_end_dt=Timestamp('2025-10-24 10:23:14.265299479'), label='Debut_2025-10-24T092314.mp4')

Pandas(Index=214, t_start=Timestamp('2025-10-24 10:23:17'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T102317.mp4', video_num_frames=107865, video_fps=29.96027476040869, video_width=640, video_height=480, video_file_size=99691659, cache_file_size=99691659, cache_file_mtime=1761319399.8841715, t_start_dt=Timestamp('2025-10-24 10:23:17'), t_end_dt=Timestamp('2025-10-24 11:23:17.267382813'), label='Debut_2025-10-24T102317.mp4')

Pandas(Index=215, t_start=Timestamp('2025-10-24 11:23:20'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T112320.mp4', video_num_frames=107161, video_fps=29.764750951965254, video_width=640, video_height=480, video_file_size=100577554, cache_file_size=100577554, cache_file_mtime=1761323002.6785672, t_start_dt=Timestamp('2025-10-24 11:23:20'), t_end_dt=Timestamp('2025-10-24 12:23:20.265299479'), label='Debut_2025-10-24T112320.mp4')

Pandas(Index=216, t_start=Timestamp('2025-10-24 12:23:23'), t_duration=3286.0152994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-24T122323.mp4', video_num_frames=98567, video_fps=29.99590416259561, video_width=640, video_height=480, video_file_size=91425948, cache_file_size=91425948, cache_file_mtime=1761326291.201575, t_start_dt=Timestamp('2025-10-24 12:23:23'), t_end_dt=Timestamp('2025-10-24 13:18:09.015299479'), label='Debut_2025-10-24T122323.mp4')

Pandas(Index=217, t_start=Timestamp('2025-10-27 08:24:23'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-27T082423.mp4', video_num_frames=107967, video_fps=29.988623342735067, video_width=640, video_height=480, video_file_size=106520942, cache_file_size=106520942, cache_file_mtime=1761571466.495807, t_start_dt=Timestamp('2025-10-27 08:24:23'), t_end_dt=Timestamp('2025-10-27 09:24:23.265299479'), label='Debut_2025-10-27T082423.mp4')

Pandas(Index=218, t_start=Timestamp('2025-10-27 09:24:27'), t_duration=3600.263346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-27T092427.mp4', video_num_frames=107758, video_fps=29.93058830241458, video_width=640, video_height=480, video_file_size=105809336, cache_file_size=105809336, cache_file_mtime=1761575070.04371, t_start_dt=Timestamp('2025-10-27 09:24:27'), t_end_dt=Timestamp('2025-10-27 10:24:27.263346354'), label='Debut_2025-10-27T092427.mp4')

Pandas(Index=219, t_start=Timestamp('2025-10-27 10:24:31'), t_duration=3600.2693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-27T102431.mp4', video_num_frames=107989, video_fps=29.994700374792924, video_width=640, video_height=480, video_file_size=103668083, cache_file_size=103668083, cache_file_mtime=1761578673.3576548, t_start_dt=Timestamp('2025-10-27 10:24:31'), t_end_dt=Timestamp('2025-10-27 11:24:31.269335937'), label='Debut_2025-10-27T102431.mp4')

Pandas(Index=220, t_start=Timestamp('2025-10-27 11:24:34'), t_duration=3600.263346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-27T112434.mp4', video_num_frames=107873, video_fps=29.96253041023746, video_width=640, video_height=480, video_file_size=105119830, cache_file_size=105119830, cache_file_mtime=1761582276.4270458, t_start_dt=Timestamp('2025-10-27 11:24:34'), t_end_dt=Timestamp('2025-10-27 12:24:34.263346354'), label='Debut_2025-10-27T112434.mp4')

Pandas(Index=221, t_start=Timestamp('2025-10-27 12:24:37'), t_duration=2013.9853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-27T122437.mp4', video_num_frames=59459, video_fps=29.52305484936632, video_width=640, video_height=480, video_file_size=58135299, cache_file_size=58135299, cache_file_mtime=1761584292.6937053, t_start_dt=Timestamp('2025-10-27 12:24:37'), t_end_dt=Timestamp('2025-10-27 12:58:10.985351562'), label='Debut_2025-10-27T122437.mp4')

Pandas(Index=222, t_start=Timestamp('2025-10-27 22:39:16'), t_duration=1.6473307291666666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-27T223916.mp4', video_num_frames=19, video_fps=11.533810220132, video_width=640, video_height=480, video_file_size=44615, cache_file_size=44615, cache_file_mtime=1761619159.1903553, t_start_dt=Timestamp('2025-10-27 22:39:16'), t_end_dt=Timestamp('2025-10-27 22:39:17.647330729'), label='Debut_2025-10-27T223916.mp4')

Pandas(Index=223, t_start=Timestamp('2025-10-27 22:39:22'), t_duration=3600.2393229166664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-27T223922.mp4', video_num_frames=86600, video_fps=24.05395648249368, video_width=640, video_height=480, video_file_size=101458626, cache_file_size=101458626, cache_file_mtime=1761622765.1465642, t_start_dt=Timestamp('2025-10-27 22:39:22'), t_end_dt=Timestamp('2025-10-27 23:39:22.239322917'), label='Debut_2025-10-27T223922.mp4')

Pandas(Index=224, t_start=Timestamp('2025-10-27 23:39:26'), t_duration=3600.213346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-27T233926.mp4', video_num_frames=55715, video_fps=15.475471767922029, video_width=640, video_height=480, video_file_size=95758796, cache_file_size=95758796, cache_file_mtime=1761626367.994401, t_start_dt=Timestamp('2025-10-27 23:39:26'), t_end_dt=Timestamp('2025-10-28 00:39:26.213346354'), label='Debut_2025-10-27T233926.mp4')

Pandas(Index=225, t_start=Timestamp('2025-10-28 00:39:28'), t_duration=1959.2453776041666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-28T003928.mp4', video_num_frames=29383, video_fps=14.997100585701293, video_width=640, video_height=480, video_file_size=52278872, cache_file_size=52278872, cache_file_mtime=1761628329.421321, t_start_dt=Timestamp('2025-10-28 00:39:28'), t_end_dt=Timestamp('2025-10-28 01:12:07.245377604'), label='Debut_2025-10-28T003928.mp4')

Pandas(Index=226, t_start=Timestamp('2025-10-28 15:05:06'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-28T150506.mp4', video_num_frames=107950, video_fps=29.983651514697797, video_width=640, video_height=480, video_file_size=105594669, cache_file_size=105594669, cache_file_mtime=1761681908.4089544, t_start_dt=Timestamp('2025-10-28 15:05:06'), t_end_dt=Timestamp('2025-10-28 16:05:06.295312500'), label='Debut_2025-10-28T150506.mp4')

Pandas(Index=227, t_start=Timestamp('2025-10-28 16:05:09'), t_duration=3600.2902994791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-28T160509.mp4', video_num_frames=105573, video_fps=29.32346872563933, video_width=640, video_height=480, video_file_size=105275798, cache_file_size=105275798, cache_file_mtime=1761685511.8247426, t_start_dt=Timestamp('2025-10-28 16:05:09'), t_end_dt=Timestamp('2025-10-28 17:05:09.290299479'), label='Debut_2025-10-28T160509.mp4')

Pandas(Index=228, t_start=Timestamp('2025-10-28 17:05:12'), t_duration=3600.4453125000005, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-28T170512.mp4', video_num_frames=68480, video_fps=19.019869503989305, video_width=640, video_height=480, video_file_size=100969411, cache_file_size=100969411, cache_file_mtime=1761689116.7144437, t_start_dt=Timestamp('2025-10-28 17:05:12'), t_end_dt=Timestamp('2025-10-28 18:05:12.445312500'), label='Debut_2025-10-28T170512.mp4')

Pandas(Index=229, t_start=Timestamp('2025-10-28 18:05:21'), t_duration=3601.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-28T180521.mp4', video_num_frames=53984, video_fps=14.990278216398318, video_width=640, video_height=480, video_file_size=97998418, cache_file_size=97998418, cache_file_mtime=1761692723.4398372, t_start_dt=Timestamp('2025-10-28 18:05:21'), t_end_dt=Timestamp('2025-10-28 19:05:22.267382812'), label='Debut_2025-10-28T180521.mp4')

Pandas(Index=230, t_start=Timestamp('2025-10-28 19:05:24'), t_duration=3015.713346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-28T190524.mp4', video_num_frames=45261, video_fps=15.008389326763462, video_width=640, video_height=480, video_file_size=82563170, cache_file_size=82563170, cache_file_mtime=1761695741.8269453, t_start_dt=Timestamp('2025-10-28 19:05:24'), t_end_dt=Timestamp('2025-10-28 19:55:39.713346354'), label='Debut_2025-10-28T190524.mp4')

Pandas(Index=231, t_start=Timestamp('2025-10-29 01:44:48'), t_duration=3600.3553385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T014448.mp4', video_num_frames=86366, video_fps=23.98818779786963, video_width=640, video_height=480, video_file_size=103095368, cache_file_size=103095368, cache_file_mtime=1761720290.8867745, t_start_dt=Timestamp('2025-10-29 01:44:48'), t_end_dt=Timestamp('2025-10-29 02:44:48.355338542'), label='Debut_2025-10-29T014448.mp4')

Pandas(Index=232, t_start=Timestamp('2025-10-29 02:44:51'), t_duration=3600.275325520833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T024451.mp4', video_num_frames=86393, video_fps=23.99622034114904, video_width=640, video_height=480, video_file_size=101033856, cache_file_size=101033856, cache_file_mtime=1761723894.12434, t_start_dt=Timestamp('2025-10-29 02:44:51'), t_end_dt=Timestamp('2025-10-29 03:44:51.275325521'), label='Debut_2025-10-29T024451.mp4')

Pandas(Index=233, t_start=Timestamp('2025-10-29 03:44:54'), t_duration=3601.409375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T034454.mp4', video_num_frames=97647, video_fps=27.11355189938661, video_width=640, video_height=480, video_file_size=103419014, cache_file_size=103419014, cache_file_mtime=1761727499.6899252, t_start_dt=Timestamp('2025-10-29 03:44:54'), t_end_dt=Timestamp('2025-10-29 04:44:55.409375'), label='Debut_2025-10-29T034454.mp4')

Pandas(Index=234, t_start=Timestamp('2025-10-29 04:45:01'), t_duration=3600.2833333333338, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T044501.mp4', video_num_frames=86373, video_fps=23.990611849993286, video_width=640, video_height=480, video_file_size=102116936, cache_file_size=102116936, cache_file_mtime=1761731103.663829, t_start_dt=Timestamp('2025-10-29 04:45:01'), t_end_dt=Timestamp('2025-10-29 05:45:01.283333333'), label='Debut_2025-10-29T044501.mp4')

Pandas(Index=235, t_start=Timestamp('2025-10-29 05:45:04'), t_duration=3600.3072916666665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T054504.mp4', video_num_frames=89132, video_fps=24.75677568031664, video_width=640, video_height=480, video_file_size=102611083, cache_file_size=102611083, cache_file_mtime=1761734706.8343875, t_start_dt=Timestamp('2025-10-29 05:45:04'), t_end_dt=Timestamp('2025-10-29 06:45:04.307291667'), label='Debut_2025-10-29T054504.mp4')

Pandas(Index=236, t_start=Timestamp('2025-10-29 06:45:08'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T064508.mp4', video_num_frames=107956, video_fps=29.985817441947834, video_width=640, video_height=480, video_file_size=104567464, cache_file_size=104567464, cache_file_mtime=1761738310.2835202, t_start_dt=Timestamp('2025-10-29 06:45:08'), t_end_dt=Timestamp('2025-10-29 07:45:08.235351562'), label='Debut_2025-10-29T064508.mp4')

Pandas(Index=237, t_start=Timestamp('2025-10-29 07:45:10'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T074510.mp4', video_num_frames=107489, video_fps=29.855855349201605, video_width=640, video_height=480, video_file_size=104739025, cache_file_size=104739025, cache_file_mtime=1761741913.2426414, t_start_dt=Timestamp('2025-10-29 07:45:10'), t_end_dt=Timestamp('2025-10-29 08:45:10.265299479'), label='Debut_2025-10-29T074510.mp4')

Pandas(Index=238, t_start=Timestamp('2025-10-29 08:45:14'), t_duration=2488.9473958333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T084514.mp4', video_num_frames=74581, video_fps=29.964875965178553, video_width=640, video_height=480, video_file_size=72636194, cache_file_size=72636194, cache_file_mtime=1761744414.7211397, t_start_dt=Timestamp('2025-10-29 08:45:14'), t_end_dt=Timestamp('2025-10-29 09:26:42.947395833'), label='Debut_2025-10-29T084514.mp4')

Pandas(Index=239, t_start=Timestamp('2025-10-29 09:35:54'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T093554.mp4', video_num_frames=106336, video_fps=29.535863416260057, video_width=640, video_height=480, video_file_size=105392507, cache_file_size=105392507, cache_file_mtime=1761748556.672851, t_start_dt=Timestamp('2025-10-29 09:35:54'), t_end_dt=Timestamp('2025-10-29 10:35:54.233333333'), label='Debut_2025-10-29T093554.mp4')

Pandas(Index=240, t_start=Timestamp('2025-10-29 10:35:57'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T103557.mp4', video_num_frames=107973, video_fps=29.99002306793708, video_width=640, video_height=480, video_file_size=105158799, cache_file_size=105158799, cache_file_mtime=1761752159.592493, t_start_dt=Timestamp('2025-10-29 10:35:57'), t_end_dt=Timestamp('2025-10-29 11:35:57.297330729'), label='Debut_2025-10-29T103557.mp4')

Pandas(Index=241, t_start=Timestamp('2025-10-29 11:36:00'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T113600.mp4', video_num_frames=107967, video_fps=29.98860598949655, video_width=640, video_height=480, video_file_size=106222080, cache_file_size=106222080, cache_file_mtime=1761755762.5156178, t_start_dt=Timestamp('2025-10-29 11:36:00'), t_end_dt=Timestamp('2025-10-29 12:36:00.267382812'), label='Debut_2025-10-29T113600.mp4')

Pandas(Index=242, t_start=Timestamp('2025-10-29 12:36:03'), t_duration=2962.5553385416665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T123603.mp4', video_num_frames=88723, video_fps=29.948132561693974, video_width=640, video_height=480, video_file_size=90398395, cache_file_size=90398395, cache_file_mtime=1761758727.6280496, t_start_dt=Timestamp('2025-10-29 12:36:03'), t_end_dt=Timestamp('2025-10-29 13:25:25.555338542'), label='Debut_2025-10-29T123603.mp4')

Pandas(Index=243, t_start=Timestamp('2025-10-29 13:25:52'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T132552.mp4', video_num_frames=107944, video_fps=29.982234924636177, video_width=640, video_height=480, video_file_size=109289004, cache_file_size=109289004, cache_file_mtime=1761762354.5602064, t_start_dt=Timestamp('2025-10-29 13:25:52'), t_end_dt=Timestamp('2025-10-29 14:25:52.265299479'), label='Debut_2025-10-29T132552.mp4')

Pandas(Index=244, t_start=Timestamp('2025-10-29 14:25:55'), t_duration=3600.2693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T142555.mp4', video_num_frames=107968, video_fps=29.988867477850913, video_width=640, video_height=480, video_file_size=114057870, cache_file_size=114057870, cache_file_mtime=1761765957.509888, t_start_dt=Timestamp('2025-10-29 14:25:55'), t_end_dt=Timestamp('2025-10-29 15:25:55.269335937'), label='Debut_2025-10-29T142555.mp4')

Pandas(Index=245, t_start=Timestamp('2025-10-29 15:25:58'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T152558.mp4', video_num_frames=107604, video_fps=29.887797439696058, video_width=640, video_height=480, video_file_size=108480980, cache_file_size=108480980, cache_file_mtime=1761769560.3839536, t_start_dt=Timestamp('2025-10-29 15:25:58'), t_end_dt=Timestamp('2025-10-29 16:25:58.265299479'), label='Debut_2025-10-29T152558.mp4')

Pandas(Index=246, t_start=Timestamp('2025-10-29 16:26:01'), t_duration=3600.2693359375003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T162601.mp4', video_num_frames=107931, video_fps=29.978590468953087, video_width=640, video_height=480, video_file_size=108251180, cache_file_size=108251180, cache_file_mtime=1761773163.540982, t_start_dt=Timestamp('2025-10-29 16:26:01'), t_end_dt=Timestamp('2025-10-29 17:26:01.269335938'), label='Debut_2025-10-29T162601.mp4')

Pandas(Index=247, t_start=Timestamp('2025-10-29 17:26:04'), t_duration=3600.2833333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T172604.mp4', video_num_frames=107892, video_fps=29.96764143562775, video_width=640, video_height=480, video_file_size=108565508, cache_file_size=108565508, cache_file_mtime=1761776766.9517124, t_start_dt=Timestamp('2025-10-29 17:26:04'), t_end_dt=Timestamp('2025-10-29 18:26:04.283333333'), label='Debut_2025-10-29T172604.mp4')

Pandas(Index=248, t_start=Timestamp('2025-10-29 18:26:08'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T182608.mp4', video_num_frames=107947, video_fps=29.98306819656212, video_width=640, video_height=480, video_file_size=111794944, cache_file_size=111794944, cache_file_mtime=1761780370.322134, t_start_dt=Timestamp('2025-10-29 18:26:08'), t_end_dt=Timestamp('2025-10-29 19:26:08.265299479'), label='Debut_2025-10-29T182608.mp4')

Pandas(Index=249, t_start=Timestamp('2025-10-29 19:26:10'), t_duration=821.7553385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-29T192610.mp4', video_num_frames=24540, video_fps=29.862903043076138, video_width=640, video_height=480, video_file_size=27085745, cache_file_size=27085745, cache_file_mtime=1761781193.7501442, t_start_dt=Timestamp('2025-10-29 19:26:10'), t_end_dt=Timestamp('2025-10-29 19:39:51.755338542'), label='Debut_2025-10-29T192610.mp4')

Pandas(Index=250, t_start=Timestamp('2025-10-30 15:20:19'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-30T152019.mp4', video_num_frames=107915, video_fps=29.9741626178047, video_width=640, video_height=480, video_file_size=107862070, cache_file_size=107862070, cache_file_mtime=1761855622.1567302, t_start_dt=Timestamp('2025-10-30 15:20:19'), t_end_dt=Timestamp('2025-10-30 16:20:19.267382812'), label='Debut_2025-10-30T152019.mp4')

Pandas(Index=251, t_start=Timestamp('2025-10-30 16:20:22'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-30T162022.mp4', video_num_frames=107736, video_fps=29.92421194615546, video_width=640, video_height=480, video_file_size=106134125, cache_file_size=106134125, cache_file_mtime=1761859225.3631897, t_start_dt=Timestamp('2025-10-30 16:20:22'), t_end_dt=Timestamp('2025-10-30 17:20:22.295312500'), label='Debut_2025-10-30T162022.mp4')

Pandas(Index=252, t_start=Timestamp('2025-10-30 17:20:26'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-30T172026.mp4', video_num_frames=107347, video_fps=29.81614853967049, video_width=640, video_height=480, video_file_size=106216893, cache_file_size=106216893, cache_file_mtime=1761862828.7974296, t_start_dt=Timestamp('2025-10-30 17:20:26'), t_end_dt=Timestamp('2025-10-30 18:20:26.297330729'), label='Debut_2025-10-30T172026.mp4')

Pandas(Index=253, t_start=Timestamp('2025-10-30 18:20:29'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-30T182029.mp4', video_num_frames=107854, video_fps=29.95723676685791, video_width=640, video_height=480, video_file_size=105610384, cache_file_size=105610384, cache_file_mtime=1761866431.5964925, t_start_dt=Timestamp('2025-10-30 18:20:29'), t_end_dt=Timestamp('2025-10-30 19:20:29.265299479'), label='Debut_2025-10-30T182029.mp4')

Pandas(Index=254, t_start=Timestamp('2025-10-30 19:20:33'), t_duration=1753.4673177083334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-30T192033.mp4', video_num_frames=52042, video_fps=29.679481034192, video_width=640, video_height=480, video_file_size=51427676, cache_file_size=51427676, cache_file_mtime=1761868188.263132, t_start_dt=Timestamp('2025-10-30 19:20:33'), t_end_dt=Timestamp('2025-10-30 19:49:46.467317708'), label='Debut_2025-10-30T192033.mp4')

Pandas(Index=255, t_start=Timestamp('2025-10-31 00:21:21'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T002121.mp4', video_num_frames=53997, video_fps=14.99819456146361, video_width=640, video_height=480, video_file_size=100597187, cache_file_size=100597187, cache_file_mtime=1761888084.2174911, t_start_dt=Timestamp('2025-10-31 00:21:21'), t_end_dt=Timestamp('2025-10-31 01:21:21.233333333'), label='Debut_2025-10-31T002121.mp4')

Pandas(Index=256, t_start=Timestamp('2025-10-31 01:21:25'), t_duration=3600.3033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T012125.mp4', video_num_frames=53993, video_fps=14.99679199121298, video_width=640, video_height=480, video_file_size=97400079, cache_file_size=97400079, cache_file_mtime=1761891687.6495714, t_start_dt=Timestamp('2025-10-31 01:21:25'), t_end_dt=Timestamp('2025-10-31 02:21:25.303320313'), label='Debut_2025-10-31T012125.mp4')

Pandas(Index=257, t_start=Timestamp('2025-10-31 02:21:28'), t_duration=3600.3353515625004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T022128.mp4', video_num_frames=53966, video_fps=14.989159267227548, video_width=640, video_height=480, video_file_size=98467371, cache_file_size=98467371, cache_file_mtime=1761895291.5455582, t_start_dt=Timestamp('2025-10-31 02:21:28'), t_end_dt=Timestamp('2025-10-31 03:21:28.335351563'), label='Debut_2025-10-31T022128.mp4')

Pandas(Index=258, t_start=Timestamp('2025-10-31 03:21:45'), t_duration=3600.425390625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T032145.mp4', video_num_frames=56754, video_fps=15.763137363651365, video_width=640, video_height=480, video_file_size=99095828, cache_file_size=99095828, cache_file_mtime=1761898908.5521307, t_start_dt=Timestamp('2025-10-31 03:21:45'), t_end_dt=Timestamp('2025-10-31 04:21:45.425390625'), label='Debut_2025-10-31T032145.mp4')

Pandas(Index=259, t_start=Timestamp('2025-10-31 04:21:49'), t_duration=3600.2753255208336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T042149.mp4', video_num_frames=53997, video_fps=14.99801962845398, video_width=640, video_height=480, video_file_size=99237496, cache_file_size=99237496, cache_file_mtime=1761902511.5817661, t_start_dt=Timestamp('2025-10-31 04:21:49'), t_end_dt=Timestamp('2025-10-31 05:21:49.275325521'), label='Debut_2025-10-31T042149.mp4')

Pandas(Index=260, t_start=Timestamp('2025-10-31 05:21:52'), t_duration=3600.2793619791664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T052152.mp4', video_num_frames=85868, video_fps=23.850371420287825, video_width=640, video_height=480, video_file_size=102394826, cache_file_size=102394826, cache_file_mtime=1761906114.886212, t_start_dt=Timestamp('2025-10-31 05:21:52'), t_end_dt=Timestamp('2025-10-31 06:21:52.279361979'), label='Debut_2025-10-31T052152.mp4')

Pandas(Index=261, t_start=Timestamp('2025-10-31 06:21:55'), t_duration=3600.3072916666665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T062155.mp4', video_num_frames=100988, video_fps=28.049827922674424, video_width=640, video_height=480, video_file_size=103942780, cache_file_size=103942780, cache_file_mtime=1761909718.2898786, t_start_dt=Timestamp('2025-10-31 06:21:55'), t_end_dt=Timestamp('2025-10-31 07:21:55.307291667'), label='Debut_2025-10-31T062155.mp4')

Pandas(Index=262, t_start=Timestamp('2025-10-31 07:21:59'), t_duration=3600.2693359375003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T072159.mp4', video_num_frames=105698, video_fps=29.35835909411942, video_width=640, video_height=480, video_file_size=104072778, cache_file_size=104072778, cache_file_mtime=1761913322.3725574, t_start_dt=Timestamp('2025-10-31 07:21:59'), t_end_dt=Timestamp('2025-10-31 08:21:59.269335938'), label='Debut_2025-10-31T072159.mp4')

Pandas(Index=263, t_start=Timestamp('2025-10-31 09:22:09'), t_duration=2164.719270833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T092209.mp4', video_num_frames=64874, video_fps=29.968782037509193, video_width=640, video_height=480, video_file_size=63421522, cache_file_size=63421522, cache_file_mtime=1761919094.8913326, t_start_dt=Timestamp('2025-10-31 09:22:09'), t_end_dt=Timestamp('2025-10-31 09:58:13.719270833'), label='Debut_2025-10-31T092209.mp4')

Pandas(Index=264, t_start=Timestamp('2025-10-31 17:30:19'), t_duration=3600.249348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T173019.mp4', video_num_frames=107895, video_fps=29.968757589309046, video_width=640, video_height=480, video_file_size=109489344, cache_file_size=109489344, cache_file_mtime=1761949821.8754349, t_start_dt=Timestamp('2025-10-31 17:30:19'), t_end_dt=Timestamp('2025-10-31 18:30:19.249348958'), label='Debut_2025-10-31T173019.mp4')

Pandas(Index=265, t_start=Timestamp('2025-10-31 18:30:22'), t_duration=2150.8212890625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-10-31T183022.mp4', video_num_frames=64455, video_fps=29.967622288179342, video_width=640, video_height=480, video_file_size=65742087, cache_file_size=65742087, cache_file_mtime=1761951974.996058, t_start_dt=Timestamp('2025-10-31 18:30:22'), t_end_dt=Timestamp('2025-10-31 19:06:12.821289062'), label='Debut_2025-10-31T183022.mp4')

Pandas(Index=266, t_start=Timestamp('2025-11-03 06:57:07'), t_duration=3600.263346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T065707.mp4', video_num_frames=107983, video_fps=29.99308373076369, video_width=640, video_height=480, video_file_size=112978125, cache_file_size=112978125, cache_file_mtime=1762174629.8107083, t_start_dt=Timestamp('2025-11-03 06:57:07'), t_end_dt=Timestamp('2025-11-03 07:57:07.263346354'), label='Debut_2025-11-03T065707.mp4')

Pandas(Index=267, t_start=Timestamp('2025-11-03 07:57:10'), t_duration=3600.237369791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T075710.mp4', video_num_frames=105996, video_fps=29.44139208413739, video_width=640, video_height=480, video_file_size=110792590, cache_file_size=110792590, cache_file_mtime=1762178233.153171, t_start_dt=Timestamp('2025-11-03 07:57:10'), t_end_dt=Timestamp('2025-11-03 08:57:10.237369792'), label='Debut_2025-11-03T075710.mp4')

Pandas(Index=268, t_start=Timestamp('2025-11-03 08:57:14'), t_duration=3600.3093098958334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T085714.mp4', video_num_frames=107848, video_fps=29.955204044154844, video_width=640, video_height=480, video_file_size=111592228, cache_file_size=111592228, cache_file_mtime=1762181836.8504336, t_start_dt=Timestamp('2025-11-03 08:57:14'), t_end_dt=Timestamp('2025-11-03 09:57:14.309309896'), label='Debut_2025-11-03T085714.mp4')

Pandas(Index=269, t_start=Timestamp('2025-11-03 09:57:17'), t_duration=3600.301302083333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T095717.mp4', video_num_frames=107819, video_fps=29.947215789303513, video_width=640, video_height=480, video_file_size=110163189, cache_file_size=110163189, cache_file_mtime=1762185439.993889, t_start_dt=Timestamp('2025-11-03 09:57:17'), t_end_dt=Timestamp('2025-11-03 10:57:17.301302083'), label='Debut_2025-11-03T095717.mp4')

Pandas(Index=270, t_start=Timestamp('2025-11-03 10:57:20'), t_duration=3600.255338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T105720.mp4', video_num_frames=107824, video_fps=29.94898690815513, video_width=640, video_height=480, video_file_size=107911959, cache_file_size=107911959, cache_file_mtime=1762189043.1384115, t_start_dt=Timestamp('2025-11-03 10:57:20'), t_end_dt=Timestamp('2025-11-03 11:57:20.255338542'), label='Debut_2025-11-03T105720.mp4')

Pandas(Index=271, t_start=Timestamp('2025-11-03 11:57:24'), t_duration=3600.253385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T115724.mp4', video_num_frames=107624, video_fps=29.893451509814884, video_width=640, video_height=480, video_file_size=110837401, cache_file_size=110837401, cache_file_mtime=1762192646.8022795, t_start_dt=Timestamp('2025-11-03 11:57:24'), t_end_dt=Timestamp('2025-11-03 12:57:24.253385417'), label='Debut_2025-11-03T115724.mp4')

Pandas(Index=272, t_start=Timestamp('2025-11-03 12:57:28'), t_duration=3600.275325520833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T125728.mp4', video_num_frames=107822, video_fps=29.94826513286229, video_width=640, video_height=480, video_file_size=107943513, cache_file_size=107943513, cache_file_mtime=1762196251.6884723, t_start_dt=Timestamp('2025-11-03 12:57:28'), t_end_dt=Timestamp('2025-11-03 13:57:28.275325521'), label='Debut_2025-11-03T125728.mp4')

Pandas(Index=273, t_start=Timestamp('2025-11-03 13:57:32'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T135732.mp4', video_num_frames=105768, video_fps=29.37783502101941, video_width=640, video_height=480, video_file_size=106822196, cache_file_size=106822196, cache_file_mtime=1762199854.941334, t_start_dt=Timestamp('2025-11-03 13:57:32'), t_end_dt=Timestamp('2025-11-03 14:57:32.265299479'), label='Debut_2025-11-03T135732.mp4')

Pandas(Index=274, t_start=Timestamp('2025-11-03 14:57:35'), t_duration=3600.305338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T145735.mp4', video_num_frames=107655, video_fps=29.901630522150807, video_width=640, video_height=480, video_file_size=106685489, cache_file_size=106685489, cache_file_mtime=1762203458.1376207, t_start_dt=Timestamp('2025-11-03 14:57:35'), t_end_dt=Timestamp('2025-11-03 15:57:35.305338542'), label='Debut_2025-11-03T145735.mp4')

Pandas(Index=275, t_start=Timestamp('2025-11-03 15:57:39'), t_duration=3019.3292968749997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T155739.mp4', video_num_frames=90557, video_fps=29.992422520367793, video_width=640, video_height=480, video_file_size=87347211, cache_file_size=87347211, cache_file_mtime=1762206480.287987, t_start_dt=Timestamp('2025-11-03 15:57:39'), t_end_dt=Timestamp('2025-11-03 16:47:58.329296875'), label='Debut_2025-11-03T155739.mp4')

Pandas(Index=276, t_start=Timestamp('2025-11-03 23:46:55'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-03T234655.mp4', video_num_frames=96391, video_fps=26.773304737832635, video_width=640, video_height=480, video_file_size=105516172, cache_file_size=105516172, cache_file_mtime=1762235217.4627643, t_start_dt=Timestamp('2025-11-03 23:46:55'), t_end_dt=Timestamp('2025-11-04 00:46:55.265299479'), label='Debut_2025-11-03T234655.mp4')

Pandas(Index=277, t_start=Timestamp('2025-11-04 00:46:58'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T004658.mp4', video_num_frames=107896, video_fps=29.9689025738211, video_width=640, video_height=480, video_file_size=104862515, cache_file_size=104862515, cache_file_mtime=1762238820.6926546, t_start_dt=Timestamp('2025-11-04 00:46:58'), t_end_dt=Timestamp('2025-11-04 01:46:58.265299479'), label='Debut_2025-11-04T004658.mp4')

Pandas(Index=278, t_start=Timestamp('2025-11-04 01:47:01'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T014701.mp4', video_num_frames=107970, video_fps=29.988939807773555, video_width=640, video_height=480, video_file_size=104885056, cache_file_size=104885056, cache_file_mtime=1762242424.3125086, t_start_dt=Timestamp('2025-11-04 01:47:01'), t_end_dt=Timestamp('2025-11-04 02:47:01.327343750'), label='Debut_2025-11-04T014701.mp4')

Pandas(Index=279, t_start=Timestamp('2025-11-04 02:47:05'), t_duration=3600.3273437499997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T024705.mp4', video_num_frames=107928, video_fps=29.977274201846665, video_width=640, video_height=480, video_file_size=104982311, cache_file_size=104982311, cache_file_mtime=1762246028.0423865, t_start_dt=Timestamp('2025-11-04 02:47:05'), t_end_dt=Timestamp('2025-11-04 03:47:05.327343750'), label='Debut_2025-11-04T024705.mp4')

Pandas(Index=280, t_start=Timestamp('2025-11-04 03:47:09'), t_duration=3600.417317708333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T034709.mp4', video_num_frames=107924, video_fps=29.97541409135696, video_width=640, video_height=480, video_file_size=105228785, cache_file_size=105228785, cache_file_mtime=1762249631.8796692, t_start_dt=Timestamp('2025-11-04 03:47:09'), t_end_dt=Timestamp('2025-11-04 04:47:09.417317708'), label='Debut_2025-11-04T034709.mp4')

Pandas(Index=281, t_start=Timestamp('2025-11-04 04:47:17'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T044717.mp4', video_num_frames=107765, video_fps=29.93225006173987, video_width=640, video_height=480, video_file_size=104347244, cache_file_size=104347244, cache_file_mtime=1762253240.0709455, t_start_dt=Timestamp('2025-11-04 04:47:17'), t_end_dt=Timestamp('2025-11-04 05:47:17.297330729'), label='Debut_2025-11-04T044717.mp4')

Pandas(Index=282, t_start=Timestamp('2025-11-04 05:47:21'), t_duration=3600.329296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T054721.mp4', video_num_frames=107793, video_fps=29.939761369484106, video_width=640, video_height=480, video_file_size=104834964, cache_file_size=104834964, cache_file_mtime=1762256843.5363445, t_start_dt=Timestamp('2025-11-04 05:47:21'), t_end_dt=Timestamp('2025-11-04 06:47:21.329296875'), label='Debut_2025-11-04T054721.mp4')

Pandas(Index=283, t_start=Timestamp('2025-11-04 06:47:24'), t_duration=1118.1572916666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T064724.mp4', video_num_frames=33457, video_fps=29.92155061666749, video_width=640, video_height=480, video_file_size=32634545, cache_file_size=32634545, cache_file_mtime=1762257963.7052116, t_start_dt=Timestamp('2025-11-04 06:47:24'), t_end_dt=Timestamp('2025-11-04 07:06:02.157291667'), label='Debut_2025-11-04T064724.mp4')

Pandas(Index=284, t_start=Timestamp('2025-11-04 15:07:10'), t_duration=3600.3553385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T150710.mp4', video_num_frames=98737, video_fps=27.42423753095262, video_width=640, video_height=480, video_file_size=105281176, cache_file_size=105281176, cache_file_mtime=1762290433.4151232, t_start_dt=Timestamp('2025-11-04 15:07:10'), t_end_dt=Timestamp('2025-11-04 16:07:10.355338542'), label='Debut_2025-11-04T150710.mp4')

Pandas(Index=285, t_start=Timestamp('2025-11-04 16:07:15'), t_duration=3600.363346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T160715.mp4', video_num_frames=103769, video_fps=28.82181324978756, video_width=640, video_height=480, video_file_size=105120710, cache_file_size=105120710, cache_file_mtime=1762294038.1978016, t_start_dt=Timestamp('2025-11-04 16:07:15'), t_end_dt=Timestamp('2025-11-04 17:07:15.363346354'), label='Debut_2025-11-04T160715.mp4')

Pandas(Index=286, t_start=Timestamp('2025-11-04 17:07:19'), t_duration=1199.8173828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-04T170719.mp4', video_num_frames=35903, video_fps=29.923720488062553, video_width=640, video_height=480, video_file_size=35025098, cache_file_size=35025098, cache_file_mtime=1762295240.97667, t_start_dt=Timestamp('2025-11-04 17:07:19'), t_end_dt=Timestamp('2025-11-04 17:27:18.817382812'), label='Debut_2025-11-04T170719.mp4')

Pandas(Index=287, t_start=Timestamp('2025-11-05 06:06:43'), t_duration=3600.263346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T060643.mp4', video_num_frames=107982, video_fps=29.99280597330436, video_width=640, video_height=480, video_file_size=105835139, cache_file_size=105835139, cache_file_mtime=1762344405.6930509, t_start_dt=Timestamp('2025-11-05 06:06:43'), t_end_dt=Timestamp('2025-11-05 07:06:43.263346354'), label='Debut_2025-11-05T060643.mp4')

Pandas(Index=288, t_start=Timestamp('2025-11-05 07:06:46'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T070646.mp4', video_num_frames=107977, video_fps=29.991417186007716, video_width=640, video_height=480, video_file_size=107376799, cache_file_size=107376799, cache_file_mtime=1762348008.562504, t_start_dt=Timestamp('2025-11-05 07:06:46'), t_end_dt=Timestamp('2025-11-05 08:06:46.263346354'), label='Debut_2025-11-05T070646.mp4')

Pandas(Index=289, t_start=Timestamp('2025-11-05 08:06:49'), t_duration=3600.2393229166664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T080649.mp4', video_num_frames=107983, video_fps=29.993283866617954, video_width=640, video_height=480, video_file_size=105338871, cache_file_size=105338871, cache_file_mtime=1762351611.2402902, t_start_dt=Timestamp('2025-11-05 08:06:49'), t_end_dt=Timestamp('2025-11-05 09:06:49.239322917'), label='Debut_2025-11-05T080649.mp4')

Pandas(Index=290, t_start=Timestamp('2025-11-05 09:06:51'), t_duration=3600.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T090651.mp4', video_num_frames=107995, video_fps=29.996633251503997, video_width=640, video_height=480, video_file_size=105090947, cache_file_size=105090947, cache_file_mtime=1762355214.1327248, t_start_dt=Timestamp('2025-11-05 09:06:51'), t_end_dt=Timestamp('2025-11-05 10:06:51.237369792'), label='Debut_2025-11-05T090651.mp4')

Pandas(Index=291, t_start=Timestamp('2025-11-05 10:06:54'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T100654.mp4', video_num_frames=107839, video_fps=29.9530704072282, video_width=640, video_height=480, video_file_size=104986605, cache_file_size=104986605, cache_file_mtime=1762358816.9584777, t_start_dt=Timestamp('2025-11-05 10:06:54'), t_end_dt=Timestamp('2025-11-05 11:06:54.265299479'), label='Debut_2025-11-05T100654.mp4')

Pandas(Index=292, t_start=Timestamp('2025-11-05 11:06:57'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T110657.mp4', video_num_frames=107894, video_fps=29.96809723507924, video_width=640, video_height=480, video_file_size=105148385, cache_file_size=105148385, cache_file_mtime=1762362420.0837238, t_start_dt=Timestamp('2025-11-05 11:06:57'), t_end_dt=Timestamp('2025-11-05 12:06:57.295312500'), label='Debut_2025-11-05T110657.mp4')

Pandas(Index=293, t_start=Timestamp('2025-11-05 12:07:00'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T120700.mp4', video_num_frames=107988, video_fps=29.99418939049938, video_width=640, video_height=480, video_file_size=104495314, cache_file_size=104495314, cache_file_mtime=1762366022.9680932, t_start_dt=Timestamp('2025-11-05 12:07:00'), t_end_dt=Timestamp('2025-11-05 13:07:00.297330729'), label='Debut_2025-11-05T120700.mp4')

Pandas(Index=294, t_start=Timestamp('2025-11-05 13:07:03'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T130703.mp4', video_num_frames=107963, video_fps=29.987512313500478, video_width=640, video_height=480, video_file_size=104380653, cache_file_size=104380653, cache_file_mtime=1762369625.9321651, t_start_dt=Timestamp('2025-11-05 13:07:03'), t_end_dt=Timestamp('2025-11-05 14:07:03.265299479'), label='Debut_2025-11-05T130703.mp4')

Pandas(Index=295, t_start=Timestamp('2025-11-05 14:07:06'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T140706.mp4', video_num_frames=107894, video_fps=29.968347059203808, video_width=640, video_height=480, video_file_size=104072759, cache_file_size=104072759, cache_file_mtime=1762373229.060313, t_start_dt=Timestamp('2025-11-05 14:07:06'), t_end_dt=Timestamp('2025-11-05 15:07:06.265299479'), label='Debut_2025-11-05T140706.mp4')

Pandas(Index=296, t_start=Timestamp('2025-11-05 15:07:09'), t_duration=3435.839322916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-05T150709.mp4', video_num_frames=103030, video_fps=29.986850465562036, video_width=640, video_height=480, video_file_size=100871221, cache_file_size=100871221, cache_file_mtime=1762390693.751381, t_start_dt=Timestamp('2025-11-05 15:07:09'), t_end_dt=Timestamp('2025-11-05 16:04:24.839322917'), label='Debut_2025-11-05T150709.mp4')

Pandas(Index=297, t_start=Timestamp('2025-11-06 08:05:35'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T080535.mp4', video_num_frames=107789, video_fps=29.939198783653794, video_width=640, video_height=480, video_file_size=108866518, cache_file_size=108866518, cache_file_mtime=1762437937.987152, t_start_dt=Timestamp('2025-11-06 08:05:35'), t_end_dt=Timestamp('2025-11-06 09:05:35.263346354'), label='Debut_2025-11-06T080535.mp4')

Pandas(Index=298, t_start=Timestamp('2025-11-06 09:05:38'), t_duration=3600.2412760416664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T090538.mp4', video_num_frames=107891, video_fps=29.96771375240223, video_width=640, video_height=480, video_file_size=108095842, cache_file_size=108095842, cache_file_mtime=1762441541.2702258, t_start_dt=Timestamp('2025-11-06 09:05:38'), t_end_dt=Timestamp('2025-11-06 10:05:38.241276042'), label='Debut_2025-11-06T090538.mp4')

Pandas(Index=299, t_start=Timestamp('2025-11-06 10:05:42'), t_duration=3600.2413411458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T100542.mp4', video_num_frames=107836, video_fps=29.95243645685139, video_width=640, video_height=480, video_file_size=105905379, cache_file_size=105905379, cache_file_mtime=1762445144.2993429, t_start_dt=Timestamp('2025-11-06 10:05:42'), t_end_dt=Timestamp('2025-11-06 11:05:42.241341146'), label='Debut_2025-11-06T100542.mp4')

Pandas(Index=300, t_start=Timestamp('2025-11-06 11:05:45'), t_duration=3600.2833333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T110545.mp4', video_num_frames=107569, video_fps=29.877926274321002, video_width=640, video_height=480, video_file_size=106728754, cache_file_size=106728754, cache_file_mtime=1762448747.5213768, t_start_dt=Timestamp('2025-11-06 11:05:45'), t_end_dt=Timestamp('2025-11-06 12:05:45.283333333'), label='Debut_2025-11-06T110545.mp4')

Pandas(Index=301, t_start=Timestamp('2025-11-06 12:05:48'), t_duration=3600.363346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T120548.mp4', video_num_frames=107813, video_fps=29.945033217043107, video_width=640, video_height=480, video_file_size=107033240, cache_file_size=107033240, cache_file_mtime=1762452351.3072872, t_start_dt=Timestamp('2025-11-06 12:05:48'), t_end_dt=Timestamp('2025-11-06 13:05:48.363346354'), label='Debut_2025-11-06T120548.mp4')

Pandas(Index=302, t_start=Timestamp('2025-11-06 13:05:52'), t_duration=3600.3993489583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T130552.mp4', video_num_frames=105841, video_fps=29.39701675888312, video_width=640, video_height=480, video_file_size=105497354, cache_file_size=105497354, cache_file_mtime=1762455955.1425533, t_start_dt=Timestamp('2025-11-06 13:05:52'), t_end_dt=Timestamp('2025-11-06 14:05:52.399348958'), label='Debut_2025-11-06T130552.mp4')

Pandas(Index=303, t_start=Timestamp('2025-11-06 14:05:56'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T140556.mp4', video_num_frames=107972, video_fps=29.989745313099593, video_width=640, video_height=480, video_file_size=106695714, cache_file_size=106695714, cache_file_mtime=1762459558.5274909, t_start_dt=Timestamp('2025-11-06 14:05:56'), t_end_dt=Timestamp('2025-11-06 15:05:56.297330729'), label='Debut_2025-11-06T140556.mp4')

Pandas(Index=304, t_start=Timestamp('2025-11-06 15:05:59'), t_duration=3600.2253255208334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T150559.mp4', video_num_frames=102821, video_fps=28.55960133137645, video_width=640, video_height=480, video_file_size=105292672, cache_file_size=105292672, cache_file_mtime=1762463161.6506774, t_start_dt=Timestamp('2025-11-06 15:05:59'), t_end_dt=Timestamp('2025-11-06 16:05:59.225325521'), label='Debut_2025-11-06T150559.mp4')

Pandas(Index=305, t_start=Timestamp('2025-11-06 16:06:02'), t_duration=3600.2793619791664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T160602.mp4', video_num_frames=107099, video_fps=29.747413806556644, video_width=640, video_height=480, video_file_size=106579903, cache_file_size=106579903, cache_file_mtime=1762466764.820417, t_start_dt=Timestamp('2025-11-06 16:06:02'), t_end_dt=Timestamp('2025-11-06 17:06:02.279361979'), label='Debut_2025-11-06T160602.mp4')

Pandas(Index=306, t_start=Timestamp('2025-11-06 17:06:05'), t_duration=3600.2473958333335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T170605.mp4', video_num_frames=107805, video_fps=29.943775565191917, video_width=640, video_height=480, video_file_size=105232541, cache_file_size=105232541, cache_file_mtime=1762470367.9785094, t_start_dt=Timestamp('2025-11-06 17:06:05'), t_end_dt=Timestamp('2025-11-06 18:06:05.247395833'), label='Debut_2025-11-06T170605.mp4')

Pandas(Index=307, t_start=Timestamp('2025-11-06 18:06:08'), t_duration=3600.293359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T180608.mp4', video_num_frames=107982, video_fps=29.992555945148133, video_width=640, video_height=480, video_file_size=105838935, cache_file_size=105838935, cache_file_mtime=1762473971.293315, t_start_dt=Timestamp('2025-11-06 18:06:08'), t_end_dt=Timestamp('2025-11-06 19:06:08.293359375'), label='Debut_2025-11-06T180608.mp4')

Pandas(Index=308, t_start=Timestamp('2025-11-06 19:06:13'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T190613.mp4', video_num_frames=106102, video_fps=29.470605962107648, video_width=640, video_height=480, video_file_size=105750600, cache_file_size=105750600, cache_file_mtime=1762477576.4971337, t_start_dt=Timestamp('2025-11-06 19:06:13'), t_end_dt=Timestamp('2025-11-06 20:06:13.265299479'), label='Debut_2025-11-06T190613.mp4')

Pandas(Index=309, t_start=Timestamp('2025-11-06 20:06:17'), t_duration=323.9993489583333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-06T200617.mp4', video_num_frames=9682, video_fps=29.882776095470227, video_width=640, video_height=480, video_file_size=9259649, cache_file_size=9259649, cache_file_mtime=1762477902.6386652, t_start_dt=Timestamp('2025-11-06 20:06:17'), t_end_dt=Timestamp('2025-11-06 20:11:40.999348958'), label='Debut_2025-11-06T200617.mp4')

Pandas(Index=310, t_start=Timestamp('2025-11-10 13:47:05'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T134705.mp4', video_num_frames=107979, video_fps=29.991956430438837, video_width=640, video_height=480, video_file_size=111180982, cache_file_size=111180982, cache_file_mtime=1762804027.9292502, t_start_dt=Timestamp('2025-11-10 13:47:05'), t_end_dt=Timestamp('2025-11-10 14:47:05.265299479'), label='Debut_2025-11-10T134705.mp4')

Pandas(Index=311, t_start=Timestamp('2025-11-10 14:47:08'), t_duration=3600.3013020833337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T144708.mp4', video_num_frames=107938, video_fps=29.98026857850511, video_width=640, video_height=480, video_file_size=110799665, cache_file_size=110799665, cache_file_mtime=1762807630.9260075, t_start_dt=Timestamp('2025-11-10 14:47:08'), t_end_dt=Timestamp('2025-11-10 15:47:08.301302083'), label='Debut_2025-11-10T144708.mp4')

Pandas(Index=312, t_start=Timestamp('2025-11-10 15:47:11'), t_duration=3600.217317708333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T154711.mp4', video_num_frames=101707, video_fps=28.250239089661434, video_width=640, video_height=480, video_file_size=104907020, cache_file_size=104907020, cache_file_mtime=1762811233.7348077, t_start_dt=Timestamp('2025-11-10 15:47:11'), t_end_dt=Timestamp('2025-11-10 16:47:11.217317708'), label='Debut_2025-11-10T154711.mp4')

Pandas(Index=313, t_start=Timestamp('2025-11-10 16:47:14'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T164714.mp4', video_num_frames=100462, video_fps=27.90428685624665, video_width=640, video_height=480, video_file_size=107852300, cache_file_size=107852300, cache_file_mtime=1762814836.4847558, t_start_dt=Timestamp('2025-11-10 16:47:14'), t_end_dt=Timestamp('2025-11-10 17:47:14.235351562'), label='Debut_2025-11-10T164714.mp4')

Pandas(Index=314, t_start=Timestamp('2025-11-10 17:47:17'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T174717.mp4', video_num_frames=104649, video_fps=29.067266381510976, video_width=640, video_height=480, video_file_size=104581570, cache_file_size=104581570, cache_file_mtime=1762818439.4905324, t_start_dt=Timestamp('2025-11-10 17:47:17'), t_end_dt=Timestamp('2025-11-10 18:47:17.235351562'), label='Debut_2025-11-10T174717.mp4')

Pandas(Index=315, t_start=Timestamp('2025-11-10 18:47:20'), t_duration=3600.2693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T184720.mp4', video_num_frames=94689, video_fps=26.300532311520314, video_width=640, video_height=480, video_file_size=98578106, cache_file_size=98578106, cache_file_mtime=1762822042.1334, t_start_dt=Timestamp('2025-11-10 18:47:20'), t_end_dt=Timestamp('2025-11-10 19:47:20.269335937'), label='Debut_2025-11-10T184720.mp4')

Pandas(Index=316, t_start=Timestamp('2025-11-10 19:47:22'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T194722.mp4', video_num_frames=107996, video_fps=29.99692836915643, video_width=640, video_height=480, video_file_size=99918502, cache_file_size=99918502, cache_file_mtime=1762825644.8388958, t_start_dt=Timestamp('2025-11-10 19:47:22'), t_end_dt=Timestamp('2025-11-10 20:47:22.235286458'), label='Debut_2025-11-10T194722.mp4')

Pandas(Index=317, t_start=Timestamp('2025-11-10 20:47:25'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T204725.mp4', video_num_frames=107882, video_fps=29.965263772003905, video_width=640, video_height=480, video_file_size=100351986, cache_file_size=100351986, cache_file_mtime=1762829247.5556939, t_start_dt=Timestamp('2025-11-10 20:47:25'), t_end_dt=Timestamp('2025-11-10 21:47:25.235286458'), label='Debut_2025-11-10T204725.mp4')

Pandas(Index=318, t_start=Timestamp('2025-11-10 21:47:28'), t_duration=3600.2033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T214728.mp4', video_num_frames=97120, video_fps=26.97625421654517, video_width=640, video_height=480, video_file_size=99082857, cache_file_size=99082857, cache_file_mtime=1762832850.236641, t_start_dt=Timestamp('2025-11-10 21:47:28'), t_end_dt=Timestamp('2025-11-10 22:47:28.203320313'), label='Debut_2025-11-10T214728.mp4')

Pandas(Index=319, t_start=Timestamp('2025-11-10 22:47:30'), t_duration=3600.2992838541663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T224730.mp4', video_num_frames=53999, video_fps=14.998475332915485, video_width=640, video_height=480, video_file_size=93661012, cache_file_size=93661012, cache_file_mtime=1762836452.6383822, t_start_dt=Timestamp('2025-11-10 22:47:30'), t_end_dt=Timestamp('2025-11-10 23:47:30.299283854'), label='Debut_2025-11-10T224730.mp4')

Pandas(Index=320, t_start=Timestamp('2025-11-10 23:47:33'), t_duration=638.3652994791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T234733.mp4', video_num_frames=14441, video_fps=22.621843655634493, video_width=640, video_height=480, video_file_size=18341561, cache_file_size=18341561, cache_file_mtime=1762837092.4563923, t_start_dt=Timestamp('2025-11-10 23:47:33'), t_end_dt=Timestamp('2025-11-10 23:58:11.365299479'), label='Debut_2025-11-10T234733.mp4')

Pandas(Index=321, t_start=Timestamp('2025-11-10 23:58:17'), t_duration=3600.209309895833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-10T235817.mp4', video_num_frames=81690, video_fps=22.690347412707396, video_width=640, video_height=480, video_file_size=102936829, cache_file_size=102936829, cache_file_mtime=1762840700.0093248, t_start_dt=Timestamp('2025-11-10 23:58:17'), t_end_dt=Timestamp('2025-11-11 00:58:17.209309896'), label='Debut_2025-11-10T235817.mp4')

Pandas(Index=322, t_start=Timestamp('2025-11-11 00:58:20'), t_duration=3600.329296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T005820.mp4', video_num_frames=102032, video_fps=28.33962995789339, video_width=640, video_height=480, video_file_size=105804923, cache_file_size=105804923, cache_file_mtime=1762844302.850699, t_start_dt=Timestamp('2025-11-11 00:58:20'), t_end_dt=Timestamp('2025-11-11 01:58:20.329296875'), label='Debut_2025-11-11T005820.mp4')

Pandas(Index=323, t_start=Timestamp('2025-11-11 01:58:23'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T015823.mp4', video_num_frames=107624, video_fps=29.893103386918348, video_width=640, video_height=480, video_file_size=105757098, cache_file_size=105757098, cache_file_mtime=1762847905.6844335, t_start_dt=Timestamp('2025-11-11 01:58:23'), t_end_dt=Timestamp('2025-11-11 02:58:23.295312500'), label='Debut_2025-11-11T015823.mp4')

Pandas(Index=324, t_start=Timestamp('2025-11-11 02:58:26'), t_duration=3600.215364583333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T025826.mp4', video_num_frames=94100, video_fps=26.13732526273204, video_width=640, video_height=480, video_file_size=103647319, cache_file_size=103647319, cache_file_mtime=1762851508.7814946, t_start_dt=Timestamp('2025-11-11 02:58:26'), t_end_dt=Timestamp('2025-11-11 03:58:26.215364583'), label='Debut_2025-11-11T025826.mp4')

Pandas(Index=325, t_start=Timestamp('2025-11-11 03:58:29'), t_duration=3600.2193359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T035829.mp4', video_num_frames=71309, video_fps=19.80684879062544, video_width=640, video_height=480, video_file_size=100272809, cache_file_size=100272809, cache_file_mtime=1762855111.445317, t_start_dt=Timestamp('2025-11-11 03:58:29'), t_end_dt=Timestamp('2025-11-11 04:58:29.219335938'), label='Debut_2025-11-11T035829.mp4')

Pandas(Index=326, t_start=Timestamp('2025-11-11 04:58:31'), t_duration=3600.193359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T045831.mp4', video_num_frames=54000, video_fps=14.999194379208149, video_width=640, video_height=480, video_file_size=97451321, cache_file_size=97451321, cache_file_mtime=1762858713.818148, t_start_dt=Timestamp('2025-11-11 04:58:31'), t_end_dt=Timestamp('2025-11-11 05:58:31.193359375'), label='Debut_2025-11-11T045831.mp4')

Pandas(Index=327, t_start=Timestamp('2025-11-11 05:58:34'), t_duration=3600.2073567708335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T055834.mp4', video_num_frames=53997, video_fps=14.99830277788, video_width=640, video_height=480, video_file_size=94037360, cache_file_size=94037360, cache_file_mtime=1762862316.1846592, t_start_dt=Timestamp('2025-11-11 05:58:34'), t_end_dt=Timestamp('2025-11-11 06:58:34.207356771'), label='Debut_2025-11-11T055834.mp4')

Pandas(Index=328, t_start=Timestamp('2025-11-11 06:58:36'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T065836.mp4', video_num_frames=88373, video_fps=24.546451264560364, video_width=640, video_height=480, video_file_size=103493263, cache_file_size=103493263, cache_file_mtime=1762865918.7956471, t_start_dt=Timestamp('2025-11-11 06:58:36'), t_end_dt=Timestamp('2025-11-11 07:58:36.235286458'), label='Debut_2025-11-11T065836.mp4')

Pandas(Index=329, t_start=Timestamp('2025-11-11 07:58:39'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T075839.mp4', video_num_frames=107992, video_fps=29.99583360337756, video_width=640, video_height=480, video_file_size=105469563, cache_file_size=105469563, cache_file_mtime=1762869521.5104113, t_start_dt=Timestamp('2025-11-11 07:58:39'), t_end_dt=Timestamp('2025-11-11 08:58:39.233333333'), label='Debut_2025-11-11T075839.mp4')

Pandas(Index=330, t_start=Timestamp('2025-11-11 08:58:42'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T085842.mp4', video_num_frames=107990, video_fps=29.99526181141156, video_width=640, video_height=480, video_file_size=105915263, cache_file_size=105915263, cache_file_mtime=1762873124.2341864, t_start_dt=Timestamp('2025-11-11 08:58:42'), t_end_dt=Timestamp('2025-11-11 09:58:42.235286458'), label='Debut_2025-11-11T085842.mp4')

Pandas(Index=331, t_start=Timestamp('2025-11-11 09:58:44'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T095844.mp4', video_num_frames=107934, video_fps=29.979190629275102, video_width=640, video_height=480, video_file_size=105921039, cache_file_size=105921039, cache_file_mtime=1762876727.0074599, t_start_dt=Timestamp('2025-11-11 09:58:44'), t_end_dt=Timestamp('2025-11-11 10:58:44.297330729'), label='Debut_2025-11-11T095844.mp4')

Pandas(Index=332, t_start=Timestamp('2025-11-11 10:58:47'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T105847.mp4', video_num_frames=107986, video_fps=29.993883375307032, video_width=640, video_height=480, video_file_size=106795307, cache_file_size=106795307, cache_file_mtime=1762880329.947696, t_start_dt=Timestamp('2025-11-11 10:58:47'), t_end_dt=Timestamp('2025-11-11 11:58:47.267382812'), label='Debut_2025-11-11T105847.mp4')

Pandas(Index=333, t_start=Timestamp('2025-11-11 11:58:50'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T115850.mp4', video_num_frames=107635, video_fps=29.896390616387052, video_width=640, video_height=480, video_file_size=106960313, cache_file_size=106960313, cache_file_mtime=1762883932.992294, t_start_dt=Timestamp('2025-11-11 11:58:50'), t_end_dt=Timestamp('2025-11-11 12:58:50.267382813'), label='Debut_2025-11-11T115850.mp4')

Pandas(Index=334, t_start=Timestamp('2025-11-11 12:58:54'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T125854.mp4', video_num_frames=107706, video_fps=29.915879296359805, video_width=640, video_height=480, video_file_size=105671712, cache_file_size=105671712, cache_file_mtime=1762887536.452263, t_start_dt=Timestamp('2025-11-11 12:58:54'), t_end_dt=Timestamp('2025-11-11 13:58:54.295312500'), label='Debut_2025-11-11T125854.mp4')

Pandas(Index=335, t_start=Timestamp('2025-11-11 13:58:59'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T135859.mp4', video_num_frames=107889, video_fps=29.9667084601133, video_width=640, video_height=480, video_file_size=105386586, cache_file_size=105386586, cache_file_mtime=1762891142.0717824, t_start_dt=Timestamp('2025-11-11 13:58:59'), t_end_dt=Timestamp('2025-11-11 14:58:59.295312500'), label='Debut_2025-11-11T135859.mp4')

Pandas(Index=336, t_start=Timestamp('2025-11-11 14:59:05'), t_duration=3600.4473307291664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T145905.mp4', video_num_frames=107872, video_fps=29.960721569048378, video_width=640, video_height=480, video_file_size=106549029, cache_file_size=106549029, cache_file_mtime=1762894749.9259183, t_start_dt=Timestamp('2025-11-11 14:59:05'), t_end_dt=Timestamp('2025-11-11 15:59:05.447330729'), label='Debut_2025-11-11T145905.mp4')

Pandas(Index=337, t_start=Timestamp('2025-11-11 15:59:17'), t_duration=3602.6053385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T155917.mp4', video_num_frames=107741, video_fps=29.906412131064435, video_width=640, video_height=480, video_file_size=106498145, cache_file_size=106498145, cache_file_mtime=1762898360.0597718, t_start_dt=Timestamp('2025-11-11 15:59:17'), t_end_dt=Timestamp('2025-11-11 16:59:19.605338542'), label='Debut_2025-11-11T155917.mp4')

Pandas(Index=338, t_start=Timestamp('2025-11-11 16:59:22'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T165922.mp4', video_num_frames=107105, video_fps=29.749196542681, video_width=640, video_height=480, video_file_size=110045024, cache_file_size=110045024, cache_file_mtime=1762901965.4279344, t_start_dt=Timestamp('2025-11-11 16:59:22'), t_end_dt=Timestamp('2025-11-11 17:59:22.265299479'), label='Debut_2025-11-11T165922.mp4')

Pandas(Index=339, t_start=Timestamp('2025-11-11 17:59:29'), t_duration=3600.2993489583337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T175929.mp4', video_num_frames=107692, video_fps=29.91195719077034, video_width=640, video_height=480, video_file_size=110014973, cache_file_size=110014973, cache_file_mtime=1762905571.6662133, t_start_dt=Timestamp('2025-11-11 17:59:29'), t_end_dt=Timestamp('2025-11-11 18:59:29.299348958'), label='Debut_2025-11-11T175929.mp4')

Pandas(Index=340, t_start=Timestamp('2025-11-11 18:59:34'), t_duration=1773.8673177083335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-11T185934.mp4', video_num_frames=53113, video_fps=29.941923767227927, video_width=640, video_height=480, video_file_size=51873050, cache_file_size=51873050, cache_file_mtime=1762907350.0678222, t_start_dt=Timestamp('2025-11-11 18:59:34'), t_end_dt=Timestamp('2025-11-11 19:29:07.867317708'), label='Debut_2025-11-11T185934.mp4')

Pandas(Index=341, t_start=Timestamp('2025-11-12 12:11:41'), t_duration=3600.3073567708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-12T121141.mp4', video_num_frames=98417, video_fps=27.335721716901304, video_width=640, video_height=480, video_file_size=104459467, cache_file_size=104459467, cache_file_mtime=1762971104.1082869, t_start_dt=Timestamp('2025-11-12 12:11:41'), t_end_dt=Timestamp('2025-11-12 13:11:41.307356771'), label='Debut_2025-11-12T121141.mp4')

Pandas(Index=342, t_start=Timestamp('2025-11-12 13:11:45'), t_duration=3600.2833333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-12T131145.mp4', video_num_frames=106777, video_fps=29.657943587773186, video_width=640, video_height=480, video_file_size=105296076, cache_file_size=105296076, cache_file_mtime=1762974707.6199398, t_start_dt=Timestamp('2025-11-12 13:11:45'), t_end_dt=Timestamp('2025-11-12 14:11:45.283333333'), label='Debut_2025-11-12T131145.mp4')

Pandas(Index=343, t_start=Timestamp('2025-11-12 14:11:49'), t_duration=3600.447330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-12T141149.mp4', video_num_frames=107992, video_fps=29.99405076094512, video_width=640, video_height=480, video_file_size=104875032, cache_file_size=104875032, cache_file_mtime=1762978312.3603823, t_start_dt=Timestamp('2025-11-12 14:11:49'), t_end_dt=Timestamp('2025-11-12 15:11:49.447330729'), label='Debut_2025-11-12T141149.mp4')

Pandas(Index=344, t_start=Timestamp('2025-11-12 15:11:53'), t_duration=3600.342317708333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-12T151153.mp4', video_num_frames=107175, video_fps=29.768002745977316, video_width=640, video_height=480, video_file_size=105542557, cache_file_size=105542557, cache_file_mtime=1762981916.22152, t_start_dt=Timestamp('2025-11-12 15:11:53'), t_end_dt=Timestamp('2025-11-12 16:11:53.342317708'), label='Debut_2025-11-12T151153.mp4')

Pandas(Index=345, t_start=Timestamp('2025-11-12 16:11:57'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-12T161157.mp4', video_num_frames=107879, video_fps=29.96366432826529, video_width=640, video_height=480, video_file_size=105621750, cache_file_size=105621750, cache_file_mtime=1762985519.7146454, t_start_dt=Timestamp('2025-11-12 16:11:57'), t_end_dt=Timestamp('2025-11-12 17:11:57.327343750'), label='Debut_2025-11-12T161157.mp4')

Pandas(Index=346, t_start=Timestamp('2025-11-12 17:12:00'), t_duration=3600.2393229166664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-12T171200.mp4', video_num_frames=102905, video_fps=28.582822076570576, video_width=640, video_height=480, video_file_size=104519648, cache_file_size=104519648, cache_file_mtime=1762989123.1351688, t_start_dt=Timestamp('2025-11-12 17:12:00'), t_end_dt=Timestamp('2025-11-12 18:12:00.239322917'), label='Debut_2025-11-12T171200.mp4')

Pandas(Index=347, t_start=Timestamp('2025-11-12 18:12:03'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-12T181203.mp4', video_num_frames=105766, video_fps=29.377262506924264, video_width=640, video_height=480, video_file_size=105457497, cache_file_size=105457497, cache_file_mtime=1762992726.1867101, t_start_dt=Timestamp('2025-11-12 18:12:03'), t_end_dt=Timestamp('2025-11-12 19:12:03.267382812'), label='Debut_2025-11-12T181203.mp4')

Pandas(Index=348, t_start=Timestamp('2025-11-12 19:12:06'), t_duration=1214.7573567708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-12T191206.mp4', video_num_frames=36430, video_fps=29.989528194207594, video_width=640, video_height=480, video_file_size=35550875, cache_file_size=35550875, cache_file_mtime=1762993942.8112483, t_start_dt=Timestamp('2025-11-12 19:12:06'), t_end_dt=Timestamp('2025-11-12 19:32:20.757356771'), label='Debut_2025-11-12T191206.mp4')

Pandas(Index=349, t_start=Timestamp('2025-11-13 05:36:19'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T053619.mp4', video_num_frames=107994, video_fps=29.996139062816315, video_width=640, video_height=480, video_file_size=106066749, cache_file_size=106066749, cache_file_mtime=1763033781.5971882, t_start_dt=Timestamp('2025-11-13 05:36:19'), t_end_dt=Timestamp('2025-11-13 06:36:19.263346354'), label='Debut_2025-11-13T053619.mp4')

Pandas(Index=350, t_start=Timestamp('2025-11-13 06:36:22'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T063622.mp4', video_num_frames=107973, video_fps=29.990539897801096, video_width=640, video_height=480, video_file_size=105443085, cache_file_size=105443085, cache_file_mtime=1763037384.0908115, t_start_dt=Timestamp('2025-11-13 06:36:22'), t_end_dt=Timestamp('2025-11-13 07:36:22.235286458'), label='Debut_2025-11-13T063622.mp4')

Pandas(Index=351, t_start=Timestamp('2025-11-13 07:36:24'), t_duration=1159.7633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T073624.mp4', video_num_frames=34439, video_fps=29.69485120241339, video_width=640, video_height=480, video_file_size=35723838, cache_file_size=35723838, cache_file_mtime=1763038545.23939, t_start_dt=Timestamp('2025-11-13 07:36:24'), t_end_dt=Timestamp('2025-11-13 07:55:43.763346354'), label='Debut_2025-11-13T073624.mp4')

Pandas(Index=352, t_start=Timestamp('2025-11-13 08:24:43'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T082443.mp4', video_num_frames=107376, video_fps=29.824717402186568, video_width=640, video_height=480, video_file_size=106623780, cache_file_size=106623780, cache_file_mtime=1763043885.8029044, t_start_dt=Timestamp('2025-11-13 08:24:43'), t_end_dt=Timestamp('2025-11-13 09:24:43.235286458'), label='Debut_2025-11-13T082443.mp4')

Pandas(Index=353, t_start=Timestamp('2025-11-13 09:24:46'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T092446.mp4', video_num_frames=107935, video_fps=29.979235274908334, video_width=640, video_height=480, video_file_size=106503412, cache_file_size=106503412, cache_file_mtime=1763047488.7644536, t_start_dt=Timestamp('2025-11-13 09:24:46'), t_end_dt=Timestamp('2025-11-13 10:24:46.325325521'), label='Debut_2025-11-13T092446.mp4')

Pandas(Index=354, t_start=Timestamp('2025-11-13 10:24:49'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T102449.mp4', video_num_frames=107848, video_fps=29.955552888894047, video_width=640, video_height=480, video_file_size=105865475, cache_file_size=105865475, cache_file_mtime=1763051091.5818346, t_start_dt=Timestamp('2025-11-13 10:24:49'), t_end_dt=Timestamp('2025-11-13 11:24:49.267382813'), label='Debut_2025-11-13T102449.mp4')

Pandas(Index=355, t_start=Timestamp('2025-11-13 11:24:52'), t_duration=3603.7673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T112452.mp4', video_num_frames=95929, video_fps=26.619087696257967, video_width=640, video_height=480, video_file_size=104330828, cache_file_size=104330828, cache_file_mtime=1763054705.0361133, t_start_dt=Timestamp('2025-11-13 11:24:52'), t_end_dt=Timestamp('2025-11-13 12:24:55.767382813'), label='Debut_2025-11-13T112452.mp4')

Pandas(Index=356, t_start=Timestamp('2025-11-13 12:25:05'), t_duration=3600.4152994791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T122505.mp4', video_num_frames=101539, video_fps=28.202024364991605, video_width=640, video_height=480, video_file_size=105905862, cache_file_size=105905862, cache_file_mtime=1763058308.4574087, t_start_dt=Timestamp('2025-11-13 12:25:05'), t_end_dt=Timestamp('2025-11-13 13:25:05.415299479'), label='Debut_2025-11-13T122505.mp4')

Pandas(Index=357, t_start=Timestamp('2025-11-13 13:25:09'), t_duration=3600.2693359375003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T132509.mp4', video_num_frames=107982, video_fps=29.992756075812252, video_width=640, video_height=480, video_file_size=106707882, cache_file_size=106707882, cache_file_mtime=1763061911.3861113, t_start_dt=Timestamp('2025-11-13 13:25:09'), t_end_dt=Timestamp('2025-11-13 14:25:09.269335938'), label='Debut_2025-11-13T132509.mp4')

Pandas(Index=358, t_start=Timestamp('2025-11-13 14:25:11'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T142511.mp4', video_num_frames=107665, video_fps=29.904491341639076, video_width=640, video_height=480, video_file_size=106295451, cache_file_size=106295451, cache_file_mtime=1763065514.5810764, t_start_dt=Timestamp('2025-11-13 14:25:11'), t_end_dt=Timestamp('2025-11-13 15:25:11.295312500'), label='Debut_2025-11-13T142511.mp4')

Pandas(Index=359, t_start=Timestamp('2025-11-13 15:25:15'), t_duration=3600.3573567708336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T152515.mp4', video_num_frames=107599, video_fps=29.885644489608588, video_width=640, video_height=480, video_file_size=107468953, cache_file_size=107468953, cache_file_mtime=1763069118.2922094, t_start_dt=Timestamp('2025-11-13 15:25:15'), t_end_dt=Timestamp('2025-11-13 16:25:15.357356771'), label='Debut_2025-11-13T152515.mp4')

Pandas(Index=360, t_start=Timestamp('2025-11-13 16:25:19'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T162519.mp4', video_num_frames=107875, video_fps=29.96281989020866, video_width=640, video_height=480, video_file_size=103509400, cache_file_size=103509400, cache_file_mtime=1763072721.3044894, t_start_dt=Timestamp('2025-11-13 16:25:19'), t_end_dt=Timestamp('2025-11-13 17:25:19.295312500'), label='Debut_2025-11-13T162519.mp4')

Pandas(Index=361, t_start=Timestamp('2025-11-13 17:25:22'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T172522.mp4', video_num_frames=107824, video_fps=29.948886717343964, video_width=640, video_height=480, video_file_size=106558075, cache_file_size=106558075, cache_file_mtime=1763076324.3869452, t_start_dt=Timestamp('2025-11-13 17:25:22'), t_end_dt=Timestamp('2025-11-13 18:25:22.267382813'), label='Debut_2025-11-13T172522.mp4')

Pandas(Index=362, t_start=Timestamp('2025-11-13 18:25:25'), t_duration=3600.223307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T182525.mp4', video_num_frames=91473, video_fps=25.40759063881852, video_width=640, video_height=480, video_file_size=103975303, cache_file_size=103975303, cache_file_mtime=1763079927.333995, t_start_dt=Timestamp('2025-11-13 18:25:25'), t_end_dt=Timestamp('2025-11-13 19:25:25.223307292'), label='Debut_2025-11-13T182525.mp4')

Pandas(Index=363, t_start=Timestamp('2025-11-13 19:25:27'), t_duration=3600.239322916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T192527.mp4', video_num_frames=53994, video_fps=14.997336331590803, video_width=640, video_height=480, video_file_size=95343331, cache_file_size=95343331, cache_file_mtime=1763083529.845592, t_start_dt=Timestamp('2025-11-13 19:25:27'), t_end_dt=Timestamp('2025-11-13 20:25:27.239322917'), label='Debut_2025-11-13T192527.mp4')

Pandas(Index=364, t_start=Timestamp('2025-11-13 20:25:30'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T202530.mp4', video_num_frames=53950, video_fps=14.985014930819677, video_width=640, video_height=480, video_file_size=94785577, cache_file_size=94785577, cache_file_mtime=1763087132.2034657, t_start_dt=Timestamp('2025-11-13 20:25:30'), t_end_dt=Timestamp('2025-11-13 21:25:30.263346354'), label='Debut_2025-11-13T202530.mp4')

Pandas(Index=365, t_start=Timestamp('2025-11-13 21:25:32'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T212532.mp4', video_num_frames=53992, video_fps=14.996805762589462, video_width=640, video_height=480, video_file_size=94518666, cache_file_size=94518666, cache_file_mtime=1763090734.4113326, t_start_dt=Timestamp('2025-11-13 21:25:32'), t_end_dt=Timestamp('2025-11-13 22:25:32.233333333'), label='Debut_2025-11-13T212532.mp4')

Pandas(Index=366, t_start=Timestamp('2025-11-13 22:25:34'), t_duration=3600.2193359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T222534.mp4', video_num_frames=54000, video_fps=14.999086155937873, video_width=640, video_height=480, video_file_size=94488025, cache_file_size=94488025, cache_file_mtime=1763094336.960762, t_start_dt=Timestamp('2025-11-13 22:25:34'), t_end_dt=Timestamp('2025-11-13 23:25:34.219335938'), label='Debut_2025-11-13T222534.mp4')

Pandas(Index=367, t_start=Timestamp('2025-11-13 23:25:37'), t_duration=3600.1873697916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-13T232537.mp4', video_num_frames=54000, video_fps=14.999219333166216, video_width=640, video_height=480, video_file_size=93908150, cache_file_size=93908150, cache_file_mtime=1763097939.3320856, t_start_dt=Timestamp('2025-11-13 23:25:37'), t_end_dt=Timestamp('2025-11-14 00:25:37.187369792'), label='Debut_2025-11-13T232537.mp4')

Pandas(Index=368, t_start=Timestamp('2025-11-14 00:25:39'), t_duration=3600.247395833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T002539.mp4', video_num_frames=80242, video_fps=22.28791279534465, video_width=640, video_height=480, video_file_size=102638736, cache_file_size=102638736, cache_file_mtime=1763101541.8350494, t_start_dt=Timestamp('2025-11-14 00:25:39'), t_end_dt=Timestamp('2025-11-14 01:25:39.247395833'), label='Debut_2025-11-14T002539.mp4')

Pandas(Index=369, t_start=Timestamp('2025-11-14 01:25:42'), t_duration=3600.239322916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T012542.mp4', video_num_frames=76246, video_fps=21.178036558478208, video_width=640, video_height=480, video_file_size=102924885, cache_file_size=102924885, cache_file_mtime=1763105144.4028232, t_start_dt=Timestamp('2025-11-14 01:25:42'), t_end_dt=Timestamp('2025-11-14 02:25:42.239322917'), label='Debut_2025-11-14T012542.mp4')

Pandas(Index=370, t_start=Timestamp('2025-11-14 02:25:44'), t_duration=3600.2233723958334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T022544.mp4', video_num_frames=53853, video_fps=14.958238539561103, video_width=640, video_height=480, video_file_size=99374787, cache_file_size=99374787, cache_file_mtime=1763108746.881673, t_start_dt=Timestamp('2025-11-14 02:25:44'), t_end_dt=Timestamp('2025-11-14 03:25:44.223372396'), label='Debut_2025-11-14T022544.mp4')

Pandas(Index=371, t_start=Timestamp('2025-11-14 03:25:47'), t_duration=1206.1253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T032547.mp4', video_num_frames=18051, video_fps=14.966106438570264, video_width=640, video_height=480, video_file_size=33580763, cache_file_size=33580763, cache_file_mtime=1763109954.8123097, t_start_dt=Timestamp('2025-11-14 03:25:47'), t_end_dt=Timestamp('2025-11-14 03:45:53.125325521'), label='Debut_2025-11-14T032547.mp4')

Pandas(Index=372, t_start=Timestamp('2025-11-14 08:11:13'), t_duration=3600.429296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T081113.mp4', video_num_frames=107341, video_fps=29.8133892236592, video_width=640, video_height=480, video_file_size=109957071, cache_file_size=109957071, cache_file_mtime=1763129476.162786, t_start_dt=Timestamp('2025-11-14 08:11:13'), t_end_dt=Timestamp('2025-11-14 09:11:13.429296875'), label='Debut_2025-11-14T081113.mp4')

Pandas(Index=373, t_start=Timestamp('2025-11-14 09:11:16'), t_duration=3600.2453125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T091116.mp4', video_num_frames=107970, video_fps=29.9896231029396, video_width=640, video_height=480, video_file_size=109348900, cache_file_size=109348900, cache_file_mtime=1763133079.372221, t_start_dt=Timestamp('2025-11-14 09:11:16'), t_end_dt=Timestamp('2025-11-14 10:11:16.245312500'), label='Debut_2025-11-14T091116.mp4')

Pandas(Index=374, t_start=Timestamp('2025-11-14 10:11:20'), t_duration=3600.27734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T101120.mp4', video_num_frames=106688, video_fps=29.633272610291524, video_width=640, video_height=480, video_file_size=109997601, cache_file_size=109997601, cache_file_mtime=1763136682.3413846, t_start_dt=Timestamp('2025-11-14 10:11:20'), t_end_dt=Timestamp('2025-11-14 11:11:20.277343750'), label='Debut_2025-11-14T101120.mp4')

Pandas(Index=375, t_start=Timestamp('2025-11-14 11:11:22'), t_duration=3600.2453124999997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T111122.mp4', video_num_frames=106593, video_fps=29.607149165616754, video_width=640, video_height=480, video_file_size=111913465, cache_file_size=111913465, cache_file_mtime=1763140285.141561, t_start_dt=Timestamp('2025-11-14 11:11:22'), t_end_dt=Timestamp('2025-11-14 12:11:22.245312500'), label='Debut_2025-11-14T111122.mp4')

Pandas(Index=376, t_start=Timestamp('2025-11-14 12:11:25'), t_duration=3600.2833333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T121125.mp4', video_num_frames=107945, video_fps=29.982362499247746, video_width=640, video_height=480, video_file_size=110138589, cache_file_size=110138589, cache_file_mtime=1763143888.4009655, t_start_dt=Timestamp('2025-11-14 12:11:25'), t_end_dt=Timestamp('2025-11-14 13:11:25.283333333'), label='Debut_2025-11-14T121125.mp4')

Pandas(Index=377, t_start=Timestamp('2025-11-14 13:11:29'), t_duration=3600.2833333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T131129.mp4', video_num_frames=107764, video_fps=29.932088678205883, video_width=640, video_height=480, video_file_size=107624237, cache_file_size=107624237, cache_file_mtime=1763147493.5512092, t_start_dt=Timestamp('2025-11-14 13:11:29'), t_end_dt=Timestamp('2025-11-14 14:11:29.283333333'), label='Debut_2025-11-14T131129.mp4')

Pandas(Index=378, t_start=Timestamp('2025-11-14 14:11:34'), t_duration=1047.8473307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T141134.mp4', video_num_frames=31008, video_fps=29.59209714111924, video_width=640, video_height=480, video_file_size=33279411, cache_file_size=33279411, cache_file_mtime=1763148543.3043447, t_start_dt=Timestamp('2025-11-14 14:11:34'), t_end_dt=Timestamp('2025-11-14 14:29:01.847330729'), label='Debut_2025-11-14T141134.mp4')

Pandas(Index=379, t_start=Timestamp('2025-11-14 14:29:53'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T142953.mp4', video_num_frames=107419, video_fps=29.836428523701926, video_width=640, video_height=480, video_file_size=114096738, cache_file_size=114096738, cache_file_mtime=1763152195.8686912, t_start_dt=Timestamp('2025-11-14 14:29:53'), t_end_dt=Timestamp('2025-11-14 15:29:53.263346354'), label='Debut_2025-11-14T142953.mp4')

Pandas(Index=380, t_start=Timestamp('2025-11-14 15:29:56'), t_duration=3600.2873046874997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T152956.mp4', video_num_frames=106455, video_fps=29.568473566372823, video_width=640, video_height=480, video_file_size=116483023, cache_file_size=116483023, cache_file_mtime=1763155799.2335727, t_start_dt=Timestamp('2025-11-14 15:29:56'), t_end_dt=Timestamp('2025-11-14 16:29:56.287304687'), label='Debut_2025-11-14T152956.mp4')

Pandas(Index=381, t_start=Timestamp('2025-11-14 16:30:00'), t_duration=3600.2833333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T163000.mp4', video_num_frames=107361, video_fps=29.820153043510466, video_width=640, video_height=480, video_file_size=114345467, cache_file_size=114345467, cache_file_mtime=1763159402.568432, t_start_dt=Timestamp('2025-11-14 16:30:00'), t_end_dt=Timestamp('2025-11-14 17:30:00.283333333'), label='Debut_2025-11-14T163000.mp4')

Pandas(Index=382, t_start=Timestamp('2025-11-14 17:30:03'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T173003.mp4', video_num_frames=107018, video_fps=29.725031656828676, video_width=640, video_height=480, video_file_size=114550595, cache_file_size=114550595, cache_file_mtime=1763163005.8244424, t_start_dt=Timestamp('2025-11-14 17:30:03'), t_end_dt=Timestamp('2025-11-14 18:30:03.265299479'), label='Debut_2025-11-14T173003.mp4')

Pandas(Index=383, t_start=Timestamp('2025-11-14 18:30:06'), t_duration=3600.2673177083334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T183006.mp4', video_num_frames=85980, video_fps=23.881560010029638, video_width=640, video_height=480, video_file_size=113160657, cache_file_size=113160657, cache_file_mtime=1763166609.232003, t_start_dt=Timestamp('2025-11-14 18:30:06'), t_end_dt=Timestamp('2025-11-14 19:30:06.267317708'), label='Debut_2025-11-14T183006.mp4')

Pandas(Index=384, t_start=Timestamp('2025-11-14 19:30:10'), t_duration=663.0533854166666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-14T193010.mp4', video_num_frames=9941, video_fps=14.992759585644853, video_width=640, video_height=480, video_file_size=19437571, cache_file_size=19437571, cache_file_mtime=1763167274.4211679, t_start_dt=Timestamp('2025-11-14 19:30:10'), t_end_dt=Timestamp('2025-11-14 19:41:13.053385417'), label='Debut_2025-11-14T193010.mp4')

Pandas(Index=385, t_start=Timestamp('2025-11-17 08:57:23'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T085723.mp4', video_num_frames=107902, video_fps=29.970569117672987, video_width=640, video_height=480, video_file_size=118511392, cache_file_size=118511392, cache_file_mtime=1763391445.4140959, t_start_dt=Timestamp('2025-11-17 08:57:23'), t_end_dt=Timestamp('2025-11-17 09:57:23.265299479'), label='Debut_2025-11-17T085723.mp4')

Pandas(Index=386, t_start=Timestamp('2025-11-17 09:57:25'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T095725.mp4', video_num_frames=107596, video_fps=29.885824519498453, video_width=640, video_height=480, video_file_size=116762197, cache_file_size=116762197, cache_file_mtime=1763395048.3141005, t_start_dt=Timestamp('2025-11-17 09:57:25'), t_end_dt=Timestamp('2025-11-17 10:57:25.235286458'), label='Debut_2025-11-17T095725.mp4')

Pandas(Index=387, t_start=Timestamp('2025-11-17 10:57:28'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T105728.mp4', video_num_frames=107991, video_fps=29.995539028617106, video_width=640, video_height=480, video_file_size=118357141, cache_file_size=118357141, cache_file_mtime=1763398651.1500826, t_start_dt=Timestamp('2025-11-17 10:57:28'), t_end_dt=Timestamp('2025-11-17 11:57:28.235351562'), label='Debut_2025-11-17T105728.mp4')

Pandas(Index=388, t_start=Timestamp('2025-11-17 11:57:31'), t_duration=3600.2933593750004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T115731.mp4', video_num_frames=107989, video_fps=29.994500231155207, video_width=640, video_height=480, video_file_size=117265153, cache_file_size=117265153, cache_file_mtime=1763402254.1234245, t_start_dt=Timestamp('2025-11-17 11:57:31'), t_end_dt=Timestamp('2025-11-17 12:57:31.293359375'), label='Debut_2025-11-17T115731.mp4')

Pandas(Index=389, t_start=Timestamp('2025-11-17 12:57:34'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T125734.mp4', video_num_frames=107841, video_fps=29.95337622044025, video_width=640, video_height=480, video_file_size=115364804, cache_file_size=115364804, cache_file_mtime=1763405857.2799616, t_start_dt=Timestamp('2025-11-17 12:57:34'), t_end_dt=Timestamp('2025-11-17 13:57:34.295312500'), label='Debut_2025-11-17T125734.mp4')

Pandas(Index=390, t_start=Timestamp('2025-11-17 13:57:37'), t_duration=3156.8033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T135737.mp4', video_num_frames=94649, video_fps=29.982545757912614, video_width=640, video_height=480, video_file_size=99982767, cache_file_size=99982767, cache_file_mtime=1763409016.6567192, t_start_dt=Timestamp('2025-11-17 13:57:37'), t_end_dt=Timestamp('2025-11-17 14:50:13.803320313'), label='Debut_2025-11-17T135737.mp4')

Pandas(Index=391, t_start=Timestamp('2025-11-17 16:08:06'), t_duration=2391.670377604167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T160806.mp4', video_num_frames=43560, video_fps=18.21321215828906, video_width=640, video_height=480, video_file_size=68135464, cache_file_size=68135464, cache_file_mtime=1763416079.684842, t_start_dt=Timestamp('2025-11-17 16:08:06'), t_end_dt=Timestamp('2025-11-17 16:47:57.670377604'), label='Debut_2025-11-17T160806.mp4')

Pandas(Index=392, t_start=Timestamp('2025-11-17 16:48:04'), t_duration=3600.2033203124997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T164804.mp4', video_num_frames=53948, video_fps=14.984709251175648, video_width=640, video_height=480, video_file_size=97591047, cache_file_size=97591047, cache_file_mtime=1763419686.9111996, t_start_dt=Timestamp('2025-11-17 16:48:04'), t_end_dt=Timestamp('2025-11-17 17:48:04.203320312'), label='Debut_2025-11-17T164804.mp4')

Pandas(Index=393, t_start=Timestamp('2025-11-17 17:48:07'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T174807.mp4', video_num_frames=53662, video_fps=14.905260937626641, video_width=640, video_height=480, video_file_size=102117329, cache_file_size=102117329, cache_file_mtime=1763423289.483111, t_start_dt=Timestamp('2025-11-17 17:48:07'), t_end_dt=Timestamp('2025-11-17 18:48:07.205338542'), label='Debut_2025-11-17T174807.mp4')

Pandas(Index=394, t_start=Timestamp('2025-11-17 18:48:10'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T184810.mp4', video_num_frames=53998, video_fps=14.998347288867487, video_width=640, video_height=480, video_file_size=100846983, cache_file_size=100846983, cache_file_mtime=1763426892.4902313, t_start_dt=Timestamp('2025-11-17 18:48:10'), t_end_dt=Timestamp('2025-11-17 19:48:10.263346354'), label='Debut_2025-11-17T184810.mp4')

Pandas(Index=395, t_start=Timestamp('2025-11-17 19:48:14'), t_duration=715.37734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T194814.mp4', video_num_frames=10749, video_fps=15.0256366013129, video_width=640, video_height=480, video_file_size=19959219, cache_file_size=19959219, cache_file_mtime=1763427610.4305491, t_start_dt=Timestamp('2025-11-17 19:48:14'), t_end_dt=Timestamp('2025-11-17 20:00:09.377343750'), label='Debut_2025-11-17T194814.mp4')

Pandas(Index=396, t_start=Timestamp('2025-11-17 20:26:43'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T202643.mp4', video_num_frames=107643, video_fps=29.898612673570415, video_width=640, video_height=480, video_file_size=107555435, cache_file_size=107555435, cache_file_mtime=1763432805.4511666, t_start_dt=Timestamp('2025-11-17 20:26:43'), t_end_dt=Timestamp('2025-11-17 21:26:43.267382812'), label='Debut_2025-11-17T202643.mp4')

Pandas(Index=397, t_start=Timestamp('2025-11-17 21:26:46'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T212646.mp4', video_num_frames=84903, video_fps=23.582441569441762, video_width=640, video_height=480, video_file_size=106989389, cache_file_size=106989389, cache_file_mtime=1763436408.7713141, t_start_dt=Timestamp('2025-11-17 21:26:46'), t_end_dt=Timestamp('2025-11-17 22:26:46.263346354'), label='Debut_2025-11-17T212646.mp4')

Pandas(Index=398, t_start=Timestamp('2025-11-17 22:26:49'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T222649.mp4', video_num_frames=58391, video_fps=16.218382715678125, video_width=640, video_height=480, video_file_size=97391722, cache_file_size=97391722, cache_file_mtime=1763440011.7499747, t_start_dt=Timestamp('2025-11-17 22:26:49'), t_end_dt=Timestamp('2025-11-17 23:26:49.297330729'), label='Debut_2025-11-17T222649.mp4')

Pandas(Index=399, t_start=Timestamp('2025-11-17 23:26:52'), t_duration=3600.5353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-17T232652.mp4', video_num_frames=56010, video_fps=15.556020016771594, video_width=640, video_height=480, video_file_size=101591809, cache_file_size=101591809, cache_file_mtime=1763443617.7339482, t_start_dt=Timestamp('2025-11-17 23:26:52'), t_end_dt=Timestamp('2025-11-18 00:26:52.535351563'), label='Debut_2025-11-17T232652.mp4')

Pandas(Index=400, t_start=Timestamp('2025-11-18 00:26:59'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T002659.mp4', video_num_frames=47080, video_fps=13.07659606932584, video_width=640, video_height=480, video_file_size=99053734, cache_file_size=99053734, cache_file_mtime=1763447221.1710632, t_start_dt=Timestamp('2025-11-18 00:26:59'), t_end_dt=Timestamp('2025-11-18 01:26:59.325325521'), label='Debut_2025-11-18T002659.mp4')

Pandas(Index=401, t_start=Timestamp('2025-11-18 01:27:02'), t_duration=3600.265364583333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T012702.mp4', video_num_frames=64392, video_fps=17.885348295000536, video_width=640, video_height=480, video_file_size=100484265, cache_file_size=100484265, cache_file_mtime=1763450824.7741973, t_start_dt=Timestamp('2025-11-18 01:27:02'), t_end_dt=Timestamp('2025-11-18 02:27:02.265364583'), label='Debut_2025-11-18T012702.mp4')

Pandas(Index=402, t_start=Timestamp('2025-11-18 02:27:05'), t_duration=3600.207356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T022705.mp4', video_num_frames=54537, video_fps=15.148294138512169, video_width=640, video_height=480, video_file_size=98757215, cache_file_size=98757215, cache_file_mtime=1763454428.0470433, t_start_dt=Timestamp('2025-11-18 02:27:05'), t_end_dt=Timestamp('2025-11-18 03:27:05.207356771'), label='Debut_2025-11-18T022705.mp4')

Pandas(Index=403, t_start=Timestamp('2025-11-18 03:27:09'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T032709.mp4', video_num_frames=54065, video_fps=15.016690105652286, video_width=640, video_height=480, video_file_size=99784742, cache_file_size=99784742, cache_file_mtime=1763458031.2230253, t_start_dt=Timestamp('2025-11-18 03:27:09'), t_end_dt=Timestamp('2025-11-18 04:27:09.327343750'), label='Debut_2025-11-18T032709.mp4')

Pandas(Index=404, t_start=Timestamp('2025-11-18 04:27:12'), t_duration=3600.295377604167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T042712.mp4', video_num_frames=53998, video_fps=14.998213850979422, video_width=640, video_height=480, video_file_size=100011117, cache_file_size=100011117, cache_file_mtime=1763461634.7409568, t_start_dt=Timestamp('2025-11-18 04:27:12'), t_end_dt=Timestamp('2025-11-18 05:27:12.295377604'), label='Debut_2025-11-18T042712.mp4')

Pandas(Index=405, t_start=Timestamp('2025-11-18 05:27:16'), t_duration=3600.2373046875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T052716.mp4', video_num_frames=55536, video_fps=15.42564983916262, video_width=640, video_height=480, video_file_size=99459049, cache_file_size=99459049, cache_file_mtime=1763465238.0248911, t_start_dt=Timestamp('2025-11-18 05:27:16'), t_end_dt=Timestamp('2025-11-18 06:27:16.237304688'), label='Debut_2025-11-18T052716.mp4')

Pandas(Index=406, t_start=Timestamp('2025-11-18 06:27:20'), t_duration=3600.180338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T062720.mp4', video_num_frames=41145, video_fps=11.428594162220968, video_width=640, video_height=480, video_file_size=93407194, cache_file_size=93407194, cache_file_mtime=1763468842.0861084, t_start_dt=Timestamp('2025-11-18 06:27:20'), t_end_dt=Timestamp('2025-11-18 07:27:20.180338542'), label='Debut_2025-11-18T062720.mp4')

Pandas(Index=407, t_start=Timestamp('2025-11-18 07:27:23'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T072723.mp4', video_num_frames=74117, video_fps=20.58635528999187, video_width=640, video_height=480, video_file_size=101546787, cache_file_size=101546787, cache_file_mtime=1763472445.4119353, t_start_dt=Timestamp('2025-11-18 07:27:23'), t_end_dt=Timestamp('2025-11-18 08:27:23.297330729'), label='Debut_2025-11-18T072723.mp4')

Pandas(Index=408, t_start=Timestamp('2025-11-18 08:27:27'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T082727.mp4', video_num_frames=104931, video_fps=29.144866230892728, video_width=640, video_height=480, video_file_size=104623641, cache_file_size=104623641, cache_file_mtime=1763476049.7280755, t_start_dt=Timestamp('2025-11-18 08:27:27'), t_end_dt=Timestamp('2025-11-18 09:27:27.325325521'), label='Debut_2025-11-18T082727.mp4')

Pandas(Index=409, t_start=Timestamp('2025-11-18 09:27:31'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T092731.mp4', video_num_frames=107953, video_fps=29.984484779677363, video_width=640, video_height=480, video_file_size=103226442, cache_file_size=103226442, cache_file_mtime=1763479653.48218, t_start_dt=Timestamp('2025-11-18 09:27:31'), t_end_dt=Timestamp('2025-11-18 10:27:31.295312500'), label='Debut_2025-11-18T092731.mp4')

Pandas(Index=410, t_start=Timestamp('2025-11-18 10:27:34'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T102734.mp4', video_num_frames=107701, video_fps=29.914722588149782, video_width=640, video_height=480, video_file_size=105341829, cache_file_size=105341829, cache_file_mtime=1763483257.1116903, t_start_dt=Timestamp('2025-11-18 10:27:34'), t_end_dt=Timestamp('2025-11-18 11:27:34.267382813'), label='Debut_2025-11-18T102734.mp4')

Pandas(Index=411, t_start=Timestamp('2025-11-18 11:27:38'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T112738.mp4', video_num_frames=107575, video_fps=29.879742477745282, video_width=640, video_height=480, video_file_size=105810322, cache_file_size=105810322, cache_file_mtime=1763486861.2074437, t_start_dt=Timestamp('2025-11-18 11:27:38'), t_end_dt=Timestamp('2025-11-18 12:27:38.265299479'), label='Debut_2025-11-18T112738.mp4')

Pandas(Index=412, t_start=Timestamp('2025-11-18 12:27:42'), t_duration=3601.2853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T122742.mp4', video_num_frames=101873, video_fps=28.287955564476462, video_width=640, video_height=480, video_file_size=105208239, cache_file_size=105208239, cache_file_mtime=1763490470.865853, t_start_dt=Timestamp('2025-11-18 12:27:42'), t_end_dt=Timestamp('2025-11-18 13:27:43.285351563'), label='Debut_2025-11-18T122742.mp4')

Pandas(Index=413, t_start=Timestamp('2025-11-18 13:27:52'), t_duration=3600.6013671875003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T132752.mp4', video_num_frames=98148, video_fps=27.258779851173948, video_width=640, video_height=480, video_file_size=104743100, cache_file_size=104743100, cache_file_mtime=1763494077.2104974, t_start_dt=Timestamp('2025-11-18 13:27:52'), t_end_dt=Timestamp('2025-11-18 14:27:52.601367188'), label='Debut_2025-11-18T132752.mp4')

Pandas(Index=414, t_start=Timestamp('2025-11-18 14:27:59'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T142759.mp4', video_num_frames=106020, video_fps=29.448091327413962, video_width=640, video_height=480, video_file_size=105878823, cache_file_size=105878823, cache_file_mtime=1763497681.470259, t_start_dt=Timestamp('2025-11-18 14:27:59'), t_end_dt=Timestamp('2025-11-18 15:27:59.233333333'), label='Debut_2025-11-18T142759.mp4')

Pandas(Index=415, t_start=Timestamp('2025-11-18 15:28:02'), t_duration=1689.5973958333334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-18T152802.mp4', video_num_frames=50434, video_fps=29.849714567727087, video_width=640, video_height=480, video_file_size=50051129, cache_file_size=50051129, cache_file_mtime=1763499373.5885377, t_start_dt=Timestamp('2025-11-18 15:28:02'), t_end_dt=Timestamp('2025-11-18 15:56:11.597395833'), label='Debut_2025-11-18T152802.mp4')

Pandas(Index=416, t_start=Timestamp('2025-11-19 05:15:55'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T051555.mp4', video_num_frames=102703, video_fps=28.526746678557288, video_width=640, video_height=480, video_file_size=108737178, cache_file_size=108737178, cache_file_mtime=1763550957.4639308, t_start_dt=Timestamp('2025-11-19 05:15:55'), t_end_dt=Timestamp('2025-11-19 06:15:55.235286458'), label='Debut_2025-11-19T051555.mp4')

Pandas(Index=417, t_start=Timestamp('2025-11-19 06:15:58'), t_duration=3600.249348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T061558.mp4', video_num_frames=103462, video_fps=28.73745398493992, video_width=640, video_height=480, video_file_size=108608094, cache_file_size=108608094, cache_file_mtime=1763554561.124442, t_start_dt=Timestamp('2025-11-19 06:15:58'), t_end_dt=Timestamp('2025-11-19 07:15:58.249348958'), label='Debut_2025-11-19T061558.mp4')

Pandas(Index=418, t_start=Timestamp('2025-11-19 07:16:02'), t_duration=3600.4212890625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T071602.mp4', video_num_frames=106566, video_fps=29.59820294467493, video_width=640, video_height=480, video_file_size=105996479, cache_file_size=105996479, cache_file_mtime=1763558164.4073546, t_start_dt=Timestamp('2025-11-19 07:16:02'), t_end_dt=Timestamp('2025-11-19 08:16:02.421289062'), label='Debut_2025-11-19T071602.mp4')

Pandas(Index=419, t_start=Timestamp('2025-11-19 08:16:05'), t_duration=3600.2693359375003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T081605.mp4', video_num_frames=107967, video_fps=29.988589720853675, video_width=640, video_height=480, video_file_size=107993793, cache_file_size=107993793, cache_file_mtime=1763561767.4343622, t_start_dt=Timestamp('2025-11-19 08:16:05'), t_end_dt=Timestamp('2025-11-19 09:16:05.269335938'), label='Debut_2025-11-19T081605.mp4')

Pandas(Index=420, t_start=Timestamp('2025-11-19 09:16:08'), t_duration=3600.2933593750004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T091608.mp4', video_num_frames=106744, video_fps=29.64869507703962, video_width=640, video_height=480, video_file_size=105701040, cache_file_size=105701040, cache_file_mtime=1763565370.665009, t_start_dt=Timestamp('2025-11-19 09:16:08'), t_end_dt=Timestamp('2025-11-19 10:16:08.293359375'), label='Debut_2025-11-19T091608.mp4')

Pandas(Index=421, t_start=Timestamp('2025-11-19 10:16:11'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T101611.mp4', video_num_frames=107754, video_fps=29.929211536032852, video_width=640, video_height=480, video_file_size=107781743, cache_file_size=107781743, cache_file_mtime=1763568974.183437, t_start_dt=Timestamp('2025-11-19 10:16:11'), t_end_dt=Timestamp('2025-11-19 11:16:11.295312500'), label='Debut_2025-11-19T101611.mp4')

Pandas(Index=422, t_start=Timestamp('2025-11-19 11:16:15'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T111615.mp4', video_num_frames=107937, video_fps=29.980273275058945, video_width=640, video_height=480, video_file_size=106583396, cache_file_size=106583396, cache_file_mtime=1763572577.6252754, t_start_dt=Timestamp('2025-11-19 11:16:15'), t_end_dt=Timestamp('2025-11-19 12:16:15.267382812'), label='Debut_2025-11-19T111615.mp4')

Pandas(Index=423, t_start=Timestamp('2025-11-19 12:16:18'), t_duration=3600.237369791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T121618.mp4', video_num_frames=107512, video_fps=29.862475430674547, video_width=640, video_height=480, video_file_size=107224530, cache_file_size=107224530, cache_file_mtime=1763576181.15054, t_start_dt=Timestamp('2025-11-19 12:16:18'), t_end_dt=Timestamp('2025-11-19 13:16:18.237369792'), label='Debut_2025-11-19T121618.mp4')

Pandas(Index=424, t_start=Timestamp('2025-11-19 13:16:22'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T131622.mp4', video_num_frames=107971, video_fps=29.99000064810614, video_width=640, video_height=480, video_file_size=108029430, cache_file_size=108029430, cache_file_mtime=1763579784.574707, t_start_dt=Timestamp('2025-11-19 13:16:22'), t_end_dt=Timestamp('2025-11-19 14:16:22.233333333'), label='Debut_2025-11-19T131622.mp4')

Pandas(Index=425, t_start=Timestamp('2025-11-19 14:16:25'), t_duration=3600.2933593750004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T141625.mp4', video_num_frames=107975, video_fps=29.990611659141056, video_width=640, video_height=480, video_file_size=108101310, cache_file_size=108101310, cache_file_mtime=1763583388.9815383, t_start_dt=Timestamp('2025-11-19 14:16:25'), t_end_dt=Timestamp('2025-11-19 15:16:25.293359375'), label='Debut_2025-11-19T141625.mp4')

Pandas(Index=426, t_start=Timestamp('2025-11-19 15:16:30'), t_duration=3600.3373046875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T151630.mp4', video_num_frames=104536, video_fps=29.03505731640704, video_width=640, video_height=480, video_file_size=106341523, cache_file_size=106341523, cache_file_mtime=1763586997.8496234, t_start_dt=Timestamp('2025-11-19 15:16:30'), t_end_dt=Timestamp('2025-11-19 16:16:30.337304687'), label='Debut_2025-11-19T151630.mp4')

Pandas(Index=427, t_start=Timestamp('2025-11-19 16:18:18'), t_duration=3601.2253255208334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T161818.mp4', video_num_frames=87041, video_fps=24.169828914388063, video_width=640, video_height=480, video_file_size=105762107, cache_file_size=105762107, cache_file_mtime=1763590700.3250537, t_start_dt=Timestamp('2025-11-19 16:18:18'), t_end_dt=Timestamp('2025-11-19 17:18:19.225325521'), label='Debut_2025-11-19T161818.mp4')

Pandas(Index=428, t_start=Timestamp('2025-11-19 17:18:21'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T171821.mp4', video_num_frames=107843, video_fps=29.95444739692798, video_width=640, video_height=480, video_file_size=107071874, cache_file_size=107071874, cache_file_mtime=1763594303.9427655, t_start_dt=Timestamp('2025-11-19 17:18:21'), t_end_dt=Timestamp('2025-11-19 18:18:21.233333333'), label='Debut_2025-11-19T171821.mp4')

Pandas(Index=429, t_start=Timestamp('2025-11-19 18:18:25'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T181825.mp4', video_num_frames=107992, video_fps=29.995567275451254, video_width=640, video_height=480, video_file_size=108970000, cache_file_size=108970000, cache_file_mtime=1763597907.4012806, t_start_dt=Timestamp('2025-11-19 18:18:25'), t_end_dt=Timestamp('2025-11-19 19:18:25.265299479'), label='Debut_2025-11-19T181825.mp4')

Pandas(Index=430, t_start=Timestamp('2025-11-19 19:18:28'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T191828.mp4', video_num_frames=54664, video_fps=15.18319894765577, video_width=640, video_height=480, video_file_size=99960842, cache_file_size=99960842, cache_file_mtime=1763601510.597489, t_start_dt=Timestamp('2025-11-19 19:18:28'), t_end_dt=Timestamp('2025-11-19 20:18:28.295312500'), label='Debut_2025-11-19T191828.mp4')

Pandas(Index=431, t_start=Timestamp('2025-11-19 20:18:32'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T201832.mp4', video_num_frames=53995, video_fps=14.997247429107466, video_width=640, video_height=480, video_file_size=94673271, cache_file_size=94673271, cache_file_mtime=1763605114.135285, t_start_dt=Timestamp('2025-11-19 20:18:32'), t_end_dt=Timestamp('2025-11-19 21:18:32.327343750'), label='Debut_2025-11-19T201832.mp4')

Pandas(Index=432, t_start=Timestamp('2025-11-19 21:18:35'), t_duration=1650.6853515624998, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-19T211835.mp4', video_num_frames=24747, video_fps=14.99195469116817, video_width=640, video_height=480, video_file_size=43340641, cache_file_size=43340641, cache_file_mtime=1763606828.6145895, t_start_dt=Timestamp('2025-11-19 21:18:35'), t_end_dt=Timestamp('2025-11-19 21:46:05.685351562'), label='Debut_2025-11-19T211835.mp4')

Pandas(Index=433, t_start=Timestamp('2025-11-20 07:39:04'), t_duration=1.1033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-20T073904.mp4', video_num_frames=10, video_fps=9.063551070986016, video_width=640, video_height=480, video_file_size=34248, cache_file_size=34248, cache_file_mtime=1763642346.5880558, t_start_dt=Timestamp('2025-11-20 07:39:04'), t_end_dt=Timestamp('2025-11-20 07:39:05.103320312'), label='Debut_2025-11-20T073904.mp4')

Pandas(Index=434, t_start=Timestamp('2025-11-20 07:45:31'), t_duration=3600.173372395833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-20T074531.mp4', video_num_frames=60621, video_fps=16.838355748311674, video_width=640, video_height=480, video_file_size=100760523, cache_file_size=100760523, cache_file_mtime=1763646333.3026083, t_start_dt=Timestamp('2025-11-20 07:45:31'), t_end_dt=Timestamp('2025-11-20 08:45:31.173372396'), label='Debut_2025-11-20T074531.mp4')

Pandas(Index=435, t_start=Timestamp('2025-11-20 08:45:33'), t_duration=3600.3273437499997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-20T084533.mp4', video_num_frames=57599, video_fps=15.998267518643596, video_width=640, video_height=480, video_file_size=100358429, cache_file_size=100358429, cache_file_mtime=1763649935.9652047, t_start_dt=Timestamp('2025-11-20 08:45:33'), t_end_dt=Timestamp('2025-11-20 09:45:33.327343750'), label='Debut_2025-11-20T084533.mp4')

Pandas(Index=436, t_start=Timestamp('2025-11-20 09:45:38'), t_duration=611.5152994791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-20T094538.mp4', video_num_frames=10925, video_fps=17.865456529550325, video_width=640, video_height=480, video_file_size=17248098, cache_file_size=17248098, cache_file_mtime=1763650550.7608566, t_start_dt=Timestamp('2025-11-20 09:45:38'), t_end_dt=Timestamp('2025-11-20 09:55:49.515299478'), label='Debut_2025-11-20T094538.mp4')

Pandas(Index=437, t_start=Timestamp('2025-11-20 15:19:02'), t_duration=5.4853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-20T151902.mp4', video_num_frames=51, video_fps=9.2974897632188, video_width=640, video_height=480, video_file_size=149575, cache_file_size=149575, cache_file_mtime=1763669948.5659895, t_start_dt=Timestamp('2025-11-20 15:19:02'), t_end_dt=Timestamp('2025-11-20 15:19:07.485351562'), label='Debut_2025-11-20T151902.mp4')

Pandas(Index=438, t_start=Timestamp('2025-11-20 15:21:03'), t_duration=9.955338541666666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-20T152103.mp4', video_num_frames=83, video_fps=8.337235308735629, video_width=640, video_height=480, video_file_size=377834, cache_file_size=377834, cache_file_mtime=1763670077.8552275, t_start_dt=Timestamp('2025-11-20 15:21:03'), t_end_dt=Timestamp('2025-11-20 15:21:12.955338542'), label='Debut_2025-11-20T152103.mp4')

Pandas(Index=439, t_start=Timestamp('2025-11-20 15:21:28'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-20T152128.mp4', video_num_frames=106422, video_fps=29.5597347207523, video_width=640, video_height=480, video_file_size=109144933, cache_file_size=109144933, cache_file_mtime=1763673691.25934, t_start_dt=Timestamp('2025-11-20 15:21:28'), t_end_dt=Timestamp('2025-11-20 16:21:28.235286458'), label='Debut_2025-11-20T152128.mp4')

Pandas(Index=440, t_start=Timestamp('2025-11-20 16:21:33'), t_duration=361.44928385416665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-20T162133.mp4', video_num_frames=10629, video_fps=29.406615187231814, video_width=640, video_height=480, video_file_size=11022521, cache_file_size=11022521, cache_file_mtime=1763674056.3157568, t_start_dt=Timestamp('2025-11-20 16:21:33'), t_end_dt=Timestamp('2025-11-20 16:27:34.449283854'), label='Debut_2025-11-20T162133.mp4')

Pandas(Index=441, t_start=Timestamp('2025-11-20 18:14:02'), t_duration=3232.8533203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-20T181402.mp4', video_num_frames=84170, video_fps=26.03582397974796, video_width=640, video_height=480, video_file_size=95606011, cache_file_size=95606011, cache_file_mtime=1763683686.5076258, t_start_dt=Timestamp('2025-11-20 18:14:02'), t_end_dt=Timestamp('2025-11-20 19:07:54.853320312'), label='Debut_2025-11-20T181402.mp4')

Pandas(Index=442, t_start=Timestamp('2025-11-21 18:38:26'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-21T183826.mp4', video_num_frames=78540, video_fps=21.815240485851483, video_width=640, video_height=480, video_file_size=107315934, cache_file_size=107315934, cache_file_mtime=1763771908.1389978, t_start_dt=Timestamp('2025-11-21 18:38:26'), t_end_dt=Timestamp('2025-11-21 19:38:26.235351562'), label='Debut_2025-11-21T183826.mp4')

Pandas(Index=443, t_start=Timestamp('2025-11-21 19:38:29'), t_duration=2747.5793619791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-21T193829.mp4', video_num_frames=41208, video_fps=14.997928929818645, video_width=640, video_height=480, video_file_size=76704253, cache_file_size=76704253, cache_file_mtime=1763774658.2089176, t_start_dt=Timestamp('2025-11-21 19:38:29'), t_end_dt=Timestamp('2025-11-21 20:24:16.579361979'), label='Debut_2025-11-21T193829.mp4')

Pandas(Index=444, t_start=Timestamp('2025-11-24 11:53:34'), t_duration=1.0432942708333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T115334.mp4', video_num_frames=13, video_fps=12.460530421216848, video_width=640, video_height=480, video_file_size=28338, cache_file_size=28338, cache_file_mtime=1764003215.8971572, t_start_dt=Timestamp('2025-11-24 11:53:34'), t_end_dt=Timestamp('2025-11-24 11:53:35.043294271'), label='Debut_2025-11-24T115334.mp4')

Pandas(Index=445, t_start=Timestamp('2025-11-24 11:53:44'), t_duration=2988.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T115344.mp4', video_num_frames=89632, video_fps=29.994960706803028, video_width=640, video_height=480, video_file_size=89715132, cache_file_size=89715132, cache_file_mtime=1764006214.6479845, t_start_dt=Timestamp('2025-11-24 11:53:44'), t_end_dt=Timestamp('2025-11-24 12:43:32.235286458'), label='Debut_2025-11-24T115344.mp4')

Pandas(Index=446, t_start=Timestamp('2025-11-24 12:57:29'), t_duration=3600.2503255208335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T125729.mp4', video_num_frames=107803, video_fps=29.94319568165155, video_width=640, video_height=480, video_file_size=118484781, cache_file_size=118484781, cache_file_mtime=1764010652.216669, t_start_dt=Timestamp('2025-11-24 12:57:29'), t_end_dt=Timestamp('2025-11-24 13:57:29.250325521'), label='Debut_2025-11-24T125729.mp4')

Pandas(Index=447, t_start=Timestamp('2025-11-24 13:57:32'), t_duration=2288.5453125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T135732.mp4', video_num_frames=58459, video_fps=25.544174144465405, video_width=640, video_height=480, video_file_size=69717250, cache_file_size=69717250, cache_file_mtime=1764012942.9621212, t_start_dt=Timestamp('2025-11-24 13:57:32'), t_end_dt=Timestamp('2025-11-24 14:35:40.545312500'), label='Debut_2025-11-24T135732.mp4')

Pandas(Index=448, t_start=Timestamp('2025-11-24 14:36:00'), t_duration=2024.813346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T143600.mp4', video_num_frames=39524, video_fps=19.519823924099484, video_width=640, video_height=480, video_file_size=55338331, cache_file_size=55338331, cache_file_mtime=1764014987.1823266, t_start_dt=Timestamp('2025-11-24 14:36:00'), t_end_dt=Timestamp('2025-11-24 15:09:44.813346354'), label='Debut_2025-11-24T143600.mp4')

Pandas(Index=449, t_start=Timestamp('2025-11-24 15:34:58'), t_duration=3600.293359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T153458.mp4', video_num_frames=73910, video_fps=20.52888268327961, video_width=640, video_height=480, video_file_size=96457544, cache_file_size=96457544, cache_file_mtime=1764020100.6042523, t_start_dt=Timestamp('2025-11-24 15:34:58'), t_end_dt=Timestamp('2025-11-24 16:34:58.293359375'), label='Debut_2025-11-24T153458.mp4')

Pandas(Index=450, t_start=Timestamp('2025-11-24 16:35:01'), t_duration=160.5533203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T163501.mp4', video_num_frames=4789, video_fps=29.828096925549218, video_width=640, video_height=480, video_file_size=4729227, cache_file_size=4729227, cache_file_mtime=1764020273.1019788, t_start_dt=Timestamp('2025-11-24 16:35:01'), t_end_dt=Timestamp('2025-11-24 16:37:41.553320313'), label='Debut_2025-11-24T163501.mp4')

Pandas(Index=451, t_start=Timestamp('2025-11-24 16:40:36'), t_duration=-1.0, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T164036.mp4', video_num_frames=-1, video_fps=1.0, video_width=0, video_height=0, video_file_size=4027, cache_file_size=4027, cache_file_mtime=1764020437.076987, t_start_dt=Timestamp('2025-11-24 16:40:36'), t_end_dt=Timestamp('2025-11-24 16:40:35'), label='Debut_2025-11-24T164036.mp4')

Pandas(Index=452, t_start=Timestamp('2025-11-24 16:40:42'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T164042.mp4', video_num_frames=107982, video_fps=29.9930397344184, video_width=640, video_height=480, video_file_size=108404412, cache_file_size=108404412, cache_file_mtime=1764024044.5510173, t_start_dt=Timestamp('2025-11-24 16:40:42'), t_end_dt=Timestamp('2025-11-24 17:40:42.235286458'), label='Debut_2025-11-24T164042.mp4')

Pandas(Index=453, t_start=Timestamp('2025-11-24 17:40:45'), t_duration=3600.207356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T174045.mp4', video_num_frames=67045, video_fps=18.622538469599508, video_width=640, video_height=480, video_file_size=101891983, cache_file_size=101891983, cache_file_mtime=1764027647.8343384, t_start_dt=Timestamp('2025-11-24 17:40:45'), t_end_dt=Timestamp('2025-11-24 18:40:45.207356771'), label='Debut_2025-11-24T174045.mp4')

Pandas(Index=454, t_start=Timestamp('2025-11-24 18:40:48'), t_duration=3600.239322916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T184048.mp4', video_num_frames=67609, video_fps=18.77902937442165, video_width=640, video_height=480, video_file_size=103815699, cache_file_size=103815699, cache_file_mtime=1764031250.6999724, t_start_dt=Timestamp('2025-11-24 18:40:48'), t_end_dt=Timestamp('2025-11-24 19:40:48.239322917'), label='Debut_2025-11-24T184048.mp4')

Pandas(Index=455, t_start=Timestamp('2025-11-24 19:40:51'), t_duration=3600.2093098958335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T194051.mp4', video_num_frames=107276, video_fps=29.79715643341411, video_width=640, video_height=480, video_file_size=108970212, cache_file_size=108970212, cache_file_mtime=1764034853.6729784, t_start_dt=Timestamp('2025-11-24 19:40:51'), t_end_dt=Timestamp('2025-11-24 20:40:51.209309896'), label='Debut_2025-11-24T194051.mp4')

Pandas(Index=456, t_start=Timestamp('2025-11-24 20:40:54'), t_duration=1155.5073567708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T204054.mp4', video_num_frames=34584, video_fps=29.929709921231503, video_width=640, video_height=480, video_file_size=34651506, cache_file_size=34651506, cache_file_mtime=1764036010.9487467, t_start_dt=Timestamp('2025-11-24 20:40:54'), t_end_dt=Timestamp('2025-11-24 21:00:09.507356771'), label='Debut_2025-11-24T204054.mp4')

Pandas(Index=457, t_start=Timestamp('2025-11-24 23:01:33'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-24T230133.mp4', video_num_frames=87882, video_fps=24.41008453155814, video_width=640, video_height=480, video_file_size=103997677, cache_file_size=103997677, cache_file_mtime=1764046895.4616363, t_start_dt=Timestamp('2025-11-24 23:01:33'), t_end_dt=Timestamp('2025-11-25 00:01:33.233333333'), label='Debut_2025-11-24T230133.mp4')

Pandas(Index=458, t_start=Timestamp('2025-11-25 00:01:37'), t_duration=3600.4152994791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T000137.mp4', video_num_frames=107865, video_fps=29.959043895742713, video_width=640, video_height=480, video_file_size=107769771, cache_file_size=107769771, cache_file_mtime=1764050499.443601, t_start_dt=Timestamp('2025-11-25 00:01:37'), t_end_dt=Timestamp('2025-11-25 01:01:37.415299479'), label='Debut_2025-11-25T000137.mp4')

Pandas(Index=459, t_start=Timestamp('2025-11-25 01:01:40'), t_duration=3600.295377604167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T010140.mp4', video_num_frames=93499, video_fps=25.969813638518556, video_width=640, video_height=480, video_file_size=104952617, cache_file_size=104952617, cache_file_mtime=1764054103.1001997, t_start_dt=Timestamp('2025-11-25 01:01:40'), t_end_dt=Timestamp('2025-11-25 02:01:40.295377604'), label='Debut_2025-11-25T010140.mp4')

Pandas(Index=460, t_start=Timestamp('2025-11-25 02:01:44'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T020144.mp4', video_num_frames=53984, video_fps=14.994450278874842, video_width=640, video_height=480, video_file_size=95236071, cache_file_size=95236071, cache_file_mtime=1764057706.4170792, t_start_dt=Timestamp('2025-11-25 02:01:44'), t_end_dt=Timestamp('2025-11-25 03:01:44.265364583'), label='Debut_2025-11-25T020144.mp4')

Pandas(Index=461, t_start=Timestamp('2025-11-25 03:01:47'), t_duration=3600.299348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T030147.mp4', video_num_frames=69625, video_fps=19.338669719267774, video_width=640, video_height=480, video_file_size=98180157, cache_file_size=98180157, cache_file_mtime=1764061309.1374488, t_start_dt=Timestamp('2025-11-25 03:01:47'), t_end_dt=Timestamp('2025-11-25 04:01:47.299348958'), label='Debut_2025-11-25T030147.mp4')

Pandas(Index=462, t_start=Timestamp('2025-11-25 04:01:49'), t_duration=3600.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T040149.mp4', video_num_frames=107978, video_fps=29.991911340625943, video_width=640, video_height=480, video_file_size=106818512, cache_file_size=106818512, cache_file_mtime=1764064912.0812426, t_start_dt=Timestamp('2025-11-25 04:01:49'), t_end_dt=Timestamp('2025-11-25 05:01:49.237369792'), label='Debut_2025-11-25T040149.mp4')

Pandas(Index=463, t_start=Timestamp('2025-11-25 05:01:52'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T050152.mp4', video_num_frames=107968, video_fps=29.988634293749648, video_width=640, video_height=480, video_file_size=106012264, cache_file_size=106012264, cache_file_mtime=1764068515.3596973, t_start_dt=Timestamp('2025-11-25 05:01:52'), t_end_dt=Timestamp('2025-11-25 06:01:52.297330729'), label='Debut_2025-11-25T050152.mp4')

Pandas(Index=464, t_start=Timestamp('2025-11-25 06:01:56'), t_duration=3600.3063151041665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T060156.mp4', video_num_frames=106091, video_fps=29.46721492971925, video_width=640, video_height=480, video_file_size=106197019, cache_file_size=106197019, cache_file_mtime=1764072119.257658, t_start_dt=Timestamp('2025-11-25 06:01:56'), t_end_dt=Timestamp('2025-11-25 07:01:56.306315104'), label='Debut_2025-11-25T060156.mp4')

Pandas(Index=465, t_start=Timestamp('2025-11-25 07:02:01'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T070201.mp4', video_num_frames=107187, video_fps=29.771955414118818, video_width=640, video_height=480, video_file_size=107921271, cache_file_size=107921271, cache_file_mtime=1764075723.9972649, t_start_dt=Timestamp('2025-11-25 07:02:01'), t_end_dt=Timestamp('2025-11-25 08:02:01.267382813'), label='Debut_2025-11-25T070201.mp4')

Pandas(Index=466, t_start=Timestamp('2025-11-25 08:02:05'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T080205.mp4', video_num_frames=107353, video_fps=29.817831783764266, video_width=640, video_height=480, video_file_size=106604652, cache_file_size=106604652, cache_file_mtime=1764079327.5179167, t_start_dt=Timestamp('2025-11-25 08:02:05'), t_end_dt=Timestamp('2025-11-25 09:02:05.295312500'), label='Debut_2025-11-25T080205.mp4')

Pandas(Index=467, t_start=Timestamp('2025-11-25 09:02:08'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T090208.mp4', video_num_frames=107963, video_fps=29.98749496090487, video_width=640, video_height=480, video_file_size=106717499, cache_file_size=106717499, cache_file_mtime=1764082930.9998798, t_start_dt=Timestamp('2025-11-25 09:02:08'), t_end_dt=Timestamp('2025-11-25 10:02:08.267382812'), label='Debut_2025-11-25T090208.mp4')

Pandas(Index=468, t_start=Timestamp('2025-11-25 10:02:12'), t_duration=3600.383333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T100212.mp4', video_num_frames=107316, video_fps=29.80682612499595, video_width=640, video_height=480, video_file_size=106881413, cache_file_size=106881413, cache_file_mtime=1764086534.5757282, t_start_dt=Timestamp('2025-11-25 10:02:12'), t_end_dt=Timestamp('2025-11-25 11:02:12.383333333'), label='Debut_2025-11-25T100212.mp4')

Pandas(Index=469, t_start=Timestamp('2025-11-25 11:02:15'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T110215.mp4', video_num_frames=107909, video_fps=29.97201370528636, video_width=640, video_height=480, video_file_size=106917316, cache_file_size=106917316, cache_file_mtime=1764090138.364457, t_start_dt=Timestamp('2025-11-25 11:02:15'), t_end_dt=Timestamp('2025-11-25 12:02:15.325325521'), label='Debut_2025-11-25T110215.mp4')

Pandas(Index=470, t_start=Timestamp('2025-11-25 12:02:19'), t_duration=3600.27734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T120219.mp4', video_num_frames=107559, video_fps=29.87519841678864, video_width=640, video_height=480, video_file_size=106975578, cache_file_size=106975578, cache_file_mtime=1764093742.2968261, t_start_dt=Timestamp('2025-11-25 12:02:19'), t_end_dt=Timestamp('2025-11-25 13:02:19.277343750'), label='Debut_2025-11-25T120219.mp4')

Pandas(Index=471, t_start=Timestamp('2025-11-25 13:02:23'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T130223.mp4', video_num_frames=107601, video_fps=29.886465880533763, video_width=640, video_height=480, video_file_size=107783543, cache_file_size=107783543, cache_file_mtime=1764097345.7512743, t_start_dt=Timestamp('2025-11-25 13:02:23'), t_end_dt=Timestamp('2025-11-25 14:02:23.325325521'), label='Debut_2025-11-25T130223.mp4')

Pandas(Index=472, t_start=Timestamp('2025-11-25 14:02:26'), t_duration=3600.273372395833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T140226.mp4', video_num_frames=107926, video_fps=29.977168074928628, video_width=640, video_height=480, video_file_size=107431887, cache_file_size=107431887, cache_file_mtime=1764100949.1422534, t_start_dt=Timestamp('2025-11-25 14:02:26'), t_end_dt=Timestamp('2025-11-25 15:02:26.273372396'), label='Debut_2025-11-25T140226.mp4')

Pandas(Index=473, t_start=Timestamp('2025-11-25 15:02:30'), t_duration=3600.305338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T150230.mp4', video_num_frames=106321, video_fps=29.531106393066704, video_width=640, video_height=480, video_file_size=107509434, cache_file_size=107509434, cache_file_mtime=1764104552.7818253, t_start_dt=Timestamp('2025-11-25 15:02:30'), t_end_dt=Timestamp('2025-11-25 16:02:30.305338542'), label='Debut_2025-11-25T150230.mp4')

Pandas(Index=474, t_start=Timestamp('2025-11-25 16:02:34'), t_duration=3600.215364583333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T160234.mp4', video_num_frames=105788, video_fps=29.383797714069043, video_width=640, video_height=480, video_file_size=105267233, cache_file_size=105267233, cache_file_mtime=1764108156.4704962, t_start_dt=Timestamp('2025-11-25 16:02:34'), t_end_dt=Timestamp('2025-11-25 17:02:34.215364583'), label='Debut_2025-11-25T160234.mp4')

Pandas(Index=475, t_start=Timestamp('2025-11-25 17:02:37'), t_duration=4.075325520833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T170237.mp4', video_num_frames=111, video_fps=27.23708803936291, video_width=640, video_height=480, video_file_size=116652, cache_file_size=116652, cache_file_mtime=1764108162.3689637, t_start_dt=Timestamp('2025-11-25 17:02:37'), t_end_dt=Timestamp('2025-11-25 17:02:41.075325521'), label='Debut_2025-11-25T170237.mp4')

Pandas(Index=476, t_start=Timestamp('2025-11-25 17:46:17'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T174617.mp4', video_num_frames=107986, video_fps=29.993900731599368, video_width=640, video_height=480, video_file_size=107862120, cache_file_size=107862120, cache_file_mtime=1764114379.99778, t_start_dt=Timestamp('2025-11-25 17:46:17'), t_end_dt=Timestamp('2025-11-25 18:46:17.265299479'), label='Debut_2025-11-25T174617.mp4')

Pandas(Index=477, t_start=Timestamp('2025-11-25 18:46:20'), t_duration=2030.9233723958334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-25T184620.mp4', video_num_frames=60191, video_fps=29.63725801677789, video_width=640, video_height=480, video_file_size=60031451, cache_file_size=60031451, cache_file_mtime=1764116413.1588411, t_start_dt=Timestamp('2025-11-25 18:46:20'), t_end_dt=Timestamp('2025-11-25 19:20:10.923372396'), label='Debut_2025-11-25T184620.mp4')

Pandas(Index=478, t_start=Timestamp('2025-11-26 09:19:24'), t_duration=3600.293359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T091924.mp4', video_num_frames=106075, video_fps=29.462876885791967, video_width=640, video_height=480, video_file_size=107975041, cache_file_size=107975041, cache_file_mtime=1764170367.1622915, t_start_dt=Timestamp('2025-11-26 09:19:24'), t_end_dt=Timestamp('2025-11-26 10:19:24.293359375'), label='Debut_2025-11-26T091924.mp4')

Pandas(Index=479, t_start=Timestamp('2025-11-26 10:19:28'), t_duration=3600.385286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T101928.mp4', video_num_frames=107862, video_fps=29.958460391916244, video_width=640, video_height=480, video_file_size=106553178, cache_file_size=106553178, cache_file_mtime=1764173971.2800741, t_start_dt=Timestamp('2025-11-26 10:19:28'), t_end_dt=Timestamp('2025-11-26 11:19:28.385286458'), label='Debut_2025-11-26T101928.mp4')

Pandas(Index=480, t_start=Timestamp('2025-11-26 11:19:32'), t_duration=3600.2693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T111932.mp4', video_num_frames=107202, video_fps=29.77610561796619, video_width=640, video_height=480, video_file_size=106208720, cache_file_size=106208720, cache_file_mtime=1764177574.8995886, t_start_dt=Timestamp('2025-11-26 11:19:32'), t_end_dt=Timestamp('2025-11-26 12:19:32.269335937'), label='Debut_2025-11-26T111932.mp4')

Pandas(Index=481, t_start=Timestamp('2025-11-26 12:19:36'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T121936.mp4', video_num_frames=107501, video_fps=29.859437355204687, video_width=640, video_height=480, video_file_size=108264744, cache_file_size=108264744, cache_file_mtime=1764181178.7198079, t_start_dt=Timestamp('2025-11-26 12:19:36'), t_end_dt=Timestamp('2025-11-26 13:19:36.235286458'), label='Debut_2025-11-26T121936.mp4')

Pandas(Index=482, t_start=Timestamp('2025-11-26 13:19:40'), t_duration=3600.2933593750004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T131940.mp4', video_num_frames=107315, video_fps=29.807293264188214, video_width=640, video_height=480, video_file_size=107416654, cache_file_size=107416654, cache_file_mtime=1764184782.4685, t_start_dt=Timestamp('2025-11-26 13:19:40'), t_end_dt=Timestamp('2025-11-26 14:19:40.293359375'), label='Debut_2025-11-26T131940.mp4')

Pandas(Index=483, t_start=Timestamp('2025-11-26 14:19:44'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T141944.mp4', video_num_frames=107829, video_fps=29.94979349106491, video_width=640, video_height=480, video_file_size=108381104, cache_file_size=108381104, cache_file_mtime=1764188386.5067704, t_start_dt=Timestamp('2025-11-26 14:19:44'), t_end_dt=Timestamp('2025-11-26 15:19:44.325325521'), label='Debut_2025-11-26T141944.mp4')

Pandas(Index=484, t_start=Timestamp('2025-11-26 15:19:48'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T151948.mp4', video_num_frames=107972, video_fps=29.98949531281769, video_width=640, video_height=480, video_file_size=108815282, cache_file_size=108815282, cache_file_mtime=1764191991.3613315, t_start_dt=Timestamp('2025-11-26 15:19:48'), t_end_dt=Timestamp('2025-11-26 16:19:48.327343750'), label='Debut_2025-11-26T151948.mp4')

Pandas(Index=485, t_start=Timestamp('2025-11-26 16:19:53'), t_duration=3600.484309895833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T161953.mp4', video_num_frames=106875, video_fps=29.683506662216793, video_width=640, video_height=480, video_file_size=107911444, cache_file_size=107911444, cache_file_mtime=1764195597.5930889, t_start_dt=Timestamp('2025-11-26 16:19:53'), t_end_dt=Timestamp('2025-11-26 17:19:53.484309896'), label='Debut_2025-11-26T161953.mp4')

Pandas(Index=486, t_start=Timestamp('2025-11-26 17:20:01'), t_duration=3600.6413411458334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T172001.mp4', video_num_frames=104396, video_fps=28.99372364779271, video_width=640, video_height=480, video_file_size=109114478, cache_file_size=109114478, cache_file_mtime=1764199204.3103645, t_start_dt=Timestamp('2025-11-26 17:20:01'), t_end_dt=Timestamp('2025-11-26 18:20:01.641341146'), label='Debut_2025-11-26T172001.mp4')

Pandas(Index=487, t_start=Timestamp('2025-11-26 18:20:06'), t_duration=3600.299348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T182006.mp4', video_num_frames=107553, video_fps=29.873349290002253, video_width=640, video_height=480, video_file_size=109352803, cache_file_size=109352803, cache_file_mtime=1764202808.2600715, t_start_dt=Timestamp('2025-11-26 18:20:06'), t_end_dt=Timestamp('2025-11-26 19:20:06.299348958'), label='Debut_2025-11-26T182006.mp4')

Pandas(Index=488, t_start=Timestamp('2025-11-26 19:20:09'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T192009.mp4', video_num_frames=82582, video_fps=22.938136087940876, video_width=640, video_height=480, video_file_size=105692889, cache_file_size=105692889, cache_file_mtime=1764206411.4996433, t_start_dt=Timestamp('2025-11-26 19:20:09'), t_end_dt=Timestamp('2025-11-26 20:20:09.205338542'), label='Debut_2025-11-26T192009.mp4')

Pandas(Index=489, t_start=Timestamp('2025-11-26 20:20:12'), t_duration=684.2653645833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-11-26T202012.mp4', video_num_frames=10259, video_fps=14.9927214367294, video_width=640, video_height=480, video_file_size=18983488, cache_file_size=18983488, cache_file_mtime=1764207097.819948, t_start_dt=Timestamp('2025-11-26 20:20:12'), t_end_dt=Timestamp('2025-11-26 20:31:36.265364583'), label='Debut_2025-11-26T202012.mp4')

Pandas(Index=490, t_start=Timestamp('2025-12-01 07:30:26'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T073026.mp4', video_num_frames=107946, video_fps=29.982790439253474, video_width=640, video_height=480, video_file_size=109916360, cache_file_size=109916360, cache_file_mtime=1764595828.629614, t_start_dt=Timestamp('2025-12-01 07:30:26'), t_end_dt=Timestamp('2025-12-01 08:30:26.265299479'), label='Debut_2025-12-01T073026.mp4')

Pandas(Index=491, t_start=Timestamp('2025-12-01 08:30:29'), t_duration=3600.3553385416662, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T083029.mp4', video_num_frames=104558, video_fps=29.041022390404247, video_width=640, video_height=480, video_file_size=110855212, cache_file_size=110855212, cache_file_mtime=1764599433.298444, t_start_dt=Timestamp('2025-12-01 08:30:29'), t_end_dt=Timestamp('2025-12-01 09:30:29.355338542'), label='Debut_2025-12-01T083029.mp4')

Pandas(Index=492, t_start=Timestamp('2025-12-01 09:30:36'), t_duration=3600.7813151041664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T093036.mp4', video_num_frames=92432, video_fps=25.669984348195843, video_width=640, video_height=480, video_file_size=108573006, cache_file_size=108573006, cache_file_mtime=1764603038.6355565, t_start_dt=Timestamp('2025-12-01 09:30:36'), t_end_dt=Timestamp('2025-12-01 10:30:36.781315104'), label='Debut_2025-12-01T093036.mp4')

Pandas(Index=493, t_start=Timestamp('2025-12-01 10:30:39'), t_duration=3600.7753255208336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T103039.mp4', video_num_frames=107923, video_fps=29.972156061803023, video_width=640, video_height=480, video_file_size=107858121, cache_file_size=107858121, cache_file_mtime=1764606643.655946, t_start_dt=Timestamp('2025-12-01 10:30:39'), t_end_dt=Timestamp('2025-12-01 11:30:39.775325521'), label='Debut_2025-12-01T103039.mp4')

Pandas(Index=494, t_start=Timestamp('2025-12-01 11:30:50'), t_duration=3602.8333333333335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T113050.mp4', video_num_frames=107874, video_fps=29.941434981727344, video_width=640, video_height=480, video_file_size=105722711, cache_file_size=105722711, cache_file_mtime=1764610253.3219893, t_start_dt=Timestamp('2025-12-01 11:30:50'), t_end_dt=Timestamp('2025-12-01 12:30:52.833333333'), label='Debut_2025-12-01T113050.mp4')

Pandas(Index=495, t_start=Timestamp('2025-12-01 12:30:54'), t_duration=3600.9053385416664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T123054.mp4', video_num_frames=107747, video_fps=29.922197300425715, video_width=640, video_height=480, video_file_size=104644346, cache_file_size=104644346, cache_file_mtime=1764613859.1763172, t_start_dt=Timestamp('2025-12-01 12:30:54'), t_end_dt=Timestamp('2025-12-01 13:30:54.905338542'), label='Debut_2025-12-01T123054.mp4')

Pandas(Index=496, t_start=Timestamp('2025-12-01 13:31:02'), t_duration=3600.4893229166664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T133102.mp4', video_num_frames=107909, video_fps=29.97064852079206, video_width=640, video_height=480, video_file_size=103203991, cache_file_size=103203991, cache_file_mtime=1764617464.6623058, t_start_dt=Timestamp('2025-12-01 13:31:02'), t_end_dt=Timestamp('2025-12-01 14:31:02.489322917'), label='Debut_2025-12-01T133102.mp4')

Pandas(Index=497, t_start=Timestamp('2025-12-01 14:31:05'), t_duration=3600.279361979167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T143105.mp4', video_num_frames=107890, video_fps=29.967118979536654, video_width=640, video_height=480, video_file_size=104726161, cache_file_size=104726161, cache_file_mtime=1764621068.4304154, t_start_dt=Timestamp('2025-12-01 14:31:05'), t_end_dt=Timestamp('2025-12-01 15:31:05.279361979'), label='Debut_2025-12-01T143105.mp4')

Pandas(Index=498, t_start=Timestamp('2025-12-01 15:31:09'), t_duration=3600.3853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T153109.mp4', video_num_frames=105911, video_fps=29.41657341040914, video_width=640, video_height=480, video_file_size=106395655, cache_file_size=106395655, cache_file_mtime=1764624672.85642, t_start_dt=Timestamp('2025-12-01 15:31:09'), t_end_dt=Timestamp('2025-12-01 16:31:09.385351563'), label='Debut_2025-12-01T153109.mp4')

Pandas(Index=499, t_start=Timestamp('2025-12-01 16:31:14'), t_duration=611.4553385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T163114.mp4', video_num_frames=17694, video_fps=28.937518220383108, video_width=640, video_height=480, video_file_size=17687288, cache_file_size=17687288, cache_file_mtime=1764625286.4733994, t_start_dt=Timestamp('2025-12-01 16:31:14'), t_end_dt=Timestamp('2025-12-01 16:41:25.455338542'), label='Debut_2025-12-01T163114.mp4')

Pandas(Index=500, t_start=Timestamp('2025-12-01 16:43:51'), t_duration=2539.5833333333335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-01T164351.mp4', video_num_frames=75988, video_fps=29.92144380639869, video_width=640, video_height=480, video_file_size=74138931, cache_file_size=74138931, cache_file_mtime=1764627972.4500327, t_start_dt=Timestamp('2025-12-01 16:43:51'), t_end_dt=Timestamp('2025-12-01 17:26:10.583333333'), label='Debut_2025-12-01T164351.mp4')

Pandas(Index=501, t_start=Timestamp('2025-12-02 02:04:32'), t_duration=1.6453125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T020432.mp4', video_num_frames=20, video_fps=12.155745489078823, video_width=640, video_height=480, video_file_size=48880, cache_file_size=48880, cache_file_mtime=1764659075.0821364, t_start_dt=Timestamp('2025-12-02 02:04:32'), t_end_dt=Timestamp('2025-12-02 02:04:33.645312500'), label='Debut_2025-12-02T020432.mp4')

Pandas(Index=502, t_start=Timestamp('2025-12-02 02:04:40'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T020440.mp4', video_num_frames=106318, video_fps=29.530847719841226, video_width=640, video_height=480, video_file_size=105242417, cache_file_size=105242417, cache_file_mtime=1764662683.1740057, t_start_dt=Timestamp('2025-12-02 02:04:40'), t_end_dt=Timestamp('2025-12-02 03:04:40.235286458'), label='Debut_2025-12-02T020440.mp4')

Pandas(Index=503, t_start=Timestamp('2025-12-02 03:04:43'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T030443.mp4', video_num_frames=107981, video_fps=29.992511945056133, video_width=640, video_height=480, video_file_size=106262024, cache_file_size=106262024, cache_file_mtime=1764666286.0031855, t_start_dt=Timestamp('2025-12-02 03:04:43'), t_end_dt=Timestamp('2025-12-02 04:04:43.265299479'), label='Debut_2025-12-02T030443.mp4')

Pandas(Index=504, t_start=Timestamp('2025-12-02 04:04:46'), t_duration=3600.299348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T040446.mp4', video_num_frames=107697, video_fps=29.913345964179268, video_width=640, video_height=480, video_file_size=105446728, cache_file_size=105446728, cache_file_mtime=1764669889.5810523, t_start_dt=Timestamp('2025-12-02 04:04:46'), t_end_dt=Timestamp('2025-12-02 05:04:46.299348958'), label='Debut_2025-12-02T040446.mp4')

Pandas(Index=505, t_start=Timestamp('2025-12-02 05:04:50'), t_duration=3600.3292968749997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T050450.mp4', video_num_frames=107591, video_fps=29.883655390462874, video_width=640, video_height=480, video_file_size=104682531, cache_file_size=104682531, cache_file_mtime=1764673493.0282078, t_start_dt=Timestamp('2025-12-02 05:04:50'), t_end_dt=Timestamp('2025-12-02 06:04:50.329296875'), label='Debut_2025-12-02T050450.mp4')

Pandas(Index=506, t_start=Timestamp('2025-12-02 06:04:53'), t_duration=3600.2753255208336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T060453.mp4', video_num_frames=107940, video_fps=29.9810404040099, video_width=640, video_height=480, video_file_size=105166630, cache_file_size=105166630, cache_file_mtime=1764677096.4157224, t_start_dt=Timestamp('2025-12-02 06:04:53'), t_end_dt=Timestamp('2025-12-02 07:04:53.275325521'), label='Debut_2025-12-02T060453.mp4')

Pandas(Index=507, t_start=Timestamp('2025-12-02 07:04:57'), t_duration=3600.2933593750004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T070457.mp4', video_num_frames=107898, video_fps=29.969224513063224, video_width=640, video_height=480, video_file_size=104700215, cache_file_size=104700215, cache_file_mtime=1764680700.0608375, t_start_dt=Timestamp('2025-12-02 07:04:57'), t_end_dt=Timestamp('2025-12-02 08:04:57.293359375'), label='Debut_2025-12-02T070457.mp4')

Pandas(Index=508, t_start=Timestamp('2025-12-02 08:05:01'), t_duration=3600.3543619791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T080501.mp4', video_num_frames=91997, video_fps=25.552207019263495, video_width=640, video_height=480, video_file_size=103753130, cache_file_size=103753130, cache_file_mtime=1764684303.7396548, t_start_dt=Timestamp('2025-12-02 08:05:01'), t_end_dt=Timestamp('2025-12-02 09:05:01.354361979'), label='Debut_2025-12-02T080501.mp4')

Pandas(Index=509, t_start=Timestamp('2025-12-02 09:05:04'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T090504.mp4', video_num_frames=107980, video_fps=29.991984164493452, video_width=640, video_height=480, video_file_size=105414013, cache_file_size=105414013, cache_file_mtime=1764687906.9907515, t_start_dt=Timestamp('2025-12-02 09:05:04'), t_end_dt=Timestamp('2025-12-02 10:05:04.295312500'), label='Debut_2025-12-02T090504.mp4')

Pandas(Index=510, t_start=Timestamp('2025-12-02 10:05:07'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T100507.mp4', video_num_frames=107975, video_fps=29.99059538952751, video_width=640, video_height=480, video_file_size=104897969, cache_file_size=104897969, cache_file_mtime=1764691510.2916503, t_start_dt=Timestamp('2025-12-02 10:05:07'), t_end_dt=Timestamp('2025-12-02 11:05:07.295312500'), label='Debut_2025-12-02T100507.mp4')

Pandas(Index=511, t_start=Timestamp('2025-12-02 11:05:11'), t_duration=3600.331380208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T110511.mp4', video_num_frames=107982, video_fps=29.992239212644815, video_width=640, video_height=480, video_file_size=106012675, cache_file_size=106012675, cache_file_mtime=1764695113.7609224, t_start_dt=Timestamp('2025-12-02 11:05:11'), t_end_dt=Timestamp('2025-12-02 12:05:11.331380208'), label='Debut_2025-12-02T110511.mp4')

Pandas(Index=512, t_start=Timestamp('2025-12-02 12:05:14'), t_duration=3600.221354166667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T120514.mp4', video_num_frames=107977, video_fps=29.99176699928028, video_width=640, video_height=480, video_file_size=105315336, cache_file_size=105315336, cache_file_mtime=1764698717.0609703, t_start_dt=Timestamp('2025-12-02 12:05:14'), t_end_dt=Timestamp('2025-12-02 13:05:14.221354167'), label='Debut_2025-12-02T120514.mp4')

Pandas(Index=513, t_start=Timestamp('2025-12-02 13:05:17'), t_duration=1014.6572916666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T130517.mp4', video_num_frames=30421, video_fps=29.981551652805596, video_width=640, video_height=480, video_file_size=29662117, cache_file_size=29662117, cache_file_mtime=1764699733.3673818, t_start_dt=Timestamp('2025-12-02 13:05:17'), t_end_dt=Timestamp('2025-12-02 13:22:11.657291667'), label='Debut_2025-12-02T130517.mp4')

Pandas(Index=514, t_start=Timestamp('2025-12-02 14:20:16'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T142016.mp4', video_num_frames=107959, video_fps=29.986401284265888, video_width=640, video_height=480, video_file_size=105119039, cache_file_size=105119039, cache_file_mtime=1764706818.920426, t_start_dt=Timestamp('2025-12-02 14:20:16'), t_end_dt=Timestamp('2025-12-02 15:20:16.265299479'), label='Debut_2025-12-02T142016.mp4')

Pandas(Index=515, t_start=Timestamp('2025-12-02 15:20:19'), t_duration=3600.305338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T152019.mp4', video_num_frames=107952, video_fps=29.984123525402666, video_width=640, video_height=480, video_file_size=105483845, cache_file_size=105483845, cache_file_mtime=1764710422.0759227, t_start_dt=Timestamp('2025-12-02 15:20:19'), t_end_dt=Timestamp('2025-12-02 16:20:19.305338542'), label='Debut_2025-12-02T152019.mp4')

Pandas(Index=516, t_start=Timestamp('2025-12-02 16:20:23'), t_duration=3600.2533203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T162023.mp4', video_num_frames=107925, video_fps=29.97705727846733, video_width=640, video_height=480, video_file_size=106605120, cache_file_size=106605120, cache_file_mtime=1764714025.2915502, t_start_dt=Timestamp('2025-12-02 16:20:23'), t_end_dt=Timestamp('2025-12-02 17:20:23.253320312'), label='Debut_2025-12-02T162023.mp4')

Pandas(Index=517, t_start=Timestamp('2025-12-02 17:20:26'), t_duration=3337.379361979167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-02T172026.mp4', video_num_frames=100097, video_fps=29.992694609533228, video_width=640, video_height=480, video_file_size=98010705, cache_file_size=98010705, cache_file_mtime=1764717365.684134, t_start_dt=Timestamp('2025-12-02 17:20:26'), t_end_dt=Timestamp('2025-12-02 18:16:03.379361979'), label='Debut_2025-12-02T172026.mp4')

Pandas(Index=518, t_start=Timestamp('2025-12-03 10:17:05'), t_duration=-1.0, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T101705.mp4', video_num_frames=-1, video_fps=1.0, video_width=0, video_height=0, video_file_size=7478, cache_file_size=7478, cache_file_mtime=1764775026.8441463, t_start_dt=Timestamp('2025-12-03 10:17:05'), t_end_dt=Timestamp('2025-12-03 10:17:04'), label='Debut_2025-12-03T101705.mp4')

Pandas(Index=519, t_start=Timestamp('2025-12-03 10:17:09'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T101709.mp4', video_num_frames=107684, video_fps=29.91026736642321, video_width=640, video_height=480, video_file_size=108488770, cache_file_size=108488770, cache_file_mtime=1764778632.1618361, t_start_dt=Timestamp('2025-12-03 10:17:09'), t_end_dt=Timestamp('2025-12-03 11:17:09.235286458'), label='Debut_2025-12-03T101709.mp4')

Pandas(Index=520, t_start=Timestamp('2025-12-03 11:17:13'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T111713.mp4', video_num_frames=107624, video_fps=29.89285419212243, video_width=640, video_height=480, video_file_size=111448012, cache_file_size=111448012, cache_file_mtime=1764782235.323984, t_start_dt=Timestamp('2025-12-03 11:17:13'), t_end_dt=Timestamp('2025-12-03 12:17:13.325325521'), label='Debut_2025-12-03T111713.mp4')

Pandas(Index=521, t_start=Timestamp('2025-12-03 12:17:15'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T121715.mp4', video_num_frames=107888, video_fps=29.9669465867953, video_width=640, video_height=480, video_file_size=105226214, cache_file_size=105226214, cache_file_mtime=1764785838.1000426, t_start_dt=Timestamp('2025-12-03 12:17:15'), t_end_dt=Timestamp('2025-12-03 13:17:15.233333333'), label='Debut_2025-12-03T121715.mp4')

Pandas(Index=522, t_start=Timestamp('2025-12-03 13:17:19'), t_duration=3600.3553385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T131719.mp4', video_num_frames=107976, video_fps=29.990373129041192, video_width=640, video_height=480, video_file_size=106034786, cache_file_size=106034786, cache_file_mtime=1764789441.358312, t_start_dt=Timestamp('2025-12-03 13:17:19'), t_end_dt=Timestamp('2025-12-03 14:17:19.355338542'), label='Debut_2025-12-03T131719.mp4')

Pandas(Index=523, t_start=Timestamp('2025-12-03 14:17:22'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T141722.mp4', video_num_frames=107783, video_fps=29.93701686788757, video_width=640, video_height=480, video_file_size=104180530, cache_file_size=104180530, cache_file_mtime=1764793044.9269073, t_start_dt=Timestamp('2025-12-03 14:17:22'), t_end_dt=Timestamp('2025-12-03 15:17:22.325325521'), label='Debut_2025-12-03T141722.mp4')

Pandas(Index=524, t_start=Timestamp('2025-12-03 15:17:25'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T151725.mp4', video_num_frames=107721, video_fps=29.92054447251657, video_width=640, video_height=480, video_file_size=106887513, cache_file_size=106887513, cache_file_mtime=1764796647.75228, t_start_dt=Timestamp('2025-12-03 15:17:25'), t_end_dt=Timestamp('2025-12-03 16:17:25.235286458'), label='Debut_2025-12-03T151725.mp4')

Pandas(Index=525, t_start=Timestamp('2025-12-03 16:17:28'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T161728.mp4', video_num_frames=106050, video_fps=29.45616258205798, video_width=640, video_height=480, video_file_size=104407134, cache_file_size=104407134, cache_file_mtime=1764800250.874533, t_start_dt=Timestamp('2025-12-03 16:17:28'), t_end_dt=Timestamp('2025-12-03 17:17:28.265299479'), label='Debut_2025-12-03T161728.mp4')

Pandas(Index=526, t_start=Timestamp('2025-12-03 17:17:31'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T171731.mp4', video_num_frames=107930, video_fps=29.97859623396286, video_width=640, video_height=480, video_file_size=110784294, cache_file_size=110784294, cache_file_mtime=1764803854.015433, t_start_dt=Timestamp('2025-12-03 17:17:31'), t_end_dt=Timestamp('2025-12-03 18:17:31.235286458'), label='Debut_2025-12-03T171731.mp4')

Pandas(Index=527, t_start=Timestamp('2025-12-03 18:17:34'), t_duration=3388.591341145833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T181734.mp4', video_num_frames=100924, video_fps=29.78346747645088, video_width=640, video_height=480, video_file_size=107168184, cache_file_size=107168184, cache_file_mtime=1764807245.479923, t_start_dt=Timestamp('2025-12-03 18:17:34'), t_end_dt=Timestamp('2025-12-03 19:14:02.591341146'), label='Debut_2025-12-03T181734.mp4')

Pandas(Index=528, t_start=Timestamp('2025-12-03 19:14:07'), t_duration=2191.7693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-03T191407.mp4', video_num_frames=65627, video_fps=29.942475662900417, video_width=640, video_height=480, video_file_size=62220475, cache_file_size=62220475, cache_file_mtime=1764809440.7211068, t_start_dt=Timestamp('2025-12-03 19:14:07'), t_end_dt=Timestamp('2025-12-03 19:50:38.769335937'), label='Debut_2025-12-03T191407.mp4')

Pandas(Index=529, t_start=Timestamp('2025-12-04 17:09:27'), t_duration=1857.0253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-04T170927.mp4', video_num_frames=55682, video_fps=29.984512992241, video_width=640, video_height=480, video_file_size=58567821, cache_file_size=58567821, cache_file_mtime=1764888025.6969192, t_start_dt=Timestamp('2025-12-04 17:09:27'), t_end_dt=Timestamp('2025-12-04 17:40:24.025325521'), label='Debut_2025-12-04T170927.mp4')

Pandas(Index=530, t_start=Timestamp('2025-12-09 11:00:19'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T110019.mp4', video_num_frames=107967, video_fps=29.988623342735067, video_width=640, video_height=480, video_file_size=116080956, cache_file_size=116080956, cache_file_mtime=1765299622.9398777, t_start_dt=Timestamp('2025-12-09 11:00:19'), t_end_dt=Timestamp('2025-12-09 12:00:19.265299479'), label='Debut_2025-12-09T110019.mp4')

Pandas(Index=531, t_start=Timestamp('2025-12-09 12:00:27'), t_duration=3600.357356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T120027.mp4', video_num_frames=107814, video_fps=29.945360784046883, video_width=640, video_height=480, video_file_size=110805949, cache_file_size=110805949, cache_file_mtime=1765303229.6036675, t_start_dt=Timestamp('2025-12-09 12:00:27'), t_end_dt=Timestamp('2025-12-09 13:00:27.357356771'), label='Debut_2025-12-09T120027.mp4')

Pandas(Index=532, t_start=Timestamp('2025-12-09 13:00:31'), t_duration=3067.3733072916666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T130031.mp4', video_num_frames=91935, video_fps=29.971898034534927, video_width=640, video_height=480, video_file_size=95218983, cache_file_size=95218983, cache_file_mtime=1765306301.0558107, t_start_dt=Timestamp('2025-12-09 13:00:31'), t_end_dt=Timestamp('2025-12-09 13:51:38.373307292'), label='Debut_2025-12-09T130031.mp4')

Pandas(Index=533, t_start=Timestamp('2025-12-09 14:25:03'), t_duration=6.5953124999999995, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T142503.mp4', video_num_frames=187, video_fps=28.353470741530444, video_width=640, video_height=480, video_file_size=184576, cache_file_size=184576, cache_file_mtime=1765308310.7679925, t_start_dt=Timestamp('2025-12-09 14:25:03'), t_end_dt=Timestamp('2025-12-09 14:25:09.595312500'), label='Debut_2025-12-09T142503.mp4')

Pandas(Index=534, t_start=Timestamp('2025-12-09 14:25:49'), t_duration=3600.237369791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T142549.mp4', video_num_frames=107962, video_fps=29.9874671892113, video_width=640, video_height=480, video_file_size=109273364, cache_file_size=109273364, cache_file_mtime=1765311951.9366553, t_start_dt=Timestamp('2025-12-09 14:25:49'), t_end_dt=Timestamp('2025-12-09 15:25:49.237369792'), label='Debut_2025-12-09T142549.mp4')

Pandas(Index=535, t_start=Timestamp('2025-12-09 15:25:53'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T152553.mp4', video_num_frames=107961, video_fps=29.986956798883185, video_width=640, video_height=480, video_file_size=108093792, cache_file_size=108093792, cache_file_mtime=1765315555.70052, t_start_dt=Timestamp('2025-12-09 15:25:53'), t_end_dt=Timestamp('2025-12-09 16:25:53.265299479'), label='Debut_2025-12-09T152553.mp4')

Pandas(Index=536, t_start=Timestamp('2025-12-09 16:25:56'), t_duration=3600.3033854166665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T162556.mp4', video_num_frames=107896, video_fps=29.96858554671861, video_width=640, video_height=480, video_file_size=108327743, cache_file_size=108327743, cache_file_mtime=1765319158.8086205, t_start_dt=Timestamp('2025-12-09 16:25:56'), t_end_dt=Timestamp('2025-12-09 17:25:56.303385417'), label='Debut_2025-12-09T162556.mp4')

Pandas(Index=537, t_start=Timestamp('2025-12-09 17:25:59'), t_duration=3600.3293619791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T172559.mp4', video_num_frames=107930, video_fps=29.97781290228095, video_width=640, video_height=480, video_file_size=107378733, cache_file_size=107378733, cache_file_mtime=1765322762.8101978, t_start_dt=Timestamp('2025-12-09 17:25:59'), t_end_dt=Timestamp('2025-12-09 18:25:59.329361979'), label='Debut_2025-12-09T172559.mp4')

Pandas(Index=538, t_start=Timestamp('2025-12-09 18:26:04'), t_duration=3600.385286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T182604.mp4', video_num_frames=107970, video_fps=29.988457181539346, video_width=640, video_height=480, video_file_size=107415999, cache_file_size=107415999, cache_file_mtime=1765326366.4704638, t_start_dt=Timestamp('2025-12-09 18:26:04'), t_end_dt=Timestamp('2025-12-09 19:26:04.385286458'), label='Debut_2025-12-09T182604.mp4')

Pandas(Index=539, t_start=Timestamp('2025-12-09 19:26:07'), t_duration=3600.1893229166662, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T192607.mp4', video_num_frames=67888, video_fps=18.85678610507101, video_width=640, video_height=480, video_file_size=101093150, cache_file_size=101093150, cache_file_mtime=1765329969.2237182, t_start_dt=Timestamp('2025-12-09 19:26:07'), t_end_dt=Timestamp('2025-12-09 20:26:07.189322917'), label='Debut_2025-12-09T192607.mp4')

Pandas(Index=540, t_start=Timestamp('2025-12-09 20:26:09'), t_duration=3600.17734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T202609.mp4', video_num_frames=54231, video_fps=15.063424609942174, video_width=640, video_height=480, video_file_size=95774486, cache_file_size=95774486, cache_file_mtime=1765333571.454885, t_start_dt=Timestamp('2025-12-09 20:26:09'), t_end_dt=Timestamp('2025-12-09 21:26:09.177343750'), label='Debut_2025-12-09T202609.mp4')

Pandas(Index=541, t_start=Timestamp('2025-12-09 21:26:11'), t_duration=3600.205338541666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T212611.mp4', video_num_frames=69884, video_fps=19.411115041651453, video_width=640, video_height=480, video_file_size=102804904, cache_file_size=102804904, cache_file_mtime=1765337173.829965, t_start_dt=Timestamp('2025-12-09 21:26:11'), t_end_dt=Timestamp('2025-12-09 22:26:11.205338542'), label='Debut_2025-12-09T212611.mp4')

Pandas(Index=542, t_start=Timestamp('2025-12-09 22:26:14'), t_duration=3600.3013671875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T222614.mp4', video_num_frames=80958, video_fps=22.486450922646828, video_width=640, video_height=480, video_file_size=103106457, cache_file_size=103106457, cache_file_mtime=1765340777.1394947, t_start_dt=Timestamp('2025-12-09 22:26:14'), t_end_dt=Timestamp('2025-12-09 23:26:14.301367188'), label='Debut_2025-12-09T222614.mp4')

Pandas(Index=543, t_start=Timestamp('2025-12-09 23:26:18'), t_duration=30.707356770833336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-09T232618.mp4', video_num_frames=456, video_fps=14.849861660288552, video_width=640, video_height=480, video_file_size=856639, cache_file_size=856639, cache_file_mtime=1765340809.8486283, t_start_dt=Timestamp('2025-12-09 23:26:18'), t_end_dt=Timestamp('2025-12-09 23:26:48.707356771'), label='Debut_2025-12-09T232618.mp4')

Pandas(Index=544, t_start=Timestamp('2025-12-10 01:54:37'), t_duration=3600.2932942708335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-10T015437.mp4', video_num_frames=54725, video_fps=15.200150523037719, video_width=640, video_height=480, video_file_size=99172883, cache_file_size=99172883, cache_file_mtime=1765353280.0241396, t_start_dt=Timestamp('2025-12-10 01:54:37'), t_end_dt=Timestamp('2025-12-10 02:54:37.293294271'), label='Debut_2025-12-10T015437.mp4')

Pandas(Index=545, t_start=Timestamp('2025-12-10 02:54:40'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-10T025440.mp4', video_num_frames=53933, video_fps=14.980035170071165, video_width=640, video_height=480, video_file_size=95427446, cache_file_size=95427446, cache_file_mtime=1765356883.0736375, t_start_dt=Timestamp('2025-12-10 02:54:40'), t_end_dt=Timestamp('2025-12-10 03:54:40.325325521'), label='Debut_2025-12-10T025440.mp4')

Pandas(Index=546, t_start=Timestamp('2025-12-10 03:54:44'), t_duration=3600.3853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-10T035444.mp4', video_num_frames=53997, video_fps=14.997561296200228, video_width=640, video_height=480, video_file_size=94920711, cache_file_size=94920711, cache_file_mtime=1765360486.1795416, t_start_dt=Timestamp('2025-12-10 03:54:44'), t_end_dt=Timestamp('2025-12-10 04:54:44.385351563'), label='Debut_2025-12-10T035444.mp4')

Pandas(Index=547, t_start=Timestamp('2025-12-10 04:54:47'), t_duration=3600.323307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-10T045447.mp4', video_num_frames=53890, video_fps=14.968100195573436, video_width=640, video_height=480, video_file_size=99706015, cache_file_size=99706015, cache_file_mtime=1765364089.223077, t_start_dt=Timestamp('2025-12-10 04:54:47'), t_end_dt=Timestamp('2025-12-10 05:54:47.323307292'), label='Debut_2025-12-10T045447.mp4')

Pandas(Index=548, t_start=Timestamp('2025-12-10 05:54:50'), t_duration=3600.3873046874996, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-10T055450.mp4', video_num_frames=54001, video_fps=14.998664151963252, video_width=640, video_height=480, video_file_size=99953816, cache_file_size=99953816, cache_file_mtime=1765367692.5425582, t_start_dt=Timestamp('2025-12-10 05:54:50'), t_end_dt=Timestamp('2025-12-10 06:54:50.387304687'), label='Debut_2025-12-10T055450.mp4')

Pandas(Index=549, t_start=Timestamp('2025-12-10 06:54:53'), t_duration=3559.6873697916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-10T065453.mp4', video_num_frames=61899, video_fps=17.38888659866293, video_width=640, video_height=480, video_file_size=99998776, cache_file_size=99998776, cache_file_mtime=1765371254.8799503, t_start_dt=Timestamp('2025-12-10 06:54:53'), t_end_dt=Timestamp('2025-12-10 07:54:12.687369792'), label='Debut_2025-12-10T065453.mp4')

Pandas(Index=550, t_start=Timestamp('2025-12-11 00:59:36'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T005936.mp4', video_num_frames=107957, video_fps=29.985845769648595, video_width=640, video_height=480, video_file_size=108854988, cache_file_size=108854988, cache_file_mtime=1765436378.970471, t_start_dt=Timestamp('2025-12-11 00:59:36'), t_end_dt=Timestamp('2025-12-11 01:59:36.265299479'), label='Debut_2025-12-11T005936.mp4')

Pandas(Index=551, t_start=Timestamp('2025-12-11 01:59:40'), t_duration=3600.31328125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T015940.mp4', video_num_frames=107721, video_fps=29.91989629374701, video_width=640, video_height=480, video_file_size=106582079, cache_file_size=106582079, cache_file_mtime=1765439982.646132, t_start_dt=Timestamp('2025-12-11 01:59:40'), t_end_dt=Timestamp('2025-12-11 02:59:40.313281250'), label='Debut_2025-12-11T015940.mp4')

Pandas(Index=552, t_start=Timestamp('2025-12-11 02:59:44'), t_duration=3600.3263671874997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T025944.mp4', video_num_frames=105934, video_fps=29.423443653735603, video_width=640, video_height=480, video_file_size=107170737, cache_file_size=107170737, cache_file_mtime=1765443586.6520612, t_start_dt=Timestamp('2025-12-11 02:59:44'), t_end_dt=Timestamp('2025-12-11 03:59:44.326367187'), label='Debut_2025-12-11T025944.mp4')

Pandas(Index=553, t_start=Timestamp('2025-12-11 03:59:47'), t_duration=3600.3533203125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T035947.mp4', video_num_frames=107752, video_fps=29.928173824519934, video_width=640, video_height=480, video_file_size=108347419, cache_file_size=108347419, cache_file_mtime=1765447190.368524, t_start_dt=Timestamp('2025-12-11 03:59:47'), t_end_dt=Timestamp('2025-12-11 04:59:47.353320313'), label='Debut_2025-12-11T035947.mp4')

Pandas(Index=554, t_start=Timestamp('2025-12-11 04:59:51'), t_duration=3600.307356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T045951.mp4', video_num_frames=107982, video_fps=29.992439339082036, video_width=640, video_height=480, video_file_size=108930163, cache_file_size=108930163, cache_file_mtime=1765450793.805454, t_start_dt=Timestamp('2025-12-11 04:59:51'), t_end_dt=Timestamp('2025-12-11 05:59:51.307356771'), label='Debut_2025-12-11T045951.mp4')

Pandas(Index=555, t_start=Timestamp('2025-12-11 05:59:54'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T055954.mp4', video_num_frames=107655, video_fps=29.901945759345455, video_width=640, video_height=480, video_file_size=108690917, cache_file_size=108690917, cache_file_mtime=1765454397.6655488, t_start_dt=Timestamp('2025-12-11 05:59:54'), t_end_dt=Timestamp('2025-12-11 06:59:54.267382813'), label='Debut_2025-12-11T055954.mp4')

Pandas(Index=556, t_start=Timestamp('2025-12-11 06:59:58'), t_duration=3600.329296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T065958.mp4', video_num_frames=107948, video_fps=29.982812987049904, video_width=640, video_height=480, video_file_size=108448393, cache_file_size=108448393, cache_file_mtime=1765458001.2772295, t_start_dt=Timestamp('2025-12-11 06:59:58'), t_end_dt=Timestamp('2025-12-11 07:59:58.329296875'), label='Debut_2025-12-11T065958.mp4')

Pandas(Index=557, t_start=Timestamp('2025-12-11 08:00:02'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T080002.mp4', video_num_frames=107920, video_fps=29.9755514035443, video_width=640, video_height=480, video_file_size=107066704, cache_file_size=107066704, cache_file_mtime=1765461605.0687397, t_start_dt=Timestamp('2025-12-11 08:00:02'), t_end_dt=Timestamp('2025-12-11 09:00:02.267382812'), label='Debut_2025-12-11T080002.mp4')

Pandas(Index=558, t_start=Timestamp('2025-12-11 09:00:06'), t_duration=3600.215364583333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T090006.mp4', video_num_frames=106863, video_fps=29.682390962288352, video_width=640, video_height=480, video_file_size=107152864, cache_file_size=107152864, cache_file_mtime=1765465209.163847, t_start_dt=Timestamp('2025-12-11 09:00:06'), t_end_dt=Timestamp('2025-12-11 10:00:06.215364583'), label='Debut_2025-12-11T090006.mp4')

Pandas(Index=559, t_start=Timestamp('2025-12-11 10:00:10'), t_duration=1290.8393229166668, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T100010.mp4', video_num_frames=37923, video_fps=29.37855961368804, video_width=640, video_height=480, video_file_size=38813353, cache_file_size=38813353, cache_file_mtime=1765466502.6210954, t_start_dt=Timestamp('2025-12-11 10:00:10'), t_end_dt=Timestamp('2025-12-11 10:21:40.839322917'), label='Debut_2025-12-11T100010.mp4')

Pandas(Index=560, t_start=Timestamp('2025-12-11 16:49:20'), t_duration=3600.2933593750004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T164920.mp4', video_num_frames=107323, video_fps=29.809515305339158, video_width=640, video_height=480, video_file_size=110158184, cache_file_size=110158184, cache_file_mtime=1765493362.5984132, t_start_dt=Timestamp('2025-12-11 16:49:20'), t_end_dt=Timestamp('2025-12-11 17:49:20.293359375'), label='Debut_2025-12-11T164920.mp4')

Pandas(Index=561, t_start=Timestamp('2025-12-11 17:49:23'), t_duration=436.08131510416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-11T174923.mp4', video_num_frames=12951, video_fps=29.698589578199186, video_width=640, video_height=480, video_file_size=13083889, cache_file_size=13083889, cache_file_mtime=1765493800.868373, t_start_dt=Timestamp('2025-12-11 17:49:23'), t_end_dt=Timestamp('2025-12-11 17:56:39.081315104'), label='Debut_2025-12-11T174923.mp4')

Pandas(Index=562, t_start=Timestamp('2025-12-12 05:34:31'), t_duration=3600.265364583333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-12T053431.mp4', video_num_frames=107287, video_fps=29.79974783398128, video_width=640, video_height=480, video_file_size=106040439, cache_file_size=106040439, cache_file_mtime=1765539275.2581518, t_start_dt=Timestamp('2025-12-12 05:34:31'), t_end_dt=Timestamp('2025-12-12 06:34:31.265364583'), label='Debut_2025-12-12T053431.mp4')

Pandas(Index=563, t_start=Timestamp('2025-12-12 06:34:36'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-12T063436.mp4', video_num_frames=107952, video_fps=29.984207024684174, video_width=640, video_height=480, video_file_size=107429090, cache_file_size=107429090, cache_file_mtime=1765542878.8271363, t_start_dt=Timestamp('2025-12-12 06:34:36'), t_end_dt=Timestamp('2025-12-12 07:34:36.295312500'), label='Debut_2025-12-12T063436.mp4')

Pandas(Index=564, t_start=Timestamp('2025-12-12 07:34:40'), t_duration=298.70735677083337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-12T073440.mp4', video_num_frames=8946, video_fps=29.949044766457902, video_width=640, video_height=480, video_file_size=8780362, cache_file_size=8780362, cache_file_mtime=1765543179.6122038, t_start_dt=Timestamp('2025-12-12 07:34:40'), t_end_dt=Timestamp('2025-12-12 07:39:38.707356771'), label='Debut_2025-12-12T073440.mp4')

Pandas(Index=565, t_start=Timestamp('2025-12-12 07:45:35'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-12T074535.mp4', video_num_frames=105593, video_fps=29.329487903561805, video_width=640, video_height=480, video_file_size=107372026, cache_file_size=107372026, cache_file_mtime=1765547138.6282592, t_start_dt=Timestamp('2025-12-12 07:45:35'), t_end_dt=Timestamp('2025-12-12 08:45:35.233333333'), label='Debut_2025-12-12T074535.mp4')

Pandas(Index=566, t_start=Timestamp('2025-12-12 08:45:40'), t_duration=3600.2833333333338, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-12T084540.mp4', video_num_frames=107994, video_fps=29.995972539198302, video_width=640, video_height=480, video_file_size=106956058, cache_file_size=106956058, cache_file_mtime=1765550742.681004, t_start_dt=Timestamp('2025-12-12 08:45:40'), t_end_dt=Timestamp('2025-12-12 09:45:40.283333333'), label='Debut_2025-12-12T084540.mp4')

Pandas(Index=567, t_start=Timestamp('2025-12-12 09:45:43'), t_duration=977.6633463541666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-12T094543.mp4', video_num_frames=29312, video_fps=29.981690639531745, video_width=640, video_height=480, video_file_size=29300421, cache_file_size=29300421, cache_file_mtime=1765551722.3861997, t_start_dt=Timestamp('2025-12-12 09:45:43'), t_end_dt=Timestamp('2025-12-12 10:02:00.663346354'), label='Debut_2025-12-12T094543.mp4')

Pandas(Index=568, t_start=Timestamp('2025-12-12 17:30:55'), t_duration=3600.2353515624995, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-12T173055.mp4', video_num_frames=60801, video_fps=16.88806260224416, video_width=640, video_height=480, video_file_size=105491342, cache_file_size=105491342, cache_file_mtime=1765582257.747544, t_start_dt=Timestamp('2025-12-12 17:30:55'), t_end_dt=Timestamp('2025-12-12 18:30:55.235351562'), label='Debut_2025-12-12T173055.mp4')

Pandas(Index=569, t_start=Timestamp('2025-12-12 18:30:59'), t_duration=733.3893229166667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-12T183059.mp4', video_num_frames=10996, video_fps=14.993400716919695, video_width=640, video_height=480, video_file_size=21340931, cache_file_size=21340931, cache_file_mtime=1765582993.846192, t_start_dt=Timestamp('2025-12-12 18:30:59'), t_end_dt=Timestamp('2025-12-12 18:43:12.389322917'), label='Debut_2025-12-12T183059.mp4')

Pandas(Index=570, t_start=Timestamp('2025-12-12 18:58:05'), t_duration=3286.6153645833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-12T185805.mp4', video_num_frames=49440, video_fps=15.042831154739595, video_width=640, video_height=480, video_file_size=98913901, cache_file_size=98913901, cache_file_mtime=1765587173.3190053, t_start_dt=Timestamp('2025-12-12 18:58:05'), t_end_dt=Timestamp('2025-12-12 19:52:51.615364583'), label='Debut_2025-12-12T185805.mp4')

Pandas(Index=571, t_start=Timestamp('2025-12-15 01:28:55'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T012855.mp4', video_num_frames=107989, video_fps=29.994734003525313, video_width=640, video_height=480, video_file_size=110088572, cache_file_size=110088572, cache_file_mtime=1765783737.9095855, t_start_dt=Timestamp('2025-12-15 01:28:55'), t_end_dt=Timestamp('2025-12-15 02:28:55.265299479'), label='Debut_2025-12-15T012855.mp4')

Pandas(Index=572, t_start=Timestamp('2025-12-15 02:28:58'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T022858.mp4', video_num_frames=107876, video_fps=29.963363682615448, video_width=640, video_height=480, video_file_size=118524480, cache_file_size=118524480, cache_file_mtime=1765787341.1918392, t_start_dt=Timestamp('2025-12-15 02:28:58'), t_end_dt=Timestamp('2025-12-15 03:28:58.263346354'), label='Debut_2025-12-15T022858.mp4')

Pandas(Index=573, t_start=Timestamp('2025-12-15 03:29:02'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T032902.mp4', video_num_frames=107943, video_fps=29.98195716732753, video_width=640, video_height=480, video_file_size=112640902, cache_file_size=112640902, cache_file_mtime=1765790944.7182572, t_start_dt=Timestamp('2025-12-15 03:29:02'), t_end_dt=Timestamp('2025-12-15 04:29:02.265299479'), label='Debut_2025-12-15T032902.mp4')

Pandas(Index=574, t_start=Timestamp('2025-12-15 04:29:05'), t_duration=3600.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T042905.mp4', video_num_frames=107529, video_fps=29.867197341552604, video_width=640, video_height=480, video_file_size=110310039, cache_file_size=110310039, cache_file_mtime=1765794548.5530424, t_start_dt=Timestamp('2025-12-15 04:29:05'), t_end_dt=Timestamp('2025-12-15 05:29:05.237369792'), label='Debut_2025-12-15T042905.mp4')

Pandas(Index=575, t_start=Timestamp('2025-12-15 05:29:10'), t_duration=3600.3073567708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T052910.mp4', video_num_frames=107963, video_fps=29.987162011865994, video_width=640, video_height=480, video_file_size=109926105, cache_file_size=109926105, cache_file_mtime=1765798152.4557226, t_start_dt=Timestamp('2025-12-15 05:29:10'), t_end_dt=Timestamp('2025-12-15 06:29:10.307356771'), label='Debut_2025-12-15T052910.mp4')

Pandas(Index=576, t_start=Timestamp('2025-12-15 06:29:13'), t_duration=3153.5753255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T062913.mp4', video_num_frames=94354, video_fps=29.91969122678775, video_width=640, video_height=480, video_file_size=94381459, cache_file_size=94381459, cache_file_mtime=1765801362.981758, t_start_dt=Timestamp('2025-12-15 06:29:13'), t_end_dt=Timestamp('2025-12-15 07:21:46.575325521'), label='Debut_2025-12-15T062913.mp4')

Pandas(Index=577, t_start=Timestamp('2025-12-15 12:25:08'), t_duration=3600.4152994791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T122508.mp4', video_num_frames=107869, video_fps=29.960154878689757, video_width=640, video_height=480, video_file_size=106650428, cache_file_size=106650428, cache_file_mtime=1765823110.4742641, t_start_dt=Timestamp('2025-12-15 12:25:08'), t_end_dt=Timestamp('2025-12-15 13:25:08.415299479'), label='Debut_2025-12-15T122508.mp4')

Pandas(Index=578, t_start=Timestamp('2025-12-15 13:25:11'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T132511.mp4', video_num_frames=105551, video_fps=29.31780555795913, video_width=640, video_height=480, video_file_size=106461116, cache_file_size=106461116, cache_file_mtime=1765826714.9609063, t_start_dt=Timestamp('2025-12-15 13:25:11'), t_end_dt=Timestamp('2025-12-15 14:25:11.235351562'), label='Debut_2025-12-15T132511.mp4')

Pandas(Index=579, t_start=Timestamp('2025-12-15 14:25:48'), t_duration=2.42734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T142548.mp4', video_num_frames=52, video_fps=21.422594142259413, video_width=640, video_height=480, video_file_size=76679, cache_file_size=76679, cache_file_mtime=1765826751.1991193, t_start_dt=Timestamp('2025-12-15 14:25:48'), t_end_dt=Timestamp('2025-12-15 14:25:50.427343750'), label='Debut_2025-12-15T142548.mp4')

Pandas(Index=580, t_start=Timestamp('2025-12-15 19:28:03'), t_duration=1694.4553385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T192803.mp4', video_num_frames=50789, video_fps=29.973643355930268, video_width=640, video_height=480, video_file_size=49856832, cache_file_size=49856832, cache_file_mtime=1765846578.8712363, t_start_dt=Timestamp('2025-12-15 19:28:03'), t_end_dt=Timestamp('2025-12-15 19:56:17.455338542'), label='Debut_2025-12-15T192803.mp4')

Pandas(Index=581, t_start=Timestamp('2025-12-15 19:56:21'), t_duration=422.27532552083335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-15T195621.mp4', video_num_frames=12653, video_fps=29.963862994821735, video_width=640, video_height=480, video_file_size=12627031, cache_file_size=12627031, cache_file_mtime=1765847004.9096017, t_start_dt=Timestamp('2025-12-15 19:56:21'), t_end_dt=Timestamp('2025-12-15 20:03:23.275325521'), label='Debut_2025-12-15T195621.mp4')

Pandas(Index=582, t_start=Timestamp('2025-12-16 01:20:38'), t_duration=3600.2033203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T012038.mp4', video_num_frames=54009, video_fps=15.001652738688097, video_width=640, video_height=480, video_file_size=98383143, cache_file_size=98383143, cache_file_mtime=1765869640.7446353, t_start_dt=Timestamp('2025-12-16 01:20:38'), t_end_dt=Timestamp('2025-12-16 02:20:38.203320313'), label='Debut_2025-12-16T012038.mp4')

Pandas(Index=583, t_start=Timestamp('2025-12-16 02:20:41'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T022041.mp4', video_num_frames=53930, video_fps=14.979451384479109, video_width=640, video_height=480, video_file_size=98281629, cache_file_size=98281629, cache_file_mtime=1765873243.6920228, t_start_dt=Timestamp('2025-12-16 02:20:41'), t_end_dt=Timestamp('2025-12-16 03:20:41.265364583'), label='Debut_2025-12-16T022041.mp4')

Pandas(Index=584, t_start=Timestamp('2025-12-16 03:20:44'), t_duration=3600.325390625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T032044.mp4', video_num_frames=53996, video_fps=14.997533317572316, video_width=640, video_height=480, video_file_size=98136600, cache_file_size=98136600, cache_file_mtime=1765876846.5459988, t_start_dt=Timestamp('2025-12-16 03:20:44'), t_end_dt=Timestamp('2025-12-16 04:20:44.325390625'), label='Debut_2025-12-16T032044.mp4')

Pandas(Index=585, t_start=Timestamp('2025-12-16 04:20:47'), t_duration=777.4733723958334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T042047.mp4', video_num_frames=11102, video_fps=14.279588721847135, video_width=640, video_height=480, video_file_size=21017528, cache_file_size=21017528, cache_file_mtime=1765877626.1195197, t_start_dt=Timestamp('2025-12-16 04:20:47'), t_end_dt=Timestamp('2025-12-16 04:33:44.473372396'), label='Debut_2025-12-16T042047.mp4')

Pandas(Index=586, t_start=Timestamp('2025-12-16 06:31:28'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T063128.mp4', video_num_frames=53914, video_fps=14.97501566228382, video_width=640, video_height=480, video_file_size=96097865, cache_file_size=96097865, cache_file_mtime=1765888290.5411668, t_start_dt=Timestamp('2025-12-16 06:31:28'), t_end_dt=Timestamp('2025-12-16 07:31:28.263346354'), label='Debut_2025-12-16T063128.mp4')

Pandas(Index=587, t_start=Timestamp('2025-12-16 07:31:31'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T073131.mp4', video_num_frames=87363, video_fps=24.265495867338938, video_width=640, video_height=480, video_file_size=102698755, cache_file_size=102698755, cache_file_mtime=1765891893.3840847, t_start_dt=Timestamp('2025-12-16 07:31:31'), t_end_dt=Timestamp('2025-12-16 08:31:31.297330729'), label='Debut_2025-12-16T073131.mp4')

Pandas(Index=588, t_start=Timestamp('2025-12-16 08:31:34'), t_duration=3600.2993489583337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T083134.mp4', video_num_frames=107986, video_fps=29.993617067215077, video_width=640, video_height=480, video_file_size=103473431, cache_file_size=103473431, cache_file_mtime=1765895496.6744828, t_start_dt=Timestamp('2025-12-16 08:31:34'), t_end_dt=Timestamp('2025-12-16 09:31:34.299348958'), label='Debut_2025-12-16T083134.mp4')

Pandas(Index=589, t_start=Timestamp('2025-12-16 09:31:37'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T093137.mp4', video_num_frames=107969, video_fps=29.98891204858713, video_width=640, video_height=480, video_file_size=105525492, cache_file_size=105525492, cache_file_mtime=1765899100.1822295, t_start_dt=Timestamp('2025-12-16 09:31:37'), t_end_dt=Timestamp('2025-12-16 10:31:37.297330729'), label='Debut_2025-12-16T093137.mp4')

Pandas(Index=590, t_start=Timestamp('2025-12-16 10:31:41'), t_duration=3600.329296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T103141.mp4', video_num_frames=101836, video_fps=28.28519049310051, video_width=640, video_height=480, video_file_size=105199340, cache_file_size=105199340, cache_file_mtime=1765902703.6672688, t_start_dt=Timestamp('2025-12-16 10:31:41'), t_end_dt=Timestamp('2025-12-16 11:31:41.329296875'), label='Debut_2025-12-16T103141.mp4')

Pandas(Index=591, t_start=Timestamp('2025-12-16 11:31:45'), t_duration=3600.3853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T113145.mp4', video_num_frames=107681, video_fps=29.908187453675882, video_width=640, video_height=480, video_file_size=106815271, cache_file_size=106815271, cache_file_mtime=1765906308.879641, t_start_dt=Timestamp('2025-12-16 11:31:45'), t_end_dt=Timestamp('2025-12-16 12:31:45.385351563'), label='Debut_2025-12-16T113145.mp4')

Pandas(Index=592, t_start=Timestamp('2025-12-16 12:31:52'), t_duration=818.8733072916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T123152.mp4', video_num_frames=23718, video_fps=28.96418748639478, video_width=640, video_height=480, video_file_size=24075243, cache_file_size=24075243, cache_file_mtime=1765907445.5362923, t_start_dt=Timestamp('2025-12-16 12:31:52'), t_end_dt=Timestamp('2025-12-16 12:45:30.873307292'), label='Debut_2025-12-16T123152.mp4')

Pandas(Index=593, t_start=Timestamp('2025-12-16 15:47:26'), t_duration=3600.3233723958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T154726.mp4', video_num_frames=107635, video_fps=29.89592568969002, video_width=640, video_height=480, video_file_size=107480643, cache_file_size=107480643, cache_file_mtime=1765921649.323063, t_start_dt=Timestamp('2025-12-16 15:47:26'), t_end_dt=Timestamp('2025-12-16 16:47:26.323372396'), label='Debut_2025-12-16T154726.mp4')

Pandas(Index=594, t_start=Timestamp('2025-12-16 16:47:30'), t_duration=3600.239322916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T164730.mp4', video_num_frames=97431, video_fps=27.06236759868177, video_width=640, video_height=480, video_file_size=105204054, cache_file_size=105204054, cache_file_mtime=1765925252.4617367, t_start_dt=Timestamp('2025-12-16 16:47:30'), t_end_dt=Timestamp('2025-12-16 17:47:30.239322917'), label='Debut_2025-12-16T164730.mp4')

Pandas(Index=595, t_start=Timestamp('2025-12-16 17:47:33'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T174733.mp4', video_num_frames=90385, video_fps=25.105079814764192, video_width=640, video_height=480, video_file_size=104610573, cache_file_size=104610573, cache_file_mtime=1765928855.588035, t_start_dt=Timestamp('2025-12-16 17:47:33'), t_end_dt=Timestamp('2025-12-16 18:47:33.267382812'), label='Debut_2025-12-16T174733.mp4')

Pandas(Index=596, t_start=Timestamp('2025-12-16 18:47:36'), t_duration=3600.323307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T184736.mp4', video_num_frames=107589, video_fps=29.883149599954546, video_width=640, video_height=480, video_file_size=107270557, cache_file_size=107270557, cache_file_mtime=1765932459.960935, t_start_dt=Timestamp('2025-12-16 18:47:36'), t_end_dt=Timestamp('2025-12-16 19:47:36.323307292'), label='Debut_2025-12-16T184736.mp4')

Pandas(Index=597, t_start=Timestamp('2025-12-16 19:47:40'), t_duration=577.5853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-16T194740.mp4', video_num_frames=16402, video_fps=28.39753459056545, video_width=640, video_height=480, video_file_size=17816940, cache_file_size=17816940, cache_file_mtime=1765933039.3431485, t_start_dt=Timestamp('2025-12-16 19:47:40'), t_end_dt=Timestamp('2025-12-16 19:57:17.585351563'), label='Debut_2025-12-16T194740.mp4')

Pandas(Index=598, t_start=Timestamp('2025-12-17 06:48:38'), t_duration=3600.325390625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T064838.mp4', video_num_frames=53996, video_fps=14.997533317572316, video_width=640, video_height=480, video_file_size=99317028, cache_file_size=99317028, cache_file_mtime=1765975720.5657187, t_start_dt=Timestamp('2025-12-17 06:48:38'), t_end_dt=Timestamp('2025-12-17 07:48:38.325390625'), label='Debut_2025-12-17T064838.mp4')

Pandas(Index=599, t_start=Timestamp('2025-12-17 07:48:41'), t_duration=3600.383333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T074841.mp4', video_num_frames=53995, video_fps=14.99701420682057, video_width=640, video_height=480, video_file_size=99108014, cache_file_size=99108014, cache_file_mtime=1765979323.8263752, t_start_dt=Timestamp('2025-12-17 07:48:41'), t_end_dt=Timestamp('2025-12-17 08:48:41.383333333'), label='Debut_2025-12-17T074841.mp4')

Pandas(Index=600, t_start=Timestamp('2025-12-17 08:48:44'), t_duration=3600.301302083333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T084844.mp4', video_num_frames=53665, video_fps=14.905696911796372, video_width=640, video_height=480, video_file_size=98331633, cache_file_size=98331633, cache_file_mtime=1765982927.28339, t_start_dt=Timestamp('2025-12-17 08:48:44'), t_end_dt=Timestamp('2025-12-17 09:48:44.301302083'), label='Debut_2025-12-17T084844.mp4')

Pandas(Index=601, t_start=Timestamp('2025-12-17 09:48:48'), t_duration=1108.9173828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T094848.mp4', video_num_frames=16625, video_fps=14.992099734098062, video_width=640, video_height=480, video_file_size=30623537, cache_file_size=30623537, cache_file_mtime=1765984038.4379883, t_start_dt=Timestamp('2025-12-17 09:48:48'), t_end_dt=Timestamp('2025-12-17 10:07:16.917382812'), label='Debut_2025-12-17T094848.mp4')

Pandas(Index=602, t_start=Timestamp('2025-12-17 15:36:23'), t_duration=3600.4453125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T153623.mp4', video_num_frames=107930, video_fps=29.976847481973802, video_width=640, video_height=480, video_file_size=107009982, cache_file_size=107009982, cache_file_mtime=1766007386.2321012, t_start_dt=Timestamp('2025-12-17 15:36:23'), t_end_dt=Timestamp('2025-12-17 16:36:23.445312500'), label='Debut_2025-12-17T153623.mp4')

Pandas(Index=603, t_start=Timestamp('2025-12-17 16:36:27'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T163627.mp4', video_num_frames=107945, video_fps=29.982245932487455, video_width=640, video_height=480, video_file_size=105843714, cache_file_size=105843714, cache_file_mtime=1766010990.2422051, t_start_dt=Timestamp('2025-12-17 16:36:27'), t_end_dt=Timestamp('2025-12-17 17:36:27.297330729'), label='Debut_2025-12-17T163627.mp4')

Pandas(Index=604, t_start=Timestamp('2025-12-17 17:36:32'), t_duration=3600.3273437499997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T173632.mp4', video_num_frames=107963, video_fps=29.986995540119075, video_width=640, video_height=480, video_file_size=105555472, cache_file_size=105555472, cache_file_mtime=1766014594.4988067, t_start_dt=Timestamp('2025-12-17 17:36:32'), t_end_dt=Timestamp('2025-12-17 18:36:32.327343750'), label='Debut_2025-12-17T173632.mp4')

Pandas(Index=605, t_start=Timestamp('2025-12-17 18:36:36'), t_duration=1190.3653645833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T183636.mp4', video_num_frames=35688, video_fps=29.980711016816223, video_width=640, video_height=480, video_file_size=35194248, cache_file_size=35194248, cache_file_mtime=1766015788.0068016, t_start_dt=Timestamp('2025-12-17 18:36:36'), t_end_dt=Timestamp('2025-12-17 18:56:26.365364583'), label='Debut_2025-12-17T183636.mp4')

Pandas(Index=606, t_start=Timestamp('2025-12-17 19:36:04'), t_duration=21.875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Record_2025-12-17T193604.mp4', video_num_frames=525, video_fps=24.0, video_width=1280, video_height=720, video_file_size=11086152, cache_file_size=11086152, cache_file_mtime=1766018216.9048977, t_start_dt=Timestamp('2025-12-17 19:36:04'), t_end_dt=Timestamp('2025-12-17 19:36:25.875000'), label='Record_2025-12-17T193604.mp4')

Pandas(Index=607, t_start=Timestamp('2025-12-17 19:40:00'), t_duration=15.625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Record_2025-12-17T194000.mp4', video_num_frames=375, video_fps=24.0, video_width=1280, video_height=720, video_file_size=7446157, cache_file_size=7446157, cache_file_mtime=1766018438.056123, t_start_dt=Timestamp('2025-12-17 19:40:00'), t_end_dt=Timestamp('2025-12-17 19:40:15.625000'), label='Record_2025-12-17T194000.mp4')

Pandas(Index=608, t_start=Timestamp('2025-12-17 19:41:33'), t_duration=43.625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Record_2025-12-17T194133.mp4', video_num_frames=1047, video_fps=24.0, video_width=1280, video_height=720, video_file_size=21118365, cache_file_size=21118365, cache_file_mtime=1766018597.583389, t_start_dt=Timestamp('2025-12-17 19:41:33'), t_end_dt=Timestamp('2025-12-17 19:42:16.625000'), label='Record_2025-12-17T194133.mp4')

Pandas(Index=609, t_start=Timestamp('2025-12-17 19:44:16'), t_duration=45.865299479166666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T194416.mp4', video_num_frames=1363, video_fps=29.71745558140558, video_width=640, video_height=480, video_file_size=1335016, cache_file_size=1335016, cache_file_mtime=1766018703.2500024, t_start_dt=Timestamp('2025-12-17 19:44:16'), t_end_dt=Timestamp('2025-12-17 19:45:01.865299479'), label='Debut_2025-12-17T194416.mp4')

Pandas(Index=610, t_start=Timestamp('2025-12-17 21:17:36'), t_duration=1055.1253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-17T211736.mp4', video_num_frames=31601, video_fps=29.949996683475533, video_width=640, video_height=480, video_file_size=34405141, cache_file_size=34405141, cache_file_mtime=1766025312.2887154, t_start_dt=Timestamp('2025-12-17 21:17:36'), t_end_dt=Timestamp('2025-12-17 21:35:11.125325521'), label='Debut_2025-12-17T211736.mp4')

Pandas(Index=611, t_start=Timestamp('2025-12-18 01:53:34'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T015334.mp4', video_num_frames=107710, video_fps=29.917255944366772, video_width=640, video_height=480, video_file_size=104651279, cache_file_size=104651279, cache_file_mtime=1766044417.316194, t_start_dt=Timestamp('2025-12-18 01:53:34'), t_end_dt=Timestamp('2025-12-18 02:53:34.263346354'), label='Debut_2025-12-18T015334.mp4')

Pandas(Index=612, t_start=Timestamp('2025-12-18 02:53:38'), t_duration=3600.2693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T025338.mp4', video_num_frames=107988, video_fps=29.994422617795685, video_width=640, video_height=480, video_file_size=104195466, cache_file_size=104195466, cache_file_mtime=1766048020.7886965, t_start_dt=Timestamp('2025-12-18 02:53:38'), t_end_dt=Timestamp('2025-12-18 03:53:38.269335937'), label='Debut_2025-12-18T025338.mp4')

Pandas(Index=613, t_start=Timestamp('2025-12-18 03:53:42'), t_duration=3600.293359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T035342.mp4', video_num_frames=107949, video_fps=29.983390025400492, video_width=640, video_height=480, video_file_size=104206802, cache_file_size=104206802, cache_file_mtime=1766051624.4689498, t_start_dt=Timestamp('2025-12-18 03:53:42'), t_end_dt=Timestamp('2025-12-18 04:53:42.293359375'), label='Debut_2025-12-18T035342.mp4')

Pandas(Index=614, t_start=Timestamp('2025-12-18 04:53:45'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T045345.mp4', video_num_frames=107939, video_fps=29.980596209772724, video_width=640, video_height=480, video_file_size=104246429, cache_file_size=104246429, cache_file_mtime=1766055227.783781, t_start_dt=Timestamp('2025-12-18 04:53:45'), t_end_dt=Timestamp('2025-12-18 05:53:45.295312500'), label='Debut_2025-12-18T045345.mp4')

Pandas(Index=615, t_start=Timestamp('2025-12-18 05:53:49'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T055349.mp4', video_num_frames=107971, video_fps=29.98923437130799, video_width=640, video_height=480, video_file_size=103398385, cache_file_size=103398385, cache_file_mtime=1766058831.3345814, t_start_dt=Timestamp('2025-12-18 05:53:49'), t_end_dt=Timestamp('2025-12-18 06:53:49.325325521'), label='Debut_2025-12-18T055349.mp4')

Pandas(Index=616, t_start=Timestamp('2025-12-18 06:53:52'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T065352.mp4', video_num_frames=107983, video_fps=29.993067459673426, video_width=640, video_height=480, video_file_size=103160688, cache_file_size=103160688, cache_file_mtime=1766062434.7752533, t_start_dt=Timestamp('2025-12-18 06:53:52'), t_end_dt=Timestamp('2025-12-18 07:53:52.265299479'), label='Debut_2025-12-18T065352.mp4')

Pandas(Index=617, t_start=Timestamp('2025-12-18 07:53:55'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T075355.mp4', video_num_frames=107974, video_fps=29.990567643895602, video_width=640, video_height=480, video_file_size=103052448, cache_file_size=103052448, cache_file_mtime=1766066038.145577, t_start_dt=Timestamp('2025-12-18 07:53:55'), t_end_dt=Timestamp('2025-12-18 08:53:55.265299479'), label='Debut_2025-12-18T075355.mp4')

Pandas(Index=618, t_start=Timestamp('2025-12-18 08:53:59'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T085359.mp4', video_num_frames=107771, video_fps=29.93391659076479, video_width=640, video_height=480, video_file_size=104541715, cache_file_size=104541715, cache_file_mtime=1766069641.8588178, t_start_dt=Timestamp('2025-12-18 08:53:59'), t_end_dt=Timestamp('2025-12-18 09:53:59.297330729'), label='Debut_2025-12-18T085359.mp4')

Pandas(Index=619, t_start=Timestamp('2025-12-18 09:54:03'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T095403.mp4', video_num_frames=107918, video_fps=29.974746551875317, video_width=640, video_height=480, video_file_size=102548182, cache_file_size=102548182, cache_file_mtime=1766073245.659768, t_start_dt=Timestamp('2025-12-18 09:54:03'), t_end_dt=Timestamp('2025-12-18 10:54:03.297330729'), label='Debut_2025-12-18T095403.mp4')

Pandas(Index=620, t_start=Timestamp('2025-12-18 10:54:06'), t_duration=3600.2352864583336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T105406.mp4', video_num_frames=107957, video_fps=29.986095743814776, video_width=640, video_height=480, video_file_size=104164620, cache_file_size=104164620, cache_file_mtime=1766076849.0724802, t_start_dt=Timestamp('2025-12-18 10:54:06'), t_end_dt=Timestamp('2025-12-18 11:54:06.235286458'), label='Debut_2025-12-18T105406.mp4')

Pandas(Index=621, t_start=Timestamp('2025-12-18 11:54:10'), t_duration=3600.3573567708336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T115410.mp4', video_num_frames=107947, video_fps=29.982301561536616, video_width=640, video_height=480, video_file_size=103932530, cache_file_size=103932530, cache_file_mtime=1766080453.0737317, t_start_dt=Timestamp('2025-12-18 11:54:10'), t_end_dt=Timestamp('2025-12-18 12:54:10.357356771'), label='Debut_2025-12-18T115410.mp4')

Pandas(Index=622, t_start=Timestamp('2025-12-18 12:54:18'), t_duration=1263.9853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T125418.mp4', video_num_frames=37900, video_fps=29.98452470445894, video_width=640, video_height=480, video_file_size=36534665, cache_file_size=36534665, cache_file_mtime=1766081723.9911914, t_start_dt=Timestamp('2025-12-18 12:54:18'), t_end_dt=Timestamp('2025-12-18 13:15:21.985351562'), label='Debut_2025-12-18T125418.mp4')

Pandas(Index=623, t_start=Timestamp('2025-12-18 19:50:10'), t_duration=863.3053385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-18T195010.mp4', video_num_frames=25758, video_fps=29.83648872542772, video_width=640, video_height=480, video_file_size=26632576, cache_file_size=26632576, cache_file_mtime=1766106276.2521434, t_start_dt=Timestamp('2025-12-18 19:50:10'), t_end_dt=Timestamp('2025-12-18 20:04:33.305338542'), label='Debut_2025-12-18T195010.mp4')

Pandas(Index=624, t_start=Timestamp('2025-12-19 09:25:08'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-19T092508.mp4', video_num_frames=107829, video_fps=29.95004316052199, video_width=640, video_height=480, video_file_size=116871020, cache_file_size=116871020, cache_file_mtime=1766157910.72242, t_start_dt=Timestamp('2025-12-19 09:25:08'), t_end_dt=Timestamp('2025-12-19 10:25:08.295312500'), label='Debut_2025-12-19T092508.mp4')

Pandas(Index=625, t_start=Timestamp('2025-12-19 10:25:12'), t_duration=1291.2293619791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-19T102512.mp4', video_num_frames=38717, video_fps=29.98460315420296, video_width=640, video_height=480, video_file_size=41046401, cache_file_size=41046401, cache_file_mtime=1766159204.789118, t_start_dt=Timestamp('2025-12-19 10:25:12'), t_end_dt=Timestamp('2025-12-19 10:46:43.229361979'), label='Debut_2025-12-19T102512.mp4')

Pandas(Index=626, t_start=Timestamp('2025-12-19 16:46:12'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-19T164612.mp4', video_num_frames=107759, video_fps=29.930849822536405, video_width=640, video_height=480, video_file_size=112244193, cache_file_size=112244193, cache_file_mtime=1766184375.4488342, t_start_dt=Timestamp('2025-12-19 16:46:12'), t_end_dt=Timestamp('2025-12-19 17:46:12.265299479'), label='Debut_2025-12-19T164612.mp4')

Pandas(Index=627, t_start=Timestamp('2025-12-19 17:46:16'), t_duration=583.4932942708333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-19T174616.mp4', video_num_frames=17465, video_fps=29.931792141373734, video_width=640, video_height=480, video_file_size=18290188, cache_file_size=18290188, cache_file_mtime=1766184961.2945263, t_start_dt=Timestamp('2025-12-19 17:46:16'), t_end_dt=Timestamp('2025-12-19 17:55:59.493294271'), label='Debut_2025-12-19T174616.mp4')

Pandas(Index=628, t_start=Timestamp('2025-12-22 05:53:35'), t_duration=3600.5352864583333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T055335.mp4', video_num_frames=107930, video_fps=29.976098389016304, video_width=640, video_height=480, video_file_size=115003441, cache_file_size=115003441, cache_file_mtime=1766404418.041162, t_start_dt=Timestamp('2025-12-22 05:53:35'), t_end_dt=Timestamp('2025-12-22 06:53:35.535286457'), label='Debut_2025-12-22T055335.mp4')

Pandas(Index=629, t_start=Timestamp('2025-12-22 06:53:39'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T065339.mp4', video_num_frames=107208, video_fps=29.777557309751934, video_width=640, video_height=480, video_file_size=116514371, cache_file_size=116514371, cache_file_mtime=1766408021.881415, t_start_dt=Timestamp('2025-12-22 06:53:39'), t_end_dt=Timestamp('2025-12-22 07:53:39.295312500'), label='Debut_2025-12-22T065339.mp4')

Pandas(Index=630, t_start=Timestamp('2025-12-22 07:53:43'), t_duration=3600.3293619791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T075343.mp4', video_num_frames=107895, video_fps=29.96809156945801, video_width=640, video_height=480, video_file_size=119055906, cache_file_size=119055906, cache_file_mtime=1766411626.231218, t_start_dt=Timestamp('2025-12-22 07:53:43'), t_end_dt=Timestamp('2025-12-22 08:53:43.329361979'), label='Debut_2025-12-22T075343.mp4')

Pandas(Index=631, t_start=Timestamp('2025-12-22 08:53:48'), t_duration=3601.1053385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T085348.mp4', video_num_frames=101144, video_fps=28.086931786605305, video_width=640, video_height=480, video_file_size=116159177, cache_file_size=116159177, cache_file_mtime=1766415230.623572, t_start_dt=Timestamp('2025-12-22 08:53:48'), t_end_dt=Timestamp('2025-12-22 09:53:49.105338542'), label='Debut_2025-12-22T085348.mp4')

Pandas(Index=632, t_start=Timestamp('2025-12-22 09:53:51'), t_duration=3600.286328125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T095351.mp4', video_num_frames=107975, video_fps=29.990670229895994, video_width=640, video_height=480, video_file_size=115447137, cache_file_size=115447137, cache_file_mtime=1766418834.415509, t_start_dt=Timestamp('2025-12-22 09:53:51'), t_end_dt=Timestamp('2025-12-22 10:53:51.286328125'), label='Debut_2025-12-22T095351.mp4')

Pandas(Index=633, t_start=Timestamp('2025-12-22 10:53:55'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T105355.mp4', video_num_frames=107890, video_fps=29.967236029969218, video_width=640, video_height=480, video_file_size=114970322, cache_file_size=114970322, cache_file_mtime=1766422438.5550349, t_start_dt=Timestamp('2025-12-22 10:53:55'), t_end_dt=Timestamp('2025-12-22 11:53:55.265299479'), label='Debut_2025-12-22T105355.mp4')

Pandas(Index=634, t_start=Timestamp('2025-12-22 11:54:01'), t_duration=1206.079296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T115401.mp4', video_num_frames=36010, video_fps=29.857074981142084, video_width=640, video_height=480, video_file_size=38131666, cache_file_size=38131666, cache_file_mtime=1766423648.1459124, t_start_dt=Timestamp('2025-12-22 11:54:01'), t_end_dt=Timestamp('2025-12-22 12:14:07.079296875'), label='Debut_2025-12-22T115401.mp4')

Pandas(Index=635, t_start=Timestamp('2025-12-22 14:45:48'), t_duration=3600.3873697916665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T144548.mp4', video_num_frames=107683, video_fps=29.908726184158063, video_width=640, video_height=480, video_file_size=109986513, cache_file_size=109986513, cache_file_mtime=1766436351.487752, t_start_dt=Timestamp('2025-12-22 14:45:48'), t_end_dt=Timestamp('2025-12-22 15:45:48.387369792'), label='Debut_2025-12-22T144548.mp4')

Pandas(Index=636, t_start=Timestamp('2025-12-22 15:45:53'), t_duration=3600.423372395833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T154553.mp4', video_num_frames=107432, video_fps=29.838713086819958, video_width=640, video_height=480, video_file_size=108406335, cache_file_size=108406335, cache_file_mtime=1766439955.825365, t_start_dt=Timestamp('2025-12-22 15:45:53'), t_end_dt=Timestamp('2025-12-22 16:45:53.423372396'), label='Debut_2025-12-22T154553.mp4')

Pandas(Index=637, t_start=Timestamp('2025-12-22 16:45:57'), t_duration=1876.479296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T164557.mp4', video_num_frames=51559, video_fps=27.47645555475295, video_width=640, video_height=480, video_file_size=55528126, cache_file_size=55528126, cache_file_mtime=1766441835.413347, t_start_dt=Timestamp('2025-12-22 16:45:57'), t_end_dt=Timestamp('2025-12-22 17:17:13.479296875'), label='Debut_2025-12-22T164557.mp4')

Pandas(Index=638, t_start=Timestamp('2025-12-22 21:09:47'), t_duration=3600.5652994791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T210947.mp4', video_num_frames=106524, video_fps=29.585354281842644, video_width=640, video_height=480, video_file_size=105455663, cache_file_size=105455663, cache_file_mtime=1766459390.1850123, t_start_dt=Timestamp('2025-12-22 21:09:47'), t_end_dt=Timestamp('2025-12-22 22:09:47.565299479'), label='Debut_2025-12-22T210947.mp4')

Pandas(Index=639, t_start=Timestamp('2025-12-22 22:10:00'), t_duration=3600.596354166667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T221000.mp4', video_num_frames=106514, video_fps=29.582321794205097, video_width=640, video_height=480, video_file_size=105627534, cache_file_size=105627534, cache_file_mtime=1766463003.0675578, t_start_dt=Timestamp('2025-12-22 22:10:00'), t_end_dt=Timestamp('2025-12-22 23:10:00.596354167'), label='Debut_2025-12-22T221000.mp4')

Pandas(Index=640, t_start=Timestamp('2025-12-22 23:10:05'), t_duration=3601.1673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-22T231005.mp4', video_num_frames=106527, video_fps=29.581240935488747, video_width=640, video_height=480, video_file_size=104727662, cache_file_size=104727662, cache_file_mtime=1766466608.7918282, t_start_dt=Timestamp('2025-12-22 23:10:05'), t_end_dt=Timestamp('2025-12-23 00:10:06.167382812'), label='Debut_2025-12-22T231005.mp4')

Pandas(Index=641, t_start=Timestamp('2025-12-23 00:10:11'), t_duration=3600.925325520833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-23T001011.mp4', video_num_frames=106495, video_fps=29.574342807177402, video_width=640, video_height=480, video_file_size=105353216, cache_file_size=105353216, cache_file_mtime=1766470213.8648427, t_start_dt=Timestamp('2025-12-23 00:10:11'), t_end_dt=Timestamp('2025-12-23 01:10:11.925325521'), label='Debut_2025-12-23T001011.mp4')

Pandas(Index=642, t_start=Timestamp('2025-12-23 01:10:15'), t_duration=3600.6573567708333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-23T011015.mp4', video_num_frames=106506, video_fps=29.579598791793245, video_width=640, video_height=480, video_file_size=103853847, cache_file_size=103853847, cache_file_mtime=1766473818.3979237, t_start_dt=Timestamp('2025-12-23 01:10:15'), t_end_dt=Timestamp('2025-12-23 02:10:15.657356771'), label='Debut_2025-12-23T011015.mp4')

Pandas(Index=643, t_start=Timestamp('2025-12-23 02:10:20'), t_duration=264.5413411458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-23T021020.mp4', video_num_frames=7682, video_fps=29.038939497041238, video_width=640, video_height=480, video_file_size=7520356, cache_file_size=7520356, cache_file_mtime=1766474085.6576307, t_start_dt=Timestamp('2025-12-23 02:10:20'), t_end_dt=Timestamp('2025-12-23 02:14:44.541341146'), label='Debut_2025-12-23T021020.mp4')

Pandas(Index=644, t_start=Timestamp('2025-12-23 13:37:42'), t_duration=3600.6533203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-23T133742.mp4', video_num_frames=106219, video_fps=29.499924194529584, video_width=640, video_height=480, video_file_size=107364127, cache_file_size=107364127, cache_file_mtime=1766518664.901502, t_start_dt=Timestamp('2025-12-23 13:37:42'), t_end_dt=Timestamp('2025-12-23 14:37:42.653320312'), label='Debut_2025-12-23T133742.mp4')

Pandas(Index=645, t_start=Timestamp('2025-12-23 14:37:47'), t_duration=3601.1693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-23T143747.mp4', video_num_frames=101843, video_fps=28.280536264615005, video_width=640, video_height=480, video_file_size=107395924, cache_file_size=107395924, cache_file_mtime=1766522270.1006248, t_start_dt=Timestamp('2025-12-23 14:37:47'), t_end_dt=Timestamp('2025-12-23 15:37:48.169335937'), label='Debut_2025-12-23T143747.mp4')

Pandas(Index=646, t_start=Timestamp('2025-12-23 15:37:52'), t_duration=3600.655338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-23T153752.mp4', video_num_frames=104082, video_fps=28.906404588603355, video_width=640, video_height=480, video_file_size=106903175, cache_file_size=106903175, cache_file_mtime=1766525875.7761307, t_start_dt=Timestamp('2025-12-23 15:37:52'), t_end_dt=Timestamp('2025-12-23 16:37:52.655338542'), label='Debut_2025-12-23T153752.mp4')

Pandas(Index=647, t_start=Timestamp('2025-12-23 16:37:57'), t_duration=3600.7473307291666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-23T163757.mp4', video_num_frames=104762, video_fps=29.094515770642882, video_width=640, video_height=480, video_file_size=107926041, cache_file_size=107926041, cache_file_mtime=1766529480.7054424, t_start_dt=Timestamp('2025-12-23 16:37:57'), t_end_dt=Timestamp('2025-12-23 17:37:57.747330729'), label='Debut_2025-12-23T163757.mp4')

Pandas(Index=648, t_start=Timestamp('2025-12-23 17:38:02'), t_duration=3600.8953776041667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-23T173802.mp4', video_num_frames=98134, video_fps=27.252666270268826, video_width=640, video_height=480, video_file_size=108738377, cache_file_size=108738377, cache_file_mtime=1766533085.6266706, t_start_dt=Timestamp('2025-12-23 17:38:02'), t_end_dt=Timestamp('2025-12-23 18:38:02.895377604'), label='Debut_2025-12-23T173802.mp4')

Pandas(Index=649, t_start=Timestamp('2025-12-23 18:38:08'), t_duration=2624.6432942708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-23T183808.mp4', video_num_frames=75450, video_fps=28.74676348008699, video_width=640, video_height=480, video_file_size=81222911, cache_file_size=81222911, cache_file_mtime=1766535714.9883113, t_start_dt=Timestamp('2025-12-23 18:38:08'), t_end_dt=Timestamp('2025-12-23 19:21:52.643294271'), label='Debut_2025-12-23T183808.mp4')

Pandas(Index=650, t_start=Timestamp('2025-12-24 08:14:43'), t_duration=3600.3533203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-24T081443.mp4', video_num_frames=92218, video_fps=25.613597276612772, video_width=640, video_height=480, video_file_size=106315899, cache_file_size=106315899, cache_file_mtime=1766585686.1595335, t_start_dt=Timestamp('2025-12-24 08:14:43'), t_end_dt=Timestamp('2025-12-24 09:14:43.353320312'), label='Debut_2025-12-24T081443.mp4')

Pandas(Index=651, t_start=Timestamp('2025-12-24 09:14:47'), t_duration=3600.361328125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-24T091447.mp4', video_num_frames=86390, video_fps=23.994813888579976, video_width=640, video_height=480, video_file_size=104199728, cache_file_size=104199728, cache_file_mtime=1766589289.386603, t_start_dt=Timestamp('2025-12-24 09:14:47'), t_end_dt=Timestamp('2025-12-24 10:14:47.361328125'), label='Debut_2025-12-24T091447.mp4')

Pandas(Index=652, t_start=Timestamp('2025-12-24 10:14:50'), t_duration=3600.4573567708335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-24T101450.mp4', video_num_frames=105864, video_fps=29.402931213979706, video_width=640, video_height=480, video_file_size=105970566, cache_file_size=105970566, cache_file_mtime=1766592892.8227954, t_start_dt=Timestamp('2025-12-24 10:14:50'), t_end_dt=Timestamp('2025-12-24 11:14:50.457356771'), label='Debut_2025-12-24T101450.mp4')

Pandas(Index=653, t_start=Timestamp('2025-12-24 11:14:54'), t_duration=3600.3483072916665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-24T111454.mp4', video_num_frames=104962, video_fps=29.15329047120911, video_width=640, video_height=480, video_file_size=106899971, cache_file_size=106899971, cache_file_mtime=1766596496.9931421, t_start_dt=Timestamp('2025-12-24 11:14:54'), t_end_dt=Timestamp('2025-12-24 12:14:54.348307292'), label='Debut_2025-12-24T111454.mp4')

Pandas(Index=654, t_start=Timestamp('2025-12-24 12:14:58'), t_duration=2193.5833333333335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-24T121458.mp4', video_num_frames=53888, video_fps=24.566196862059794, video_width=640, video_height=480, video_file_size=60851167, cache_file_size=60851167, cache_file_mtime=1766598693.3831556, t_start_dt=Timestamp('2025-12-24 12:14:58'), t_end_dt=Timestamp('2025-12-24 12:51:31.583333333'), label='Debut_2025-12-24T121458.mp4')

Pandas(Index=655, t_start=Timestamp('2025-12-24 19:54:15'), t_duration=3600.2433593749997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-24T195415.mp4', video_num_frames=54238, video_fps=15.06509271345915, video_width=640, video_height=480, video_file_size=101732280, cache_file_size=101732280, cache_file_mtime=1766627657.6728752, t_start_dt=Timestamp('2025-12-24 19:54:15'), t_end_dt=Timestamp('2025-12-24 20:54:15.243359375'), label='Debut_2025-12-24T195415.mp4')

Pandas(Index=656, t_start=Timestamp('2025-12-24 20:54:19'), t_duration=3600.357356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-24T205419.mp4', video_num_frames=53996, video_fps=14.997400160418827, video_width=640, video_height=480, video_file_size=100924790, cache_file_size=100924790, cache_file_mtime=1766631261.0777447, t_start_dt=Timestamp('2025-12-24 20:54:19'), t_end_dt=Timestamp('2025-12-24 21:54:19.357356771'), label='Debut_2025-12-24T205419.mp4')

Pandas(Index=657, t_start=Timestamp('2025-12-24 21:54:22'), t_duration=157.89335937500002, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2025-12-24T215422.mp4', video_num_frames=2364, video_fps=14.972130616243657, video_width=640, video_height=480, video_file_size=4446108, cache_file_size=4446108, cache_file_mtime=1766631421.4021618, t_start_dt=Timestamp('2025-12-24 21:54:22'), t_end_dt=Timestamp('2025-12-24 21:56:59.893359375'), label='Debut_2025-12-24T215422.mp4')

Pandas(Index=658, t_start=Timestamp('2026-01-04 21:22:08'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-04T212208.mp4', video_num_frames=97225, video_fps=27.00517896914834, video_width=640, video_height=480, video_file_size=108503390, cache_file_size=108503390, cache_file_mtime=1767583330.5658116, t_start_dt=Timestamp('2026-01-04 21:22:08'), t_end_dt=Timestamp('2026-01-04 22:22:08.235351562'), label='Debut_2026-01-04T212208.mp4')

Pandas(Index=659, t_start=Timestamp('2026-01-04 22:22:11'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-04T222211.mp4', video_num_frames=98310, video_fps=27.306335826670665, video_width=640, video_height=480, video_file_size=106715795, cache_file_size=106715795, cache_file_mtime=1767586933.5431623, t_start_dt=Timestamp('2026-01-04 22:22:11'), t_end_dt=Timestamp('2026-01-04 23:22:11.263346354'), label='Debut_2026-01-04T222211.mp4')

Pandas(Index=660, t_start=Timestamp('2026-01-04 23:22:14'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-04T232214.mp4', video_num_frames=105722, video_fps=29.365041192415777, video_width=640, video_height=480, video_file_size=106938782, cache_file_size=106938782, cache_file_mtime=1767590536.459624, t_start_dt=Timestamp('2026-01-04 23:22:14'), t_end_dt=Timestamp('2026-01-05 00:22:14.267382812'), label='Debut_2026-01-04T232214.mp4')

Pandas(Index=661, t_start=Timestamp('2026-01-05 00:22:17'), t_duration=3600.2373697916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-05T002217.mp4', video_num_frames=107224, video_fps=29.782480705211025, video_width=640, video_height=480, video_file_size=107252666, cache_file_size=107252666, cache_file_mtime=1767594139.2795496, t_start_dt=Timestamp('2026-01-05 00:22:17'), t_end_dt=Timestamp('2026-01-05 01:22:17.237369792'), label='Debut_2026-01-05T002217.mp4')

Pandas(Index=662, t_start=Timestamp('2026-01-05 01:22:19'), t_duration=3600.4453125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-05T012219.mp4', video_num_frames=96925, video_fps=26.920281128419443, video_width=640, video_height=480, video_file_size=106082423, cache_file_size=106082423, cache_file_mtime=1767597742.7922456, t_start_dt=Timestamp('2026-01-05 01:22:19'), t_end_dt=Timestamp('2026-01-05 02:22:19.445312500'), label='Debut_2026-01-05T012219.mp4')

Pandas(Index=663, t_start=Timestamp('2026-01-05 02:22:24'), t_duration=3600.357356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-05T022224.mp4', video_num_frames=104244, video_fps=28.953792546164536, video_width=640, video_height=480, video_file_size=107598128, cache_file_size=107598128, cache_file_mtime=1767601346.4538078, t_start_dt=Timestamp('2026-01-05 02:22:24'), t_end_dt=Timestamp('2026-01-05 03:22:24.357356771'), label='Debut_2026-01-05T022224.mp4')

Pandas(Index=664, t_start=Timestamp('2026-01-05 03:22:27'), t_duration=1788.9643229166666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-05T032227.mp4', video_num_frames=50712, video_fps=28.347127637135255, video_width=640, video_height=480, video_file_size=53667144, cache_file_size=53667144, cache_file_mtime=1767603137.8287416, t_start_dt=Timestamp('2026-01-05 03:22:27'), t_end_dt=Timestamp('2026-01-05 03:52:15.964322917'), label='Debut_2026-01-05T032227.mp4')

Pandas(Index=665, t_start=Timestamp('2026-01-06 06:23:45'), t_duration=3600.295377604167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-06T062345.mp4', video_num_frames=53996, video_fps=14.99765834100309, video_width=640, video_height=480, video_file_size=99418627, cache_file_size=99418627, cache_file_mtime=1767702228.0177896, t_start_dt=Timestamp('2026-01-06 06:23:45'), t_end_dt=Timestamp('2026-01-06 07:23:45.295377604'), label='Debut_2026-01-06T062345.mp4')

Pandas(Index=666, t_start=Timestamp('2026-01-06 07:23:48'), t_duration=3600.2463541666666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-06T072348.mp4', video_num_frames=53759, video_fps=14.932033730909328, video_width=640, video_height=480, video_file_size=99462882, cache_file_size=99462882, cache_file_mtime=1767705830.6806617, t_start_dt=Timestamp('2026-01-06 07:23:48'), t_end_dt=Timestamp('2026-01-06 08:23:48.246354167'), label='Debut_2026-01-06T072348.mp4')

Pandas(Index=667, t_start=Timestamp('2026-01-06 08:23:51'), t_duration=3599.7853515624997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-06T082351.mp4', video_num_frames=47876, video_fps=13.299681876648354, video_width=640, video_height=480, video_file_size=97846323, cache_file_size=97846323, cache_file_mtime=1767709449.0003908, t_start_dt=Timestamp('2026-01-06 08:23:51'), t_end_dt=Timestamp('2026-01-06 09:23:50.785351562'), label='Debut_2026-01-06T082351.mp4')

Pandas(Index=668, t_start=Timestamp('2026-01-06 09:24:10'), t_duration=3602.9992838541666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-06T092410.mp4', video_num_frames=48429, video_fps=13.441301589212358, video_width=640, video_height=480, video_file_size=94395205, cache_file_size=94395205, cache_file_mtime=1767713052.6281898, t_start_dt=Timestamp('2026-01-06 09:24:10'), t_end_dt=Timestamp('2026-01-06 10:24:12.999283854'), label='Debut_2026-01-06T092410.mp4')

Pandas(Index=669, t_start=Timestamp('2026-01-06 10:24:13'), t_duration=3600.3313151041666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-06T102413.mp4', video_num_frames=31240, video_fps=8.676979218257348, video_width=640, video_height=480, video_file_size=94723814, cache_file_size=94723814, cache_file_mtime=1767716655.3919084, t_start_dt=Timestamp('2026-01-06 10:24:13'), t_end_dt=Timestamp('2026-01-06 11:24:13.331315104'), label='Debut_2026-01-06T102413.mp4')

Pandas(Index=670, t_start=Timestamp('2026-01-06 11:24:17'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-06T112417.mp4', video_num_frames=60661, video_fps=16.84874574121841, video_width=640, video_height=480, video_file_size=100420844, cache_file_size=100420844, cache_file_mtime=1767720259.2455356, t_start_dt=Timestamp('2026-01-06 11:24:17'), t_end_dt=Timestamp('2026-01-06 12:24:17.327343750'), label='Debut_2026-01-06T112417.mp4')

Pandas(Index=671, t_start=Timestamp('2026-01-06 12:24:20'), t_duration=2373.572330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-06T122420.mp4', video_num_frames=34910, video_fps=14.707788571699254, video_width=640, video_height=480, video_file_size=65517597, cache_file_size=65517597, cache_file_mtime=1767722634.9801598, t_start_dt=Timestamp('2026-01-06 12:24:20'), t_end_dt=Timestamp('2026-01-06 13:03:53.572330729'), label='Debut_2026-01-06T122420.mp4')

Pandas(Index=672, t_start=Timestamp('2026-01-06 18:51:00'), t_duration=3600.415364583333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-06T185100.mp4', video_num_frames=106064, video_fps=29.458823291149496, video_width=640, video_height=480, video_file_size=108522964, cache_file_size=108522964, cache_file_mtime=1767747062.5538628, t_start_dt=Timestamp('2026-01-06 18:51:00'), t_end_dt=Timestamp('2026-01-06 19:51:00.415364583'), label='Debut_2026-01-06T185100.mp4')

Pandas(Index=673, t_start=Timestamp('2026-01-06 19:51:03'), t_duration=567.8443359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-06T195103.mp4', video_num_frames=16099, video_fps=28.351079655344034, video_width=640, video_height=480, video_file_size=17022915, cache_file_size=17022915, cache_file_mtime=1767747632.6683142, t_start_dt=Timestamp('2026-01-06 19:51:03'), t_end_dt=Timestamp('2026-01-06 20:00:30.844335937'), label='Debut_2026-01-06T195103.mp4')

Pandas(Index=674, t_start=Timestamp('2026-01-07 04:15:10'), t_duration=849.2833333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T041510.mp4', video_num_frames=13110, video_fps=15.436544537551269, video_width=640, video_height=480, video_file_size=24141913, cache_file_size=24141913, cache_file_mtime=1767778161.9835415, t_start_dt=Timestamp('2026-01-07 04:15:10'), t_end_dt=Timestamp('2026-01-07 04:29:19.283333333'), label='Debut_2026-01-07T041510.mp4')

Pandas(Index=675, t_start=Timestamp('2026-01-07 04:39:43'), t_duration=1065.7933593750001, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T043943.mp4', video_num_frames=15158, video_fps=14.22226913563143, video_width=640, video_height=480, video_file_size=32115285, cache_file_size=32115285, cache_file_mtime=1767780415.8816442, t_start_dt=Timestamp('2026-01-07 04:39:43'), t_end_dt=Timestamp('2026-01-07 04:57:28.793359375'), label='Debut_2026-01-07T043943.mp4')

Pandas(Index=676, t_start=Timestamp('2026-01-07 05:14:47'), t_duration=3600.263346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T051447.mp4', video_num_frames=53712, video_fps=14.918908655499285, video_width=640, video_height=480, video_file_size=98757698, cache_file_size=98757698, cache_file_mtime=1767784490.0937939, t_start_dt=Timestamp('2026-01-07 05:14:47'), t_end_dt=Timestamp('2026-01-07 06:14:47.263346354'), label='Debut_2026-01-07T051447.mp4')

Pandas(Index=677, t_start=Timestamp('2026-01-07 06:14:51'), t_duration=3600.2833333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T061451.mp4', video_num_frames=53827, video_fps=14.950767763648232, video_width=640, video_height=480, video_file_size=97861378, cache_file_size=97861378, cache_file_mtime=1767788093.3087416, t_start_dt=Timestamp('2026-01-07 06:14:51'), t_end_dt=Timestamp('2026-01-07 07:14:51.283333333'), label='Debut_2026-01-07T061451.mp4')

Pandas(Index=678, t_start=Timestamp('2026-01-07 07:14:54'), t_duration=3600.298307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T071454.mp4', video_num_frames=48219, video_fps=13.393056875965609, video_width=640, video_height=480, video_file_size=95084538, cache_file_size=95084538, cache_file_mtime=1767791696.4266124, t_start_dt=Timestamp('2026-01-07 07:14:54'), t_end_dt=Timestamp('2026-01-07 08:14:54.298307292'), label='Debut_2026-01-07T071454.mp4')

Pandas(Index=679, t_start=Timestamp('2026-01-07 08:14:57'), t_duration=3600.2673177083334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T081457.mp4', video_num_frames=53455, video_fps=14.847508610562157, video_width=640, video_height=480, video_file_size=96383300, cache_file_size=96383300, cache_file_mtime=1767795299.7420704, t_start_dt=Timestamp('2026-01-07 08:14:57'), t_end_dt=Timestamp('2026-01-07 09:14:57.267317708'), label='Debut_2026-01-07T081457.mp4')

Pandas(Index=680, t_start=Timestamp('2026-01-07 09:15:01'), t_duration=3600.3853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T091501.mp4', video_num_frames=70660, video_fps=19.62567700408371, video_width=640, video_height=480, video_file_size=102169069, cache_file_size=102169069, cache_file_mtime=1767798904.3190224, t_start_dt=Timestamp('2026-01-07 09:15:01'), t_end_dt=Timestamp('2026-01-07 10:15:01.385351563'), label='Debut_2026-01-07T091501.mp4')

Pandas(Index=681, t_start=Timestamp('2026-01-07 10:15:05'), t_duration=3602.7073567708335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T101505.mp4', video_num_frames=104787, video_fps=29.08562634238556, video_width=640, video_height=480, video_file_size=107619112, cache_file_size=107619112, cache_file_mtime=1767802543.3473735, t_start_dt=Timestamp('2026-01-07 10:15:05'), t_end_dt=Timestamp('2026-01-07 11:15:07.707356771'), label='Debut_2026-01-07T101505.mp4')

Pandas(Index=682, t_start=Timestamp('2026-01-07 11:16:03'), t_duration=3601.8553385416662, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T111603.mp4', video_num_frames=96656, video_fps=26.835058855843574, video_width=640, video_height=480, video_file_size=105157322, cache_file_size=105157322, cache_file_mtime=1767806167.0354626, t_start_dt=Timestamp('2026-01-07 11:16:03'), t_end_dt=Timestamp('2026-01-07 12:16:04.855338542'), label='Debut_2026-01-07T111603.mp4')

Pandas(Index=683, t_start=Timestamp('2026-01-07 12:16:08'), t_duration=3600.8213541666664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T121608.mp4', video_num_frames=89892, video_fps=24.96430429573577, video_width=640, video_height=480, video_file_size=103425432, cache_file_size=103425432, cache_file_mtime=1767809771.993865, t_start_dt=Timestamp('2026-01-07 12:16:08'), t_end_dt=Timestamp('2026-01-07 13:16:08.821354167'), label='Debut_2026-01-07T121608.mp4')

Pandas(Index=684, t_start=Timestamp('2026-01-07 13:16:13'), t_duration=1146.0583333333332, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T131613.mp4', video_num_frames=22762, video_fps=19.861118180430026, video_width=640, video_height=480, video_file_size=32733772, cache_file_size=32733772, cache_file_mtime=1767810981.7850347, t_start_dt=Timestamp('2026-01-07 13:16:13'), t_end_dt=Timestamp('2026-01-07 13:35:19.058333333'), label='Debut_2026-01-07T131613.mp4')

Pandas(Index=685, t_start=Timestamp('2026-01-07 18:44:19'), t_duration=3600.2822916666664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T184419.mp4', video_num_frames=90551, video_fps=25.15108334965632, video_width=640, video_height=480, video_file_size=106108782, cache_file_size=106108782, cache_file_mtime=1767833061.34264, t_start_dt=Timestamp('2026-01-07 18:44:19'), t_end_dt=Timestamp('2026-01-07 19:44:19.282291667'), label='Debut_2026-01-07T184419.mp4')

Pandas(Index=686, t_start=Timestamp('2026-01-07 19:44:22'), t_duration=3600.1962890624995, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T194422.mp4', video_num_frames=64809, video_fps=18.001518471893217, video_width=640, video_height=480, video_file_size=100252095, cache_file_size=100252095, cache_file_mtime=1767836664.6650944, t_start_dt=Timestamp('2026-01-07 19:44:22'), t_end_dt=Timestamp('2026-01-07 20:44:22.196289062'), label='Debut_2026-01-07T194422.mp4')

Pandas(Index=687, t_start=Timestamp('2026-01-07 20:44:25'), t_duration=10.07734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-07T204425.mp4', video_num_frames=148, video_fps=14.68640979920924, video_width=640, video_height=480, video_file_size=274680, cache_file_size=274680, cache_file_mtime=1767836708.3364253, t_start_dt=Timestamp('2026-01-07 20:44:25'), t_end_dt=Timestamp('2026-01-07 20:44:35.077343750'), label='Debut_2026-01-07T204425.mp4')

Pandas(Index=688, t_start=Timestamp('2026-01-08 05:56:11'), t_duration=3600.3763671875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-08T055611.mp4', video_num_frames=89700, video_fps=24.914061990155435, video_width=640, video_height=480, video_file_size=108287581, cache_file_size=108287581, cache_file_mtime=1767873374.1584506, t_start_dt=Timestamp('2026-01-08 05:56:11'), t_end_dt=Timestamp('2026-01-08 06:56:11.376367187'), label='Debut_2026-01-08T055611.mp4')

Pandas(Index=689, t_start=Timestamp('2026-01-08 06:56:15'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-08T065615.mp4', video_num_frames=106786, video_fps=29.660574797802834, video_width=640, video_height=480, video_file_size=111017710, cache_file_size=111017710, cache_file_mtime=1767876977.5952566, t_start_dt=Timestamp('2026-01-08 06:56:15'), t_end_dt=Timestamp('2026-01-08 07:56:15.267382812'), label='Debut_2026-01-08T065615.mp4')

Pandas(Index=690, t_start=Timestamp('2026-01-08 07:56:18'), t_duration=3600.2173828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-08T075618.mp4', video_num_frames=107858, video_fps=29.958746523172728, video_width=640, video_height=480, video_file_size=110451096, cache_file_size=110451096, cache_file_mtime=1767880581.084535, t_start_dt=Timestamp('2026-01-08 07:56:18'), t_end_dt=Timestamp('2026-01-08 08:56:18.217382813'), label='Debut_2026-01-08T075618.mp4')

Pandas(Index=691, t_start=Timestamp('2026-01-08 08:56:22'), t_duration=3448.8913411458334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-08T085622.mp4', video_num_frames=99217, video_fps=28.767795266938418, video_width=640, video_height=480, video_file_size=105835367, cache_file_size=105835367, cache_file_mtime=1767884033.252815, t_start_dt=Timestamp('2026-01-08 08:56:22'), t_end_dt=Timestamp('2026-01-08 09:53:50.891341146'), label='Debut_2026-01-08T085622.mp4')

Pandas(Index=692, t_start=Timestamp('2026-01-08 15:01:33'), t_duration=2686.4933593749997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-08T150133.mp4', video_num_frames=80206, video_fps=29.85527573336699, video_width=640, video_height=480, video_file_size=88543433, cache_file_size=88543433, cache_file_mtime=1767905182.1838539, t_start_dt=Timestamp('2026-01-08 15:01:33'), t_end_dt=Timestamp('2026-01-08 15:46:19.493359375'), label='Debut_2026-01-08T150133.mp4')

Pandas(Index=693, t_start=Timestamp('2026-01-08 17:45:08'), t_duration=3600.3683593749997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-08T174508.mp4', video_num_frames=104489, video_fps=29.02175265703607, video_width=640, video_height=480, video_file_size=117859406, cache_file_size=117859406, cache_file_mtime=1767915910.5188808, t_start_dt=Timestamp('2026-01-08 17:45:08'), t_end_dt=Timestamp('2026-01-08 18:45:08.368359375'), label='Debut_2026-01-08T174508.mp4')

Pandas(Index=694, t_start=Timestamp('2026-01-08 18:45:13'), t_duration=3600.2413411458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-08T184513.mp4', video_num_frames=104382, video_fps=28.99305632849013, video_width=640, video_height=480, video_file_size=120488721, cache_file_size=120488721, cache_file_mtime=1767919516.1156192, t_start_dt=Timestamp('2026-01-08 18:45:13'), t_end_dt=Timestamp('2026-01-08 19:45:13.241341146'), label='Debut_2026-01-08T184513.mp4')

Pandas(Index=695, t_start=Timestamp('2026-01-08 19:45:18'), t_duration=148.94733072916668, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-08T194518.mp4', video_num_frames=4442, video_fps=29.82262238775504, video_width=640, video_height=480, video_file_size=5144236, cache_file_size=5144236, cache_file_mtime=1767919667.708485, t_start_dt=Timestamp('2026-01-08 19:45:18'), t_end_dt=Timestamp('2026-01-08 19:47:46.947330729'), label='Debut_2026-01-08T194518.mp4')

Pandas(Index=696, t_start=Timestamp('2026-01-09 01:17:15'), t_duration=3600.238346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T011715.mp4', video_num_frames=90793, video_fps=25.218608121304758, video_width=640, video_height=480, video_file_size=107693613, cache_file_size=107693613, cache_file_mtime=1767943037.7329903, t_start_dt=Timestamp('2026-01-09 01:17:15'), t_end_dt=Timestamp('2026-01-09 02:17:15.238346354'), label='Debut_2026-01-09T011715.mp4')

Pandas(Index=697, t_start=Timestamp('2026-01-09 02:17:18'), t_duration=3600.3013020833337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T021718.mp4', video_num_frames=88848, video_fps=24.677934579694103, video_width=640, video_height=480, video_file_size=106262295, cache_file_size=106262295, cache_file_mtime=1767946640.837893, t_start_dt=Timestamp('2026-01-09 02:17:18'), t_end_dt=Timestamp('2026-01-09 03:17:18.301302083'), label='Debut_2026-01-09T021718.mp4')

Pandas(Index=698, t_start=Timestamp('2026-01-09 03:17:21'), t_duration=3600.2533203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T031721.mp4', video_num_frames=92635, video_fps=25.730133898455605, video_width=640, video_height=480, video_file_size=105051530, cache_file_size=105051530, cache_file_mtime=1767950244.3367898, t_start_dt=Timestamp('2026-01-09 03:17:21'), t_end_dt=Timestamp('2026-01-09 04:17:21.253320312'), label='Debut_2026-01-09T031721.mp4')

Pandas(Index=699, t_start=Timestamp('2026-01-09 04:17:25'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T041725.mp4', video_num_frames=104051, video_fps=28.90042767378574, video_width=640, video_height=480, video_file_size=105969812, cache_file_size=105969812, cache_file_mtime=1767953847.7827806, t_start_dt=Timestamp('2026-01-09 04:17:25'), t_end_dt=Timestamp('2026-01-09 05:17:25.327343750'), label='Debut_2026-01-09T041725.mp4')

Pandas(Index=700, t_start=Timestamp('2026-01-09 05:17:28'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T051728.mp4', video_num_frames=106687, video_fps=29.63334102115071, video_width=640, video_height=480, video_file_size=106425148, cache_file_size=106425148, cache_file_mtime=1767957450.5985007, t_start_dt=Timestamp('2026-01-09 05:17:28'), t_end_dt=Timestamp('2026-01-09 06:17:28.235286458'), label='Debut_2026-01-09T051728.mp4')

Pandas(Index=701, t_start=Timestamp('2026-01-09 06:17:31'), t_duration=520.7953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T061731.mp4', video_num_frames=14781, video_fps=28.381591856205503, video_width=640, video_height=480, video_file_size=15626756, cache_file_size=15626756, cache_file_mtime=1767957974.4427466, t_start_dt=Timestamp('2026-01-09 06:17:31'), t_end_dt=Timestamp('2026-01-09 06:26:11.795312500'), label='Debut_2026-01-09T061731.mp4')

Pandas(Index=702, t_start=Timestamp('2026-01-09 07:11:57'), t_duration=1750.8573567708333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T071157.mp4', video_num_frames=45456, video_fps=25.962137820202596, video_width=640, video_height=480, video_file_size=51418348, cache_file_size=51418348, cache_file_mtime=1767962469.2184076, t_start_dt=Timestamp('2026-01-09 07:11:57'), t_end_dt=Timestamp('2026-01-09 07:41:07.857356771'), label='Debut_2026-01-09T071157.mp4')

Pandas(Index=703, t_start=Timestamp('2026-01-09 15:47:13'), t_duration=3600.339322916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T154713.mp4', video_num_frames=99739, video_fps=27.702666625100367, video_width=640, video_height=480, video_file_size=106652697, cache_file_size=106652697, cache_file_mtime=1767995235.9926834, t_start_dt=Timestamp('2026-01-09 15:47:13'), t_end_dt=Timestamp('2026-01-09 16:47:13.339322917'), label='Debut_2026-01-09T154713.mp4')

Pandas(Index=704, t_start=Timestamp('2026-01-09 16:47:17'), t_duration=2017.4673828124999, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T164717.mp4', video_num_frames=57589, video_fps=28.54519507508302, video_width=640, video_height=480, video_file_size=60653254, cache_file_size=60653254, cache_file_mtime=1767997256.296661, t_start_dt=Timestamp('2026-01-09 16:47:17'), t_end_dt=Timestamp('2026-01-09 17:20:54.467382812'), label='Debut_2026-01-09T164717.mp4')

Pandas(Index=705, t_start=Timestamp('2026-01-09 18:06:44'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T180644.mp4', video_num_frames=53930, video_fps=14.979584656550038, video_width=640, video_height=480, video_file_size=101795745, cache_file_size=101795745, cache_file_mtime=1768003606.753781, t_start_dt=Timestamp('2026-01-09 18:06:44'), t_end_dt=Timestamp('2026-01-09 19:06:44.233333333'), label='Debut_2026-01-09T180644.mp4')

Pandas(Index=706, t_start=Timestamp('2026-01-09 19:06:47'), t_duration=3600.2713541666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T190647.mp4', video_num_frames=53626, video_fps=14.894988384122088, video_width=640, video_height=480, video_file_size=103036270, cache_file_size=103036270, cache_file_mtime=1768007209.7758455, t_start_dt=Timestamp('2026-01-09 19:06:47'), t_end_dt=Timestamp('2026-01-09 20:06:47.271354167'), label='Debut_2026-01-09T190647.mp4')

Pandas(Index=707, t_start=Timestamp('2026-01-09 20:06:51'), t_duration=3600.2673177083334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T200651.mp4', video_num_frames=53998, video_fps=14.998330744610145, video_width=640, video_height=480, video_file_size=97009467, cache_file_size=97009467, cache_file_mtime=1768010813.105361, t_start_dt=Timestamp('2026-01-09 20:06:51'), t_end_dt=Timestamp('2026-01-09 21:06:51.267317708'), label='Debut_2026-01-09T200651.mp4')

Pandas(Index=708, t_start=Timestamp('2026-01-09 21:06:54'), t_duration=2203.3453125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-09T210654.mp4', video_num_frames=33039, video_fps=14.994926039310963, video_width=640, video_height=480, video_file_size=57987952, cache_file_size=57987952, cache_file_mtime=1768013110.9654763, t_start_dt=Timestamp('2026-01-09 21:06:54'), t_end_dt=Timestamp('2026-01-09 21:43:37.345312500'), label='Debut_2026-01-09T210654.mp4')

Pandas(Index=709, t_start=Timestamp('2026-01-12 06:30:19'), t_duration=3600.3873697916665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-12T063019.mp4', video_num_frames=86281, video_fps=23.964365813502056, video_width=640, video_height=480, video_file_size=112426331, cache_file_size=112426331, cache_file_mtime=1768221021.8918467, t_start_dt=Timestamp('2026-01-12 06:30:19'), t_end_dt=Timestamp('2026-01-12 07:30:19.387369792'), label='Debut_2026-01-12T063019.mp4')

Pandas(Index=710, t_start=Timestamp('2026-01-12 07:30:23'), t_duration=3600.3593098958336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-12T073023.mp4', video_num_frames=87793, video_fps=24.384510667781115, video_width=640, video_height=480, video_file_size=107693860, cache_file_size=107693860, cache_file_mtime=1768224625.9727407, t_start_dt=Timestamp('2026-01-12 07:30:23'), t_end_dt=Timestamp('2026-01-12 08:30:23.359309896'), label='Debut_2026-01-12T073023.mp4')

Pandas(Index=711, t_start=Timestamp('2026-01-12 08:30:27'), t_duration=3600.3852864583337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-12T083027.mp4', video_num_frames=101863, video_fps=28.29224982757379, video_width=640, video_height=480, video_file_size=107765704, cache_file_size=107765704, cache_file_mtime=1768228238.2066283, t_start_dt=Timestamp('2026-01-12 08:30:27'), t_end_dt=Timestamp('2026-01-12 09:30:27.385286458'), label='Debut_2026-01-12T083027.mp4')

Pandas(Index=712, t_start=Timestamp('2026-01-12 09:31:17'), t_duration=1888.2673177083332, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-12T093117.mp4', video_num_frames=56133, video_fps=29.72725284899013, video_width=640, video_height=480, video_file_size=56381834, cache_file_size=56381834, cache_file_mtime=1768230166.7351177, t_start_dt=Timestamp('2026-01-12 09:31:17'), t_end_dt=Timestamp('2026-01-12 10:02:45.267317708'), label='Debut_2026-01-12T093117.mp4')

Pandas(Index=713, t_start=Timestamp('2026-01-12 15:31:19'), t_duration=3600.2953125000004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-12T153119.mp4', video_num_frames=106664, video_fps=29.626458593457393, video_width=640, video_height=480, video_file_size=104398407, cache_file_size=104398407, cache_file_mtime=1768253482.0390317, t_start_dt=Timestamp('2026-01-12 15:31:19'), t_end_dt=Timestamp('2026-01-12 16:31:19.295312500'), label='Debut_2026-01-12T153119.mp4')

Pandas(Index=714, t_start=Timestamp('2026-01-12 16:31:24'), t_duration=3600.779296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-12T163124.mp4', video_num_frames=107834, video_fps=29.947406133329427, video_width=640, video_height=480, video_file_size=103309596, cache_file_size=103309596, cache_file_mtime=1768257087.932006, t_start_dt=Timestamp('2026-01-12 16:31:24'), t_end_dt=Timestamp('2026-01-12 17:31:24.779296875'), label='Debut_2026-01-12T163124.mp4')

Pandas(Index=715, t_start=Timestamp('2026-01-12 17:31:30'), t_duration=3600.3133463541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-12T173130.mp4', video_num_frames=107843, video_fps=29.953781692142574, video_width=640, video_height=480, video_file_size=103490328, cache_file_size=103490328, cache_file_mtime=1768260692.5983765, t_start_dt=Timestamp('2026-01-12 17:31:30'), t_end_dt=Timestamp('2026-01-12 18:31:30.313346354'), label='Debut_2026-01-12T173130.mp4')

Pandas(Index=716, t_start=Timestamp('2026-01-12 18:31:34'), t_duration=3600.329296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-12T183134.mp4', video_num_frames=107967, video_fps=29.988090282106356, video_width=640, video_height=480, video_file_size=103100529, cache_file_size=103100529, cache_file_mtime=1768264296.4682097, t_start_dt=Timestamp('2026-01-12 18:31:34'), t_end_dt=Timestamp('2026-01-12 19:31:34.329296875'), label='Debut_2026-01-12T183134.mp4')

Pandas(Index=717, t_start=Timestamp('2026-01-12 19:31:37'), t_duration=309.5633463541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-12T193137.mp4', video_num_frames=9274, video_fps=29.958327137960833, video_width=640, video_height=480, video_file_size=9020284, cache_file_size=9020284, cache_file_mtime=1768264607.9745877, t_start_dt=Timestamp('2026-01-12 19:31:37'), t_end_dt=Timestamp('2026-01-12 19:36:46.563346354'), label='Debut_2026-01-12T193137.mp4')

Pandas(Index=718, t_start=Timestamp('2026-01-13 23:46:44'), t_duration=527.0373697916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-13T234644.mp4', video_num_frames=7902, video_fps=14.993244223125188, video_width=640, video_height=480, video_file_size=15119942, cache_file_size=15119942, cache_file_mtime=1768366532.067111, t_start_dt=Timestamp('2026-01-13 23:46:44'), t_end_dt=Timestamp('2026-01-13 23:55:31.037369792'), label='Debut_2026-01-13T234644.mp4')

Pandas(Index=719, t_start=Timestamp('2026-01-14 06:04:20'), t_duration=3600.3573567708336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T060420.mp4', video_num_frames=70212, video_fps=19.501397512099537, video_width=640, video_height=480, video_file_size=101883792, cache_file_size=101883792, cache_file_mtime=1768392263.089555, t_start_dt=Timestamp('2026-01-14 06:04:20'), t_end_dt=Timestamp('2026-01-14 07:04:20.357356771'), label='Debut_2026-01-14T060420.mp4')

Pandas(Index=720, t_start=Timestamp('2026-01-14 07:04:26'), t_duration=3600.4933593749997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T070426.mp4', video_num_frames=106832, video_fps=29.671489247947033, video_width=640, video_height=480, video_file_size=105613361, cache_file_size=105613361, cache_file_mtime=1768395868.5346377, t_start_dt=Timestamp('2026-01-14 07:04:26'), t_end_dt=Timestamp('2026-01-14 08:04:26.493359375'), label='Debut_2026-01-14T070426.mp4')

Pandas(Index=721, t_start=Timestamp('2026-01-14 08:04:30'), t_duration=3600.3693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T080430.mp4', video_num_frames=107571, video_fps=29.87776807403277, video_width=640, video_height=480, video_file_size=105941309, cache_file_size=105941309, cache_file_mtime=1768399472.83401, t_start_dt=Timestamp('2026-01-14 08:04:30'), t_end_dt=Timestamp('2026-01-14 09:04:30.369335938'), label='Debut_2026-01-14T080430.mp4')

Pandas(Index=722, t_start=Timestamp('2026-01-14 09:04:34'), t_duration=3600.3173177083336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T090434.mp4', video_num_frames=107070, video_fps=29.739045353966738, video_width=640, video_height=480, video_file_size=106272480, cache_file_size=106272480, cache_file_mtime=1768403077.0646186, t_start_dt=Timestamp('2026-01-14 09:04:34'), t_end_dt=Timestamp('2026-01-14 10:04:34.317317708'), label='Debut_2026-01-14T090434.mp4')

Pandas(Index=723, t_start=Timestamp('2026-01-14 10:04:38'), t_duration=3600.337369791667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T100438.mp4', video_num_frames=107197, video_fps=29.774154194389553, video_width=640, video_height=480, video_file_size=105482495, cache_file_size=105482495, cache_file_mtime=1768406680.970211, t_start_dt=Timestamp('2026-01-14 10:04:38'), t_end_dt=Timestamp('2026-01-14 11:04:38.337369792'), label='Debut_2026-01-14T100438.mp4')

Pandas(Index=724, t_start=Timestamp('2026-01-14 11:04:42'), t_duration=3600.301302083333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T110442.mp4', video_num_frames=107103, video_fps=29.748343545031712, video_width=640, video_height=480, video_file_size=105050629, cache_file_size=105050629, cache_file_mtime=1768410284.8230202, t_start_dt=Timestamp('2026-01-14 11:04:42'), t_end_dt=Timestamp('2026-01-14 12:04:42.301302083'), label='Debut_2026-01-14T110442.mp4')

Pandas(Index=725, t_start=Timestamp('2026-01-14 12:04:46'), t_duration=3600.3093098958334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T120446.mp4', video_num_frames=107784, video_fps=29.937427793702113, video_width=640, video_height=480, video_file_size=104274728, cache_file_size=104274728, cache_file_mtime=1768413888.8627293, t_start_dt=Timestamp('2026-01-14 12:04:46'), t_end_dt=Timestamp('2026-01-14 13:04:46.309309896'), label='Debut_2026-01-14T120446.mp4')

Pandas(Index=726, t_start=Timestamp('2026-01-14 13:04:50'), t_duration=3600.423372395833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T130450.mp4', video_num_frames=107723, video_fps=29.9195369149928, video_width=640, video_height=480, video_file_size=106210118, cache_file_size=106210118, cache_file_mtime=1768417493.3854852, t_start_dt=Timestamp('2026-01-14 13:04:50'), t_end_dt=Timestamp('2026-01-14 14:04:50.423372396'), label='Debut_2026-01-14T130450.mp4')

Pandas(Index=727, t_start=Timestamp('2026-01-14 14:04:55'), t_duration=3600.3073567708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T140455.mp4', video_num_frames=106625, video_fps=29.615527074231093, video_width=640, video_height=480, video_file_size=107906199, cache_file_size=107906199, cache_file_mtime=1768421097.7492428, t_start_dt=Timestamp('2026-01-14 14:04:55'), t_end_dt=Timestamp('2026-01-14 15:04:55.307356771'), label='Debut_2026-01-14T140455.mp4')

Pandas(Index=728, t_start=Timestamp('2026-01-14 15:04:59'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T150459.mp4', video_num_frames=107793, video_fps=29.940293029615365, video_width=640, video_height=480, video_file_size=104468760, cache_file_size=104468760, cache_file_mtime=1768424703.1613789, t_start_dt=Timestamp('2026-01-14 15:04:59'), t_end_dt=Timestamp('2026-01-14 16:04:59.265364583'), label='Debut_2026-01-14T150459.mp4')

Pandas(Index=729, t_start=Timestamp('2026-01-14 16:05:04'), t_duration=3600.3093098958334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T160504.mp4', video_num_frames=103950, video_fps=28.87251929001832, video_width=640, video_height=480, video_file_size=105825900, cache_file_size=105825900, cache_file_mtime=1768428306.8800547, t_start_dt=Timestamp('2026-01-14 16:05:04'), t_end_dt=Timestamp('2026-01-14 17:05:04.309309896'), label='Debut_2026-01-14T160504.mp4')

Pandas(Index=730, t_start=Timestamp('2026-01-14 17:05:08'), t_duration=3600.3503255208334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T170508.mp4', video_num_frames=100093, video_fps=27.800905731449998, video_width=640, video_height=480, video_file_size=103282363, cache_file_size=103282363, cache_file_mtime=1768431911.2300403, t_start_dt=Timestamp('2026-01-14 17:05:08'), t_end_dt=Timestamp('2026-01-14 18:05:08.350325521'), label='Debut_2026-01-14T170508.mp4')

Pandas(Index=731, t_start=Timestamp('2026-01-14 18:05:13'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T180513.mp4', video_num_frames=107542, video_fps=29.87057648655992, video_width=640, video_height=480, video_file_size=105472076, cache_file_size=105472076, cache_file_mtime=1768435515.9432886, t_start_dt=Timestamp('2026-01-14 18:05:13'), t_end_dt=Timestamp('2026-01-14 19:05:13.265299479'), label='Debut_2026-01-14T180513.mp4')

Pandas(Index=732, t_start=Timestamp('2026-01-14 19:05:17'), t_duration=3600.3233723958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T190517.mp4', video_num_frames=107850, video_fps=29.95564254780572, video_width=640, video_height=480, video_file_size=106081984, cache_file_size=106081984, cache_file_mtime=1768439120.1372695, t_start_dt=Timestamp('2026-01-14 19:05:17'), t_end_dt=Timestamp('2026-01-14 20:05:17.323372396'), label='Debut_2026-01-14T190517.mp4')

Pandas(Index=733, t_start=Timestamp('2026-01-14 20:05:22'), t_duration=440.1393229166667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-14T200522.mp4', video_num_frames=12847, video_fps=29.188484943510428, video_width=640, video_height=480, video_file_size=12900021, cache_file_size=12900021, cache_file_mtime=1768439563.3804512, t_start_dt=Timestamp('2026-01-14 20:05:22'), t_end_dt=Timestamp('2026-01-14 20:12:42.139322917'), label='Debut_2026-01-14T200522.mp4')

Pandas(Index=734, t_start=Timestamp('2026-01-15 02:04:02'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T020402.mp4', video_num_frames=107912, video_fps=29.97334669075946, video_width=640, video_height=480, video_file_size=105944874, cache_file_size=105944874, cache_file_mtime=1768464245.431044, t_start_dt=Timestamp('2026-01-15 02:04:02'), t_end_dt=Timestamp('2026-01-15 03:04:02.265299479'), label='Debut_2026-01-15T020402.mp4')

Pandas(Index=735, t_start=Timestamp('2026-01-15 03:04:06'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T030406.mp4', video_num_frames=107667, video_fps=29.905046851625453, video_width=640, video_height=480, video_file_size=105798848, cache_file_size=105798848, cache_file_mtime=1768467848.9106247, t_start_dt=Timestamp('2026-01-15 03:04:06'), t_end_dt=Timestamp('2026-01-15 04:04:06.295312500'), label='Debut_2026-01-15T030406.mp4')

Pandas(Index=736, t_start=Timestamp('2026-01-15 04:04:10'), t_duration=786.9233072916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T040410.mp4', video_num_frames=23436, video_fps=29.781809463312335, video_width=640, video_height=480, video_file_size=23272956, cache_file_size=23272956, cache_file_mtime=1768468909.8704016, t_start_dt=Timestamp('2026-01-15 04:04:10'), t_end_dt=Timestamp('2026-01-15 04:17:16.923307292'), label='Debut_2026-01-15T040410.mp4')

Pandas(Index=737, t_start=Timestamp('2026-01-15 11:18:30'), t_duration=3600.2583333333337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T111830.mp4', video_num_frames=105615, video_fps=29.335394913790907, video_width=640, video_height=480, video_file_size=106202274, cache_file_size=106202274, cache_file_mtime=1768497513.2520723, t_start_dt=Timestamp('2026-01-15 11:18:30'), t_end_dt=Timestamp('2026-01-15 12:18:30.258333333'), label='Debut_2026-01-15T111830.mp4')

Pandas(Index=738, t_start=Timestamp('2026-01-15 12:18:34'), t_duration=3600.2903645833335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T121834.mp4', video_num_frames=104323, video_fps=28.976273976744498, video_width=640, video_height=480, video_file_size=105593688, cache_file_size=105593688, cache_file_mtime=1768501117.6309462, t_start_dt=Timestamp('2026-01-15 12:18:34'), t_end_dt=Timestamp('2026-01-15 13:18:34.290364583'), label='Debut_2026-01-15T121834.mp4')

Pandas(Index=739, t_start=Timestamp('2026-01-15 13:18:38'), t_duration=3600.3873046875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T131838.mp4', video_num_frames=106584, video_fps=29.603481786871562, video_width=640, video_height=480, video_file_size=109935481, cache_file_size=109935481, cache_file_mtime=1768504721.1301985, t_start_dt=Timestamp('2026-01-15 13:18:38'), t_end_dt=Timestamp('2026-01-15 14:18:38.387304688'), label='Debut_2026-01-15T131838.mp4')

Pandas(Index=740, t_start=Timestamp('2026-01-15 14:18:42'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T141842.mp4', video_num_frames=107754, video_fps=29.929211536032852, video_width=640, video_height=480, video_file_size=106930632, cache_file_size=106930632, cache_file_mtime=1768508324.6295936, t_start_dt=Timestamp('2026-01-15 14:18:42'), t_end_dt=Timestamp('2026-01-15 15:18:42.295312500'), label='Debut_2026-01-15T141842.mp4')

Pandas(Index=741, t_start=Timestamp('2026-01-15 15:18:45'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T151845.mp4', video_num_frames=107956, video_fps=29.98505127246459, video_width=640, video_height=480, video_file_size=112179891, cache_file_size=112179891, cache_file_mtime=1768511927.9627047, t_start_dt=Timestamp('2026-01-15 15:18:45'), t_end_dt=Timestamp('2026-01-15 16:18:45.327343750'), label='Debut_2026-01-15T151845.mp4')

Pandas(Index=742, t_start=Timestamp('2026-01-15 16:18:48'), t_duration=3600.2473307291666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T161848.mp4', video_num_frames=107974, video_fps=29.990717326115416, video_width=640, video_height=480, video_file_size=109425392, cache_file_size=109425392, cache_file_mtime=1768515531.2684526, t_start_dt=Timestamp('2026-01-15 16:18:48'), t_end_dt=Timestamp('2026-01-15 17:18:48.247330729'), label='Debut_2026-01-15T161848.mp4')

Pandas(Index=743, t_start=Timestamp('2026-01-15 17:18:52'), t_duration=3600.3313151041666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T171852.mp4', video_num_frames=107497, video_fps=29.857529930378043, video_width=640, video_height=480, video_file_size=110019617, cache_file_size=110019617, cache_file_mtime=1768519134.9520793, t_start_dt=Timestamp('2026-01-15 17:18:52'), t_end_dt=Timestamp('2026-01-15 18:18:52.331315104'), label='Debut_2026-01-15T171852.mp4')

Pandas(Index=744, t_start=Timestamp('2026-01-15 18:18:56'), t_duration=3600.3313151041666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T181856.mp4', video_num_frames=107500, video_fps=29.858363187025123, video_width=640, video_height=480, video_file_size=110305589, cache_file_size=110305589, cache_file_mtime=1768522738.5299456, t_start_dt=Timestamp('2026-01-15 18:18:56'), t_end_dt=Timestamp('2026-01-15 19:18:56.331315104'), label='Debut_2026-01-15T181856.mp4')

Pandas(Index=745, t_start=Timestamp('2026-01-15 19:18:59'), t_duration=3600.1573567708333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T191859.mp4', video_num_frames=80830, video_fps=22.45179640494953, video_width=640, video_height=480, video_file_size=104284680, cache_file_size=104284680, cache_file_mtime=1768526341.5854719, t_start_dt=Timestamp('2026-01-15 19:18:59'), t_end_dt=Timestamp('2026-01-15 20:18:59.157356771'), label='Debut_2026-01-15T191859.mp4')

Pandas(Index=746, t_start=Timestamp('2026-01-15 20:19:02'), t_duration=3600.2053385416666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T201902.mp4', video_num_frames=53965, video_fps=14.989422803828067, video_width=640, video_height=480, video_file_size=94611228, cache_file_size=94611228, cache_file_mtime=1768529944.3238187, t_start_dt=Timestamp('2026-01-15 20:19:02'), t_end_dt=Timestamp('2026-01-15 21:19:02.205338542'), label='Debut_2026-01-15T201902.mp4')

Pandas(Index=747, t_start=Timestamp('2026-01-15 21:19:05'), t_duration=247.70937500000002, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-15T211905.mp4', video_num_frames=3708, video_fps=14.969154881602684, video_width=640, video_height=480, video_file_size=6508525, cache_file_size=6508525, cache_file_mtime=1768530232.1308012, t_start_dt=Timestamp('2026-01-15 21:19:05'), t_end_dt=Timestamp('2026-01-15 21:23:12.709375'), label='Debut_2026-01-15T211905.mp4')

Pandas(Index=748, t_start=Timestamp('2026-01-16 08:35:48'), t_duration=3600.27734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-16T083548.mp4', video_num_frames=94518, video_fps=26.252977472438648, video_width=640, video_height=480, video_file_size=109452152, cache_file_size=109452152, cache_file_mtime=1768574150.6536129, t_start_dt=Timestamp('2026-01-16 08:35:48'), t_end_dt=Timestamp('2026-01-16 09:35:48.277343750'), label='Debut_2026-01-16T083548.mp4')

Pandas(Index=749, t_start=Timestamp('2026-01-16 09:35:51'), t_duration=3600.361393229167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-16T093551.mp4', video_num_frames=107020, video_fps=29.724793794662286, video_width=640, video_height=480, video_file_size=109732598, cache_file_size=109732598, cache_file_mtime=1768577754.3136292, t_start_dt=Timestamp('2026-01-16 09:35:51'), t_end_dt=Timestamp('2026-01-16 10:35:51.361393229'), label='Debut_2026-01-16T093551.mp4')

Pandas(Index=750, t_start=Timestamp('2026-01-16 10:35:55'), t_duration=3600.329296875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-16T103555.mp4', video_num_frames=107971, video_fps=29.989201291591925, video_width=640, video_height=480, video_file_size=107583414, cache_file_size=107583414, cache_file_mtime=1768581358.1483347, t_start_dt=Timestamp('2026-01-16 10:35:55'), t_end_dt=Timestamp('2026-01-16 11:35:55.329296875'), label='Debut_2026-01-16T103555.mp4')

Pandas(Index=751, t_start=Timestamp('2026-01-16 11:35:59'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-16T113559.mp4', video_num_frames=107987, video_fps=29.994161132454952, video_width=640, video_height=480, video_file_size=107112609, cache_file_size=107112609, cache_file_mtime=1768584961.900377, t_start_dt=Timestamp('2026-01-16 11:35:59'), t_end_dt=Timestamp('2026-01-16 12:35:59.267382812'), label='Debut_2026-01-16T113559.mp4')

Pandas(Index=752, t_start=Timestamp('2026-01-16 12:36:03'), t_duration=2540.9933593749997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-16T123603.mp4', video_num_frames=76212, video_fps=29.992994558138328, video_width=640, video_height=480, video_file_size=75521779, cache_file_size=75521779, cache_file_mtime=1768587505.8309238, t_start_dt=Timestamp('2026-01-16 12:36:03'), t_end_dt=Timestamp('2026-01-16 13:18:23.993359375'), label='Debut_2026-01-16T123603.mp4')

Pandas(Index=753, t_start=Timestamp('2026-01-16 20:50:12'), t_duration=1990.4653645833332, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-16T205012.mp4', video_num_frames=59620, video_fps=29.952794487574685, video_width=640, video_height=480, video_file_size=62389280, cache_file_size=62389280, cache_file_mtime=1768616604.929507, t_start_dt=Timestamp('2026-01-16 20:50:12'), t_end_dt=Timestamp('2026-01-16 21:23:22.465364583'), label='Debut_2026-01-16T205012.mp4')

Pandas(Index=754, t_start=Timestamp('2026-01-19 07:25:21'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T072521.mp4', video_num_frames=107488, video_fps=29.855328707844713, video_width=640, video_height=480, video_file_size=114726639, cache_file_size=114726639, cache_file_mtime=1768829124.1385596, t_start_dt=Timestamp('2026-01-19 07:25:21'), t_end_dt=Timestamp('2026-01-19 08:25:21.295312500'), label='Debut_2026-01-19T072521.mp4')

Pandas(Index=755, t_start=Timestamp('2026-01-19 08:25:25'), t_duration=3600.455338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T082525.mp4', video_num_frames=107644, video_fps=29.897329609315545, video_width=640, video_height=480, video_file_size=111971634, cache_file_size=111971634, cache_file_mtime=1768832728.159122, t_start_dt=Timestamp('2026-01-19 08:25:25'), t_end_dt=Timestamp('2026-01-19 09:25:25.455338542'), label='Debut_2026-01-19T082525.mp4')

Pandas(Index=756, t_start=Timestamp('2026-01-19 09:25:30'), t_duration=3600.6693359375004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T092530.mp4', video_num_frames=104639, video_fps=29.06098567719641, video_width=640, video_height=480, video_file_size=110853187, cache_file_size=110853187, cache_file_mtime=1768836332.832094, t_start_dt=Timestamp('2026-01-19 09:25:30'), t_end_dt=Timestamp('2026-01-19 10:25:30.669335938'), label='Debut_2026-01-19T092530.mp4')

Pandas(Index=757, t_start=Timestamp('2026-01-19 10:25:34'), t_duration=3600.5152994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T102534.mp4', video_num_frames=105079, video_fps=29.184433687922457, video_width=640, video_height=480, video_file_size=110678810, cache_file_size=110678810, cache_file_mtime=1768839938.5166538, t_start_dt=Timestamp('2026-01-19 10:25:34'), t_end_dt=Timestamp('2026-01-19 11:25:34.515299478'), label='Debut_2026-01-19T102534.mp4')

Pandas(Index=758, t_start=Timestamp('2026-01-19 11:26:56'), t_duration=3600.4473307291664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T112656.mp4', video_num_frames=106836, video_fps=29.672979545673137, video_width=640, video_height=480, video_file_size=109286373, cache_file_size=109286373, cache_file_mtime=1768843619.0200498, t_start_dt=Timestamp('2026-01-19 11:26:56'), t_end_dt=Timestamp('2026-01-19 12:26:56.447330729'), label='Debut_2026-01-19T112656.mp4')

Pandas(Index=759, t_start=Timestamp('2026-01-19 12:27:03'), t_duration=3600.6833333333334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T122703.mp4', video_num_frames=64034, video_fps=17.783846584676056, video_width=640, video_height=480, video_file_size=100988796, cache_file_size=100988796, cache_file_mtime=1768847244.3299665, t_start_dt=Timestamp('2026-01-19 12:27:03'), t_end_dt=Timestamp('2026-01-19 13:27:03.683333333'), label='Debut_2026-01-19T122703.mp4')

Pandas(Index=760, t_start=Timestamp('2026-01-19 13:27:29'), t_duration=3602.8383463541663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T132729.mp4', video_num_frames=78007, video_fps=21.651540397014458, video_width=640, video_height=480, video_file_size=103247215, cache_file_size=103247215, cache_file_mtime=1768850885.3779645, t_start_dt=Timestamp('2026-01-19 13:27:29'), t_end_dt=Timestamp('2026-01-19 14:27:31.838346354'), label='Debut_2026-01-19T132729.mp4')

Pandas(Index=761, t_start=Timestamp('2026-01-19 14:28:10'), t_duration=3602.615299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T142810.mp4', video_num_frames=104654, video_fps=29.049451939853228, video_width=640, video_height=480, video_file_size=107658684, cache_file_size=107658684, cache_file_mtime=1768854493.6791575, t_start_dt=Timestamp('2026-01-19 14:28:10'), t_end_dt=Timestamp('2026-01-19 15:28:12.615299479'), label='Debut_2026-01-19T142810.mp4')

Pandas(Index=762, t_start=Timestamp('2026-01-19 15:28:14'), t_duration=3600.2853515624997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T152814.mp4', video_num_frames=91263, video_fps=25.34882407595622, video_width=640, video_height=480, video_file_size=105172155, cache_file_size=105172155, cache_file_mtime=1768858097.3400156, t_start_dt=Timestamp('2026-01-19 15:28:14'), t_end_dt=Timestamp('2026-01-19 16:28:14.285351562'), label='Debut_2026-01-19T152814.mp4')

Pandas(Index=763, t_start=Timestamp('2026-01-19 16:28:18'), t_duration=1878.1513020833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T162818.mp4', video_num_frames=55767, video_fps=29.692495986953038, video_width=640, video_height=480, video_file_size=57503068, cache_file_size=57503068, cache_file_mtime=1768859978.5630684, t_start_dt=Timestamp('2026-01-19 16:28:18'), t_end_dt=Timestamp('2026-01-19 16:59:36.151302083'), label='Debut_2026-01-19T162818.mp4')

Pandas(Index=764, t_start=Timestamp('2026-01-19 17:48:35'), t_duration=3600.267317708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T174835.mp4', video_num_frames=71575, video_fps=19.880468221887313, video_width=640, video_height=480, video_file_size=102369923, cache_file_size=102369923, cache_file_mtime=1768866517.2400353, t_start_dt=Timestamp('2026-01-19 17:48:35'), t_end_dt=Timestamp('2026-01-19 18:48:35.267317708'), label='Debut_2026-01-19T174835.mp4')

Pandas(Index=765, t_start=Timestamp('2026-01-19 18:48:38'), t_duration=3600.2373046875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T184838.mp4', video_num_frames=53968, video_fps=14.990122992652124, video_width=640, video_height=480, video_file_size=101329261, cache_file_size=101329261, cache_file_mtime=1768870120.367494, t_start_dt=Timestamp('2026-01-19 18:48:38'), t_end_dt=Timestamp('2026-01-19 19:48:38.237304688'), label='Debut_2026-01-19T184838.mp4')

Pandas(Index=766, t_start=Timestamp('2026-01-19 19:48:41'), t_duration=3249.8973307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T194841.mp4', video_num_frames=48739, video_fps=14.997089150833151, video_width=640, video_height=480, video_file_size=87358799, cache_file_size=87358799, cache_file_mtime=1768873373.6790738, t_start_dt=Timestamp('2026-01-19 19:48:41'), t_end_dt=Timestamp('2026-01-19 20:42:50.897330729'), label='Debut_2026-01-19T194841.mp4')

Pandas(Index=767, t_start=Timestamp('2026-01-19 20:42:58'), t_duration=3600.400390625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T204258.mp4', video_num_frames=105654, video_fps=29.345069585902177, video_width=640, video_height=480, video_file_size=109291982, cache_file_size=109291982, cache_file_mtime=1768876980.7200768, t_start_dt=Timestamp('2026-01-19 20:42:58'), t_end_dt=Timestamp('2026-01-19 21:42:58.400390625'), label='Debut_2026-01-19T204258.mp4')

Pandas(Index=768, t_start=Timestamp('2026-01-19 21:43:02'), t_duration=3600.571354166667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T214302.mp4', video_num_frames=107895, video_fps=29.966077432444532, video_width=640, video_height=480, video_file_size=107145554, cache_file_size=107145554, cache_file_mtime=1768880585.7582338, t_start_dt=Timestamp('2026-01-19 21:43:02'), t_end_dt=Timestamp('2026-01-19 22:43:02.571354167'), label='Debut_2026-01-19T214302.mp4')

Pandas(Index=769, t_start=Timestamp('2026-01-19 22:43:07'), t_duration=3600.3652994791664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T224307.mp4', video_num_frames=107986, video_fps=29.993067652224454, video_width=640, video_height=480, video_file_size=106021462, cache_file_size=106021462, cache_file_mtime=1768884189.804776, t_start_dt=Timestamp('2026-01-19 22:43:07'), t_end_dt=Timestamp('2026-01-19 23:43:07.365299479'), label='Debut_2026-01-19T224307.mp4')

Pandas(Index=770, t_start=Timestamp('2026-01-19 23:43:11'), t_duration=1904.5733723958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-19T234311.mp4', video_num_frames=54943, video_fps=28.84793035349705, video_width=640, video_height=480, video_file_size=56691891, cache_file_size=56691891, cache_file_mtime=1768886161.2435107, t_start_dt=Timestamp('2026-01-19 23:43:11'), t_end_dt=Timestamp('2026-01-20 00:14:55.573372396'), label='Debut_2026-01-19T234311.mp4')

Pandas(Index=771, t_start=Timestamp('2026-01-21 01:19:43'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T011943.mp4', video_num_frames=53975, video_fps=14.99195886730291, video_width=640, video_height=480, video_file_size=99386224, cache_file_size=99386224, cache_file_mtime=1768979985.358713, t_start_dt=Timestamp('2026-01-21 01:19:43'), t_end_dt=Timestamp('2026-01-21 02:19:43.263346354'), label='Debut_2026-01-21T011943.mp4')

Pandas(Index=772, t_start=Timestamp('2026-01-21 02:19:46'), t_duration=3600.254361979167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T021946.mp4', video_num_frames=54000, video_fps=14.998940233299127, video_width=640, video_height=480, video_file_size=98259821, cache_file_size=98259821, cache_file_mtime=1768983588.2013948, t_start_dt=Timestamp('2026-01-21 02:19:46'), t_end_dt=Timestamp('2026-01-21 03:19:46.254361979'), label='Debut_2026-01-21T021946.mp4')

Pandas(Index=773, t_start=Timestamp('2026-01-21 03:19:49'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T031949.mp4', video_num_frames=53953, video_fps=14.985839802462477, video_width=640, video_height=480, video_file_size=98815978, cache_file_size=98815978, cache_file_mtime=1768987191.2967348, t_start_dt=Timestamp('2026-01-21 03:19:49'), t_end_dt=Timestamp('2026-01-21 04:19:49.265364583'), label='Debut_2026-01-21T031949.mp4')

Pandas(Index=774, t_start=Timestamp('2026-01-21 04:19:51'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T041951.mp4', video_num_frames=53933, video_fps=14.980293054011078, video_width=640, video_height=480, video_file_size=98758380, cache_file_size=98758380, cache_file_mtime=1768990794.1161382, t_start_dt=Timestamp('2026-01-21 04:19:51'), t_end_dt=Timestamp('2026-01-21 05:19:51.263346354'), label='Debut_2026-01-21T041951.mp4')

Pandas(Index=775, t_start=Timestamp('2026-01-21 05:19:55'), t_duration=3600.325390625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T051955.mp4', video_num_frames=53919, video_fps=14.976146361770903, video_width=640, video_height=480, video_file_size=97223407, cache_file_size=97223407, cache_file_mtime=1768994397.2475202, t_start_dt=Timestamp('2026-01-21 05:19:55'), t_end_dt=Timestamp('2026-01-21 06:19:55.325390625'), label='Debut_2026-01-21T051955.mp4')

Pandas(Index=776, t_start=Timestamp('2026-01-21 06:19:58'), t_duration=3600.4753906250003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T061958.mp4', video_num_frames=53847, video_fps=14.955525078773777, video_width=640, video_height=480, video_file_size=95867386, cache_file_size=95867386, cache_file_mtime=1768998000.3508599, t_start_dt=Timestamp('2026-01-21 06:19:58'), t_end_dt=Timestamp('2026-01-21 07:19:58.475390625'), label='Debut_2026-01-21T061958.mp4')

Pandas(Index=777, t_start=Timestamp('2026-01-21 07:20:01'), t_duration=3600.4133463541666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T072001.mp4', video_num_frames=53959, video_fps=14.986890339866033, video_width=640, video_height=480, video_file_size=96970088, cache_file_size=96970088, cache_file_mtime=1769001603.6310678, t_start_dt=Timestamp('2026-01-21 07:20:01'), t_end_dt=Timestamp('2026-01-21 08:20:01.413346354'), label='Debut_2026-01-21T072001.mp4')

Pandas(Index=778, t_start=Timestamp('2026-01-21 08:20:05'), t_duration=3600.5053385416663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T082005.mp4', video_num_frames=91238, video_fps=25.340331820464584, video_width=640, video_height=480, video_file_size=102807451, cache_file_size=102807451, cache_file_mtime=1769005207.413696, t_start_dt=Timestamp('2026-01-21 08:20:05'), t_end_dt=Timestamp('2026-01-21 09:20:05.505338541'), label='Debut_2026-01-21T082005.mp4')

Pandas(Index=779, t_start=Timestamp('2026-01-21 09:20:08'), t_duration=1365.9873046875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T092008.mp4', video_num_frames=39598, video_fps=28.98855638271025, video_width=640, video_height=480, video_file_size=43997228, cache_file_size=43997228, cache_file_mtime=1769006989.6148975, t_start_dt=Timestamp('2026-01-21 09:20:08'), t_end_dt=Timestamp('2026-01-21 09:42:53.987304688'), label='Debut_2026-01-21T092008.mp4')

Pandas(Index=780, t_start=Timestamp('2026-01-21 16:44:09'), t_duration=3600.475390625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T164409.mp4', video_num_frames=104046, video_fps=28.897850620203474, video_width=640, video_height=480, video_file_size=107901123, cache_file_size=107901123, cache_file_mtime=1769035451.9064453, t_start_dt=Timestamp('2026-01-21 16:44:09'), t_end_dt=Timestamp('2026-01-21 17:44:09.475390625'), label='Debut_2026-01-21T164409.mp4')

Pandas(Index=781, t_start=Timestamp('2026-01-21 17:44:13'), t_duration=3600.3533203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T174413.mp4', video_num_frames=105086, video_fps=29.187690943309654, video_width=640, video_height=480, video_file_size=107382489, cache_file_size=107382489, cache_file_mtime=1769039055.6514947, t_start_dt=Timestamp('2026-01-21 17:44:13'), t_end_dt=Timestamp('2026-01-21 18:44:13.353320312'), label='Debut_2026-01-21T174413.mp4')

Pandas(Index=782, t_start=Timestamp('2026-01-21 18:44:19'), t_duration=2438.4853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-21T184419.mp4', video_num_frames=39308, video_fps=16.119842579662308, video_width=640, video_height=480, video_file_size=69170550, cache_file_size=69170550, cache_file_mtime=1769041499.465904, t_start_dt=Timestamp('2026-01-21 18:44:19'), t_end_dt=Timestamp('2026-01-21 19:24:57.485351562'), label='Debut_2026-01-21T184419.mp4')

Pandas(Index=783, t_start=Timestamp('2026-01-22 08:43:11'), t_duration=2767.4353515625003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-22T084311.mp4', video_num_frames=78606, video_fps=28.40391554426696, video_width=640, video_height=480, video_file_size=81868905, cache_file_size=81868905, cache_file_mtime=1769092161.533149, t_start_dt=Timestamp('2026-01-22 08:43:11'), t_end_dt=Timestamp('2026-01-22 09:29:18.435351563'), label='Debut_2026-01-22T084311.mp4')

Pandas(Index=784, t_start=Timestamp('2026-01-22 14:39:00'), t_duration=3600.263346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-22T143900.mp4', video_num_frames=107051, video_fps=29.734213778668714, video_width=640, video_height=480, video_file_size=110963164, cache_file_size=110963164, cache_file_mtime=1769114342.6676047, t_start_dt=Timestamp('2026-01-22 14:39:00'), t_end_dt=Timestamp('2026-01-22 15:39:00.263346354'), label='Debut_2026-01-22T143900.mp4')

Pandas(Index=785, t_start=Timestamp('2026-01-22 15:39:04'), t_duration=3600.797330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-22T153904.mp4', video_num_frames=103980, video_fps=28.87693764729155, video_width=640, video_height=480, video_file_size=107090310, cache_file_size=107090310, cache_file_mtime=1769117951.9202049, t_start_dt=Timestamp('2026-01-22 15:39:04'), t_end_dt=Timestamp('2026-01-22 16:39:04.797330729'), label='Debut_2026-01-22T153904.mp4')

Pandas(Index=786, t_start=Timestamp('2026-01-22 16:39:20'), t_duration=3321.6053385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-22T163920.mp4', video_num_frames=96209, video_fps=28.96460903517215, video_width=640, video_height=480, video_file_size=98501333, cache_file_size=98501333, cache_file_mtime=1769121283.693157, t_start_dt=Timestamp('2026-01-22 16:39:20'), t_end_dt=Timestamp('2026-01-22 17:34:41.605338542'), label='Debut_2026-01-22T163920.mp4')

Pandas(Index=787, t_start=Timestamp('2026-01-22 17:34:47'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-22T173447.mp4', video_num_frames=107980, video_fps=29.991734145407904, video_width=640, video_height=480, video_file_size=107770534, cache_file_size=107770534, cache_file_mtime=1769124890.1058142, t_start_dt=Timestamp('2026-01-22 17:34:47'), t_end_dt=Timestamp('2026-01-22 18:34:47.325325521'), label='Debut_2026-01-22T173447.mp4')

Pandas(Index=788, t_start=Timestamp('2026-01-22 18:34:51'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-22T183451.mp4', video_num_frames=107987, video_fps=29.994444804503413, video_width=640, video_height=480, video_file_size=107573372, cache_file_size=107573372, cache_file_mtime=1769128493.613698, t_start_dt=Timestamp('2026-01-22 18:34:51'), t_end_dt=Timestamp('2026-01-22 19:34:51.233333333'), label='Debut_2026-01-22T183451.mp4')

Pandas(Index=789, t_start=Timestamp('2026-01-22 19:34:54'), t_duration=3600.299348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-22T193454.mp4', video_num_frames=107233, video_fps=29.784467791831112, video_width=640, video_height=480, video_file_size=107599415, cache_file_size=107599415, cache_file_mtime=1769132098.3754878, t_start_dt=Timestamp('2026-01-22 19:34:54'), t_end_dt=Timestamp('2026-01-22 20:34:54.299348958'), label='Debut_2026-01-22T193454.mp4')

Pandas(Index=790, t_start=Timestamp('2026-01-22 20:34:59'), t_duration=3072.959375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-22T203459.mp4', video_num_frames=92065, video_fps=29.95971920390259, video_width=640, video_height=480, video_file_size=85842738, cache_file_size=85842738, cache_file_mtime=1769135222.9117765, t_start_dt=Timestamp('2026-01-22 20:34:59'), t_end_dt=Timestamp('2026-01-22 21:26:11.959375'), label='Debut_2026-01-22T203459.mp4')

Pandas(Index=791, t_start=Timestamp('2026-01-23 06:46:41'), t_duration=3600.2953776041663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T064641.mp4', video_num_frames=106988, video_fps=29.71645067388767, video_width=640, video_height=480, video_file_size=112372995, cache_file_size=112372995, cache_file_mtime=1769172404.7838542, t_start_dt=Timestamp('2026-01-23 06:46:41'), t_end_dt=Timestamp('2026-01-23 07:46:41.295377604'), label='Debut_2026-01-23T064641.mp4')

Pandas(Index=792, t_start=Timestamp('2026-01-23 07:46:47'), t_duration=3606.488346354167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T074647.mp4', video_num_frames=92444, video_fps=25.63269061813343, video_width=640, video_height=480, video_file_size=111736875, cache_file_size=111736875, cache_file_mtime=1769176017.2271106, t_start_dt=Timestamp('2026-01-23 07:46:47'), t_end_dt=Timestamp('2026-01-23 08:46:53.488346354'), label='Debut_2026-01-23T074647.mp4')

Pandas(Index=793, t_start=Timestamp('2026-01-23 08:46:59'), t_duration=371.55533854166663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T084659.mp4', video_num_frames=6982, video_fps=18.791278917977465, video_width=640, video_height=480, video_file_size=10920879, cache_file_size=10920879, cache_file_mtime=1769176395.0640118, t_start_dt=Timestamp('2026-01-23 08:46:59'), t_end_dt=Timestamp('2026-01-23 08:53:10.555338542'), label='Debut_2026-01-23T084659.mp4')

Pandas(Index=794, t_start=Timestamp('2026-01-23 08:57:19'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T085719.mp4', video_num_frames=106194, video_fps=29.496142566234095, video_width=640, video_height=480, video_file_size=109720324, cache_file_size=109720324, cache_file_mtime=1769180241.3939126, t_start_dt=Timestamp('2026-01-23 08:57:19'), t_end_dt=Timestamp('2026-01-23 09:57:19.267382812'), label='Debut_2026-01-23T085719.mp4')

Pandas(Index=795, t_start=Timestamp('2026-01-23 09:57:22'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T095722.mp4', video_num_frames=107607, video_fps=29.88861341624529, video_width=640, video_height=480, video_file_size=110607681, cache_file_size=110607681, cache_file_mtime=1769183844.9687366, t_start_dt=Timestamp('2026-01-23 09:57:22'), t_end_dt=Timestamp('2026-01-23 10:57:22.267382812'), label='Debut_2026-01-23T095722.mp4')

Pandas(Index=796, t_start=Timestamp('2026-01-23 10:57:26'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T105726.mp4', video_num_frames=107510, video_fps=29.86119038685686, video_width=640, video_height=480, video_file_size=113376520, cache_file_size=113376520, cache_file_mtime=1769187449.22224, t_start_dt=Timestamp('2026-01-23 10:57:26'), t_end_dt=Timestamp('2026-01-23 11:57:26.325325521'), label='Debut_2026-01-23T105726.mp4')

Pandas(Index=797, t_start=Timestamp('2026-01-23 11:57:30'), t_duration=3600.2393229166664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T115730.mp4', video_num_frames=107743, video_fps=29.926621631562544, video_width=640, video_height=480, video_file_size=112401353, cache_file_size=112401353, cache_file_mtime=1769191054.351274, t_start_dt=Timestamp('2026-01-23 11:57:30'), t_end_dt=Timestamp('2026-01-23 12:57:30.239322917'), label='Debut_2026-01-23T115730.mp4')

Pandas(Index=798, t_start=Timestamp('2026-01-23 12:57:36'), t_duration=3600.3853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T125736.mp4', video_num_frames=107942, video_fps=29.9806796939542, video_width=640, video_height=480, video_file_size=110059247, cache_file_size=110059247, cache_file_mtime=1769194659.3960588, t_start_dt=Timestamp('2026-01-23 12:57:36'), t_end_dt=Timestamp('2026-01-23 13:57:36.385351563'), label='Debut_2026-01-23T125736.mp4')

Pandas(Index=799, t_start=Timestamp('2026-01-23 13:57:41'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T135741.mp4', video_num_frames=107730, video_fps=29.92277754543947, video_width=640, video_height=480, video_file_size=106205312, cache_file_size=106205312, cache_file_mtime=1769198263.5991914, t_start_dt=Timestamp('2026-01-23 13:57:41'), t_end_dt=Timestamp('2026-01-23 14:57:41.267382812'), label='Debut_2026-01-23T135741.mp4')

Pandas(Index=800, t_start=Timestamp('2026-01-23 14:57:45'), t_duration=3600.2693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T145745.mp4', video_num_frames=106056, video_fps=29.45779609913082, video_width=640, video_height=480, video_file_size=110021344, cache_file_size=110021344, cache_file_mtime=1769201868.2851422, t_start_dt=Timestamp('2026-01-23 14:57:45'), t_end_dt=Timestamp('2026-01-23 15:57:45.269335937'), label='Debut_2026-01-23T145745.mp4')

Pandas(Index=801, t_start=Timestamp('2026-01-23 15:57:50'), t_duration=3600.447330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T155750.mp4', video_num_frames=105301, video_fps=29.24664363266059, video_width=640, video_height=480, video_file_size=110171523, cache_file_size=110171523, cache_file_mtime=1769205473.3197114, t_start_dt=Timestamp('2026-01-23 15:57:50'), t_end_dt=Timestamp('2026-01-23 16:57:50.447330729'), label='Debut_2026-01-23T155750.mp4')

Pandas(Index=802, t_start=Timestamp('2026-01-23 16:57:54'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T165754.mp4', video_num_frames=107580, video_fps=29.881113973251445, video_width=640, video_height=480, video_file_size=109988713, cache_file_size=109988713, cache_file_mtime=1769209077.281052, t_start_dt=Timestamp('2026-01-23 16:57:54'), t_end_dt=Timestamp('2026-01-23 17:57:54.267382812'), label='Debut_2026-01-23T165754.mp4')

Pandas(Index=803, t_start=Timestamp('2026-01-23 17:57:58'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T175758.mp4', video_num_frames=107142, video_fps=29.759721650136655, video_width=640, video_height=480, video_file_size=109530118, cache_file_size=109530118, cache_file_mtime=1769212681.217398, t_start_dt=Timestamp('2026-01-23 17:57:58'), t_end_dt=Timestamp('2026-01-23 18:57:58.235286458'), label='Debut_2026-01-23T175758.mp4')

Pandas(Index=804, t_start=Timestamp('2026-01-23 18:58:02'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T185802.mp4', video_num_frames=107993, video_fps=29.996095090283994, video_width=640, video_height=480, video_file_size=110131552, cache_file_size=110131552, cache_file_mtime=1769216285.4610147, t_start_dt=Timestamp('2026-01-23 18:58:02'), t_end_dt=Timestamp('2026-01-23 19:58:02.235286458'), label='Debut_2026-01-23T185802.mp4')

Pandas(Index=805, t_start=Timestamp('2026-01-23 19:58:07'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T195807.mp4', video_num_frames=105815, video_fps=29.39088961452584, video_width=640, video_height=480, video_file_size=108352163, cache_file_size=108352163, cache_file_mtime=1769219889.5521083, t_start_dt=Timestamp('2026-01-23 19:58:07'), t_end_dt=Timestamp('2026-01-23 20:58:07.265299479'), label='Debut_2026-01-23T195807.mp4')

Pandas(Index=806, t_start=Timestamp('2026-01-23 20:58:10'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T205810.mp4', video_num_frames=107728, video_fps=29.92198990620995, video_width=640, video_height=480, video_file_size=110370385, cache_file_size=110370385, cache_file_mtime=1769223493.1543863, t_start_dt=Timestamp('2026-01-23 20:58:10'), t_end_dt=Timestamp('2026-01-23 21:58:10.295312500'), label='Debut_2026-01-23T205810.mp4')

Pandas(Index=807, t_start=Timestamp('2026-01-23 21:58:14'), t_duration=593.7553385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-01-23T215814.mp4', video_num_frames=17799, video_fps=29.97699362790817, video_width=640, video_height=480, video_file_size=18028401, cache_file_size=18028401, cache_file_mtime=1769224089.3088934, t_start_dt=Timestamp('2026-01-23 21:58:14'), t_end_dt=Timestamp('2026-01-23 22:08:07.755338542'), label='Debut_2026-01-23T215814.mp4')

Pandas(Index=808, t_start=Timestamp('2026-02-02 16:49:00'), t_duration=3600.4153645833335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-02T164900.mp4', video_num_frames=103653, video_fps=28.789178331927125, video_width=640, video_height=480, video_file_size=106652379, cache_file_size=106652379, cache_file_mtime=1770072543.7579975, t_start_dt=Timestamp('2026-02-02 16:49:00'), t_end_dt=Timestamp('2026-02-02 17:49:00.415364583'), label='Debut_2026-02-02T164900.mp4')

Pandas(Index=809, t_start=Timestamp('2026-02-02 17:49:05'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-02T174905.mp4', video_num_frames=107935, video_fps=29.979218469501145, video_width=640, video_height=480, video_file_size=107021241, cache_file_size=107021241, cache_file_mtime=1770076147.6768103, t_start_dt=Timestamp('2026-02-02 17:49:05'), t_end_dt=Timestamp('2026-02-02 18:49:05.327343750'), label='Debut_2026-02-02T174905.mp4')

Pandas(Index=810, t_start=Timestamp('2026-02-02 18:49:08'), t_duration=3600.3553385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-02T184908.mp4', video_num_frames=99877, video_fps=27.740872944073192, video_width=640, video_height=480, video_file_size=105651581, cache_file_size=105651581, cache_file_mtime=1770079751.575273, t_start_dt=Timestamp('2026-02-02 18:49:08'), t_end_dt=Timestamp('2026-02-02 19:49:08.355338542'), label='Debut_2026-02-02T184908.mp4')

Pandas(Index=811, t_start=Timestamp('2026-02-02 19:49:13'), t_duration=637.8533854166666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-02T194913.mp4', video_num_frames=18972, video_fps=29.74351227689553, video_width=640, video_height=480, video_file_size=18918597, cache_file_size=18918597, cache_file_mtime=1770080392.4390512, t_start_dt=Timestamp('2026-02-02 19:49:13'), t_end_dt=Timestamp('2026-02-02 19:59:50.853385417'), label='Debut_2026-02-02T194913.mp4')

Pandas(Index=812, t_start=Timestamp('2026-02-02 19:59:57'), t_duration=2292.6072916666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-02T195957.mp4', video_num_frames=68476, video_fps=29.868176834690125, video_width=640, video_height=480, video_file_size=66790434, cache_file_size=66790434, cache_file_mtime=1770091190.0740898, t_start_dt=Timestamp('2026-02-02 19:59:57'), t_end_dt=Timestamp('2026-02-02 20:38:09.607291667'), label='Debut_2026-02-02T195957.mp4')

Pandas(Index=813, t_start=Timestamp('2026-02-02 22:59:54'), t_duration=2915.5153645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-02T225954.mp4', video_num_frames=84995, video_fps=29.152650345283615, video_width=640, video_height=480, video_file_size=88398144, cache_file_size=88398144, cache_file_mtime=1770094112.2091105, t_start_dt=Timestamp('2026-02-02 22:59:54'), t_end_dt=Timestamp('2026-02-02 23:48:29.515364583'), label='Debut_2026-02-02T225954.mp4')

Pandas(Index=814, t_start=Timestamp('2026-02-02 23:48:37'), t_duration=2342.965299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-02T234837.mp4', video_num_frames=69683, video_fps=29.741370909543686, video_width=640, video_height=480, video_file_size=70151731, cache_file_size=70151731, cache_file_mtime=1770096461.8033187, t_start_dt=Timestamp('2026-02-02 23:48:37'), t_end_dt=Timestamp('2026-02-03 00:27:39.965299479'), label='Debut_2026-02-02T234837.mp4')

Pandas(Index=815, t_start=Timestamp('2026-02-03 00:27:43'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T002743.mp4', video_num_frames=107639, video_fps=29.897784402862776, video_width=640, video_height=480, video_file_size=106984591, cache_file_size=106984591, cache_file_mtime=1770100066.1799588, t_start_dt=Timestamp('2026-02-03 00:27:43'), t_end_dt=Timestamp('2026-02-03 01:27:43.233333333'), label='Debut_2026-02-03T002743.mp4')

Pandas(Index=816, t_start=Timestamp('2026-02-03 01:27:47'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T012747.mp4', video_num_frames=107776, video_fps=29.935571696783413, video_width=640, video_height=480, video_file_size=106126668, cache_file_size=106126668, cache_file_mtime=1770103669.2723892, t_start_dt=Timestamp('2026-02-03 01:27:47'), t_end_dt=Timestamp('2026-02-03 02:27:47.265299479'), label='Debut_2026-02-03T012747.mp4')

Pandas(Index=817, t_start=Timestamp('2026-02-03 02:27:50'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T022750.mp4', video_num_frames=107978, video_fps=29.99192869592182, video_width=640, video_height=480, video_file_size=106918788, cache_file_size=106918788, cache_file_mtime=1770107272.4842355, t_start_dt=Timestamp('2026-02-03 02:27:50'), t_end_dt=Timestamp('2026-02-03 03:27:50.235286458'), label='Debut_2026-02-03T022750.mp4')

Pandas(Index=818, t_start=Timestamp('2026-02-03 03:27:54'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T032754.mp4', video_num_frames=99145, video_fps=27.537773800515968, video_width=640, video_height=480, video_file_size=105860301, cache_file_size=105860301, cache_file_mtime=1770110876.2426984, t_start_dt=Timestamp('2026-02-03 03:27:54'), t_end_dt=Timestamp('2026-02-03 04:27:54.327343750'), label='Debut_2026-02-03T032754.mp4')

Pandas(Index=819, t_start=Timestamp('2026-02-03 04:27:57'), t_duration=3600.359309895833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T042757.mp4', video_num_frames=107991, video_fps=29.99450629918502, video_width=640, video_height=480, video_file_size=106287718, cache_file_size=106287718, cache_file_mtime=1770114479.9361641, t_start_dt=Timestamp('2026-02-03 04:27:57'), t_end_dt=Timestamp('2026-02-03 05:27:57.359309896'), label='Debut_2026-02-03T042757.mp4')

Pandas(Index=820, t_start=Timestamp('2026-02-03 05:28:00'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T052800.mp4', video_num_frames=107993, video_fps=29.995845032759902, video_width=640, video_height=480, video_file_size=106208109, cache_file_size=106208109, cache_file_mtime=1770118083.1582456, t_start_dt=Timestamp('2026-02-03 05:28:00'), t_end_dt=Timestamp('2026-02-03 06:28:00.265299479'), label='Debut_2026-02-03T052800.mp4')

Pandas(Index=821, t_start=Timestamp('2026-02-03 06:28:03'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T062803.mp4', video_num_frames=107351, video_fps=29.817789587711907, video_width=640, video_height=480, video_file_size=106559314, cache_file_size=106559314, cache_file_mtime=1770121686.5027356, t_start_dt=Timestamp('2026-02-03 06:28:03'), t_end_dt=Timestamp('2026-02-03 07:28:03.233333333'), label='Debut_2026-02-03T062803.mp4')

Pandas(Index=822, t_start=Timestamp('2026-02-03 07:28:08'), t_duration=3600.3273437499997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T072808.mp4', video_num_frames=85458, video_fps=23.736175030959643, video_width=640, video_height=480, video_file_size=103486845, cache_file_size=103486845, cache_file_mtime=1770125290.8362565, t_start_dt=Timestamp('2026-02-03 07:28:08'), t_end_dt=Timestamp('2026-02-03 08:28:08.327343750'), label='Debut_2026-02-03T072808.mp4')

Pandas(Index=823, t_start=Timestamp('2026-02-03 08:28:13'), t_duration=3600.3573567708336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T082813.mp4', video_num_frames=86362, video_fps=23.987063350138726, video_width=640, video_height=480, video_file_size=103185440, cache_file_size=103185440, cache_file_mtime=1770128895.4192176, t_start_dt=Timestamp('2026-02-03 08:28:13'), t_end_dt=Timestamp('2026-02-03 09:28:13.357356771'), label='Debut_2026-02-03T082813.mp4')

Pandas(Index=824, t_start=Timestamp('2026-02-03 09:28:17'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T092817.mp4', video_num_frames=85160, video_fps=23.653404779383123, video_width=640, video_height=480, video_file_size=103143315, cache_file_size=103143315, cache_file_mtime=1770132500.7715704, t_start_dt=Timestamp('2026-02-03 09:28:17'), t_end_dt=Timestamp('2026-02-03 10:28:17.327343750'), label='Debut_2026-02-03T092817.mp4')

Pandas(Index=825, t_start=Timestamp('2026-02-03 10:28:23'), t_duration=3600.3673177083333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T102823.mp4', video_num_frames=92584, video_fps=25.71515399126847, video_width=640, video_height=480, video_file_size=105039282, cache_file_size=105039282, cache_file_mtime=1770136105.5825295, t_start_dt=Timestamp('2026-02-03 10:28:23'), t_end_dt=Timestamp('2026-02-03 11:28:23.367317708'), label='Debut_2026-02-03T102823.mp4')

Pandas(Index=826, t_start=Timestamp('2026-02-03 11:28:27'), t_duration=3600.2733072916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T112827.mp4', video_num_frames=107990, video_fps=29.99494504522389, video_width=640, video_height=480, video_file_size=106954317, cache_file_size=106954317, cache_file_mtime=1770139709.8761997, t_start_dt=Timestamp('2026-02-03 11:28:27'), t_end_dt=Timestamp('2026-02-03 12:28:27.273307292'), label='Debut_2026-02-03T112827.mp4')

Pandas(Index=827, t_start=Timestamp('2026-02-03 12:28:31'), t_duration=3602.4293619791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T122831.mp4', video_num_frames=106205, video_fps=29.48149410531431, video_width=640, video_height=480, video_file_size=106150359, cache_file_size=106150359, cache_file_mtime=1770143316.7364614, t_start_dt=Timestamp('2026-02-03 12:28:31'), t_end_dt=Timestamp('2026-02-03 13:28:33.429361979'), label='Debut_2026-02-03T122831.mp4')

Pandas(Index=828, t_start=Timestamp('2026-02-03 13:28:38'), t_duration=3601.383333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T132838.mp4', video_num_frames=95561, video_fps=26.53452608488405, video_width=640, video_height=480, video_file_size=104418243, cache_file_size=104418243, cache_file_mtime=1770146921.95778, t_start_dt=Timestamp('2026-02-03 13:28:38'), t_end_dt=Timestamp('2026-02-03 14:28:39.383333333'), label='Debut_2026-02-03T132838.mp4')

Pandas(Index=829, t_start=Timestamp('2026-02-03 14:28:43'), t_duration=3600.301302083333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T142843.mp4', video_num_frames=107455, video_fps=29.84611313998098, video_width=640, video_height=480, video_file_size=106913866, cache_file_size=106913866, cache_file_mtime=1770150525.952571, t_start_dt=Timestamp('2026-02-03 14:28:43'), t_end_dt=Timestamp('2026-02-03 15:28:43.301302083'), label='Debut_2026-02-03T142843.mp4')

Pandas(Index=830, t_start=Timestamp('2026-02-03 15:28:47'), t_duration=2345.3652994791664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T152847.mp4', video_num_frames=57832, video_fps=24.65799251521403, video_width=640, video_height=480, video_file_size=66792851, cache_file_size=66792851, cache_file_mtime=1770153001.0698683, t_start_dt=Timestamp('2026-02-03 15:28:47'), t_end_dt=Timestamp('2026-02-03 16:07:52.365299479'), label='Debut_2026-02-03T152847.mp4')

Pandas(Index=831, t_start=Timestamp('2026-02-03 18:23:16'), t_duration=3601.0753906249997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T182316.mp4', video_num_frames=53980, video_fps=14.989966647332889, video_width=640, video_height=480, video_file_size=99497246, cache_file_size=99497246, cache_file_mtime=1770164598.5216014, t_start_dt=Timestamp('2026-02-03 18:23:16'), t_end_dt=Timestamp('2026-02-03 19:23:17.075390625'), label='Debut_2026-02-03T182316.mp4')

Pandas(Index=832, t_start=Timestamp('2026-02-03 19:23:20'), t_duration=2911.7383463541664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-03T192320.mp4', video_num_frames=43128, video_fps=14.811770451146906, video_width=640, video_height=480, video_file_size=80453611, cache_file_size=80453611, cache_file_mtime=1770167513.6427438, t_start_dt=Timestamp('2026-02-03 19:23:20'), t_end_dt=Timestamp('2026-02-03 20:11:51.738346354'), label='Debut_2026-02-03T192320.mp4')

Pandas(Index=833, t_start=Timestamp('2026-02-04 00:42:05'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T004205.mp4', video_num_frames=98868, video_fps=27.461080666559905, video_width=640, video_height=480, video_file_size=105745857, cache_file_size=105745857, cache_file_mtime=1770187327.6107988, t_start_dt=Timestamp('2026-02-04 00:42:05'), t_end_dt=Timestamp('2026-02-04 01:42:05.295312500'), label='Debut_2026-02-04T004205.mp4')

Pandas(Index=834, t_start=Timestamp('2026-02-04 01:42:08'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T014208.mp4', video_num_frames=92541, video_fps=25.7039390995401, video_width=640, video_height=480, video_file_size=106569943, cache_file_size=106569943, cache_file_mtime=1770190930.6714246, t_start_dt=Timestamp('2026-02-04 01:42:08'), t_end_dt=Timestamp('2026-02-04 02:42:08.265299479'), label='Debut_2026-02-04T014208.mp4')

Pandas(Index=835, t_start=Timestamp('2026-02-04 02:42:11'), t_duration=3600.299348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T024211.mp4', video_num_frames=105737, video_fps=29.36894678788103, video_width=640, video_height=480, video_file_size=106487003, cache_file_size=106487003, cache_file_mtime=1770194533.813447, t_start_dt=Timestamp('2026-02-04 02:42:11'), t_end_dt=Timestamp('2026-02-04 03:42:11.299348958'), label='Debut_2026-02-04T024211.mp4')

Pandas(Index=836, t_start=Timestamp('2026-02-04 03:42:14'), t_duration=3600.2563151041663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T034214.mp4', video_num_frames=94613, video_fps=26.279517822958823, video_width=640, video_height=480, video_file_size=104948758, cache_file_size=104948758, cache_file_mtime=1770198137.2793193, t_start_dt=Timestamp('2026-02-04 03:42:14'), t_end_dt=Timestamp('2026-02-04 04:42:14.256315104'), label='Debut_2026-02-04T034214.mp4')

Pandas(Index=837, t_start=Timestamp('2026-02-04 04:42:18'), t_duration=3600.299283854167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T044218.mp4', video_num_frames=88889, video_fps=24.689336355627407, video_width=640, video_height=480, video_file_size=105019538, cache_file_size=105019538, cache_file_mtime=1770201741.0698175, t_start_dt=Timestamp('2026-02-04 04:42:18'), t_end_dt=Timestamp('2026-02-04 05:42:18.299283854'), label='Debut_2026-02-04T044218.mp4')

Pandas(Index=838, t_start=Timestamp('2026-02-04 05:42:22'), t_duration=2460.4733723958334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T054222.mp4', video_num_frames=58812, video_fps=23.902717525747118, video_width=640, video_height=480, video_file_size=71262556, cache_file_size=71262556, cache_file_mtime=1770204204.72542, t_start_dt=Timestamp('2026-02-04 05:42:22'), t_end_dt=Timestamp('2026-02-04 06:23:22.473372396'), label='Debut_2026-02-04T054222.mp4')

Pandas(Index=839, t_start=Timestamp('2026-02-04 06:23:28'), t_duration=3600.3573567708336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T062328.mp4', video_num_frames=87287, video_fps=24.24398229132673, video_width=640, video_height=480, video_file_size=105313843, cache_file_size=105313843, cache_file_mtime=1770207810.23965, t_start_dt=Timestamp('2026-02-04 06:23:28'), t_end_dt=Timestamp('2026-02-04 07:23:28.357356771'), label='Debut_2026-02-04T062328.mp4')

Pandas(Index=840, t_start=Timestamp('2026-02-04 07:23:31'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T072331.mp4', video_num_frames=86391, video_fps=23.99574466892387, video_width=640, video_height=480, video_file_size=104455231, cache_file_size=104455231, cache_file_mtime=1770211414.038941, t_start_dt=Timestamp('2026-02-04 07:23:31'), t_end_dt=Timestamp('2026-02-04 08:23:31.263346354'), label='Debut_2026-02-04T072331.mp4')

Pandas(Index=841, t_start=Timestamp('2026-02-04 08:23:35'), t_duration=3600.3852864583337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T082335.mp4', video_num_frames=95153, video_fps=26.42856039821259, video_width=640, video_height=480, video_file_size=106995864, cache_file_size=106995864, cache_file_mtime=1770215017.700462, t_start_dt=Timestamp('2026-02-04 08:23:35'), t_end_dt=Timestamp('2026-02-04 09:23:35.385286458'), label='Debut_2026-02-04T082335.mp4')

Pandas(Index=842, t_start=Timestamp('2026-02-04 09:23:38'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T092338.mp4', video_num_frames=105703, video_fps=29.35929129812976, video_width=640, video_height=480, video_file_size=110338958, cache_file_size=110338958, cache_file_mtime=1770218621.3064525, t_start_dt=Timestamp('2026-02-04 09:23:38'), t_end_dt=Timestamp('2026-02-04 10:23:38.325325521'), label='Debut_2026-02-04T092338.mp4')

Pandas(Index=843, t_start=Timestamp('2026-02-04 10:23:42'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T102342.mp4', video_num_frames=107989, video_fps=29.99448395943215, video_width=640, video_height=480, video_file_size=107297135, cache_file_size=107297135, cache_file_mtime=1770222224.751211, t_start_dt=Timestamp('2026-02-04 10:23:42'), t_end_dt=Timestamp('2026-02-04 11:23:42.295312500'), label='Debut_2026-02-04T102342.mp4')

Pandas(Index=844, t_start=Timestamp('2026-02-04 11:23:46'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T112346.mp4', video_num_frames=100062, video_fps=27.793183511190513, video_width=640, video_height=480, video_file_size=107594649, cache_file_size=107594649, cache_file_mtime=1770225828.2542882, t_start_dt=Timestamp('2026-02-04 11:23:46'), t_end_dt=Timestamp('2026-02-04 12:23:46.235286458'), label='Debut_2026-02-04T112346.mp4')

Pandas(Index=845, t_start=Timestamp('2026-02-04 12:23:49'), t_duration=3600.4773437500003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T122349.mp4', video_num_frames=102965, video_fps=28.597596976616163, video_width=640, video_height=480, video_file_size=107678124, cache_file_size=107678124, cache_file_mtime=1770229431.8347208, t_start_dt=Timestamp('2026-02-04 12:23:49'), t_end_dt=Timestamp('2026-02-04 13:23:49.477343750'), label='Debut_2026-02-04T122349.mp4')

Pandas(Index=846, t_start=Timestamp('2026-02-04 13:23:53'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T132353.mp4', video_num_frames=107398, video_fps=29.830330758457748, video_width=640, video_height=480, video_file_size=109033678, cache_file_size=109033678, cache_file_mtime=1770233035.5540478, t_start_dt=Timestamp('2026-02-04 13:23:53'), t_end_dt=Timestamp('2026-02-04 14:23:53.295312500'), label='Debut_2026-02-04T132353.mp4')

Pandas(Index=847, t_start=Timestamp('2026-02-04 14:23:56'), t_duration=3600.235286458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T142356.mp4', video_num_frames=107906, video_fps=29.971930002983385, video_width=640, video_height=480, video_file_size=110205130, cache_file_size=110205130, cache_file_mtime=1770236639.1650019, t_start_dt=Timestamp('2026-02-04 14:23:56'), t_end_dt=Timestamp('2026-02-04 15:23:56.235286458'), label='Debut_2026-02-04T142356.mp4')

Pandas(Index=848, t_start=Timestamp('2026-02-04 15:24:00'), t_duration=3600.3953776041667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T152400.mp4', video_num_frames=106682, video_fps=29.63063464185149, video_width=640, video_height=480, video_file_size=108692880, cache_file_size=108692880, cache_file_mtime=1770240242.7348342, t_start_dt=Timestamp('2026-02-04 15:24:00'), t_end_dt=Timestamp('2026-02-04 16:24:00.395377604'), label='Debut_2026-02-04T152400.mp4')

Pandas(Index=849, t_start=Timestamp('2026-02-04 16:24:04'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T162404.mp4', video_num_frames=105798, video_fps=29.38592276935616, video_width=640, video_height=480, video_file_size=112777782, cache_file_size=112777782, cache_file_mtime=1770243847.079231, t_start_dt=Timestamp('2026-02-04 16:24:04'), t_end_dt=Timestamp('2026-02-04 17:24:04.295312500'), label='Debut_2026-02-04T162404.mp4')

Pandas(Index=850, t_start=Timestamp('2026-02-04 17:24:08'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T172408.mp4', video_num_frames=107463, video_fps=29.848136011001756, video_width=640, video_height=480, video_file_size=113048453, cache_file_size=113048453, cache_file_mtime=1770247452.3980455, t_start_dt=Timestamp('2026-02-04 17:24:08'), t_end_dt=Timestamp('2026-02-04 18:24:08.325325521'), label='Debut_2026-02-04T172408.mp4')

Pandas(Index=851, t_start=Timestamp('2026-02-04 18:24:14'), t_duration=3577.7953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T182414.mp4', video_num_frames=102118, video_fps=28.542158251262453, video_width=640, video_height=480, video_file_size=108536933, cache_file_size=108536933, cache_file_mtime=1770251033.7918959, t_start_dt=Timestamp('2026-02-04 18:24:14'), t_end_dt=Timestamp('2026-02-04 19:23:51.795312500'), label='Debut_2026-02-04T182414.mp4')

Pandas(Index=852, t_start=Timestamp('2026-02-04 19:24:02'), t_duration=3600.2073567708335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T192402.mp4', video_num_frames=107499, video_fps=29.85911347518051, video_width=640, video_height=480, video_file_size=108450904, cache_file_size=108450904, cache_file_mtime=1770254645.1160426, t_start_dt=Timestamp('2026-02-04 19:24:02'), t_end_dt=Timestamp('2026-02-04 20:24:02.207356771'), label='Debut_2026-02-04T192402.mp4')

Pandas(Index=853, t_start=Timestamp('2026-02-04 20:24:06'), t_duration=3139.4073567708333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-04T202406.mp4', video_num_frames=49400, video_fps=15.735453984159738, video_width=640, video_height=480, video_file_size=83944843, cache_file_size=83944843, cache_file_mtime=1770259508.4634166, t_start_dt=Timestamp('2026-02-04 20:24:06'), t_end_dt=Timestamp('2026-02-04 21:16:25.407356771'), label='Debut_2026-02-04T202406.mp4')

Pandas(Index=854, t_start=Timestamp('2026-02-05 03:24:13'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T032413.mp4', video_num_frames=53992, video_fps=14.996539185574715, video_width=640, video_height=480, video_file_size=99863041, cache_file_size=99863041, cache_file_mtime=1770283455.6120932, t_start_dt=Timestamp('2026-02-05 03:24:13'), t_end_dt=Timestamp('2026-02-05 04:24:13.297330729'), label='Debut_2026-02-05T032413.mp4')

Pandas(Index=855, t_start=Timestamp('2026-02-05 04:24:17'), t_duration=3600.4673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T042417.mp4', video_num_frames=56535, video_fps=15.70212808200411, video_width=640, video_height=480, video_file_size=100847982, cache_file_size=100847982, cache_file_mtime=1770287059.4115705, t_start_dt=Timestamp('2026-02-05 04:24:17'), t_end_dt=Timestamp('2026-02-05 05:24:17.467382813'), label='Debut_2026-02-05T042417.mp4')

Pandas(Index=856, t_start=Timestamp('2026-02-05 05:24:21'), t_duration=3600.3853515624996, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T052421.mp4', video_num_frames=53988, video_fps=14.995061563776838, video_width=640, video_height=480, video_file_size=98706622, cache_file_size=98706622, cache_file_mtime=1770290663.0331254, t_start_dt=Timestamp('2026-02-05 05:24:21'), t_end_dt=Timestamp('2026-02-05 06:24:21.385351562'), label='Debut_2026-02-05T052421.mp4')

Pandas(Index=857, t_start=Timestamp('2026-02-05 06:24:24'), t_duration=3600.2673177083334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T062424.mp4', video_num_frames=53998, video_fps=14.998330744610145, video_width=640, video_height=480, video_file_size=99813430, cache_file_size=99813430, cache_file_mtime=1770294266.161304, t_start_dt=Timestamp('2026-02-05 06:24:24'), t_end_dt=Timestamp('2026-02-05 07:24:24.267317708'), label='Debut_2026-02-05T062424.mp4')

Pandas(Index=858, t_start=Timestamp('2026-02-05 07:24:27'), t_duration=3600.4152994791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T072427.mp4', video_num_frames=55109, video_fps=15.306289807170863, video_width=640, video_height=480, video_file_size=97798004, cache_file_size=97798004, cache_file_mtime=1770297869.9500692, t_start_dt=Timestamp('2026-02-05 07:24:27'), t_end_dt=Timestamp('2026-02-05 08:24:27.415299479'), label='Debut_2026-02-05T072427.mp4')

Pandas(Index=859, t_start=Timestamp('2026-02-05 08:24:31'), t_duration=3600.3233072916664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T082431.mp4', video_num_frames=88366, video_fps=24.543906882205277, video_width=640, video_height=480, video_file_size=104653912, cache_file_size=104653912, cache_file_mtime=1770301473.7259004, t_start_dt=Timestamp('2026-02-05 08:24:31'), t_end_dt=Timestamp('2026-02-05 09:24:31.323307292'), label='Debut_2026-02-05T082431.mp4')

Pandas(Index=860, t_start=Timestamp('2026-02-05 09:24:34'), t_duration=3196.5853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T092434.mp4', video_num_frames=80025, video_fps=25.03452628314259, video_width=640, video_height=480, video_file_size=93464125, cache_file_size=93464125, cache_file_mtime=1770304673.1026015, t_start_dt=Timestamp('2026-02-05 09:24:34'), t_end_dt=Timestamp('2026-02-05 10:17:50.585351562'), label='Debut_2026-02-05T092434.mp4')

Pandas(Index=861, t_start=Timestamp('2026-02-05 15:27:22'), t_duration=3600.323307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T152722.mp4', video_num_frames=105877, video_fps=29.407636749057872, video_width=640, video_height=480, video_file_size=110298505, cache_file_size=110298505, cache_file_mtime=1770326845.0435095, t_start_dt=Timestamp('2026-02-05 15:27:22'), t_end_dt=Timestamp('2026-02-05 16:27:22.323307292'), label='Debut_2026-02-05T152722.mp4')

Pandas(Index=862, t_start=Timestamp('2026-02-05 16:27:27'), t_duration=2397.9833333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T162727.mp4', video_num_frames=59908, video_fps=24.982659039887682, video_width=640, video_height=480, video_file_size=71857363, cache_file_size=71857363, cache_file_mtime=1770329247.3606825, t_start_dt=Timestamp('2026-02-05 16:27:27'), t_end_dt=Timestamp('2026-02-05 17:07:24.983333333'), label='Debut_2026-02-05T162727.mp4')

Pandas(Index=863, t_start=Timestamp('2026-02-05 17:07:30'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T170730.mp4', video_num_frames=72465, video_fps=20.127862083013138, video_width=640, video_height=480, video_file_size=110828930, cache_file_size=110828930, cache_file_mtime=1770332853.089942, t_start_dt=Timestamp('2026-02-05 17:07:30'), t_end_dt=Timestamp('2026-02-05 18:07:30.233333333'), label='Debut_2026-02-05T170730.mp4')

Pandas(Index=864, t_start=Timestamp('2026-02-05 18:07:34'), t_duration=3600.2693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T180734.mp4', video_num_frames=78751, video_fps=21.87364128953243, video_width=640, video_height=480, video_file_size=110657215, cache_file_size=110657215, cache_file_mtime=1770336456.8885517, t_start_dt=Timestamp('2026-02-05 18:07:34'), t_end_dt=Timestamp('2026-02-05 19:07:34.269335937'), label='Debut_2026-02-05T180734.mp4')

Pandas(Index=865, t_start=Timestamp('2026-02-05 19:07:38'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T190738.mp4', video_num_frames=81620, video_fps=22.670349835653585, video_width=640, video_height=480, video_file_size=110092941, cache_file_size=110092941, cache_file_mtime=1770340060.8106675, t_start_dt=Timestamp('2026-02-05 19:07:38'), t_end_dt=Timestamp('2026-02-05 20:07:38.297330729'), label='Debut_2026-02-05T190738.mp4')

Pandas(Index=866, t_start=Timestamp('2026-02-05 20:07:42'), t_duration=2553.7152994791663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-05T200742.mp4', video_num_frames=43677, video_fps=17.103316101410357, video_width=640, video_height=480, video_file_size=71790028, cache_file_size=71790028, cache_file_mtime=1770343010.499578, t_start_dt=Timestamp('2026-02-05 20:07:42'), t_end_dt=Timestamp('2026-02-05 20:50:15.715299479'), label='Debut_2026-02-05T200742.mp4')

Pandas(Index=867, t_start=Timestamp('2026-02-06 08:12:41'), t_duration=3600.4753255208334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T081241.mp4', video_num_frames=105149, video_fps=29.204199582950753, video_width=640, video_height=480, video_file_size=107576110, cache_file_size=107576110, cache_file_mtime=1770387164.2696092, t_start_dt=Timestamp('2026-02-06 08:12:41'), t_end_dt=Timestamp('2026-02-06 09:12:41.475325521'), label='Debut_2026-02-06T081241.mp4')

Pandas(Index=868, t_start=Timestamp('2026-02-06 09:12:46'), t_duration=1264.7413411458333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T091246.mp4', video_num_frames=37324, video_fps=29.511172589792245, video_width=640, video_height=480, video_file_size=35024060, cache_file_size=35024060, cache_file_mtime=1770388432.2016015, t_start_dt=Timestamp('2026-02-06 09:12:46'), t_end_dt=Timestamp('2026-02-06 09:33:50.741341146'), label='Debut_2026-02-06T091246.mp4')

Pandas(Index=869, t_start=Timestamp('2026-02-06 09:34:15'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T093415.mp4', video_num_frames=102129, video_fps=28.367312141323225, video_width=640, video_height=480, video_file_size=110088491, cache_file_size=110088491, cache_file_mtime=1770392057.4435005, t_start_dt=Timestamp('2026-02-06 09:34:15'), t_end_dt=Timestamp('2026-02-06 10:34:15.235351562'), label='Debut_2026-02-06T093415.mp4')

Pandas(Index=870, t_start=Timestamp('2026-02-06 10:34:18'), t_duration=3485.5513020833337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T103418.mp4', video_num_frames=90868, video_fps=26.069907490871728, video_width=640, video_height=480, video_file_size=108663272, cache_file_size=108663272, cache_file_mtime=1770395546.34119, t_start_dt=Timestamp('2026-02-06 10:34:18'), t_end_dt=Timestamp('2026-02-06 11:32:23.551302083'), label='Debut_2026-02-06T103418.mp4')

Pandas(Index=871, t_start=Timestamp('2026-02-06 17:24:31'), t_duration=4.317317708333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T172431.mp4', video_num_frames=90, video_fps=20.846276804294718, video_width=640, video_height=480, video_file_size=137647, cache_file_size=137647, cache_file_mtime=1770416676.8099544, t_start_dt=Timestamp('2026-02-06 17:24:31'), t_end_dt=Timestamp('2026-02-06 17:24:35.317317708'), label='Debut_2026-02-06T172431.mp4')

Pandas(Index=872, t_start=Timestamp('2026-02-06 17:26:24'), t_duration=3600.175325520833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T172624.mp4', video_num_frames=91016, video_fps=25.280990999190525, video_width=640, video_height=480, video_file_size=112893789, cache_file_size=112893789, cache_file_mtime=1770420386.2996044, t_start_dt=Timestamp('2026-02-06 17:26:24'), t_end_dt=Timestamp('2026-02-06 18:26:24.175325521'), label='Debut_2026-02-06T172624.mp4')

Pandas(Index=873, t_start=Timestamp('2026-02-06 18:26:27'), t_duration=3600.293359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T182627.mp4', video_num_frames=86450, video_fps=24.011932187383604, video_width=640, video_height=480, video_file_size=112524842, cache_file_size=112524842, cache_file_mtime=1770423990.1809058, t_start_dt=Timestamp('2026-02-06 18:26:27'), t_end_dt=Timestamp('2026-02-06 19:26:27.293359375'), label='Debut_2026-02-06T182627.mp4')

Pandas(Index=874, t_start=Timestamp('2026-02-06 19:26:31'), t_duration=3600.4152994791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T192631.mp4', video_num_frames=85085, video_fps=23.631996012323448, video_width=640, video_height=480, video_file_size=110634818, cache_file_size=110634818, cache_file_mtime=1770427594.1618693, t_start_dt=Timestamp('2026-02-06 19:26:31'), t_end_dt=Timestamp('2026-02-06 20:26:31.415299479'), label='Debut_2026-02-06T192631.mp4')

Pandas(Index=875, t_start=Timestamp('2026-02-06 20:26:35'), t_duration=3600.2333333333336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T202635.mp4', video_num_frames=87088, video_fps=24.189543270343588, video_width=640, video_height=480, video_file_size=110384943, cache_file_size=110384943, cache_file_mtime=1770431197.886595, t_start_dt=Timestamp('2026-02-06 20:26:35'), t_end_dt=Timestamp('2026-02-06 21:26:35.233333333'), label='Debut_2026-02-06T202635.mp4')

Pandas(Index=876, t_start=Timestamp('2026-02-06 21:26:39'), t_duration=3600.1753255208337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T212639.mp4', video_num_frames=58820, video_fps=16.338093198694587, video_width=640, video_height=480, video_file_size=104820915, cache_file_size=104820915, cache_file_mtime=1770434801.2214437, t_start_dt=Timestamp('2026-02-06 21:26:39'), t_end_dt=Timestamp('2026-02-06 22:26:39.175325521'), label='Debut_2026-02-06T212639.mp4')

Pandas(Index=877, t_start=Timestamp('2026-02-06 22:26:42'), t_duration=3600.3533203125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T222642.mp4', video_num_frames=53966, video_fps=14.989084458887472, video_width=640, video_height=480, video_file_size=94479243, cache_file_size=94479243, cache_file_mtime=1770438404.7043228, t_start_dt=Timestamp('2026-02-06 22:26:42'), t_end_dt=Timestamp('2026-02-06 23:26:42.353320312'), label='Debut_2026-02-06T222642.mp4')

Pandas(Index=878, t_start=Timestamp('2026-02-06 23:26:46'), t_duration=728.0953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T232646.mp4', video_num_frames=10910, video_fps=14.984301935057438, video_width=640, video_height=480, video_file_size=19104162, cache_file_size=19104162, cache_file_mtime=1770439247.332832, t_start_dt=Timestamp('2026-02-06 23:26:46'), t_end_dt=Timestamp('2026-02-06 23:38:54.095312500'), label='Debut_2026-02-06T232646.mp4')

Pandas(Index=879, t_start=Timestamp('2026-02-06 23:40:49'), t_duration=1680.7153645833332, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-06T234049.mp4', video_num_frames=29154, video_fps=17.346185210383663, video_width=640, video_height=480, video_file_size=54896968, cache_file_size=54896968, cache_file_mtime=1770440931.4623995, t_start_dt=Timestamp('2026-02-06 23:40:49'), t_end_dt=Timestamp('2026-02-07 00:08:49.715364583'), label='Debut_2026-02-06T234049.mp4')

Pandas(Index=880, t_start=Timestamp('2026-02-09 07:23:34'), t_duration=3600.3593098958336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T072334.mp4', video_num_frames=94645, video_fps=26.28765405160028, video_width=640, video_height=480, video_file_size=118406818, cache_file_size=118406818, cache_file_mtime=1770643418.07899, t_start_dt=Timestamp('2026-02-09 07:23:34'), t_end_dt=Timestamp('2026-02-09 08:23:34.359309896'), label='Debut_2026-02-09T072334.mp4')

Pandas(Index=881, t_start=Timestamp('2026-02-09 08:23:39'), t_duration=3600.3853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T082339.mp4', video_num_frames=103425, video_fps=28.72609176545935, video_width=640, video_height=480, video_file_size=116653103, cache_file_size=116653103, cache_file_mtime=1770647022.0465996, t_start_dt=Timestamp('2026-02-09 08:23:39'), t_end_dt=Timestamp('2026-02-09 09:23:39.385351563'), label='Debut_2026-02-09T082339.mp4')

Pandas(Index=882, t_start=Timestamp('2026-02-09 09:23:43'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T092343.mp4', video_num_frames=107970, video_fps=29.988956618630223, video_width=640, video_height=480, video_file_size=115142020, cache_file_size=115142020, cache_file_mtime=1770650625.8837793, t_start_dt=Timestamp('2026-02-09 09:23:43'), t_end_dt=Timestamp('2026-02-09 10:23:43.325325521'), label='Debut_2026-02-09T092343.mp4')

Pandas(Index=883, t_start=Timestamp('2026-02-09 10:23:47'), t_duration=3600.3292968749997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T102347.mp4', video_num_frames=107980, video_fps=29.991701062934457, video_width=640, video_height=480, video_file_size=112509915, cache_file_size=112509915, cache_file_mtime=1770654229.2732034, t_start_dt=Timestamp('2026-02-09 10:23:47'), t_end_dt=Timestamp('2026-02-09 11:23:47.329296875'), label='Debut_2026-02-09T102347.mp4')

Pandas(Index=884, t_start=Timestamp('2026-02-09 11:23:49'), t_duration=82.55533854166667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T112349.mp4', video_num_frames=2464, video_fps=29.846646425614132, video_width=640, video_height=480, video_file_size=2503567, cache_file_size=2503567, cache_file_mtime=1770654313.2534075, t_start_dt=Timestamp('2026-02-09 11:23:49'), t_end_dt=Timestamp('2026-02-09 11:25:11.555338542'), label='Debut_2026-02-09T112349.mp4')

Pandas(Index=885, t_start=Timestamp('2026-02-09 14:01:00'), t_duration=1111.4072916666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T140100.mp4', video_num_frames=33295, video_fps=29.957514450054408, video_width=640, video_height=480, video_file_size=33482295, cache_file_size=33482295, cache_file_mtime=1770664772.750604, t_start_dt=Timestamp('2026-02-09 14:01:00'), t_end_dt=Timestamp('2026-02-09 14:19:31.407291667'), label='Debut_2026-02-09T140100.mp4')

Pandas(Index=886, t_start=Timestamp('2026-02-09 14:19:35'), t_duration=3600.4033854166664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T141935.mp4', video_num_frames=107505, video_fps=29.859154236840794, video_width=640, video_height=480, video_file_size=108279318, cache_file_size=108279318, cache_file_mtime=1770668377.6300986, t_start_dt=Timestamp('2026-02-09 14:19:35'), t_end_dt=Timestamp('2026-02-09 15:19:35.403385417'), label='Debut_2026-02-09T141935.mp4')

Pandas(Index=887, t_start=Timestamp('2026-02-09 15:19:40'), t_duration=1187.8873046874999, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T151940.mp4', video_num_frames=34389, video_fps=28.94971590680211, video_width=640, video_height=480, video_file_size=35744859, cache_file_size=35744859, cache_file_mtime=1770669571.6280491, t_start_dt=Timestamp('2026-02-09 15:19:40'), t_end_dt=Timestamp('2026-02-09 15:39:27.887304687'), label='Debut_2026-02-09T151940.mp4')

Pandas(Index=888, t_start=Timestamp('2026-02-09 15:41:18'), t_duration=3619.0133463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T154118.mp4', video_num_frames=108320, video_fps=29.930809763142417, video_width=640, video_height=480, video_file_size=109938425, cache_file_size=109938425, cache_file_mtime=1770673301.0921564, t_start_dt=Timestamp('2026-02-09 15:41:18'), t_end_dt=Timestamp('2026-02-09 16:41:37.013346354'), label='Debut_2026-02-09T154118.mp4')

Pandas(Index=889, t_start=Timestamp('2026-02-09 16:41:44'), t_duration=19.349348958333334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T164144.mp4', video_num_frames=556, video_fps=28.734816928325806, video_width=640, video_height=480, video_file_size=639840, cache_file_size=639840, cache_file_mtime=1770673324.9656851, t_start_dt=Timestamp('2026-02-09 16:41:44'), t_end_dt=Timestamp('2026-02-09 16:42:03.349348958'), label='Debut_2026-02-09T164144.mp4')

Pandas(Index=890, t_start=Timestamp('2026-02-09 16:43:10'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T164310.mp4', video_num_frames=107370, video_fps=29.82253690093268, video_width=640, video_height=480, video_file_size=107271768, cache_file_size=107271768, cache_file_mtime=1770676992.578332, t_start_dt=Timestamp('2026-02-09 16:43:10'), t_end_dt=Timestamp('2026-02-09 17:43:10.297330729'), label='Debut_2026-02-09T164310.mp4')

Pandas(Index=891, t_start=Timestamp('2026-02-09 17:43:15'), t_duration=843.8173177083333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T174315.mp4', video_num_frames=25095, video_fps=29.739849459541578, video_width=640, video_height=480, video_file_size=25066694, cache_file_size=25066694, cache_file_mtime=1770677840.4636736, t_start_dt=Timestamp('2026-02-09 17:43:15'), t_end_dt=Timestamp('2026-02-09 17:57:18.817317708'), label='Debut_2026-02-09T174315.mp4')

Pandas(Index=892, t_start=Timestamp('2026-02-09 17:57:25'), t_duration=3600.273372395833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T175725.mp4', video_num_frames=101752, video_fps=28.262298296611917, video_width=640, video_height=480, video_file_size=107536485, cache_file_size=107536485, cache_file_mtime=1770681448.1781874, t_start_dt=Timestamp('2026-02-09 17:57:25'), t_end_dt=Timestamp('2026-02-09 18:57:25.273372396'), label='Debut_2026-02-09T175725.mp4')

Pandas(Index=893, t_start=Timestamp('2026-02-09 18:57:30'), t_duration=3600.2833333333338, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T185730.mp4', video_num_frames=104050, video_fps=28.900503201136946, video_width=640, video_height=480, video_file_size=106354731, cache_file_size=106354731, cache_file_mtime=1770685052.241271, t_start_dt=Timestamp('2026-02-09 18:57:30'), t_end_dt=Timestamp('2026-02-09 19:57:30.283333333'), label='Debut_2026-02-09T185730.mp4')

Pandas(Index=894, t_start=Timestamp('2026-02-09 19:57:35'), t_duration=216.309375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T195735.mp4', video_num_frames=5543, video_fps=25.625334084572156, video_width=640, video_height=480, video_file_size=6323752, cache_file_size=6323752, cache_file_mtime=1770685272.3731835, t_start_dt=Timestamp('2026-02-09 19:57:35'), t_end_dt=Timestamp('2026-02-09 20:01:11.309375'), label='Debut_2026-02-09T195735.mp4')

Pandas(Index=895, t_start=Timestamp('2026-02-09 22:00:42'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T220042.mp4', video_num_frames=98322, video_fps=27.309426440278987, video_width=640, video_height=480, video_file_size=103765623, cache_file_size=103765623, cache_file_mtime=1770696044.7063487, t_start_dt=Timestamp('2026-02-09 22:00:42'), t_end_dt=Timestamp('2026-02-09 23:00:42.295312500'), label='Debut_2026-02-09T220042.mp4')

Pandas(Index=896, t_start=Timestamp('2026-02-09 23:00:47'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-09T230047.mp4', video_num_frames=107940, video_fps=29.98060723211149, video_width=640, video_height=480, video_file_size=106546695, cache_file_size=106546695, cache_file_mtime=1770699649.5731263, t_start_dt=Timestamp('2026-02-09 23:00:47'), t_end_dt=Timestamp('2026-02-10 00:00:47.327343750'), label='Debut_2026-02-09T230047.mp4')

Pandas(Index=897, t_start=Timestamp('2026-02-10 00:00:51'), t_duration=3600.2973307291663, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T000051.mp4', video_num_frames=107673, video_fps=29.90669661669111, video_width=640, video_height=480, video_file_size=105952036, cache_file_size=105952036, cache_file_mtime=1770703254.2312922, t_start_dt=Timestamp('2026-02-10 00:00:51'), t_end_dt=Timestamp('2026-02-10 01:00:51.297330729'), label='Debut_2026-02-10T000051.mp4')

Pandas(Index=898, t_start=Timestamp('2026-02-10 01:00:56'), t_duration=3600.293359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T010056.mp4', video_num_frames=107515, video_fps=29.862844292961803, video_width=640, video_height=480, video_file_size=104798330, cache_file_size=104798330, cache_file_mtime=1770706858.3591273, t_start_dt=Timestamp('2026-02-10 01:00:56'), t_end_dt=Timestamp('2026-02-10 02:00:56.293359375'), label='Debut_2026-02-10T010056.mp4')

Pandas(Index=899, t_start=Timestamp('2026-02-10 02:01:00'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T020100.mp4', video_num_frames=107992, video_fps=29.99506717754112, video_width=640, video_height=480, video_file_size=105550025, cache_file_size=105550025, cache_file_mtime=1770710462.6586487, t_start_dt=Timestamp('2026-02-10 02:01:00'), t_end_dt=Timestamp('2026-02-10 03:01:00.325325521'), label='Debut_2026-02-10T020100.mp4')

Pandas(Index=900, t_start=Timestamp('2026-02-10 03:01:04'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T030104.mp4', video_num_frames=99183, video_fps=27.548803143576208, video_width=640, video_height=480, video_file_size=104736283, cache_file_size=104736283, cache_file_mtime=1770714066.8679602, t_start_dt=Timestamp('2026-02-10 03:01:04'), t_end_dt=Timestamp('2026-02-10 04:01:04.265299479'), label='Debut_2026-02-10T030104.mp4')

Pandas(Index=901, t_start=Timestamp('2026-02-10 04:01:08'), t_duration=719.12734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T040108.mp4', video_num_frames=17238, video_fps=23.9707197199731, video_width=640, video_height=480, video_file_size=20327994, cache_file_size=20327994, cache_file_mtime=1770715165.339978, t_start_dt=Timestamp('2026-02-10 04:01:08'), t_end_dt=Timestamp('2026-02-10 04:13:07.127343750'), label='Debut_2026-02-10T040108.mp4')

Pandas(Index=902, t_start=Timestamp('2026-02-10 07:12:59'), t_duration=3600.2353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T071259.mp4', video_num_frames=101351, video_fps=28.151215157646217, video_width=640, video_height=480, video_file_size=105034671, cache_file_size=105034671, cache_file_mtime=1770729181.976922, t_start_dt=Timestamp('2026-02-10 07:12:59'), t_end_dt=Timestamp('2026-02-10 08:12:59.235351562'), label='Debut_2026-02-10T071259.mp4')

Pandas(Index=903, t_start=Timestamp('2026-02-10 08:13:04'), t_duration=3512.51328125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T081304.mp4', video_num_frames=104859, video_fps=29.85298320713645, video_width=640, video_height=480, video_file_size=102914917, cache_file_size=102914917, cache_file_mtime=1770732698.8101861, t_start_dt=Timestamp('2026-02-10 08:13:04'), t_end_dt=Timestamp('2026-02-10 09:11:36.513281250'), label='Debut_2026-02-10T081304.mp4')

Pandas(Index=904, t_start=Timestamp('2026-02-10 09:24:45'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T092445.mp4', video_num_frames=107983, video_fps=29.993050103863272, video_width=640, video_height=480, video_file_size=105116452, cache_file_size=105116452, cache_file_mtime=1770737087.7707424, t_start_dt=Timestamp('2026-02-10 09:24:45'), t_end_dt=Timestamp('2026-02-10 10:24:45.267382812'), label='Debut_2026-02-10T092445.mp4')

Pandas(Index=905, t_start=Timestamp('2026-02-10 10:24:49'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T102449.mp4', video_num_frames=107990, video_fps=29.99449485821493, video_width=640, video_height=480, video_file_size=104282098, cache_file_size=104282098, cache_file_mtime=1770740692.5141883, t_start_dt=Timestamp('2026-02-10 10:24:49'), t_end_dt=Timestamp('2026-02-10 11:24:49.327343750'), label='Debut_2026-02-10T102449.mp4')

Pandas(Index=906, t_start=Timestamp('2026-02-10 11:24:54'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T112454.mp4', video_num_frames=107434, video_fps=29.840081183346477, video_width=640, video_height=480, video_file_size=105170349, cache_file_size=105170349, cache_file_mtime=1770744297.0372248, t_start_dt=Timestamp('2026-02-10 11:24:54'), t_end_dt=Timestamp('2026-02-10 12:24:54.325325521'), label='Debut_2026-02-10T112454.mp4')

Pandas(Index=907, t_start=Timestamp('2026-02-10 12:25:00'), t_duration=3600.265299479167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T122500.mp4', video_num_frames=107991, video_fps=29.995289518142606, video_width=640, video_height=480, video_file_size=104657150, cache_file_size=104657150, cache_file_mtime=1770747903.1457727, t_start_dt=Timestamp('2026-02-10 12:25:00'), t_end_dt=Timestamp('2026-02-10 13:25:00.265299479'), label='Debut_2026-02-10T122500.mp4')

Pandas(Index=908, t_start=Timestamp('2026-02-10 13:25:05'), t_duration=3600.329361979167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T132505.mp4', video_num_frames=107919, video_fps=29.97475762625088, video_width=640, video_height=480, video_file_size=105806710, cache_file_size=105806710, cache_file_mtime=1770751508.076455, t_start_dt=Timestamp('2026-02-10 13:25:05'), t_end_dt=Timestamp('2026-02-10 14:25:05.329361979'), label='Debut_2026-02-10T132505.mp4')

Pandas(Index=909, t_start=Timestamp('2026-02-10 14:25:10'), t_duration=1402.2873046875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T142510.mp4', video_num_frames=42006, video_fps=29.955344999262504, video_width=640, video_height=480, video_file_size=41174891, cache_file_size=41174891, cache_file_mtime=1770752914.4918885, t_start_dt=Timestamp('2026-02-10 14:25:10'), t_end_dt=Timestamp('2026-02-10 14:48:32.287304687'), label='Debut_2026-02-10T142510.mp4')

Pandas(Index=910, t_start=Timestamp('2026-02-10 18:03:26'), t_duration=3600.357356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T180326.mp4', video_num_frames=107801, video_fps=29.941750031359916, video_width=640, video_height=480, video_file_size=114380524, cache_file_size=114380524, cache_file_mtime=1770768208.9369073, t_start_dt=Timestamp('2026-02-10 18:03:26'), t_end_dt=Timestamp('2026-02-10 19:03:26.357356771'), label='Debut_2026-02-10T180326.mp4')

Pandas(Index=911, t_start=Timestamp('2026-02-10 19:03:31'), t_duration=3600.3553385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T190331.mp4', video_num_frames=107991, video_fps=29.994539384476987, video_width=640, video_height=480, video_file_size=110499925, cache_file_size=110499925, cache_file_mtime=1770771813.776263, t_start_dt=Timestamp('2026-02-10 19:03:31'), t_end_dt=Timestamp('2026-02-10 20:03:31.355338542'), label='Debut_2026-02-10T190331.mp4')

Pandas(Index=912, t_start=Timestamp('2026-02-10 20:03:36'), t_duration=202.06432291666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-10T200336.mp4', video_num_frames=4512, video_fps=22.329523267008366, video_width=640, video_height=480, video_file_size=5826223, cache_file_size=5826223, cache_file_mtime=1770772019.2310662, t_start_dt=Timestamp('2026-02-10 20:03:36'), t_end_dt=Timestamp('2026-02-10 20:06:58.064322916'), label='Debut_2026-02-10T200336.mp4')

Pandas(Index=913, t_start=Timestamp('2026-02-11 02:02:31'), t_duration=3650.0223307291662, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T020231.mp4', video_num_frames=86632, video_fps=23.734649311773797, video_width=640, video_height=480, video_file_size=104709295, cache_file_size=104709295, cache_file_mtime=1770797004.360188, t_start_dt=Timestamp('2026-02-11 02:02:31'), t_end_dt=Timestamp('2026-02-11 03:03:21.022330729'), label='Debut_2026-02-11T020231.mp4')

Pandas(Index=914, t_start=Timestamp('2026-02-11 03:03:27'), t_duration=1570.3973307291665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T030327.mp4', video_num_frames=37645, video_fps=23.9716403380033, video_width=640, video_height=480, video_file_size=46846173, cache_file_size=46846173, cache_file_mtime=1770798579.0604033, t_start_dt=Timestamp('2026-02-11 03:03:27'), t_end_dt=Timestamp('2026-02-11 03:29:37.397330729'), label='Debut_2026-02-11T030327.mp4')

Pandas(Index=915, t_start=Timestamp('2026-02-11 03:36:25'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T033625.mp4', video_num_frames=86387, video_fps=23.99462018822542, video_width=640, video_height=480, video_file_size=105005710, cache_file_size=105005710, cache_file_mtime=1770802588.1181624, t_start_dt=Timestamp('2026-02-11 03:36:25'), t_end_dt=Timestamp('2026-02-11 04:36:25.265364583'), label='Debut_2026-02-11T033625.mp4')

Pandas(Index=916, t_start=Timestamp('2026-02-11 04:36:30'), t_duration=3600.549348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T043630.mp4', video_num_frames=89727, video_fps=24.92036389557019, video_width=640, video_height=480, video_file_size=105986374, cache_file_size=105986374, cache_file_mtime=1770806192.6873505, t_start_dt=Timestamp('2026-02-11 04:36:30'), t_end_dt=Timestamp('2026-02-11 05:36:30.549348958'), label='Debut_2026-02-11T043630.mp4')

Pandas(Index=917, t_start=Timestamp('2026-02-11 05:36:34'), t_duration=3600.4473307291664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T053634.mp4', video_num_frames=86386, video_fps=23.99312975993597, video_width=640, video_height=480, video_file_size=104762299, cache_file_size=104762299, cache_file_mtime=1770809796.9750614, t_start_dt=Timestamp('2026-02-11 05:36:34'), t_end_dt=Timestamp('2026-02-11 06:36:34.447330729'), label='Debut_2026-02-11T053634.mp4')

Pandas(Index=918, t_start=Timestamp('2026-02-11 06:36:38'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T063638.mp4', video_num_frames=85225, video_fps=23.6714586933176, video_width=640, video_height=480, video_file_size=107472237, cache_file_size=107472237, cache_file_mtime=1770813401.1155944, t_start_dt=Timestamp('2026-02-11 06:36:38'), t_end_dt=Timestamp('2026-02-11 07:36:38.327343750'), label='Debut_2026-02-11T063638.mp4')

Pandas(Index=919, t_start=Timestamp('2026-02-11 07:36:43'), t_duration=2736.0453125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T073643.mp4', video_num_frames=65184, video_fps=23.824166837514685, video_width=640, video_height=480, video_file_size=79690703, cache_file_size=79690703, cache_file_mtime=1770816429.6016238, t_start_dt=Timestamp('2026-02-11 07:36:43'), t_end_dt=Timestamp('2026-02-11 08:22:19.045312500'), label='Debut_2026-02-11T073643.mp4')

Pandas(Index=920, t_start=Timestamp('2026-02-11 11:41:43'), t_duration=3600.3273437499997, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T114143.mp4', video_num_frames=86452, video_fps=24.012261037896078, video_width=640, video_height=480, video_file_size=108198241, cache_file_size=108198241, cache_file_mtime=1770831705.4345374, t_start_dt=Timestamp('2026-02-11 11:41:43'), t_end_dt=Timestamp('2026-02-11 12:41:43.327343750'), label='Debut_2026-02-11T114143.mp4')

Pandas(Index=921, t_start=Timestamp('2026-02-11 12:41:46'), t_duration=3600.2652994791665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T124146.mp4', video_num_frames=89658, video_fps=24.903164778709613, video_width=640, video_height=480, video_file_size=105144601, cache_file_size=105144601, cache_file_mtime=1770835308.8437304, t_start_dt=Timestamp('2026-02-11 12:41:46'), t_end_dt=Timestamp('2026-02-11 13:41:46.265299479'), label='Debut_2026-02-11T124146.mp4')

Pandas(Index=922, t_start=Timestamp('2026-02-11 13:41:50'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T134150.mp4', video_num_frames=87795, video_fps=24.385485957133135, video_width=640, video_height=480, video_file_size=114644641, cache_file_size=114644641, cache_file_mtime=1770838912.4788902, t_start_dt=Timestamp('2026-02-11 13:41:50'), t_end_dt=Timestamp('2026-02-11 14:41:50.297330729'), label='Debut_2026-02-11T134150.mp4')

Pandas(Index=923, t_start=Timestamp('2026-02-11 14:41:53'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T144153.mp4', video_num_frames=87618, video_fps=24.336539428987404, video_width=640, video_height=480, video_file_size=106759772, cache_file_size=106759772, cache_file_mtime=1770842515.968515, t_start_dt=Timestamp('2026-02-11 14:41:53'), t_end_dt=Timestamp('2026-02-11 15:41:53.265364583'), label='Debut_2026-02-11T144153.mp4')

Pandas(Index=924, t_start=Timestamp('2026-02-11 15:41:57'), t_duration=3600.4152994791666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T154157.mp4', video_num_frames=92141, video_fps=25.591769930910207, video_width=640, video_height=480, video_file_size=111624532, cache_file_size=111624532, cache_file_mtime=1770846119.940776, t_start_dt=Timestamp('2026-02-11 15:41:57'), t_end_dt=Timestamp('2026-02-11 16:41:57.415299479'), label='Debut_2026-02-11T154157.mp4')

Pandas(Index=925, t_start=Timestamp('2026-02-11 16:42:01'), t_duration=2789.0353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T164201.mp4', video_num_frames=65424, video_fps=23.45757287133257, video_width=640, video_height=480, video_file_size=86218292, cache_file_size=86218292, cache_file_mtime=1770850638.1094518, t_start_dt=Timestamp('2026-02-11 16:42:01'), t_end_dt=Timestamp('2026-02-11 17:28:30.035351563'), label='Debut_2026-02-11T164201.mp4')

Pandas(Index=926, t_start=Timestamp('2026-02-11 18:39:23'), t_duration=3600.293294270833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T183923.mp4', video_num_frames=54037, video_fps=15.009054980600991, video_width=640, video_height=480, video_file_size=111470626, cache_file_size=111470626, cache_file_mtime=1770856765.8992655, t_start_dt=Timestamp('2026-02-11 18:39:23'), t_end_dt=Timestamp('2026-02-11 19:39:23.293294271'), label='Debut_2026-02-11T183923.mp4')

Pandas(Index=927, t_start=Timestamp('2026-02-11 19:39:27'), t_duration=1208.3973307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-11T193927.mp4', video_num_frames=18121, video_fps=14.995895422133623, video_width=640, video_height=480, video_file_size=35424538, cache_file_size=35424538, cache_file_mtime=1770857976.9980345, t_start_dt=Timestamp('2026-02-11 19:39:27'), t_end_dt=Timestamp('2026-02-11 19:59:35.397330729'), label='Debut_2026-02-11T193927.mp4')

Pandas(Index=928, t_start=Timestamp('2026-02-12 07:26:05'), t_duration=3443.12734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T072605.mp4', video_num_frames=83112, video_fps=24.138520508358702, video_width=640, video_height=480, video_file_size=103879593, cache_file_size=103879593, cache_file_mtime=1770902611.5151396, t_start_dt=Timestamp('2026-02-12 07:26:05'), t_end_dt=Timestamp('2026-02-12 08:23:28.127343750'), label='Debut_2026-02-12T072605.mp4')

Pandas(Index=929, t_start=Timestamp('2026-02-12 08:32:31'), t_duration=3600.2933593750004, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T083231.mp4', video_num_frames=88462, video_fps=24.5707755368459, video_width=640, video_height=480, video_file_size=104796625, cache_file_size=104796625, cache_file_mtime=1770906753.8325765, t_start_dt=Timestamp('2026-02-12 08:32:31'), t_end_dt=Timestamp('2026-02-12 09:32:31.293359375'), label='Debut_2026-02-12T083231.mp4')

Pandas(Index=930, t_start=Timestamp('2026-02-12 09:32:35'), t_duration=837.6833333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T093235.mp4', video_num_frames=20095, video_fps=23.988778575834147, video_width=640, video_height=480, video_file_size=25283173, cache_file_size=25283173, cache_file_mtime=1770907594.1624115, t_start_dt=Timestamp('2026-02-12 09:32:35'), t_end_dt=Timestamp('2026-02-12 09:46:32.683333333'), label='Debut_2026-02-12T093235.mp4')

Pandas(Index=931, t_start=Timestamp('2026-02-12 12:12:23'), t_duration=3600.3553385416667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T121223.mp4', video_num_frames=102745, video_fps=28.53746098339758, video_width=640, video_height=480, video_file_size=111119317, cache_file_size=111119317, cache_file_mtime=1770919946.2727993, t_start_dt=Timestamp('2026-02-12 12:12:23'), t_end_dt=Timestamp('2026-02-12 13:12:23.355338542'), label='Debut_2026-02-12T121223.mp4')

Pandas(Index=932, t_start=Timestamp('2026-02-12 13:12:27'), t_duration=3600.2712890625003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T131227.mp4', video_num_frames=99746, video_fps=27.705134416682682, video_width=640, video_height=480, video_file_size=108112882, cache_file_size=108112882, cache_file_mtime=1770923549.4127698, t_start_dt=Timestamp('2026-02-12 13:12:27'), t_end_dt=Timestamp('2026-02-12 14:12:27.271289063'), label='Debut_2026-02-12T131227.mp4')

Pandas(Index=933, t_start=Timestamp('2026-02-12 14:12:30'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T141230.mp4', video_num_frames=107981, video_fps=29.99201189808567, video_width=640, video_height=480, video_file_size=107188914, cache_file_size=107188914, cache_file_mtime=1770927152.7670763, t_start_dt=Timestamp('2026-02-12 14:12:30'), t_end_dt=Timestamp('2026-02-12 15:12:30.325325521'), label='Debut_2026-02-12T141230.mp4')

Pandas(Index=934, t_start=Timestamp('2026-02-12 15:12:33'), t_duration=3600.2073567708335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T151233.mp4', video_num_frames=107977, video_fps=29.991883605517874, video_width=640, video_height=480, video_file_size=103539106, cache_file_size=103539106, cache_file_mtime=1770930756.7000513, t_start_dt=Timestamp('2026-02-12 15:12:33'), t_end_dt=Timestamp('2026-02-12 16:12:33.207356771'), label='Debut_2026-02-12T151233.mp4')

Pandas(Index=935, t_start=Timestamp('2026-02-12 16:12:38'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T161238.mp4', video_num_frames=107980, video_fps=29.991967351799484, video_width=640, video_height=480, video_file_size=108844522, cache_file_size=108844522, cache_file_mtime=1770934360.97361, t_start_dt=Timestamp('2026-02-12 16:12:38'), t_end_dt=Timestamp('2026-02-12 17:12:38.297330729'), label='Debut_2026-02-12T161238.mp4')

Pandas(Index=936, t_start=Timestamp('2026-02-12 17:12:42'), t_duration=3600.2473307291666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T171242.mp4', video_num_frames=105376, video_fps=29.269100236693447, video_width=640, video_height=480, video_file_size=108302056, cache_file_size=108302056, cache_file_mtime=1770937964.2975225, t_start_dt=Timestamp('2026-02-12 17:12:42'), t_end_dt=Timestamp('2026-02-12 18:12:42.247330729'), label='Debut_2026-02-12T171242.mp4')

Pandas(Index=937, t_start=Timestamp('2026-02-12 18:12:45'), t_duration=3600.2693359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T181245.mp4', video_num_frames=94574, video_fps=26.268590256837882, video_width=640, video_height=480, video_file_size=105984212, cache_file_size=105984212, cache_file_mtime=1770941567.347927, t_start_dt=Timestamp('2026-02-12 18:12:45'), t_end_dt=Timestamp('2026-02-12 19:12:45.269335937'), label='Debut_2026-02-12T181245.mp4')

Pandas(Index=938, t_start=Timestamp('2026-02-12 19:12:48'), t_duration=3600.279361979167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T191248.mp4', video_num_frames=99228, video_fps=27.561194569482463, video_width=640, video_height=480, video_file_size=106906603, cache_file_size=106906603, cache_file_mtime=1770945170.5417602, t_start_dt=Timestamp('2026-02-12 19:12:48'), t_end_dt=Timestamp('2026-02-12 20:12:48.279361979'), label='Debut_2026-02-12T191248.mp4')

Pandas(Index=939, t_start=Timestamp('2026-02-12 20:12:51'), t_duration=3600.2693359375003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T201251.mp4', video_num_frames=107983, video_fps=29.99303383280949, video_width=640, video_height=480, video_file_size=103492043, cache_file_size=103492043, cache_file_mtime=1770948773.5451236, t_start_dt=Timestamp('2026-02-12 20:12:51'), t_end_dt=Timestamp('2026-02-12 21:12:51.269335938'), label='Debut_2026-02-12T201251.mp4')

Pandas(Index=940, t_start=Timestamp('2026-02-12 21:12:54'), t_duration=556.9733072916666, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T211254.mp4', video_num_frames=16683, video_fps=29.95296144643377, video_width=640, video_height=480, video_file_size=15548175, cache_file_size=15548175, cache_file_mtime=1770950165.115657, t_start_dt=Timestamp('2026-02-12 21:12:54'), t_end_dt=Timestamp('2026-02-12 21:22:10.973307292'), label='Debut_2026-02-12T211254.mp4')

Pandas(Index=941, t_start=Timestamp('2026-02-12 22:43:56'), t_duration=3600.2633463541665, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T224356.mp4', video_num_frames=104324, video_fps=28.976769187077515, video_width=640, video_height=480, video_file_size=106421079, cache_file_size=106421079, cache_file_mtime=1770957839.181384, t_start_dt=Timestamp('2026-02-12 22:43:56'), t_end_dt=Timestamp('2026-02-12 23:43:56.263346354'), label='Debut_2026-02-12T224356.mp4')

Pandas(Index=942, t_start=Timestamp('2026-02-12 23:44:00'), t_duration=3600.2733723958336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-12T234400.mp4', video_num_frames=96709, video_fps=26.861571329969355, video_width=640, video_height=480, video_file_size=105881138, cache_file_size=105881138, cache_file_mtime=1770961442.657176, t_start_dt=Timestamp('2026-02-12 23:44:00'), t_end_dt=Timestamp('2026-02-13 00:44:00.273372396'), label='Debut_2026-02-12T234400.mp4')

Pandas(Index=943, t_start=Timestamp('2026-02-13 00:44:03'), t_duration=3600.27734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T004403.mp4', video_num_frames=85579, video_fps=23.77011319657448, video_width=640, video_height=480, video_file_size=105047328, cache_file_size=105047328, cache_file_mtime=1770965046.0329695, t_start_dt=Timestamp('2026-02-13 00:44:03'), t_end_dt=Timestamp('2026-02-13 01:44:03.277343750'), label='Debut_2026-02-13T004403.mp4')

Pandas(Index=944, t_start=Timestamp('2026-02-13 01:44:07'), t_duration=2025.7353515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T014407.mp4', video_num_frames=52924, video_fps=26.12582140069699, video_width=640, video_height=480, video_file_size=58883782, cache_file_size=58883782, cache_file_mtime=1770984943.0437236, t_start_dt=Timestamp('2026-02-13 01:44:07'), t_end_dt=Timestamp('2026-02-13 02:17:52.735351562'), label='Debut_2026-02-13T014407.mp4')

Pandas(Index=945, t_start=Timestamp('2026-02-13 07:18:05'), t_duration=3600.3013020833337, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T071805.mp4', video_num_frames=93584, video_fps=25.99338003901149, video_width=640, video_height=480, video_file_size=107940274, cache_file_size=107940274, cache_file_mtime=1770988688.125465, t_start_dt=Timestamp('2026-02-13 07:18:05'), t_end_dt=Timestamp('2026-02-13 08:18:05.301302083'), label='Debut_2026-02-13T071805.mp4')

Pandas(Index=946, t_start=Timestamp('2026-02-13 08:18:09'), t_duration=3600.255338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T081809.mp4', video_num_frames=92210, video_fps=25.6120722918922, video_width=640, video_height=480, video_file_size=104784866, cache_file_size=104784866, cache_file_mtime=1770992291.8196437, t_start_dt=Timestamp('2026-02-13 08:18:09'), t_end_dt=Timestamp('2026-02-13 09:18:09.255338542'), label='Debut_2026-02-13T081809.mp4')

Pandas(Index=947, t_start=Timestamp('2026-02-13 10:19:14'), t_duration=3600.357356770833, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T101914.mp4', video_num_frames=107697, video_fps=29.912864009864183, video_width=640, video_height=480, video_file_size=118060414, cache_file_size=118060414, cache_file_mtime=1770999556.9819045, t_start_dt=Timestamp('2026-02-13 10:19:14'), t_end_dt=Timestamp('2026-02-13 11:19:14.357356771'), label='Debut_2026-02-13T101914.mp4')

Pandas(Index=948, t_start=Timestamp('2026-02-13 11:19:18'), t_duration=3600.2733072916667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T111918.mp4', video_num_frames=107680, video_fps=29.908840471059435, video_width=640, video_height=480, video_file_size=116536694, cache_file_size=116536694, cache_file_mtime=1771003161.3006718, t_start_dt=Timestamp('2026-02-13 11:19:18'), t_end_dt=Timestamp('2026-02-13 12:19:18.273307292'), label='Debut_2026-02-13T111918.mp4')

Pandas(Index=949, t_start=Timestamp('2026-02-13 12:19:22'), t_duration=3600.299348958333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T121922.mp4', video_num_frames=107927, video_fps=29.977229540989775, video_width=640, video_height=480, video_file_size=109344146, cache_file_size=109344146, cache_file_mtime=1771006765.352227, t_start_dt=Timestamp('2026-02-13 12:19:22'), t_end_dt=Timestamp('2026-02-13 13:19:22.299348958'), label='Debut_2026-02-13T121922.mp4')

Pandas(Index=950, t_start=Timestamp('2026-02-13 13:19:26'), t_duration=3600.2673828125003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T131926.mp4', video_num_frames=107056, video_fps=29.735569227741276, video_width=640, video_height=480, video_file_size=117003595, cache_file_size=117003595, cache_file_mtime=1771010368.854966, t_start_dt=Timestamp('2026-02-13 13:19:26'), t_end_dt=Timestamp('2026-02-13 14:19:26.267382813'), label='Debut_2026-02-13T131926.mp4')

Pandas(Index=951, t_start=Timestamp('2026-02-13 14:19:29'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T141929.mp4', video_num_frames=107167, video_fps=29.765921218382374, video_width=640, video_height=480, video_file_size=114979919, cache_file_size=114979919, cache_file_mtime=1771013972.334288, t_start_dt=Timestamp('2026-02-13 14:19:29'), t_end_dt=Timestamp('2026-02-13 15:19:29.325325521'), label='Debut_2026-02-13T141929.mp4')

Pandas(Index=952, t_start=Timestamp('2026-02-13 15:19:33'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T151933.mp4', video_num_frames=107934, video_fps=29.97920743480678, video_width=640, video_height=480, video_file_size=113473361, cache_file_size=113473361, cache_file_mtime=1771017575.9637964, t_start_dt=Timestamp('2026-02-13 15:19:33'), t_end_dt=Timestamp('2026-02-13 16:19:33.295312500'), label='Debut_2026-02-13T151933.mp4')

Pandas(Index=953, t_start=Timestamp('2026-02-13 16:19:37'), t_duration=3600.2693359375003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T161937.mp4', video_num_frames=106441, video_fps=29.56473254306766, video_width=640, video_height=480, video_file_size=111886606, cache_file_size=111886606, cache_file_mtime=1771021179.520819, t_start_dt=Timestamp('2026-02-13 16:19:37'), t_end_dt=Timestamp('2026-02-13 17:19:37.269335938'), label='Debut_2026-02-13T161937.mp4')

Pandas(Index=954, t_start=Timestamp('2026-02-13 18:26:45'), t_duration=471.5932942708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-13T182645.mp4', video_num_frames=10543, video_fps=22.356127892576044, video_width=640, video_height=480, video_file_size=15385105, cache_file_size=15385105, cache_file_mtime=1771025677.911799, t_start_dt=Timestamp('2026-02-13 18:26:45'), t_end_dt=Timestamp('2026-02-13 18:34:36.593294271'), label='Debut_2026-02-13T182645.mp4')

Pandas(Index=955, t_start=Timestamp('2026-02-16 07:39:25'), t_duration=3600.2673828125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T073925.mp4', video_num_frames=107799, video_fps=29.94194278864596, video_width=640, video_height=480, video_file_size=112088946, cache_file_size=112088946, cache_file_mtime=1771249167.96331, t_start_dt=Timestamp('2026-02-16 07:39:25'), t_end_dt=Timestamp('2026-02-16 08:39:25.267382812'), label='Debut_2026-02-16T073925.mp4')

Pandas(Index=956, t_start=Timestamp('2026-02-16 08:39:29'), t_duration=3600.3253255208333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T083929.mp4', video_num_frames=105730, video_fps=29.3667906204295, video_width=640, video_height=480, video_file_size=114033626, cache_file_size=114033626, cache_file_mtime=1771252771.7965183, t_start_dt=Timestamp('2026-02-16 08:39:29'), t_end_dt=Timestamp('2026-02-16 09:39:29.325325521'), label='Debut_2026-02-16T083929.mp4')

Pandas(Index=957, t_start=Timestamp('2026-02-16 09:39:34'), t_duration=3600.8073567708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T093934.mp4', video_num_frames=66802, video_fps=18.55195054364345, video_width=640, video_height=480, video_file_size=106529548, cache_file_size=106529548, cache_file_mtime=1771256378.0453682, t_start_dt=Timestamp('2026-02-16 09:39:34'), t_end_dt=Timestamp('2026-02-16 10:39:34.807356771'), label='Debut_2026-02-16T093934.mp4')

Pandas(Index=958, t_start=Timestamp('2026-02-16 10:39:41'), t_duration=3600.4063151041664, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T103941.mp4', video_num_frames=99974, video_fps=27.76742157700264, video_width=640, video_height=480, video_file_size=111317314, cache_file_size=111317314, cache_file_mtime=1771259984.2653198, t_start_dt=Timestamp('2026-02-16 10:39:41'), t_end_dt=Timestamp('2026-02-16 11:39:41.406315104'), label='Debut_2026-02-16T103941.mp4')

Pandas(Index=959, t_start=Timestamp('2026-02-16 11:39:45'), t_duration=602.5473307291667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T113945.mp4', video_num_frames=18056, video_fps=29.96611067573681, video_width=640, video_height=480, video_file_size=18809347, cache_file_size=18809347, cache_file_mtime=1771260588.8336768, t_start_dt=Timestamp('2026-02-16 11:39:45'), t_end_dt=Timestamp('2026-02-16 11:49:47.547330729'), label='Debut_2026-02-16T113945.mp4')

Pandas(Index=960, t_start=Timestamp('2026-02-16 12:10:48'), t_duration=3600.233333333333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T121048.mp4', video_num_frames=106652, video_fps=29.62363550510615, video_width=640, video_height=480, video_file_size=111870125, cache_file_size=111870125, cache_file_mtime=1771265451.0617476, t_start_dt=Timestamp('2026-02-16 12:10:48'), t_end_dt=Timestamp('2026-02-16 13:10:48.233333333'), label='Debut_2026-02-16T121048.mp4')

Pandas(Index=961, t_start=Timestamp('2026-02-16 13:10:52'), t_duration=602.3153645833333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T131052.mp4', video_num_frames=17770, video_fps=29.502817037205816, video_width=640, video_height=480, video_file_size=18434962, cache_file_size=18434962, cache_file_mtime=1771266055.7501326, t_start_dt=Timestamp('2026-02-16 13:10:52'), t_end_dt=Timestamp('2026-02-16 13:20:54.315364583'), label='Debut_2026-02-16T131052.mp4')

Pandas(Index=962, t_start=Timestamp('2026-02-16 13:21:16'), t_duration=3605.9013671875, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T132116.mp4', video_num_frames=93959, video_fps=26.05700778590218, video_width=640, video_height=480, video_file_size=105262680, cache_file_size=105262680, cache_file_mtime=1771269708.6513507, t_start_dt=Timestamp('2026-02-16 13:21:16'), t_end_dt=Timestamp('2026-02-16 14:21:21.901367188'), label='Debut_2026-02-16T132116.mp4')

Pandas(Index=963, t_start=Timestamp('2026-02-16 14:21:50'), t_duration=3602.0663411458336, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T142150.mp4', video_num_frames=94938, video_fps=26.356538444486226, video_width=640, video_height=480, video_file_size=108363107, cache_file_size=108363107, cache_file_mtime=1771273313.412016, t_start_dt=Timestamp('2026-02-16 14:21:50'), t_end_dt=Timestamp('2026-02-16 15:21:52.066341146'), label='Debut_2026-02-16T142150.mp4')

Pandas(Index=964, t_start=Timestamp('2026-02-16 15:21:55'), t_duration=3600.3073567708334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T152155.mp4', video_num_frames=107347, video_fps=29.81606550844066, video_width=640, video_height=480, video_file_size=110932724, cache_file_size=110932724, cache_file_mtime=1771276917.4954498, t_start_dt=Timestamp('2026-02-16 15:21:55'), t_end_dt=Timestamp('2026-02-16 16:21:55.307356771'), label='Debut_2026-02-16T152155.mp4')

Pandas(Index=965, t_start=Timestamp('2026-02-16 16:21:58'), t_duration=3600.297330729167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T162158.mp4', video_num_frames=106963, video_fps=29.709490682075646, video_width=640, video_height=480, video_file_size=109851464, cache_file_size=109851464, cache_file_mtime=1771280521.318741, t_start_dt=Timestamp('2026-02-16 16:21:58'), t_end_dt=Timestamp('2026-02-16 17:21:58.297330729'), label='Debut_2026-02-16T162158.mp4')

Pandas(Index=966, t_start=Timestamp('2026-02-16 17:22:02'), t_duration=3600.2713541666667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T172202.mp4', video_num_frames=105676, video_fps=29.35223198598601, video_width=640, video_height=480, video_file_size=108469332, cache_file_size=108469332, cache_file_mtime=1771284125.3209813, t_start_dt=Timestamp('2026-02-16 17:22:02'), t_end_dt=Timestamp('2026-02-16 18:22:02.271354167'), label='Debut_2026-02-16T172202.mp4')

Pandas(Index=967, t_start=Timestamp('2026-02-16 18:22:07'), t_duration=391.8853515625, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T182207.mp4', video_num_frames=11733, video_fps=29.939878980469516, video_width=640, video_height=480, video_file_size=11926287, cache_file_size=11926287, cache_file_mtime=1771284519.7678354, t_start_dt=Timestamp('2026-02-16 18:22:07'), t_end_dt=Timestamp('2026-02-16 18:28:38.885351562'), label='Debut_2026-02-16T182207.mp4')

Pandas(Index=968, t_start=Timestamp('2026-02-16 19:23:36'), t_duration=2102.6653645833335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T192336.mp4', video_num_frames=31517, video_fps=14.989070791226661, video_width=640, video_height=480, video_file_size=58929210, cache_file_size=58929210, cache_file_mtime=1771289920.28711, t_start_dt=Timestamp('2026-02-16 19:23:36'), t_end_dt=Timestamp('2026-02-16 19:58:38.665364583'), label='Debut_2026-02-16T192336.mp4')

Pandas(Index=969, t_start=Timestamp('2026-02-16 21:21:49'), t_duration=2375.7263020833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T212149.mp4', video_num_frames=35290, video_fps=14.85440472206471, video_width=640, video_height=480, video_file_size=68648810, cache_file_size=68648810, cache_file_mtime=1771297287.0256934, t_start_dt=Timestamp('2026-02-16 21:21:49'), t_end_dt=Timestamp('2026-02-16 22:01:24.726302083'), label='Debut_2026-02-16T212149.mp4')

Pandas(Index=970, t_start=Timestamp('2026-02-16 22:01:29'), t_duration=3600.2653645833334, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T220129.mp4', video_num_frames=53999, video_fps=14.998616638429214, video_width=640, video_height=480, video_file_size=100982885, cache_file_size=100982885, cache_file_mtime=1771300892.0194244, t_start_dt=Timestamp('2026-02-16 22:01:29'), t_end_dt=Timestamp('2026-02-16 23:01:29.265364583'), label='Debut_2026-02-16T220129.mp4')

Pandas(Index=971, t_start=Timestamp('2026-02-16 23:01:34'), t_duration=3600.255338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-16T230134.mp4', video_num_frames=53090, video_fps=14.746176314679069, video_width=640, video_height=480, video_file_size=101265200, cache_file_size=101265200, cache_file_mtime=1771304496.120608, t_start_dt=Timestamp('2026-02-16 23:01:34'), t_end_dt=Timestamp('2026-02-17 00:01:34.255338542'), label='Debut_2026-02-16T230134.mp4')

Pandas(Index=972, t_start=Timestamp('2026-02-17 00:01:38'), t_duration=3600.2193359375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T000138.mp4', video_num_frames=56555, video_fps=15.708765139797526, video_width=640, video_height=480, video_file_size=100622110, cache_file_size=100622110, cache_file_mtime=1771308100.079412, t_start_dt=Timestamp('2026-02-17 00:01:38'), t_end_dt=Timestamp('2026-02-17 01:01:38.219335938'), label='Debut_2026-02-17T000138.mp4')

Pandas(Index=973, t_start=Timestamp('2026-02-17 01:01:41'), t_duration=3600.1773437499996, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T010141.mp4', video_num_frames=53686, video_fps=14.912043178428494, video_width=640, video_height=480, video_file_size=100180543, cache_file_size=100180543, cache_file_mtime=1771311703.848022, t_start_dt=Timestamp('2026-02-17 01:01:41'), t_end_dt=Timestamp('2026-02-17 02:01:41.177343750'), label='Debut_2026-02-17T010141.mp4')

Pandas(Index=974, t_start=Timestamp('2026-02-17 02:01:45'), t_duration=3600.2923177083335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T020145.mp4', video_num_frames=54335, video_fps=15.091830108557808, video_width=640, video_height=480, video_file_size=99905743, cache_file_size=99905743, cache_file_mtime=1771315308.0743067, t_start_dt=Timestamp('2026-02-17 02:01:45'), t_end_dt=Timestamp('2026-02-17 03:01:45.292317708'), label='Debut_2026-02-17T020145.mp4')

Pandas(Index=975, t_start=Timestamp('2026-02-17 03:01:50'), t_duration=3600.2473958333335, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T030150.mp4', video_num_frames=53997, video_fps=14.998135978791966, video_width=640, video_height=480, video_file_size=99638528, cache_file_size=99638528, cache_file_mtime=1771318912.0631154, t_start_dt=Timestamp('2026-02-17 03:01:50'), t_end_dt=Timestamp('2026-02-17 04:01:50.247395833'), label='Debut_2026-02-17T030150.mp4')

Pandas(Index=976, t_start=Timestamp('2026-02-17 04:01:53'), t_duration=3600.2953125, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T040153.mp4', video_num_frames=54054, video_fps=15.01376840181079, video_width=640, video_height=480, video_file_size=99274674, cache_file_size=99274674, cache_file_mtime=1771322515.864226, t_start_dt=Timestamp('2026-02-17 04:01:53'), t_end_dt=Timestamp('2026-02-17 05:01:53.295312500'), label='Debut_2026-02-17T040153.mp4')

Pandas(Index=977, t_start=Timestamp('2026-02-17 05:02:08'), t_duration=3600.155338541667, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T050208.mp4', video_num_frames=53996, video_fps=14.998241720834312, video_width=640, video_height=480, video_file_size=99508876, cache_file_size=99508876, cache_file_mtime=1771326131.0673554, t_start_dt=Timestamp('2026-02-17 05:02:08'), t_end_dt=Timestamp('2026-02-17 06:02:08.155338542'), label='Debut_2026-02-17T050208.mp4')

Pandas(Index=978, t_start=Timestamp('2026-02-17 06:02:12'), t_duration=3600.181315104167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T060212.mp4', video_num_frames=52454, video_fps=14.569821742014765, video_width=640, video_height=480, video_file_size=98834992, cache_file_size=98834992, cache_file_mtime=1771329734.5230148, t_start_dt=Timestamp('2026-02-17 06:02:12'), t_end_dt=Timestamp('2026-02-17 07:02:12.181315104'), label='Debut_2026-02-17T060212.mp4')

Pandas(Index=979, t_start=Timestamp('2026-02-17 07:02:16'), t_duration=3600.299283854167, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T070216.mp4', video_num_frames=54010, video_fps=15.001530634470365, video_width=640, video_height=480, video_file_size=98529745, cache_file_size=98529745, cache_file_mtime=1771333338.683488, t_start_dt=Timestamp('2026-02-17 07:02:16'), t_end_dt=Timestamp('2026-02-17 08:02:16.299283854'), label='Debut_2026-02-17T070216.mp4')

Pandas(Index=980, t_start=Timestamp('2026-02-17 08:02:20'), t_duration=3600.32734375, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T080220.mp4', video_num_frames=53999, video_fps=14.99835843919574, video_width=640, video_height=480, video_file_size=98303527, cache_file_size=98303527, cache_file_mtime=1771336942.546973, t_start_dt=Timestamp('2026-02-17 08:02:20'), t_end_dt=Timestamp('2026-02-17 09:02:20.327343750'), label='Debut_2026-02-17T080220.mp4')

Pandas(Index=981, t_start=Timestamp('2026-02-17 09:02:24'), t_duration=3600.4773437500003, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T090224.mp4', video_num_frames=85460, video_fps=23.735741636688363, video_width=640, video_height=480, video_file_size=104178310, cache_file_size=104178310, cache_file_mtime=1771340546.7552242, t_start_dt=Timestamp('2026-02-17 09:02:24'), t_end_dt=Timestamp('2026-02-17 10:02:24.477343750'), label='Debut_2026-02-17T090224.mp4')

Pandas(Index=982, t_start=Timestamp('2026-02-17 10:02:28'), t_duration=2377.467317708333, video_file_path='\\\\APOGEE\\mdd_m\\ScreenRecordings\\EyeTrackerVR_Recordings\\Debut_2026-02-17T100228.mp4', video_num_frames=70142, video_fps=29.502824067256007, video_width=640, video_height=480, video_file_size=70243673, cache_file_size=70243673, cache_file_mtime=1771342927.49202, t_start_dt=Timestamp('2026-02-17 10:02:28'), t_end_dt=Timestamp('2026-02-17 10:42:05.467317708'), label='Debut_2026-02-17T100228.mp4')

### Add "now" lines

In [ ]:
import pyqtgraph as pg
from datetime import datetime
from pypho_timeline.utils.datetime_helpers import datetime_to_unix_timestamp

# Get current datetime
now_dt = datetime.now()

# Convert to unix timestamp
now_timestamp = datetime_to_unix_timestamp(now_dt)

# Create a thick red pen
red_pen = pg.mkPen(color='red', width=3)

now_line_items = {}
# Add the vertical line to all plot items
for plot_item in timeline.interval_rendering_plots:
    vline = pg.InfiniteLine(angle=90, movable=False, pos=now_timestamp)
    vline.setPen(red_pen)
    plot_item.addItem(vline, ignoreBounds=True)
    now_line_items[plot_item] = vline

## Export loaded XDF data for analysis in an external apps

#### To .json

In [ ]:
from phopymnehelper.exporters.JSON_Exporter import export_xdf_data_to_json
from pathlib import Path

output_path = Path("xdf_export.json")
export_xdf_data_to_json(
    eeg_raws=_out_eeg_raw,
    stream_infos_df=_out_xdf_stream_infos_df,
    output_path=output_path,
    include_raw_data=True,
    max_samples_per_stream=10000  # Optional: limit for large files
)

In [ ]:

# Usage in your notebook:
# After building the timeline:
# timeline = builder.build_from_xdf_files(xdf_file_paths=demo_xdf_paths)

# Export to JSON:
from pathlib import Path
output_path = Path("timeline_export.json")
export_timeline_to_json(timeline, output_path, include_raw_data=True, max_samples_per_stream=10000)

### to AirTable

In [ ]:
# ===================================================================================
# Complete Airtable Export Demonstration
# Export the newest EEG dataset from loaded XDF files to Airtable
# ===================================================================================

from phopymnehelper.exporters.AiirTable_Exporter import export_eeg_dataset_to_airtable
from phoofflineeeganalysis.analysis.xdf_files import LabRecorderXDF, XDFDataStreamAccessor
from pathlib import Path
import pandas as pd

# ===================================================================================
# Step 1: Ensure data is loaded (assuming this was already done in previous cells)
# ===================================================================================
# The following variables should already exist from earlier cells:
# - _out_eeg_raw: List of MNE Raw objects (sorted by time, newest last)
# - _out_xdf_stream_infos_df: DataFrame with stream information
# - lab_recorder_xdf_files: List of XDF file paths

# Verify data is loaded
assert '_out_eeg_raw' in locals() or '_out_eeg_raw' in globals(), "Please load XDF data first using LabRecorderXDF.load_and_process_all()"
assert len(_out_eeg_raw) > 0, "No EEG datasets loaded"

# ===================================================================================
# Step 2: Get the newest EEG dataset
# ===================================================================================
# The _out_eeg_raw list is sorted by time (most recent last), so the newest is the last item
newest_eeg_raw = _out_eeg_raw[-1]

# Get the corresponding stream info for the newest dataset
# Find the dataset index (should be the highest xdf_dataset_idx)
newest_dataset_idx = _out_xdf_stream_infos_df['xdf_dataset_idx'].max()
newest_stream_info = _out_xdf_stream_infos_df[_out_xdf_stream_infos_df['xdf_dataset_idx'] == newest_dataset_idx].iloc[0]

# Get the source XDF file path
newest_xdf_filename = newest_stream_info.get('xdf_filename', None)
newest_xdf_file_path = None
if newest_xdf_filename:
    # Find the matching file in lab_recorder_xdf_files
    for xdf_file in lab_recorder_xdf_files:
        if xdf_file.name == newest_xdf_filename:
            newest_xdf_file_path = xdf_file
            break

# If not found, try to get from raw.info.description
if newest_xdf_file_path is None:
    desc = newest_eeg_raw.info.get('description', None)
    if desc:
        newest_xdf_file_path = Path(desc)

print(f"Newest EEG Dataset Info:")
print(f"  Dataset Index: {newest_dataset_idx}")
print(f"  Recording Date: {newest_eeg_raw.info.get('meas_date', 'N/A')}")
print(f"  Duration: {newest_eeg_raw.times[-1]:.2f} seconds" if len(newest_eeg_raw.times) > 0 else "  Duration: N/A")
print(f"  Channels: {len(newest_eeg_raw.info['ch_names'])}")
print(f"  Source File: {newest_xdf_file_path}")

# ===================================================================================
# Step 3: Prepare Airtable credentials
# ===================================================================================
# Set your Airtable credentials (you may want to use environment variables or a config file)
AIRTABLE_API_KEY = "your_airtable_api_key_here"  # Get from https://airtable.com/api
AIRTABLE_BASE_ID = "appXXXXXXXXXXXXXX"  # Get from your Airtable base URL
AIRTABLE_TABLE_NAME = "EEG Recordings"  # Name of your table in Airtable

# ===================================================================================
# Step 4: Prepare additional fields from stream info
# ===================================================================================
additional_fields = {
    'XDF Filename': newest_stream_info.get('xdf_filename', None),
    'Stream Name': newest_stream_info.get('name', None),
    'Stream Type': newest_stream_info.get('type', None),
    'Sampling Rate (Hz)': newest_stream_info.get('fs', None),
    'Number of Samples': newest_stream_info.get('n_samples', None),
    'Recording Day Date': newest_stream_info.get('recording_day_date', None),
    'Duration (seconds)': newest_stream_info.get('duration_sec', None),
    'Source ID': newest_stream_info.get('source_id', None),
    'Hostname': newest_stream_info.get('hostname', None),
    'Device Key': newest_stream_info.get('eeg_device_key', None),
    'Number of Segments': newest_stream_info.get('n_eeg_segments_in_group', None),
}

# Remove None values
additional_fields = {k: v for k, v in additional_fields.items() if v is not None}

# Convert datetime/timedelta objects to strings if needed
for key, value in additional_fields.items():
    if hasattr(value, 'isoformat'):
        additional_fields[key] = value.isoformat()
    elif hasattr(value, 'total_seconds'):
        additional_fields[key] = value.total_seconds()

# ===================================================================================
# Step 5: Export to Airtable
# ===================================================================================
print(f"\nExporting to Airtable...")
print(f"  Base ID: {AIRTABLE_BASE_ID}")
print(f"  Table: {AIRTABLE_TABLE_NAME}")

result = export_eeg_dataset_to_airtable(
    raw=newest_eeg_raw,
    airtable_base_id=AIRTABLE_BASE_ID,
    airtable_table_name=AIRTABLE_TABLE_NAME,
    airtable_api_key=AIRTABLE_API_KEY,
    xdf_file_path=newest_xdf_file_path,
    additional_fields=additional_fields
)

# ===================================================================================
# Step 6: Display results
# ===================================================================================
if result['success']:
    print(f"\n✅ Successfully exported to Airtable!")
    print(f"  Record ID: {result['record_id']}")
    print(f"  Fields created: {list(result['fields'].keys())}")
    
    # Display some key fields
    print(f"\nKey exported fields:")
    key_fields = ['Recording Date', 'File Name', 'Number of Channels', 
                  'Sampling Rate (Hz)', 'Duration (seconds)', 'Stream Name']
    for field_name in key_fields:
        if field_name in result['fields']:
            print(f"  {field_name}: {result['fields'][field_name]}")
else:
    print(f"\n❌ Export failed!")
    print(f"  Error: {result.get('error', 'Unknown error')}")

# ===================================================================================
# Optional: Export multiple newest datasets (e.g., last 5)
# ===================================================================================
# If you want to export the last N newest datasets:
"""
from phopymnehelper.exporters.AiirTable_Exporter import export_multiple_eeg_datasets_to_airtable

# Get last 5 newest datasets
n_newest = 5
newest_raws = _out_eeg_raw[-n_newest:]
newest_indices = _out_xdf_stream_infos_df['xdf_dataset_idx'].nlargest(n_newest).tolist()
newest_xdf_paths = []

for idx in newest_indices:
    stream_info = _out_xdf_stream_infos_df[_out_xdf_stream_infos_df['xdf_dataset_idx'] == idx].iloc[0]
    xdf_filename = stream_info.get('xdf_filename', None)
    if xdf_filename:
        for xdf_file in lab_recorder_xdf_files:
            if xdf_file.name == xdf_filename:
                newest_xdf_paths.append(xdf_file)
                break

# Export all
results = export_multiple_eeg_datasets_to_airtable(
    raws=newest_raws,
    airtable_base_id=AIRTABLE_BASE_ID,
    airtable_table_name=AIRTABLE_TABLE_NAME,
    airtable_api_key=AIRTABLE_API_KEY,
    xdf_file_paths=newest_xdf_paths
)

# Check results
successful = sum(1 for r in results if r['success'])
print(f"Successfully exported {successful}/{len(results)} datasets")
"""

In [ ]:
enable_hide_extra_track_x_axes = False
if len(timeline.ui.matplotlib_view_widgets) > 1:
    # Get all plot items
    all_plot_items = []
    for widget_name, widget in timeline.ui.matplotlib_view_widgets.items():
        plot_item = widget.getRootPlotItem()
        if plot_item is not None:
            all_plot_items.append((widget_name, plot_item))
    
    # Hide x-axis for all except the last one (bottom-most)
    if len(all_plot_items) > 1:
        # Hide x-axis for all tracks except the last one
        if enable_hide_extra_track_x_axes:
            for widget_name, plot_item in all_plot_items[:-3]:
                plot_item.hideAxis('bottom')
            # Ensure the last track shows its x-axis
            all_plot_items[-1][1].showAxis('bottom')
        else:
            ## show all
            for widget_name, plot_item in all_plot_items:
                plot_item.showAxis('bottom')

In [ ]:
timeline.track_datasources['EEG_Epoc X'].zo #['Epoc X']

In [ ]:
timeline.track_renderers['EEG_Epoc X']

In [ ]:
zoom_to_fit

In [ ]:
timeline.remove_track(video_track_name)

# SavedSessionProcessor

In [ ]:

sso: SavedSessionsProcessor = SavedSessionsProcessor(eeg_recordings_file_path=eeg_recordings_file_path,
                                                     headset_motion_recordings_file_path=headset_motion_recordings_file_path, WhisperVideoTranscripts_LSL_Converted_file_path=WhisperVideoTranscripts_LSL_Converted, pho_log_to_LSL_recordings_path=pho_log_to_LSL_recordings_path,
                                                    eeg_analyzed_parent_export_path=eeg_analyzed_parent_export_path, 
                                                     n_most_recent_sessions_to_preprocess=n_most_recent_sessions_to_preprocess, 
                                                    # should_load_data=False, should_load_preprocessed=False,
                                                    should_load_data=True, should_load_preprocessed=False,
                                                    #  should_load_data=True, should_load_preprocessed=True,
													)

In [ ]:
most_recent_modern_found_EEG_recording_file_df['src_file'].to_list()
demo_xdf_paths: List[Path] = [Path(v) for v in most_recent_modern_found_EEG_recording_file_df['src_file'].to_list()]

modern_found_EEG_recording_file_df = most_recent_modern_found_EEG_recording_file_df

In [ ]:
modern_found_EEG_recording_file_df.sort_values(by='meas_datetime', ascending=False, inplace=False, ignore_index=True, na_position='last')

In [ ]:
most_recent_xdfs = [Path(v).resolve() for v in deepcopy(modern_found_EEG_recording_file_df).head(n_most_recent_sessions_to_preprocess)['src_file'].tolist()]
most_recent_xdfs

In [ ]:
# modern_found_EEG_recording_files = HistoricalData.get_recording_files(recordings_dir=eeg_recordings_file_path)
# modern_found_EEG_recording_file_df: pd.DataFrame = HistoricalData.build_file_comparison_df(recording_files=modern_found_EEG_recording_files)

In [ ]:
# updated_file_paths, (pending_updated_recording_file_df, modern_found_EEG_recording_file_df, pre_processed_EEG_recording_file_df) = HistoricalData.discover_updated_recording_files(eeg_recordings_file_path=sso.eeg_recordings_file_path,
#                                                                                                                                                                                    eeg_analyzed_parent_export_path=sso.eeg_analyzed_parent_export_path)

In [ ]:
# included_xdf_file_names = [
# 	"E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-21T051157.400Z_eeg.xdf", ## When it started to work
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T215045.162Z_eeg.xdf"
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-20T164055.381Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-18T092615.398Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-17T215112.606Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-17T124127.644Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-17T214946.083Z_eeg.xdf",
#     # # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-22T182649.051Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T220233.548Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T212744.771Z_eeg.xdf",
#     # # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T212721.939Z_eeg.xdf",
#     # # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-10-16T212528.076Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-23T141026.412Z_eeg.xdf",
#     # "E:/Dropbox (Personal)/Databases/UnparsedData/LabRecorderStudies/sub-P001/LabRecorder_Apogee_2025-09-22T213547.659Z_eeg.xdf",
# ]

included_xdf_file_names = deepcopy(most_recent_xdfs)

included_xdf_file_names = [Path(v).resolve() for v in included_xdf_file_names]
included_xdf_file_names = [v.name for v in included_xdf_file_names]


# included_xdf_file_names = None ## include all 
included_xdf_file_names

# 2025-09-18 - LabRecorder XDF Imports

In [ ]:
from phoofflineeeganalysis.analysis.EEG_data import EEGData
from phoofflineeeganalysis.analysis.MNE_helpers import DatasetDatetimeBoundsRenderingMixin, RawArrayExtended, RawExtended, up_convert_raw_objects, up_convert_raw_obj
from phoofflineeeganalysis.analysis.xdf_files import LabRecorderXDF, XDFDataStreamAccessor


labRecorder_PostProcessed_path: Path = sso.eeg_analyzed_parent_export_path.joinpath(f'LabRecorder_PostProcessed')
labRecorder_PostProcessed_path.mkdir(exist_ok=True)

should_load_full_file_data: bool = True
# should_load_full_file_data: bool = False
# should_write_final_merged_eeg_fif: bool = True
should_write_final_merged_eeg_fif: bool = False

fail_on_exception = False
# fail_on_exception = True

_out_eeg_raw, _out_xdf_stream_infos_df, lab_recorder_xdf_files = LabRecorderXDF.load_and_process_all(lab_recorder_output_path=lab_recorder_output_path, 
                                                                                                     labRecorder_PostProcessed_path=labRecorder_PostProcessed_path, 
                                                                                                     should_load_full_file_data=should_load_full_file_data, should_write_final_merged_eeg_fif=should_write_final_merged_eeg_fif,
                                                                                                     included_xdf_file_names=included_xdf_file_names, fail_on_exception=fail_on_exception)
xdf_dataset_indicies = np.unique(deepcopy(_out_xdf_stream_infos_df).reset_index(drop=False, inplace=False)['xdf_dataset_idx'].to_numpy())
n_unique_xdf_datasets: int = len(xdf_dataset_indicies)
print(f'n_unique_xdf_datasets: {n_unique_xdf_datasets}')
_out_xdf_stream_infos_df: pd.DataFrame = XDFDataStreamAccessor.init_from_results(_out_xdf_stream_infos_df=_out_xdf_stream_infos_df, active_only_out_eeg_raws=_out_eeg_raw) # [_out_xdf_stream_infos_df['name'] == 'Epoc X']
_out_xdf_stream_infos_df


## 2m 30s

## Timeline

In [ ]:
included_dataset_idxs = np.arange(3)

_active_out_xdf_stream_infos_df = _out_xdf_stream_infos_df[np.isin(_out_xdf_stream_infos_df['xdf_dataset_idx'], included_dataset_idxs)]
_active_out_eeg_raw = [_out_eeg_raw[i] for i in included_dataset_idxs]

_active_out_xdf_stream_infos_df
len(_active_out_eeg_raw)

In [ ]:
import importlib
import pypho_timeline.rendering.datasources.specific.eeg as eeg
import pypho_timeline.rendering.datasources.track_datasource as track_datasource
import pypho_timeline.rendering.graphics.track_renderer as track_renderer
import pypho_timeline.rendering.async_detail_fetcher as async_detail_fetcher

importlib.reload(track_datasource)
importlib.reload(eeg)
importlib.reload(track_renderer)
importlib.reload(async_detail_fetcher)

In [ ]:

import pyphoplacecellanalysis.External.pyqtgraph as pg
from pypho_timeline.timeline_builder import TimelineBuilder
from pypho_timeline.rendering.datasources.track_datasource import IntervalProvidingTrackDatasource, BaseTrackDatasource
from pypho_timeline.rendering.async_detail_fetcher import AsyncDetailFetcher, DetailFetchWorker
from pypho_timeline.rendering.graphics.track_renderer import TrackRenderer
from pypho_timeline.rendering.datasources.specific.motion import MotionTrackDatasource
from pypho_timeline.rendering.datasources.specific.eeg import EEGTrackDatasource
## INPUTS: _out_eeg_raw, _out_xdf_stream_infos_df -- builds and displays timeline with proper datetime support

# Create Qt application
app = pg.mkQApp("pyPhoTimelineXDFExample")

builder: TimelineBuilder = TimelineBuilder()
# timeline = builder.build_from_eeg_raw_and_stream_info(eeg_raws=_out_eeg_raw, stream_infos_df=_out_xdf_stream_infos_df) 
timeline = builder.build_from_eeg_raw_and_stream_info(eeg_raws=_active_out_eeg_raw, stream_infos_df=_active_out_xdf_stream_infos_df)

In [ ]:
# timeline.interval_datasource_names
timeline.track_datasources

In [ ]:
from pypho_timeline.utils.datetime_helpers import datetime_to_unix_timestamp

x0 = datetime_to_unix_timestamp(timeline.total_data_start_time)
x1 = datetime_to_unix_timestamp(timeline.total_data_end_time)

for plot in timeline.interval_rendering_plots:
    plot.setXRange(x0, x1, padding=0)

In [ ]:
timeline.
# timeline.active_window_visible_intervals_dict

In [ ]:
## I want to pass _out_eeg_raw and _out_xdf_stream_infos_df to the timeline

In [ ]:
_out_eeg_raw[-1].annotations.to_data_frame('datetime')

In [ ]:
(1435.384078 / 60.0) # ~24 mins

(3884.001499 / 60.0) # ~65 mins

In [ ]:
# ## INPUTS to timeline: _out_xdf_stream_infos_df: pd.DataFrame, _out_eeg_raw, lab_recorder_xdf_files, xdf_dataset_indicies

# from phoofflineeeganalysis.analysis.UI.historical_data_timeline import (
#     TimelineWidget, VideoMetadataTrack, EEGRecordingTrack, 
#     MotionRecordingTrack, PhoLogTrack, WhisperTrack
# )

# timeline = TimelineWidget()
# timeline.add_tracks_from_xdf_streams(_out_xdf_stream_infos_df)
# timeline.show()

In [ ]:
# from phoofflineeeganalysis.analysis.UI.historical_data_timeline import (
#     TimelineWidget, VideoMetadataTrack, EEGRecordingTrack, 
#     MotionRecordingTrack, PhoLogTrack, WhisperTrack
# )

# timeline = TimelineWidget()
# timeline.add_tracks_from_xdf_streams(_out_xdf_stream_infos_df)
# timeline.show()

In [ ]:
## sort by 'recording_day_date'
from datetime import timedelta


_filtering_xdf_stream_infos_df = deepcopy(_out_xdf_stream_infos_df).reset_index(drop=True)
_all_xdf_filenames = list(set(_filtering_xdf_stream_infos_df['xdf_filename'].to_list())) ## set(...) to de-duplicate the list

# _out_xdf_stream_infos_df['recording_day_date']
is_eeg_stream = (_filtering_xdf_stream_infos_df['type'] == 'EEG') ## only EEG files
_filtering_xdf_stream_infos_df = _filtering_xdf_stream_infos_df[is_eeg_stream].reset_index(drop=True)
# _filtering_xdf_stream_infos_df
# is_sufficiently_long = [(_filtering_xdf_stream_infos_df['duration_sec'] > timedelta(seconds=30.0))]
# _filtering_xdf_stream_infos_df = _filtering_xdf_stream_infos_df[is_sufficiently_long].reset_index(drop=True)
_filtering_xdf_stream_infos_df = _filtering_xdf_stream_infos_df[(_filtering_xdf_stream_infos_df['duration_sec'] > timedelta(seconds=90.0))].reset_index(drop=True)

_filtering_xdf_stream_infos_df = _filtering_xdf_stream_infos_df.sort_values(by=['recording_datetime', 'created_at_dt', 'first_timestamp_dt', 'last_timestamp_dt'], ascending=True, inplace=False)
_filtering_xdf_stream_infos_df
# _out_xdf_stream_infos_df[is_sufficiently_long]

In [ ]:
_all_xdf_filenames

In [ ]:
included_xdf_filenames: List[str] = _filtering_xdf_stream_infos_df['xdf_filename'].to_list()
excluded_xdf_filenames: List[str] = list(set(_all_xdf_filenames) - set(included_xdf_filenames))
excluded_xdf_filenames

# included_xdf_filenames = ['LabRecorder_2025-09-10T153731.079Z_eeg.xdf',
#  'LabRecorder_2025-09-11T014154.084Z_eeg.xdf',
#  'LabRecorder_2025-09-11T101328.256Z_eeg.xdf',
#  'LabRecorder_2025-09-11T154549.460Z_eeg.xdf',
#  'LabRecorder_2025-09-12T220903.464Z_eeg.xdf',
#  'LabRecorder_2025-09-18T031842.989Z_eeg.xdf',
#  'LabRecorder_2025-09-18T121337.267Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-12T215537.892Z.xdf',
#  'LabRecorder_Apogee_2025-09-18T151839.043Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-18T152308.395Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-19T051346.012Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-19T205118.364Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-20T214749.964Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-21T003051.428Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-21T085541.696Z_eeg.xdf',
#  'LabRecorder_Apogee_2025-09-22T213547.659Z_eeg.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-12T014018.162Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-13T021042.451Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-13T031209.598Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-19T001746.449Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-19T012938.518Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-19T015439.979Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-19T022210.910Z.xdf',
#  'LabRecorder_rMBPPinkDot_2025-09-20T023803.932Z.xdf']




# ['xdf_filename', 'first_timestamp', 'last_timestamp', 'sample_count',
    #    'lab_recorder_xdf_file_idx', 'xdf_filename', 'proccessed_fif_filename',
    #    'proccessed_mat_filename', 'xdf_dataset_idx', 'recording_datetime',
    #    'recording_day_date', 'duration_sec']

In [ ]:
_out_xdf_stream_infos_df.reset_index(drop=True).groupby('xdf_dataset_idx').first()

In [ ]:
lab_recorder_xdf_files

In [ ]:


def extract_annotations_df(active_only_out_eeg_raws) -> pd.DataFrame:
    ## Extract comments/notes/annotations/etc from the outputs

    _extracted_comments = []
    ignored_comment_descriptions = ['BAD_motion', '']
    for a_raw in active_only_out_eeg_raws:
        an_annotations = a_raw.annotations
        if (an_annotations is not None) and (len(an_annotations) > 0):
            an_annotation_df = an_annotations.to_data_frame(time_format='datetime')
            an_annotation_df = an_annotation_df[np.logical_not(np.isin(an_annotation_df['description'], ignored_comment_descriptions))]
            _extracted_comments.append(an_annotation_df)
            # an_annotation_df


    extracted_comments_df: pd.DataFrame = pd.concat(_extracted_comments)
    extracted_comments_df = extracted_comments_df.rename(columns={'onset':'time', 'description':'text'}, inplace=False)
    return extracted_comments_df

annotations_df = extract_annotations_df(_out_eeg_raw)
annotations_df

In [ ]:
# from pyphoplacecellanalysis.GUI.PyQtPlot.Widgets.SpikeRasterWidgets.Spike2DRaster import Spike2DRaster, SynchronizedPlotMode

In [ ]:
_out_xdf_stream_infos_df

In [ ]:
len(_out_xdf_stream_infos_df)
_out_xdf_stream_infos_df.loc[0]

In [ ]:
_out_eeg_raw

# 2025-12-10 - Build Timeline Browser from parsed streams

_out_xdf_stream_infos_df: pd.DataFrame = XDFDataStreamAccessor.init_from_results(_out_xdf_stream_infos_df=_out_xdf_stream_infos_df, active_only_out_eeg_raws=_out_eeg_raw) # [_out_xdf_stream_infos_df['name'] == 'Epoc X']
_out_xdf_stream_infos_df

In [ ]:
## INPUTS: _out_xdf_stream_infos_df: pd.DataFrame

In [ ]:
_out_xdf_stream_infos_df

# csv_save_path = Path('../output').joinpath('2025-12-10_all_xdf_stream_infos.csv').resolve()
csv_save_path = Path('../output').joinpath('2025-12-17_all_xdf_stream_infos.csv').resolve()
print(f'csv_save_path: "{csv_save_path.as_posix()}"')
_out_xdf_stream_infos_df.to_csv(csv_save_path)

## load with: 
# csv_save_path = Path('../output').joinpath('2025-12-10_all_xdf_stream_infos.csv').resolve()
# assert csv_save_path.exists()
# all_xdf_stream_infos_df: pd.DataFrame = pd.read_csv(csv_save_path)

In [ ]:
# from phoofflineeeganalysis.analysis.UI.historical_data_timeline import (
#     TimelineWidget, VideoMetadataTrack, EEGRecordingTrack, 
#     MotionRecordingTrack, PhoLogTrack, WhisperTrack
# )

timeline = TimelineWidget()


csv_save_path = Path('../output').joinpath('2025-12-09_parsed_videos.csv').resolve()
assert csv_save_path.exists()
video_df: pd.DataFrame = pd.read_csv(csv_save_path)

csv_save_path = Path('../output').joinpath('2025-12-10_all_xdf_stream_infos.csv').resolve()
assert csv_save_path.exists()
all_xdf_stream_infos_df: pd.DataFrame = pd.read_csv(csv_save_path)


# Add tracks from different modalities
timeline.add_track(VideoMetadataTrack(video_df))
timeline.add_tracks_from_xdf_streams(all_xdf_stream_infos_df)
timeline.show()

In [ ]:
timeline.add_tracks_from_xdf_streams(all_xdf_stream_infos_df)

In [ ]:

timeline.add_track(EEGRecordingTrack(eeg_df))
timeline.add_track(MotionRecordingTrack(motion_df))
timeline.add_track(PhoLogTrack(pho_log_df))
timeline.add_track(WhisperTrack(whisper_df))

# 2025-12-11 - Build Detailed Timeline Browser from actual recent data

In [ ]:
## INPUTS: _out_xdf_stream_infos_df: pd.DataFrame
from phoofflineeeganalysis.analysis.video_metadata import VideoMetadataParser

output_folder = Path('../output').resolve()
assert output_folder.exists()

# csv_save_path = output_folder.joinpath('2025-12-17_parsed_videos.csv').resolve()
# assert csv_save_path.exists()
# video_df: pd.DataFrame = pd.read_csv(csv_save_path)
# video_df


## parse videos from scratch because it's pretty fast:
video_recordings_folder_path = Path(r"M:\ScreenRecordings\EyeTrackerVR_Recordings")

print(f"Parsing videos in: {video_recordings_folder_path}")
video_df = VideoMetadataParser.parse_video_folder(video_recordings_folder_path)
video_df

In [ ]:
from phoofflineeeganalysis.analysis.UI.timeline.TimelineWidget import TimelineWidget
from phoofflineeeganalysis.analysis.UI.timeline import (
    TimelineWidget,
    TrackWidget,
    VideoMetadataTrack,
    EEGRecordingTrack,
    MotionRecordingTrack,
    PhoLogTrack,
    WhisperTrack,
    XDFStreamTrack,
    TrackRegistry,
)


timeline = TimelineWidget()

timeline.add_track(VideoMetadataTrack(video_df))
timeline.show()

In [ ]:
_out_xdf_stream_infos_df

csv_save_path = output_folder.joinpath('2025-12-15_all_xdf_stream_infos.csv').resolve()
print(f'csv_save_path: "{csv_save_path.as_posix()}"')
_out_xdf_stream_infos_df.to_csv(csv_save_path)

## load with: 
# csv_save_path = Path('../output').joinpath('2025-12-10_all_xdf_stream_infos.csv').resolve()
# assert csv_save_path.exists()
# all_xdf_stream_infos_df: pd.DataFrame = pd.read_csv(csv_save_path)

In [ ]:
csv_save_path = Path('../output').joinpath('2025-12-15_all_xdf_stream_infos.csv').resolve()
print(f'csv_save_path: "{csv_save_path.as_posix()}"')
_out_xdf_stream_infos_df.to_csv(csv_save_path)

In [ ]:
from phoofflineeeganalysis.analysis.UI.historical_data_timeline import (
    TimelineWidget, VideoMetadataTrack, EEGRecordingTrack, 
    MotionRecordingTrack, PhoLogTrack, WhisperTrack
)

timeline = TimelineWidget()


csv_save_path = Path('../output').joinpath('2025-12-09_parsed_videos.csv').resolve()
assert csv_save_path.exists()
video_df: pd.DataFrame = pd.read_csv(csv_save_path)

csv_save_path = Path('../output').joinpath('2025-12-10_all_xdf_stream_infos.csv').resolve()
assert csv_save_path.exists()
all_xdf_stream_infos_df: pd.DataFrame = pd.read_csv(csv_save_path)


# Add tracks from different modalities
timeline.add_track(VideoMetadataTrack(video_df))
timeline.add_tracks_from_xdf_streams(all_xdf_stream_infos_df)
timeline.show()

# From detailed data: 
INPUTS to timeline: _out_xdf_stream_infos_df: pd.DataFrame, _out_eeg_raw, lab_recorder_xdf_files, xdf_dataset_indicies

In [ ]:
## INPUTS: active_only_out_eeg_raws, results
## INPUTS: extracted_comments_df: pd.DataFrame ## comments track

In [ ]:
_out_xdf_stream_infos_df

In [ ]:
# lab_recorder_output_path

# print(list(_out_xdf_stream_infos_df.columns))

if 'xdf_file_path' not in _out_xdf_stream_infos_df.columns:
    _out_xdf_stream_infos_df['xdf_file_path'] = _out_xdf_stream_infos_df['xdf_filename'].map(lambda x: Path(lab_recorder_output_path).joinpath(x).resolve())


xdf_file_paths: List[Path] = _out_xdf_stream_infos_df['xdf_file_path'].to_list()
xdf_file_paths

In [ ]:
## INPUTS to timeline: _out_xdf_stream_infos_df: pd.DataFrame, _out_eeg_raw, lab_recorder_xdf_files, xdf_dataset_indicies
from phoofflineeeganalysis.analysis.xdf_files import LabRecorderXDF
from phoofflineeeganalysis.analysis.UI.timeline.datasource.datasources import XDFDatasource, DataframeDatasource, IntervalDataframeDatasource, BaseDatasource

a_ds = XDFDatasource(a_xdf_file=xdf_file_paths[0], datasource_name='test_xdf')
a_ds

In [ ]:
# a_ds.df
# list(a_ds.lab_recorder_xdf.stream_infos.columns)

a_ds.lab_recorder_xdf.stream_infos
# 'last_timestamp_dt'

In [ ]:
a_ds.total_datasource_start_end_times

In [ ]:

from phoofflineeeganalysis.analysis.UI.timeline import (
    TimelineWidget, VideoMetadataTrack, EEGRecordingTrack, 
    MotionRecordingTrack, PhoLogTrack, WhisperTrack, StringDataTrack, XDFStreamTrack, TrackWidget
)

## INPUTS: xdf_file_paths
timeline = TimelineWidget()

# Get stream information DataFrame from the datasource
stream_infos_df = a_ds.lab_recorder_xdf.stream_infos

# Add tracks for all available stream modalities
if stream_infos_df is not None and not stream_infos_df.empty:
    timeline.add_tracks_from_xdf_streams(stream_infos_df, fail_on_exception=False)

# Always add XDFStreamTrack in addition to individual modality tracks
timeline.add_track(track=XDFStreamTrack(a_ds))

timeline.show()

In [ ]:
a_ds.get_detailed_data()

In [ ]:
# a_ds.lab_recorder_xdf
a_ds.lab_recorder_xdf.datasets

In [ ]:
a_ds.lab_recorder_xdf.stream_infos

In [ ]:
from phoofflineeeganalysis.analysis.UI.timeline.tracks.MotionRecordingTrack import MotionRecordingTrack
from phoofflineeeganalysis.analysis.MNE_helpers import up_convert_raw_objects, up_convert_raw_obj
from phoofflineeeganalysis.analysis.MNE_helpers import MNEHelpers

## INPUTS: _out_xdf_stream_infos_df
a_motion_raw = up_convert_raw_objects(a_ds.lab_recorder_xdf.datasets_dict[DataModalityType.MOTION.value])[0]
a_motion_df = a_ds.lab_recorder_xdf.streams_timestamp_dfs['Epoc X Motion'] ## not right
a_motion_overview_df = a_ds.lab_recorder_xdf.stream_infos ## overview
dataset_MOTION_df = a_motion_raw.to_data_frame(time_format='datetime')
dataset_MOTION_df = MNEHelpers.convert_df_columns_to_datetime(dataset_MOTION_df, dt_col_names=["start_time", "end_time"])
dataset_MOTION_df
from phoofflineeeganalysis.analysis.UI.timeline.datasource.datasources import IntervalDataframeDatasource

motion_ds = IntervalDataframeDatasource(df=dataset_MOTION_df, time_column_name='time') # , time_col_name='time'
motion_ds
# def load_motion_series(metadata: Dict[str, Any], window_ts: Tuple[float, float]) -> Dict[str, Tuple[np.ndarray, np.ndarray]]:
#     # Use metadata['xdf_filename'], metadata['sampling_rate'], etc.
#     # Return: {"AccX": (t_accx, v_accx), "AccY": (...), ..., "GyroZ": (...)}
#     xdf_filepath = Path(metadata['xdf_filename']).resolve() ## load the detailed data from the XDF file
    
motion_track = MotionRecordingTrack(motion_source=motion_ds, height=80)
timeline.add_track(motion_track)

In [ ]:
motion_track._is_detailed_mode
# motion_track._ensure_detailed_items()
motion_track._render_detailed(motion_ds.total_datasource_start_end_times)
motion_track._is_detailed_mode

In [ ]:
motion_track._is_detailed_mode
motion_track.set_detailed_threshold(seconds=1000000.0)  # Adjust this value as needed
motion_track.update_display()
motion_track._is_detailed_mode

In [ ]:
motion_track._ensure_detailed_items()

In [ ]:
motion_ds.total_datasource_start_end_times
motion_ds.total_df_start_end_times

In [ ]:
timeline.set_time_range(start_dt=motion_ds.total_datasource_start_end_times[0], end_dt=motion_ds.total_datasource_start_end_times[1])

In [ ]:
# dataset_MOTION_df ## overview

# a_ds.lab_recorder_xdf.stream_infos ## overview
a_motion_raw[0].to_df()

## Other Tracks

In [ ]:
# Build the detailed PhoLogger track from `extracted_comments_df: pd.DataFrame` with columns: ['time', 'text']. It should componently layout the strings so they don't excessively overlap, elliding or wrapping when needed.
## It can use the full height to stagger strings that would otherwise overlap horizontally.
from phoofflineeeganalysis.analysis.UI.timeline import PhoLogTrack, WhisperTrack
## Extract comments/notes/annotations/etc from the outputs (`active_only_out_eeg_raws`)

_extracted_comments = []
ignored_comment_descriptions = ['BAD_motion', '']
for a_raw in active_only_out_eeg_raws:
    an_annotations = a_raw.annotations
    if (an_annotations is not None) and (len(an_annotations) > 0):
        an_annotation_df = an_annotations.to_data_frame(time_format='datetime')
        an_annotation_df = an_annotation_df[np.logical_not(np.isin(an_annotation_df['description'], ignored_comment_descriptions))]
        _extracted_comments.append(an_annotation_df)
        # an_annotation_df


extracted_comments_df: pd.DataFrame = pd.concat(_extracted_comments)
extracted_comments_df = extracted_comments_df.rename(columns={'onset':'time', 'description':'text'}, inplace=False)
extracted_comments_df

timeline.add_track(PhoLogTrack(extracted_comments_df))

In [ ]:
from phoofflineeeganalysis.analysis.MNE_helpers import DatasetDatetimeBoundsRenderingMixin, RawArrayExtended, RawExtended, up_convert_raw_objects, up_convert_raw_obj
from phoofflineeeganalysis.analysis.EEG_data import EEGData
from PhoOfflineEEGAnalysis.src.phoofflineeeganalysis.analysis.SavedSessionsProcessor import LabRecorderXDF


assert lab_recorder_output_path.exists()

lab_recorder_xdf_files: List[Path] = list(lab_recorder_output_path.glob('*.xdf'))
n_total_found_files: int = len(lab_recorder_xdf_files)
if included_xdf_file_names is not None:
    print(f'limiting to included_xdf_file_names: {included_xdf_file_names}...')
    lab_recorder_xdf_files = [v for v in lab_recorder_xdf_files if v.name in included_xdf_file_names]
    n_filtered_found_files: int = len(lab_recorder_xdf_files)
    print(f'\tlimited to {n_filtered_found_files}/{n_total_found_files} files')

if not should_load_full_file_data:
    assert (not should_write_final_merged_eeg_fif)

if (labRecorder_PostProcessed_path is not None) and should_write_final_merged_eeg_fif:
    labRecorder_PostProcessed_path.mkdir(exist_ok=True)

# a_xdf_file = lab_recorder_xdf_files[-3]
# a_xdf_file = lab_recorder_xdf_files[-1]
# a_xdf_file = Path(r"E:\Dropbox (Personal)\Databases\UnparsedData\LabRecorderStudies\sub-P001\LabRecorder_2025-09-18T031842.989Z_eeg.xdf").resolve()
# a_xdf_file = Path(r"E:\Dropbox (Personal)\Databases\UnparsedData\LabRecorderStudies\sub-P001\LabRecorder_2025-09-18T121337.267Z_eeg.xdf").resolve()

_out_eeg_raw = []
_out_xdf_stream_infos_df = []

for an_xdf_file_idx, a_xdf_file in enumerate(lab_recorder_xdf_files):
    print(f'trying to process XDF file {an_xdf_file_idx}/{len(lab_recorder_xdf_files)}: "{a_xdf_file.as_posix()}"...')
    try:
        _obj = LabRecorderXDF.init_from_lab_recorder_xdf_file(a_xdf_file=a_xdf_file, should_load_full_file_data=should_load_full_file_data, debug_print=True)
        stream_infos = _obj.stream_infos
        raws = _obj.datasets
        raws_dict = _obj.datasets_dict
        eeg_raws = raws_dict.get(DataModalityType.EEG.value, [])
        if len(eeg_raws) > 0:
            print(f'\tWARN: no EEG streams found in "{a_xdf_file.as_posix()}". Skipping file.')
            # Merge by device so we can handle multiple EEG streams per XDF
            merged_eeg_raws, merge_meta = LabRecorderXDF.merge_eeg_streams_by_device(
                eeg_raws=eeg_raws, strict_merge=False, debug_print=False
            )
            eeg_raw = up_convert_raw_obj(eeg_raw)
            EEGData.set_montage(datasets_EEG=[eeg_raw])
            eeg_raw.debug_test_annotations_timestamps()
            _out_eeg_raw.append(eeg_raw)
        
    except (ValueError, KeyError, AssertionError, TypeError) as e:
        print(f'\t failed with error: {e}\n\tskipping file.')
        if fail_on_exception:
            raise
        else:
            continue
        
    except Exception as e:
        print(f'\t failed with error: {e}\n\tskipping file.')
        raise

In [ ]:
motion_df = _out_xdf_stream_infos_df[_out_xdf_stream_infos_df['name'] == 'Epoc X Motion']
list(motion_df.columns) # 'xdf_filename', 'xdf_dataset_idx'
motion_df['xdf_filename']

In [ ]:
def load_motion_series(metadata: Dict[str, Any], window_ts: Tuple[float, float]) -> Dict[str, Tuple[np.ndarray, np.ndarray]]:
    # Use metadata['xdf_filename'], metadata['sampling_rate'], etc.
    # Return: {"AccX": (t_accx, v_accx), "AccY": (...), ..., "GyroZ": (...)}
    xdf_filepath = Path(metadata['xdf_filename']).resolve() ## load the detailed data from the XDF file
    

DataModalityType.MOTION.value
## INPUTS: _out_xdf_stream_infos_df
motion_df = _out_xdf_stream_infos_df[_out_xdf_stream_infos_df['name'] == 'Epoc X Motion']
motion_track = MotionRecordingTrack(motion_df, detailed_data_provider=load_motion_series)
timeline.add_track(motion_track)

In [ ]:

timeline.add_track(EEGRecordingTrack(eeg_df))
timeline.add_track(MotionRecordingTrack(motion_df))
timeline.add_track(PhoLogTrack(pho_log_df))
timeline.add_track(WhisperTrack(whisper_df))

# 2025-01-05 - `pyPhoTimeline`

In [ ]:
from pypho_timeline.rendering.datasources.track_datasource import TrackDatasource, BaseTrackDatasource
from pypho_timeline.rendering.detail_renderers import PositionPlotDetailRenderer, VideoThumbnailDetailRenderer


class PositionTrackDatasource(BaseTrackDatasource):
    """Example TrackDatasource for position data.
    
    Inherits from BaseTrackDatasource and implements all required methods for
    displaying position data with async detail loading.
    """
    
    def __init__(self, position_df: pd.DataFrame, intervals_df: pd.DataFrame):
        """Initialize with position data and intervals.
        
        Args:
            position_df: DataFrame with columns ['t', 'x', 'y'] (or ['t', 'x'] for 1D)
            intervals_df: DataFrame with columns ['t_start', 't_duration'] for intervals
        """
        super().__init__()
        self.position_df = position_df
        self.intervals_df = intervals_df.copy()
        self.custom_datasource_name = "PositionTrack"
        
        # Add visualization columns to intervals
        self.intervals_df['series_vertical_offset'] = 0.0
        self.intervals_df['series_height'] = 1.0
        
        # Create pens and brushes
        color = pg.mkColor('blue')
        color.setAlphaF(0.3)
        pen = pg.mkPen(color, width=1)
        brush = pg.mkBrush(color)
        self.intervals_df['pen'] = [pen] * len(self.intervals_df)
        self.intervals_df['brush'] = [brush] * len(self.intervals_df)
    
    @property
    def df(self) -> pd.DataFrame:
        return self.intervals_df
    
    @property
    def time_column_names(self) -> list:
        return ['t_start', 't_duration', 't_end']
    
    @property
    def total_df_start_end_times(self) -> tuple:
        if len(self.intervals_df) == 0:
            return (0.0, 1.0)
        t_start = self.intervals_df['t_start'].min()
        t_end = (self.intervals_df['t_start'] + self.intervals_df['t_duration']).max()
        return (t_start, t_end)
    
    def get_updated_data_window(self, new_start: float, new_end: float) -> pd.DataFrame:
        """Get intervals overlapping with time window."""
        mask = (self.intervals_df['t_start'] + self.intervals_df['t_duration'] >= new_start) & \
               (self.intervals_df['t_start'] <= new_end)
        return self.intervals_df[mask].copy()
    
    def update_visualization_properties(self, dataframe_vis_columns_function):
        """Update visualization properties."""
        self.intervals_df = dataframe_vis_columns_function(self.intervals_df)
    
    def get_overview_intervals(self) -> pd.DataFrame:
        """Get overview intervals."""
        return self.intervals_df
    
    def fetch_detailed_data(self, interval: pd.Series) -> pd.DataFrame:
        """Fetch position data for an interval."""
        if self.position_df is None:
            return pd.DataFrame()  # Return empty DataFrame if no position data available
        t_start = interval['t_start']
        t_end = t_start + interval['t_duration']
        mask = (self.position_df['t'] >= t_start) & (self.position_df['t'] < t_end)
        return self.position_df[mask].copy()
    
    def get_detail_renderer(self):
        """Get detail renderer for position data."""
        if self.position_df is None:
            return PositionPlotDetailRenderer(pen_color='cyan', pen_width=2, y_column=None)
        return PositionPlotDetailRenderer(pen_color='cyan', pen_width=2, y_column='y' if 'y' in self.position_df.columns else None)
    
    def get_detail_cache_key(self, interval: pd.Series) -> str:
        """Get cache key for interval."""
        return f"position_{interval['t_start']:.3f}_{interval['t_duration']:.3f}"


class VideoTrackDatasource(BaseTrackDatasource):
    """Example TrackDatasource for video data.
    
    Inherits from BaseTrackDatasource and implements all required methods for
    displaying video intervals with async detail loading.
    """
    
    def __init__(self, video_intervals_df: pd.DataFrame):
        """Initialize with video intervals.
        
        Args:
            video_intervals_df: DataFrame with columns ['t_start', 't_duration', 'video_path']
        """
        super().__init__()
        self.video_intervals_df = video_intervals_df.copy()
        self.custom_datasource_name = "VideoTrack"
        
        # Add visualization columns
        self.video_intervals_df['series_vertical_offset'] = 0.0
        self.video_intervals_df['series_height'] = 50.0
        
        # Create pens and brushes
        color = pg.mkColor('green')
        color.setAlphaF(0.3)
        pen = pg.mkPen(color, width=1)
        brush = pg.mkBrush(color)
        self.video_intervals_df['pen'] = [pen] * len(self.video_intervals_df)
        self.video_intervals_df['brush'] = [brush] * len(self.video_intervals_df)
    
    @property
    def df(self) -> pd.DataFrame:
        return self.video_intervals_df
    
    @property
    def time_column_names(self) -> list:
        return ['t_start', 't_duration', 't_end']
    
    @property
    def total_df_start_end_times(self) -> tuple:
        if len(self.video_intervals_df) == 0:
            return (0.0, 1.0)
        t_start = self.video_intervals_df['t_start'].min()
        t_end = (self.video_intervals_df['t_start'] + self.video_intervals_df['t_duration']).max()
        return (t_start, t_end)
    
    def get_updated_data_window(self, new_start: float, new_end: float) -> pd.DataFrame:
        """Get intervals overlapping with time window."""
        mask = (self.video_intervals_df['t_start'] + self.video_intervals_df['t_duration'] >= new_start) & \
               (self.video_intervals_df['t_start'] <= new_end)
        return self.video_intervals_df[mask].copy()
    
    def update_visualization_properties(self, dataframe_vis_columns_function):
        """Update visualization properties."""
        self.video_intervals_df = dataframe_vis_columns_function(self.video_intervals_df)
    
    def get_overview_intervals(self) -> pd.DataFrame:
        """Get overview intervals."""
        return self.video_intervals_df
    
    def fetch_detailed_data(self, interval: pd.Series) -> dict:
        """Fetch video frames for an interval (simulated with random images)."""
        # In a real implementation, this would load video frames
        # For demo, generate synthetic frame data
        n_frames = max(1, int(interval['t_duration'] * 10))  # 10 fps
        frames = []
        for i in range(n_frames):
            # Generate a simple colored frame
            frame = np.random.randint(0, 255, (64, 64, 3), dtype=np.uint8)
            frames.append(frame)
        return {'frames': frames, 'timestamps': np.linspace(interval['t_start'], interval['t_start'] + interval['t_duration'], n_frames)}
    
    def get_detail_renderer(self):
        """Get detail renderer for video."""
        return VideoThumbnailDetailRenderer(thumbnail_height=50.0, spacing=0.1)
    
    def get_detail_cache_key(self, interval: pd.Series) -> str:
        """Get cache key for interval."""
        return f"video_{interval['t_start']:.3f}_{interval['t_duration']:.3f}"